deepjavalibrary/djl

- engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtEngine.java
- engines/paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpEngine.java
- engines/paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jni/JniUtils.java
- engines/paddlepaddle/paddlepaddle-engine/src/test/java/ai/djl/paddlepaddle/jni/PpEngineTest.java
> bump up versions

- basicdataset/src/main/java/ai/djl/basicdataset/tabular/AirfoilRandomAccess.java
- basicdataset/src/main/java/ai/djl/basicdataset/tabular/CsvDataset.java
- basicdataset/src/main/java/ai/djl/basicdataset/tabular/DailyDelhiClimate.java
- basicdataset/src/main/java/ai/djl/basicdataset/tabular/TabularDataset.java
- docs/development/how_to_use_dataset.md
- extensions/tablesaw/src/main/java/ai/djl/tablesaw/TablesawDataset.java
This creates a new abstract dataset called tabular. It contains common
functionality of features and label management that is shared between the
CsvDataset, the TablesawDataset, and likely future datasets from other tabular
sources.
> Create tabular dataset

- api/src/main/java/ai/djl/translate/ServingTranslatorFactory.java
Change-Id: I63cee2f2c8dcb9deec39e037a5291dbf0d68f045
> [api] Refactor ServingTranslatorFactory

- engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_inference.cc
- engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_tensor.cc
Change-Id: Ic08086214a5826d10ca2f40b61a7b56cd7b21a97
> [pytorch] Fixes model loading bug for 1.11.0

- .github/workflows/native_jni_s3_pytorch_android.yml
- .github/workflows/native_s3_pytorch_android.yml
Change-Id: Iaa20c3bf8ae509eefa4b355e54d026ace4142a08
> [ci] Upgrade NDK version to 21.1.6352462

- android/core/src/androidTest/java/ai/djl/android/core/ModelLoadingTest.java
Add android model loading test code
> add android test code

- .github/workflows/serving_publish.yml
Add nightly deb file publish to S3
> [DJLServing] add serving deb file publish

- android/pytorch-native/README.md
Update README to reflect PyTorch 1.11 build process
> [docs] Readme updates for PyTorch 1.11

- .github/workflows/codeql-analysis-java.yml
Change-Id: Ia639fe602221439ad9d2f95365c3fff4ec096dad
> [ci] Upgrade codeql github action to v2

- docs/development/example_dataset.md
Change-Id: I37fa61b94b7711ef5e7981e37d2cab756e09f6c5
> [doc] Update CVSDataset example README file

- .github/workflows/serving_publish.yml
Change-Id: Id55884b5d5c9e2d81c5b6c50abbea5b11441f50c
> [ci] Fixes publish serving deb

- api/src/main/java/ai/djl/nn/Activation.java
- api/src/main/java/ai/djl/nn/Blocks.java
- api/src/main/java/ai/djl/nn/LambdaBlock.java
- api/src/main/java/ai/djl/nn/SequentialBlock.java
- api/src/main/java/ai/djl/nn/convolutional/Convolution.java
- api/src/main/java/ai/djl/nn/pooling/Pool.java
Change-Id: I6dbceb21493443e06aa2911d5c74dbc8b93b9f99
> [api] Add name to LambdaBlock

- engines/mxnet/mxnet-engine/README.md
Change-Id: I990c1db63a52890010579d4896b3ea9e598abd11
> [mxnet] Update document to use MXNet 1.9.0

- .github/workflows/serving_publish.yml
Change-Id: I81504d21ef5bccb52eec129e7465015d869be8f1
> [ci] Fixes serving publish github actions

- api/src/main/java/ai/djl/BaseModel.java
- api/src/main/java/ai/djl/util/Utils.java
Change-Id: I298e136a2d8db1cc6a68e24ddc8dc26b7b2fbb4d
> [api] Ignore hidden files for nested model directory

- .github/workflows/native_jni_s3_pytorch.yml
Create JNI build for AARCH64 using custom runner
> Build jni for aarch64

- api/src/main/java/ai/djl/translate/ServingTranslatorFactory.java
Change-Id: I8950901a46ae0764a3ea1d9e2d35e554924b556d
> [api] Add log for custom Translator loading

- api/src/main/java/ai/djl/ndarray/NDArray.java
- api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
- engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
- engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_tensor.cc
- engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
- extensions/fasttext/src/main/native/ai_djl_fasttext_jni_FastTextLibrary.cc
- extensions/sentencepiece/src/main/native/ai_djl_sentencepiece_jni_SentencePieceLibrary.cc
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDIndexTest.java
Add `put` feature support on PyTorch engine. This corresponds to `take` which get values according to linear indexing.
The relavant preceding PRs
[Support of take from pytorch #1627](https://github.com/deepjavalibrary/djl/pull/1627)
> Add `put` feature with linear indexing on PyTorch engine

- engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
Solve the NDSerializer issues
Solve issues in https://github.com/deepjavalibrary/djl-serving/pull/152
> make tensorflow NDArray always dense

- engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtModel.java
Change-Id: Ic3ec4249adb432b2a54668b7a45481698fa83ea5
> [ort] Add support for registerCustomOpLibrary.

- api/src/main/java/ai/djl/modality/cv/translator/ImageServingTranslator.java
Change-Id: I4646a9b411bbaaf81203b7531bf70f4bdfe9f9f8
> [api] Supports Image output for ImageServingTranslator

- api/src/main/java/ai/djl/ndarray/NDArray.java
- api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
- engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
- engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_torch_pointwise.cc
- engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayOtherOpTest.java
Implementing inverse of an NDArray. Issue [https://github.com/deepjavalibrary/djl/issues/1068](https://github.com/deepjavalibrary/djl/issues/1068)
> Implementing inverse operation

- engines/paddlepaddle/paddlepaddle-engine/src/test/java/ai/djl/paddlepaddle/jni/PpEngineTest.java
- engines/pytorch/pytorch-native/build.gradle
Change-Id: Id090f251e887a41ed92b4601a121fa554a59520d
> [m1] Fix test failure on macOS M1 machine

- api/src/main/java/ai/djl/modality/cv/translator/SemanticSegmentationTranslator.java
- api/src/main/java/ai/djl/modality/cv/translator/SemanticSegmentationTranslatorFactory.java
- engines/pytorch/pytorch-model-zoo/src/main/java/ai/djl/pytorch/zoo/PtModelZoo.java
- examples/src/main/java/ai/djl/examples/inference/SemanticSegmentation.java
- Adds support for direct reference to model from model zoo instead of using url to specify
> Adding model zoo implementation

- engines/paddlepaddle/paddlepaddle-model-zoo/build.gradle
- engines/paddlepaddle/paddlepaddle-model-zoo/src/main/java/ai/djl/paddlepaddle/zoo/cv/objectdetection/PpWordDetectionTranslator.java
Change-Id: I02b8596dc4bccc44b87fed2360567c4fad0c714f
> [paddle] paddle model zoo should not have compile time dependency on opencv

- jupyter/rank_classification_using_BERT_on_Amazon_Review.ipynb
> fix typo in bert notebook

- README.md
> Update README for 0.18.0 Release

- api/README.md
- examples/pom.xml
- gradle.properties
> Increase build version to 0.19.0

- docs/development/troubleshooting.md
Change-Id: I3974e10b74e56d2c3f496af906f737beabe3b470
> [docs] Updates troubleshooting.md to remove -native-auto package

- engines/pytorch/pytorch-model-zoo/src/test/resources/mlrepo/model/cv/semantic_segmentation/ai/djl/pytorch/deeplabv3/metadata.json
Change-Id: I15e043697379170034018257ac9cdb5bc9a80b3c
> [model-zoo] Add deeplabvs metadata.json

- android/core/src/androidTest/java/ai/djl/android/core/BitmapWrapperTest.java
- android/core/src/main/java/ai/djl/android/core/BitmapImageFactory.java
- api/src/main/java/ai/djl/modality/cv/BufferedImageFactory.java
- api/src/main/java/ai/djl/modality/cv/translator/BigGANTranslator.java
- api/src/main/java/ai/djl/modality/cv/translator/SemanticSegmentationTranslator.java
- api/src/main/java/ai/djl/modality/cv/translator/StyleTransferTranslator.java
- engines/paddlepaddle/paddlepaddle-model-zoo/src/main/java/ai/djl/paddlepaddle/zoo/cv/objectdetection/PpWordDetectionTranslator.java
- examples/src/main/java/ai/djl/examples/inference/sr/SuperResolution.java
- examples/src/main/java/ai/djl/examples/inference/sr/SuperResolutionTranslator.java
- extensions/opencv/src/main/java/ai/djl/opencv/OpenCVImageFactory.java
- extensions/opencv/src/test/java/ai/djl/opencv/OpenCVImageFactoryTest.java
- integration/src/main/java/ai/djl/integration/tests/modality/cv/BufferedImageFactoryTest.java
- integration/src/main/java/ai/djl/integration/tests/modality/cv/NDImageUtilsTest.java
Change-Id: I5b40ff44af3bd11c80f56d20f2046cf2ed52ee79
> [api] Allows convert float32 NDArray to Image.

- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
Change-Id: I52c405d269b4c8d9129ff4fbd2875c80bfeaa317
> [pytorch] Add debug log for model loading options.

- android/core/src/main/java/ai/djl/android/core/BitmapImageFactory.java
- api/src/main/java/ai/djl/modality/cv/BufferedImageFactory.java
- api/src/main/java/ai/djl/modality/cv/translator/SemanticSegmentationTranslator.java
Change-Id: I3e81e9fd46359ff7537193bb0e18ca7eda5e58f1
> [api] Fixes ImageFactory.fromNDArray() bug

- api/src/main/java/ai/djl/modality/nlp/bert/BertFullTokenizer.java
- engines/mxnet/mxnet-model-zoo/src/main/java/ai/djl/mxnet/zoo/nlp/qa/MxBertQATranslator.java
- engines/pytorch/pytorch-model-zoo/src/main/java/ai/djl/pytorch/zoo/nlp/qa/PtBertQATranslator.java
- extensions/tokenizers/rust/src/lib.rs
- extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizer.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/jni/TokenizersLibrary.java
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizerTest.java
1. support question answering encoding
2. remove redunant tokenToString() api
Change-Id: I514b85147e59adc552c616d278c91c5a9037cf56
> [tokenizer] Add encodeDual support for huggingface tokenizer

- engines/pytorch/pytorch-model-zoo/src/main/java/ai/djl/pytorch/zoo/nlp/qa/PtBertQATranslator.java
Change-Id: I16ce250daea8cf2a07a39b064cff9f9bfa58399d
> [pt-model-zoo] Make PtBertQATranslator compatible with huggingface model

- extensions/tokenizers/build.gradle
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/QuestionAnsweringTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/QuestionAnsweringTranslatorFactory.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/package-info.java
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/TranslatorTest.java
Adds question answering Translator that leverage Huggingface tokenizer.
> Added Huggingface QuestionAnsweringTranslator

- api/src/main/java/ai/djl/ndarray/index/NDIndex.java
Change-Id: I74ad840321ae54d6a2849a43a89a643e403d3c85
> [doc] Fixes NDIndex javadoc issue

- extensions/tokenizers/rust/src/lib.rs
- extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizer.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/jni/TokenizersLibrary.java
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizerTest.java
Expose tokenizers decode method https://github.com/deepjavalibrary/djl/issues/1829
> Tokenizers decode

- .github/workflows/native_s3_huggingface.yml
Change-Id: I3176eb1e1c97b47640b823281ba1e56d3e370cbc
> [ci] Fixes huggingface tokenizer JNI publish task

- extensions/tokenizers/src/main/python/huggingface_converter.py
This PR added fill-mask support.
- Manually imported 20 models without error
- Will add Java FillMaskTranslator later
> Added fill-mask support for converting huggingface model to model zoo

- api/src/main/java/ai/djl/nn/IdentityBlockFactory.java
- api/src/test/java/ai/djl/nn/BlockFactoryTest.java
- api/src/test/java/ai/djl/nn/package-info.java
- model-zoo/src/main/java/ai/djl/basicmodelzoo/basic/MlpBlockFactory.java
Change-Id: I51eaedafec628d326af66f61ffc1f7c65a7c6b52
> [api] Adds IdentityBlockFactory for demo/test purpose

- engines/paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpModel.java
Fix String to Integer parsing issue
> [Paddle] fix the parsing issue

- .github/workflows/continuous.yml
- .github/workflows/nightly_android.yml
- android/core/src/androidTest/java/ai/djl/android/core/ModelLoadingTest.java
Fix cAT and add android CI testing
> add android CI tests

- .github/workflows/continuous.yml
- integration/build.gradle
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayOtherOpTest.java
Add ARM support for ONNXRuntime update integration test
> Add ARM support for ONNXRuntime update integration test

- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizerTest.java
huggingface shouldn't be executed on arm devices
> Add non arm requirement to tokenizer decode test

- android/gradlew.bat
> [Android] add gradlew.bat

- extensions/tokenizers/src/main/python/huggingface_converter.py
Fixed post processing in question-answering converter 
Fixed an issue with the result of `verify_jit_model()` being ignored
> Fixes bugs in huggingface question-answering converter

- android/build.gradle
- android/core/src/androidTest/java/ai/djl/android/core/BitmapWrapperTest.java
- android/core/src/androidTest/java/ai/djl/android/core/ModelLoadingTest.java
- android/core/src/main/java/ai/djl/android/core/BitmapImageFactory.java
- tools/gradle/android-formatter.gradle
Change-Id: If15efb1ad2a744b1bfadb7bf89a09a265a81082b
> [android] Adds formatJava task for android project

- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtEngine.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtGradientCollector.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
- engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_system.cc
Change-Id: I7d27aa8df9b75ca005223f095557d1ea80643f2a
> [pytorch] Disable autograd when engine start

- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/QuestionAnsweringTranslator.java
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/TranslatorTest.java
Fixed bug in `QuestionAnsweringTranslator`
> Fix huggingface question-answering translator bug

- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/FillMaskTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/FillMaskTranslatorFactory.java
- extensions/tokenizers/src/main/python/.gitignore
- extensions/tokenizers/src/main/python/huggingface_converter.py
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/TranslatorTest.java
Adds huggingface `FillMaskTranslator`
> Adds huggingface FillMaskTranslator

- api/src/main/java/ai/djl/Model.java
- api/src/main/java/ai/djl/translate/DeferredTranslatorFactory.java
- api/src/main/java/ai/djl/translate/ServingTranslatorFactory.java
- api/src/test/java/ai/djl/translate/DeferredTranslatorFactoryTest.java
- api/src/test/resources/identity/serving.properties
Change-Id: I656ec0a0f67176bb0de85763c04e6690db7148a6
> [api] Adds DeferredTranslatorFactory to let serving.properties take effect

- extensions/hadoop/src/test/java/ai/djl/hadoop/hdfs/HdfsRepositoryTest.java
- tools/gradle/check.gradle
Change-Id: I4c15161fdfb91fc164af05137ef69fbc2acadd62
> [ci] Workaround JDK 18 spotbugs issue.

- api/src/main/java/ai/djl/engine/Engine.java
- api/src/main/java/ai/djl/util/Utils.java
- engines/dlr/dlr-engine/src/main/java/ai/djl/dlr/jni/LibUtils.java
- engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxEngine.java
- engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/jna/LibUtils.java
- engines/paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jni/LibUtils.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtEngine.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java
- engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/javacpp/LibUtils.java
- engines/tensorrt/src/main/java/ai/djl/tensorrt/engine/TrtEngine.java
Change-Id: I06d17bef2a7d01a2605d3b651a7b4a7109368975
> [api] Makes the get system environment variable behavior for all engines

- extensions/tokenizers/src/main/python/fill_mask_converter.py
- extensions/tokenizers/src/main/python/huggingface_converter.py
- extensions/tokenizers/src/main/python/huggingface_models.py
- extensions/tokenizers/src/main/python/model_zoo_importer.py
- extensions/tokenizers/src/main/python/question_answering_converter.py
Change-Id: I7e3f53efd35e7971d12b4bfca7677d9ef383620d
> [tokenizer] Refactors huggingface converter

- examples/src/main/java/ai/djl/examples/training/TrainBertOnGoemotions.java
- examples/src/main/java/ai/djl/examples/training/util/BertGoemotionsDataset.java
- examples/src/test/java/ai/djl/examples/training/TrainBertOnGoemotionsTest.java
* Create a new example of training the BERT model with the Goemotions dataset
* Closed #191
> Create New Bert example using Goemotions

- extensions/tokenizers/src/main/python/huggingface_models.py
- extensions/tokenizers/src/main/python/model_zoo_importer.py
- extensions/tokenizers/src/main/python/token_classification_converter.py
> Adds support for converting huggingface token-classification models

- build.gradle
Change-Id: Idc2396a86210f2025e39fded93ffcbdf3db342cd
> [ci] Workaround Windows JDK 17 compile error

- .github/workflows/native_build_mxnet_osx.yml
- engines/mxnet/mxnet-engine/README.md
Change-Id: If80d5e210536722e9bb7fc4eeb70cc0f860ad2f2
> [mxnet] Update README for 1.9.1

- api/src/main/java/ai/djl/engine/Engine.java
- engines/dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrEngine.java
- engines/ml/lightgbm/src/main/java/ai/djl/ml/lightgbm/LgbmEngine.java
- engines/ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbEngine.java
- engines/paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpEngine.java
- engines/tflite/tflite-engine/src/main/java/ai/djl/tflite/engine/TfLiteEngine.java
Change-Id: If1c6f3b20b86b7cab1cafdbbb5ba5f976ec362c7
> [api] Print engine version and capabilities in debugEnvironment

- bom/build.gradle
- engines/ml/xgboost/src/test/java/ai/djl/ml/xgboost/XgbModelTest.java
Change-Id: I7ef58aab4a0e993c4d11b0a745bf9a69b3143468
> [bom] Adds xgboost-gpu to bom

- .github/workflows/nightly_publish.yml
Change-Id: Ied9916b11a39d32d9cefa3b8a9c81e406a08be36
> [xgb] Publish xgboost-gpu package

- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtModel.java
Change-Id: I3d873ebe43e41456cc446120a135b8780ce4aff9
> [pytorch] Fixes typo in error message

- .github/workflows/native_jni_s3_pytorch.yml
- .github/workflows/nightly_publish.yml
Change-Id: Ib0ba95795f7a7597be0733f2704e580311d1fc79
> [ci] Only run workflow tasks on djl repo

- .github/workflows/native_jni_s3_pytorch_android.yml
- .github/workflows/native_s3_pytorch_android.yml
- android/gradle.properties
- android/pytorch-native/README.md
- engines/pytorch/pytorch-native/build_android.sh
[Android] Upgrade PyTorch to 1.12.1
> [Android] Upgrade PyTorch to 1.12.1

- .github/workflows/native_s3_pytorch_android.yml
- android/pytorch-native/README.md
- engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_system.cc
[Android] Don't support torchSetGradMode
> [Android] Fixes torchSetGradMode bug for android

- engines/ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbNDArray.java
Change-Id: I06a866e61e6c754c2f3c1e7b44be7b445f7c0c70
> [xgb] Remove unnecessary inheritDoc

- engines/ml/xgboost/build.gradle
Change-Id: I74d01e7ece26b094ccafa429872be15d7a9aa680
> [xgb] Fixes XGBoost gpu package publishing

- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayOtherOpTest.java
Change-Id: I0df189e3bde4f7dd4dacf9be5471699dbb306122
> [integration] Remove hard coded PyTorch engine

- .github/workflows/native_s3_huggingface.yml
- extensions/tokenizers/build.gradle
- extensions/tokenizers/build.sh
Change-Id: Ibe6f4b1bf93e4dad846002a7e30d67c20413a82e
> [tokenizers] Adds aarch64 support

- extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizer.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/FillMaskTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/FillMaskTranslatorFactory.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/QuestionAnsweringTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/QuestionAnsweringTranslatorFactory.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TokenClassificationTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TokenClassificationTranslatorFactory.java
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizerTest.java
1. Add builder for HuggingfaceTokenizer
2. Make HuggingfaceTokenizer immutable
Change-Id: I84724b83051cb2079046b49893d96485d8fdcd3b
> [tokenizer] Use builder for HuggingfaceTokenizer

- extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizer.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/FillMaskTranslatorFactory.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/QuestionAnsweringTranslatorFactory.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TokenClassificationTranslatorFactory.java
Change-Id: I228b18d04a4ba6509db5e855bb94f9381ed4d989
> [tokenizer] Avoid memory leak if HuggingfaceTokenizer is not closed

- .github/workflows/nightly_android.yml
- .github/workflows/nightly_publish.yml
Use 1 gpu to decrease chance for failed spinning
> [nightly] use 1 gpu runner for nightly ci

- engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtEngine.java
- engines/pytorch/pytorch-engine/README.md
Change-Id: Ibd25f34dd1057eb451186db97957f0b176870119
> [ort] Fixes reported OrtEngine version

- engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/javacpp/LibUtils.java
Change-Id: I26d28707d479d3c06e87fc00c34549131c0e0565
> [tensorflow] Fixes fallback to CPU bug

- bom/README.md
- docs/development/dependency_management.md
- engines/pytorch/pytorch-engine/README.md
- examples/README.md
Change-Id: I26272235e4fb311bdd56e8f9241498be92826eeb
> [docs] Remove -native-auto in documents

- examples/src/main/java/ai/djl/examples/inference/NeuralMachineTranslation.java
- examples/src/main/java/ai/djl/examples/inference/SemanticSegmentation.java
Change-Id: Ib7703cafbcaace3a9a24b3ecad64c5d211754ba4
> [example] Refactor NMT example

- engines/pytorch/pytorch-engine/README.md
Change-Id: I208f89f934d953986705f61f43ce204c8262e1c9
> [docs] Fixes type on pytorch README.

- bom/build.gradle
- extensions/timeseries/build.gradle
Change-Id: Ib736e38e2a7e7f204d1518ec66d5957277073248
> [api] Fixes timeseries extension package name

- api/src/main/java/ai/djl/nn/recurrent/RecurrentBlock.java
- engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArrayEx.java
This fixes issue https://github.com/deepjavalibrary/djl/issues/1936. An unsupported exception is thrown. See https://mxnet.apache.org/versions/master/api/python/docs/api/npx/generated/mxnet.npx.rnn.html
> fix issue in TrainMnistWithLSTM

- extensions/tokenizers/src/main/python/huggingface_converter.py
- extensions/tokenizers/src/main/python/huggingface_models.py
- extensions/tokenizers/src/main/python/metadata.py
- extensions/tokenizers/src/main/python/model_zoo_importer.py
Change-Id: I6c47cd32658d1c1c55b6d9d2b13ef8308eaa7f2f
> [converter] Includes language and downloads in metadata.json

- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDManager.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/IValue.java
- engines/pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/IValueTest.java
Add string tensor support for PyTorch
> Add string tensor support for PyTorch

- extensions/tokenizers/src/main/python/huggingface_converter.py
- extensions/tokenizers/src/main/python/huggingface_models.py
- extensions/tokenizers/src/main/python/metadata.py
Change-Id: I11b751c1fcc7933ddc1315b94c6a9f989601160e
> [huggingface] Update model zoo group id

- api/src/main/java/ai/djl/repository/RepositoryFactoryImpl.java
- api/src/main/java/ai/djl/repository/zoo/DefaultModelZoo.java
- api/src/main/java/ai/djl/repository/zoo/ModelZoo.java
- engines/dlr/dlr-engine/src/main/java/ai/djl/dlr/zoo/DlrModelZoo.java
- engines/mxnet/mxnet-model-zoo/src/main/java/ai/djl/mxnet/zoo/MxModelZoo.java
- engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/zoo/OrtModelZoo.java
- engines/paddlepaddle/paddlepaddle-model-zoo/src/main/java/ai/djl/paddlepaddle/zoo/PpModelZoo.java
- engines/pytorch/pytorch-model-zoo/src/main/java/ai/djl/pytorch/zoo/PtModelZoo.java
- engines/tensorflow/tensorflow-model-zoo/src/main/java/ai/djl/tensorflow/zoo/TfModelZoo.java
- engines/tflite/tflite-engine/src/main/java/ai/djl/tflite/zoo/TfLiteModelZoo.java
- examples/src/test/java/ai/djl/examples/inference/InstanceSegmentationTest.java
- examples/src/test/java/ai/djl/examples/inference/ListModelsTest.java
- extensions/fasttext/src/main/java/ai/djl/fasttext/zoo/FtModelZoo.java
- model-zoo/src/main/java/ai/djl/basicmodelzoo/BasicModelZoo.java
Change-Id: I2f91152719b53f630cfda974f1f3238ef52fd71d
> [api] Refactor ModelZoo implemenation

- extensions/tokenizers/README.md
Add readme to instruct how to use tokenizer
> add tokenizer readme for usage

- api/src/main/java/ai/djl/repository/RepositoryFactoryImpl.java
Change-Id: I986eddca7d89df5572244ba834493785053979b9
> [api] Fixes path parsing bug on Windows

- api/src/main/java/ai/djl/training/dataset/ArrayDataset.java
- api/src/main/java/ai/djl/training/dataset/BulkDataIterable.java
> Return Batches with ArrayDataset helpers

- extensions/tokenizers/src/main/python/.gitignore
- extensions/tokenizers/src/main/python/arg_parser.py
- extensions/tokenizers/src/main/python/huggingface_models.py
Change-Id: Iadb53761d022863574fac42125e16c0712910ed2
> [huggingface] Allows retry failed model in model converter

- .github/workflows/native_jni_s3_pytorch_android.yml
- .github/workflows/native_s3_pytorch_android.yml
- .github/workflows/publish_android_packages.yml
Publish android JNI on nightly basis
> [PyTorch] make pytorch jni publish in nightly

- .github/workflows/publish_android_packages.yml
Fix the empty input issue while publishing
> [Android] fix nightly publish failure

- examples/README.md
Change-Id: I2c3df60ada80c9832491ca49f5da74f6e43fdd4e
> Add Semantic segmentation and Speech recognition to README

- docs/quick_start.md
Change-Id: Iaa86bc01de40073a76dfea5133d9ed2e7d769794
> [doc] Fixes youtube link in quick start

- api/README.md
- examples/pom.xml
- gradle.properties
Increase build version to 0.20.0
> Increase build version to 0.20.0

- docs/development/configure_logging.md
- engines/ml/lightgbm/README.md
- extensions/audio/README.md
- extensions/opencv/README.md
- extensions/sentencepiece/README.md
- extensions/tablesaw/README.md
- extensions/timeseries/README.md
- extensions/tokenizers/README.md
- website/javadoc.html
> [docs] Update javadoc links

- .github/workflows/serving_publish.yml
Upload djl-bench release files to S3
> [ci] Upload djl-bench release artifacts to S3

- .github/workflows/serving_publish.yml
Add missing condition for benchmark release
> [ci] Add missing condition for benchmark release

- api/src/main/java/ai/djl/ndarray/index/full/NDIndexFullPick.java
- api/src/main/java/ai/djl/ndarray/index/full/NDIndexFullTake.java
Add the error info to let the user know the change in https://github.com/deepjavalibrary/djl/pull/1869.
Relavant issue: https://github.com/deepjavalibrary/djl/issues/1800
> Info added

- .github/workflows/native_jni_s3_pytorch.yml
- .github/workflows/native_s3_huggingface.yml
> [ci] Add Mac M1 build

- engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/zoo/OrtModelZoo.java
- engines/onnxruntime/onnxruntime-engine/src/test/resources/mlrepo/model/cv/object_detection/ai/djl/onnxruntime/yolo5s/metadata.json
> [ort] Adds yolo5s to OnnxRuntime model zoo

- extensions/tokenizers/src/main/python/arg_parser.py
- extensions/tokenizers/src/main/python/huggingface_converter.py
- extensions/tokenizers/src/main/python/huggingface_models.py
- extensions/tokenizers/src/main/python/model_zoo_importer.py
> [tokenizer] Add cli options to only validate jit model on CPU

- engines/pytorch/pytorch-model-zoo/src/test/resources/mlrepo/model/cv/semantic_segmentation/ai/djl/pytorch/deeplabv3/metadata.json
> [pytorch] Update deeplabv3 model zoo metadata

- api/src/main/java/ai/djl/training/loss/TabNetClassificationLoss.java
- api/src/main/java/ai/djl/training/loss/TabNetLoss.java
- api/src/main/java/ai/djl/training/loss/TabNetRegressionLoss.java
- basicdataset/src/main/java/ai/djl/basicdataset/tabular/TabularDataset.java
- djl-zero/src/main/java/ai/djl/zero/tabular/Tabular.java
- djl-zero/src/main/java/ai/djl/zero/tabular/package-info.java
- examples/src/main/java/ai/djl/examples/training/TrainAirfoilWithTabNet.java
- examples/src/test/java/ai/djl/examples/training/TrainAirfoilWithTabNetTest.java
- integration/src/main/java/ai/djl/integration/tests/model_zoo/tabular/TabNetTest.java
- model-zoo/src/main/java/ai/djl/basicmodelzoo/tabular/TabNet.java
1. checkout the bugs in TabNet and fix them
2. change tabNetLoss as an embedding mode(add L2Loss for it)
3. add Tabular for tabular training in djl-Zero
4. add an example on airfoil dataset on how tabNet should be used and its corresponding test
> TabNet Training

- api/src/test/java/ai/djl/modality/cv/translator/BigGANTranslatorFactoryTest.java
- api/src/test/java/ai/djl/modality/cv/translator/ImageClassificationTranslatorFactoryTest.java
- api/src/test/java/ai/djl/modality/cv/translator/InstanceSegmentationTranslatorFactoryTest.java
- api/src/test/java/ai/djl/modality/cv/translator/SimplePoseTranslatorFactoryTest.java
- api/src/test/java/ai/djl/modality/cv/translator/SingleShotDetectionTranslatorFactoryTest.java
- api/src/test/java/ai/djl/modality/cv/translator/StyleTransferTranslatorFactoryTest.java
- api/src/test/java/ai/djl/modality/cv/translator/YoloTranslatorFactoryTest.java
- api/src/test/java/ai/djl/modality/cv/translator/YoloV5TranslatorFactoryTest.java
- api/src/test/java/ai/djl/modality/cv/translator/package-info.java
> Add some unit tests

- engines/mxnet/mxnet-engine/README.md
> [mxnet] Fixes MXNet engine cu112 document

- api/src/main/java/ai/djl/ndarray/NDArray.java
- api/src/main/java/ai/djl/ndarray/internal/NDFormat.java
- docs/development/development_guideline.md
This also provide a way to show NDArray in JShell.
> [api] Allow show NDArray content in debugger

- docs/mkdocs.yml
This requires a PR that will follow on the serving repo for the re-organization.
> Move serving docs to top level and reorganize

- docs/mkdocs.yml
> Update docs top level memu

- engines/ml/xgboost/src/test/java/ai/djl/ml/xgboost/XgbModelTest.java
- engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtEngine.java
- engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtSymbolBlock.java
- gradle.properties
upgrade onnxruntime and xgboost
> bump up onnxruntime and xgboost

- api/src/main/java/ai/djl/training/loss/SoftmaxCrossEntropyLoss.java
The issue is here https://github.com/deepjavalibrary/djl/issues/2107
> Fix a document issue

- api/src/main/java/ai/djl/util/cuda/CudaUtils.java
> [api] Handle conflict JNA package issue

- .github/workflows/codeql-analysis-java.yml
- .github/workflows/continuous.yml
- .github/workflows/docs.yml
- .github/workflows/native_build_mxnet_osx.yml
- .github/workflows/native_jni_s3_dlr.yml
- .github/workflows/native_jni_s3_paddle.yml
- .github/workflows/native_jni_s3_pytorch.yml
- .github/workflows/native_jni_s3_pytorch_android.yml
- .github/workflows/native_jni_s3_tensorrt.yml
- .github/workflows/native_publish_dlr.yml
- .github/workflows/native_publish_mxnet.yml
- .github/workflows/native_publish_paddle.yml
- .github/workflows/native_publish_pytorch.yml
- .github/workflows/native_publish_tensorflow.yml
- .github/workflows/native_publish_tflite.yml
- .github/workflows/native_s3_dlr.yml
- .github/workflows/native_s3_fasttext.yml
- .github/workflows/native_s3_huggingface.yml
- .github/workflows/native_s3_pytorch.yml
- .github/workflows/native_s3_pytorch_android.yml
- .github/workflows/native_s3_sentencepiece.yml
- .github/workflows/native_s3_tensorflow.yml
- .github/workflows/native_s3_tflite.yml
- .github/workflows/nightly_android.yml
- .github/workflows/nightly_publish.yml
- .github/workflows/publish_android_packages.yml
- .github/workflows/serving_publish.yml
1. Upgrade checkout@v3
2. Upgrade setup-java@v3
3. Upgrade cache@v3
> [ci] Upgrade deprecated github actions

- .github/workflows/continuous.yml
- .github/workflows/docs.yml
- .github/workflows/native_build_mxnet_osx.yml
- .github/workflows/native_jni_s3_paddle.yml
- .github/workflows/native_s3_tflite.yml
- .github/workflows/nightly_publish.yml
> [ci] Upgrade github actions to latest version

- api/src/test/java/ai/djl/nn/convolutional/OutputShapeTest.java
- build.gradle
> [ci] Avoid static setup/tearDown in testng

- .github/workflows/nightly_publish.yml
Upgrade to OSX12 to mitigate paddle issue
> [Paddle] fix mac os build failure

- extensions/tokenizers/rust/src/lib.rs
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizerTest.java
Fixed char offset issues.
fix #2112
> [Tokenizer] fix char offset

- engines/paddlepaddle/paddlepaddle-native/src/main/native/ai_djl_paddlepaddle_jni_PaddleLibrary_inference.cc
- engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_tensor.cc
- integration/src/test/java/ai/djl/integration/IntegrationTests.java
The issue is in https://github.com/deepjavalibrary/djl/issues/2133
The fix is to align the defination of requires_grad in djl and in pytorch.
> Requires grad torch

- engines/ml/xgboost/src/test/java/ai/djl/ml/xgboost/XgbModelTest.java
- gradle.properties
Upgrade to 1.7.1, the latest version
> [XGBoost] xgboost version bump up

- jupyter/tutorial/02_train_your_first_model.ipynb
> [jupyter] Fix ndarry operator warnings show up in Jupyter notebook

- api/src/main/java/ai/djl/translate/ServingTranslatorFactory.java
> [api] Allows non-ServingTranslatorFactory for DJLServing

- api/src/main/java/ai/djl/ndarray/NDArray.java
- api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
- engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
- engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_torch_reduction.cc
- engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayReductionOpTest.java
> add cumprod operator

- .github/workflows/native_jni_s3_pytorch.yml
- .github/workflows/nightly_publish.yml
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java
- engines/pytorch/pytorch-jni/build.gradle
- engines/pytorch/pytorch-native/README.md
- engines/pytorch/pytorch-native/build.cmd
- engines/pytorch/pytorch-native/build.gradle
- engines/pytorch/pytorch-native/build.sh
- gradle.properties
> [pytorch] Upgrade PyTorch to 1.13.0

- .github/workflows/continuous.yml
> [ci] compile JNI only when file changes

- integration/src/main/java/ai/djl/integration/tests/nn/BlockCoreTest.java
> Use Path instead of File

- basicdataset/src/test/resources/mlrepo/dataset/tabular/ai/djl/basicdataset/movielens-100k/metadata.json
> [dataset] Fixes movielens download issue

- extensions/aws-ai/src/test/java/ai/djl/aws/sagemaker/SageMakerTest.java
- model-zoo/src/main/java/ai/djl/basicmodelzoo/cv/object_detection/yolo/YOLOV3.java
> [modelzoo] Fixes Yolov3 javadoc warning

- .github/workflows/native_s3_pytorch_android.yml
- android/gradle.properties
- android/pytorch-native/README.md
> [pytorch] Upgrade PyTorch for Android to 1.13.0

- djl-zero/build.gradle
> [djl-zero] Fixes build dependency for testng

- build.gradle
> [ci] Respect -SNAPSHOT version in jar manifest

- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtEngine.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java
> [pytorch] Reduce nested exception level

- api/build.gradle
- api/src/main/java/ai/djl/engine/Engine.java
- api/src/main/java/ai/djl/util/Ec2Utils.java
- docs/telemetry.md
> [api] Add telemetry report

- engines/onnxruntime/onnxruntime-android/README.md
> Fix ONNXRuntime Android doc

- android/README.md
- android/pytorch-native/README.md
Increase DJL version to 0.20.0 for android
> Increase DJL version to 0.20.0 for android

- .github/workflows/continuous.yml
- .github/workflows/docs.yml
- .github/workflows/native_jni_s3_pytorch_android.yml
- .github/workflows/native_publish_dlr.yml
- .github/workflows/native_publish_mxnet.yml
- .github/workflows/native_publish_paddle.yml
- .github/workflows/native_publish_tensorflow.yml
- .github/workflows/native_publish_tflite.yml
- .github/workflows/native_s3_pytorch_android.yml
- .github/workflows/native_s3_tensorflow.yml
- .github/workflows/nightly_publish.yml
- .github/workflows/publish_android_packages.yml
- .github/workflows/serving_publish.yml
> [ci] Use ubuntu-latest as runner

- jupyter/tutorial/02_train_your_first_model.ipynb
> [jupyter] Remove SNAPSHOT in jupyter notebook

- api/README.md
- docs/get.md
- examples/pom.xml
- gradle.properties
Increase build version to 0.21.0
> Increase build version to 0.21.0

- .github/workflows/docs.yml
- .github/workflows/native_jni_s3_dlr.yml
- .github/workflows/native_jni_s3_paddle.yml
- .github/workflows/native_jni_s3_pytorch.yml
- .github/workflows/native_jni_s3_pytorch_android.yml
- .github/workflows/native_jni_s3_tensorrt.yml
- .github/workflows/native_s3_dlr.yml
- .github/workflows/native_s3_fasttext.yml
- .github/workflows/native_s3_huggingface.yml
- .github/workflows/native_s3_pytorch.yml
- .github/workflows/native_s3_pytorch_android.yml
- .github/workflows/native_s3_sentencepiece.yml
- .github/workflows/native_s3_tensorflow.yml
- .github/workflows/native_s3_tflite.yml
- .github/workflows/nightly_publish.yml
- .github/workflows/serving_publish.yml
> [ci] Updates configure-aws-credentials to v1-node16

- djl-zero/README.md
> Fix djl-zero doc

- .github/workflows/native_jni_s3_pytorch.yml
- engines/pytorch/pytorch-native/build.cmd
- engines/pytorch/pytorch-native/src/main/patch/1.11.0/Parallel.h
- engines/pytorch/pytorch-native/src/main/patch/1.12.1/Parallel.h
- engines/pytorch/pytorch-native/src/main/patch/1.13.0/Parallel.h
> [ci] Workaround PyTorch JNI build issue with VS 17.4.0

- api/src/main/java/ai/djl/repository/zoo/BaseModelLoader.java
> [api] Fixes nested model directory issue

- android/README.md
- android/core/build.gradle
> [android] Fixes gradle dependencies

- engines/dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrNDManager.java
- engines/ml/lightgbm/src/main/java/ai/djl/ml/lightgbm/LgbmNDManager.java
- engines/ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbNDManager.java
- engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDManager.java
- engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtNDManager.java
- engines/paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpNDManager.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDManager.java
- engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDManager.java
- engines/tensorrt/src/main/java/ai/djl/tensorrt/engine/TrtNDManager.java
- engines/tflite/tflite-engine/src/main/java/ai/djl/tflite/engine/TfLiteNDManager.java
Fix name passing bugs on the ndarrays
> fix the name passing bug

- .github/workflows/serving_publish.yml
> [ci] Allows publish djl-serving from a branch

- bom/build.gradle
- engines/onnxruntime/onnxruntime-engine/README.md
> [onnx] Update onnx version in README file

- .github/workflows/serving_publish.yml
> fix the content format

- basicdataset/build.gradle
- build.gradle
- docs/quick_start.md
- engines/ml/lightgbm/build.gradle
- engines/ml/xgboost/build.gradle
- engines/mxnet/mxnet-engine/build.gradle
- engines/mxnet/mxnet-model-zoo/build.gradle
- engines/onnxruntime/onnxruntime-engine/build.gradle
- engines/paddlepaddle/paddlepaddle-engine/build.gradle
- engines/paddlepaddle/paddlepaddle-model-zoo/build.gradle
- engines/tensorflow/tensorflow-engine/build.gradle
- engines/tensorflow/tensorflow-model-zoo/build.gradle
- engines/tflite/tflite-engine/build.gradle
- examples/pom.xml
- extensions/audio/build.gradle
- extensions/fasttext/build.gradle
- extensions/hadoop/build.gradle
- extensions/opencv/build.gradle
- extensions/sentencepiece/build.gradle
- extensions/spark/build.gradle
- extensions/tablesaw/build.gradle
- extensions/timeseries/build.gradle
- extensions/tokenizers/build.gradle
- gradle.properties
- integration/build.gradle
- testing/build.gradle
> [ci] Upgrade testng to 7.7.0

- extensions/tokenizers/src/test/java/ai/djl/huggingface/zoo/ModelZooTest.java
> [tokenizer] Avoid unittest polluting cache directory.

- docs/pytorch/how_to_convert_your_model_to_torchscript.md
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/IValueUtils.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
- engines/pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/TorchScriptTest.java
- engines/pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/jni/IValueUtilsTest.java
- engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_inference.cc
Support run different methods on pytorch with different names
> [PyTorch] use runMethod to replace forward function

- engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxEngine.java
- engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxEngineProvider.java
- engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtEngineProvider.java
Makes usage of Engine.RANK consistent across engine providers.
> Fix inconsistencies using RANK in engine providers

- .github/workflows/native_s3_pytorch_android.yml
- engines/pytorch/pytorch-engine/README.md
- engines/pytorch/pytorch-native/src/main/patch/1.13.1/Parallel.h
- gradle.properties
> [pytorch] Upgrade to PyTorch 1.13.1

- engines/onnxruntime/onnxruntime-engine/README.md
> [onnx] Fixes Onnx version in README

- .github/workflows/native_jni_s3_pytorch.yml
- engines/pytorch/pytorch-native/build.gradle
- engines/pytorch/pytorch-native/build.sh
> [ci] Build cu102 JNI for PyTorch 1.11.0 and 1.12.1

- api/src/test/java/ai/djl/ndarray/internal/NDFormatTest.java
> [api] Fixes unittest failure on GPU

- engines/ml/lightgbm/src/main/java/ai/djl/ml/lightgbm/jni/LibUtils.java
> [lightGBM] Fixes atomic move issue

- api/src/main/java/ai/djl/ndarray/NDArray.java
- api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
- api/src/main/java/ai/djl/ndarray/NDManager.java
- api/src/main/java/ai/djl/ndarray/types/DataType.java
- engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDManager.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
- engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_torch_creation.cc
- engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_torch_other.cc
- engines/pytorch/pytorch-native/src/main/native/djl_pytorch_utils.h
- engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
- extensions/audio/src/main/java/ai/djl/audio/processor/LinearSpecgram.java
- extensions/audio/src/test/java/ai/djl/audio/processor/AudioProcessorTest.java
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayCreationOpTest.java
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayOtherOpTest.java
Build forier transform operator and complex64 type support on DJL.
> [Audio] add stft and fft forier transform

- engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_torch_creation.cc
- engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_torch_other.cc
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextEmbeddingTranslator.java
- extensions/tokenizers/src/main/python/fill_mask_converter.py
- extensions/tokenizers/src/main/python/huggingface_converter.py
- extensions/tokenizers/src/main/python/sentence_similarity_converter.py
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/TranslatorTest.java
> [tokenizer] Adds more pooling mode form TextEmbedding

- engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_torch_creation.cc
> [pytorch] Workaround hann_window issue for PyTorch 1.12.1

- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
- engines/pytorch/pytorch-native/CMakeLists.txt
- engines/pytorch/pytorch-native/build.cmd
- engines/pytorch/pytorch-native/build.sh
- engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_torch_other.cc
> [pytorch] Makes JNI comptible with PyTorch 1.11.0

- examples/pom.xml
> [examples] Adds tensorflow dependency to pom.xml

- examples/src/test/java/ai/djl/examples/inference/SpeechRecognitionTest.java
- examples/src/test/java/ai/djl/examples/inference/clip/ClipModelTest.java
- examples/src/test/java/ai/djl/examples/training/TrainTicTacToeTest.java
> [examples] Fixes PyTorch nightly test

- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextEmbeddingTranslator.java
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/TranslatorTest.java
> [tokenizer] Adds mean_sqrt_len and weightedmean pooling for TextEmbedding

- extensions/aws-ai/src/test/java/ai/djl/aws/sagemaker/SageMakerTest.java
> [extension] Fixes SageMaker unitest permission issue

- api/src/main/java/ai/djl/ndarray/NDManager.java
- engines/paddlepaddle/paddlepaddle-engine/src/test/java/ai/djl/paddlepaddle/jni/JniUtilsTest.java
- examples/src/main/java/ai/djl/examples/inference/timeseries/AirPassengersDeepAR.java
> [api] Adds newBaseManager(String engineName) api

- api/src/main/java/ai/djl/ndarray/NDArrays.java
- api/src/main/java/ai/djl/ndarray/NDUtils.java
- api/src/test/java/ai/djl/ndarray/NDUtilsTest.java
- engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
- engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
- extensions/opencv/src/test/java/ai/djl/opencv/OpenCVImageFactoryTest.java
- extensions/sentencepiece/src/test/java/ai/djl/sentencepiece/SpTokenizerTest.java
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayElementArithmeticOpTest.java
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayElementComparisonOpTest.java
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayOtherOpTest.java
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayShapesManipulationOpTest.java
1. Fixes contentEquals bug for boolean type
2. Add NDUtilsTest
> [integration] Increase test coverage for NDArrays.java

- docs/engine.md
- docs/mkdocs.yml
> [docs] Update README for engines

- docs/mkdocs.yml
> [docs] Adds extensions to docs web page

- api/src/main/java/ai/djl/modality/Input.java
- api/src/main/java/ai/djl/modality/nlp/preprocess/HyphenNormalizer.java
- api/src/main/java/ai/djl/training/dataset/RandomAccessDataset.java
> [pmd] Fixes PMD 6.21.0 reported issues

- api/src/main/java/ai/djl/engine/Engine.java
- engines/dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrEngine.java
- engines/ml/lightgbm/src/main/java/ai/djl/ml/lightgbm/LgbmEngine.java
- engines/ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbEngine.java
- engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxEngine.java
- engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtEngine.java
- engines/paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpEngine.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtEngine.java
- engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfEngine.java
- engines/tensorrt/src/main/java/ai/djl/tensorrt/engine/TrtEngine.java
- engines/tflite/tflite-engine/src/main/java/ai/djl/tflite/engine/TfLiteEngine.java
> [api] Refactor Engine class

- integration/src/main/java/ai/djl/integration/util/DebugEnvironment.java
> [ci] Fixes jdk18 compile error

- api/src/main/java/ai/djl/nn/norm/LayerNorm.java
This change would help me in a particular project.
> opened LayerNorm.Builder for inheritance

- engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/jna/LibUtils.java
> [mxnet] Allows MXNet runs on Ampere GPU

- api/src/main/java/ai/djl/modality/audio/Audio.java
- api/src/main/java/ai/djl/modality/audio/AudioFactory.java
- api/src/main/java/ai/djl/modality/audio/SampledAudioFactory.java
- api/src/test/java/ai/djl/modality/audio/AudioFactoryTest.java
- examples/build.gradle
- examples/docs/whisper_speech_text.md
- examples/src/main/java/ai/djl/examples/inference/SpeechRecognition.java
- examples/src/main/java/ai/djl/examples/inference/whisper/SpeechToTextGeneration.java
- examples/src/main/java/ai/djl/examples/inference/whisper/WhisperModel.java
- examples/src/main/java/ai/djl/examples/inference/whisper/WhisperTranslator.java
- examples/src/main/java/ai/djl/examples/inference/whisper/package-info.java
- extensions/audio/src/main/java/ai/djl/audio/FFmpegAudioFactory.java
- extensions/audio/src/main/java/ai/djl/audio/processor/LogMelSpectrogram.java
- extensions/audio/src/main/java/ai/djl/audio/processor/PadOrTrim.java
- extensions/audio/src/test/java/ai/djl/audio/FFmpegAudioFactoryTest.java
- extensions/audio/src/test/java/ai/djl/audio/processor/AudioProcessorTest.java
Add OpenAI Whisper model to DJL
> add openai whisper model

- api/src/main/java/ai/djl/modality/nlp/translator/TextEmbeddingServingTranslator.java
- api/src/main/java/ai/djl/translate/Translator.java
- api/src/test/java/ai/djl/translate/TranslatorTest.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextEmbeddingBatchTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextEmbeddingTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextEmbeddingTranslatorFactory.java
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/TranslatorTest.java
> [tokenizer] Adds batch support for TextEmbeddingTranslator

- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextEmbeddingTranslator.java
- extensions/tokenizers/src/main/python/sentence_similarity_converter.py
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/TranslatorTest.java
> [tokenizer] Update TextEmbedding pooling model name

- extensions/tokenizers/build.gradle
- extensions/tokenizers/src/main/java/ai/djl/huggingface/zoo/HfModelZoo.java
- extensions/tokenizers/src/main/python/huggingface_converter.py
- extensions/tokenizers/src/test/java/ai/djl/huggingface/zoo/ModelZooTest.java
> [tokenizer] Allows Huggingface model zoo list models in offline mode

- .github/workflows/native_s3_sentencepiece.yml
- extensions/sentencepiece/build.gradle
- extensions/sentencepiece/build.sh
> [sentencepiece] Build macOS M1 and aarch64 JNI for sentencepiece

- extensions/sentencepiece/src/test/java/ai/djl/sentencepiece/SpTextEmbeddingTest.java
- extensions/sentencepiece/src/test/java/ai/djl/sentencepiece/SpTokenizerTest.java
- extensions/sentencepiece/src/test/java/ai/djl/sentencepiece/SpVocabularyTest.java
> [sentencepiece] Adds aarch64 support for sentencepiece

- docs/faq.md
> [doc] Updates FAQ

- extensions/timeseries/build.gradle
> [timeseries] Remove unnecessary dependency

- examples/build.gradle
> [example] Workaround AudioGrabber bug for whisper model issue

- api/src/main/java/ai/djl/ndarray/NDArray.java
- api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
- engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
- engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_tensor.cc
- engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDIndexTest.java
> Add scatter function to PtNDArray

- docs/development/cache_management.md
> [doc] Updates cache menagement adds ONNX and Huggingface cache directory

- api/src/main/java/ai/djl/util/Platform.java
- api/src/main/java/ai/djl/util/Utils.java
- engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxModel.java
- engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/jna/JnaUtils.java
- engines/paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpModel.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtModel.java
- engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfModel.java
- examples/src/main/java/ai/djl/examples/inference/BertClassification.java
- examples/src/main/java/ai/djl/examples/inference/UniversalSentenceEncoder.java
- extensions/fasttext/src/main/java/ai/djl/fasttext/FtModel.java
- extensions/fasttext/src/main/java/ai/djl/fasttext/FtTrainingConfig.java
- extensions/sentencepiece/src/main/java/ai/djl/sentencepiece/SpTokenizer.java
- extensions/tokenizers/rust/src/lib.rs
- extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizer.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/jni/TokenizersLibrary.java
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizerTest.java
> [tokenizer] Adds batchEncode for text pair

- extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/Encoding.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizer.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/FillMaskTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/QuestionAnsweringTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextClassificationTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextEmbeddingBatchTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextEmbeddingTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TokenClassificationTranslator.java
> [tokenizer] Minor refactor encoding class

- examples/src/main/java/ai/djl/examples/inference/whisper/SpeechToTextGeneration.java
- examples/src/main/java/ai/djl/examples/inference/whisper/WhisperTranslator.java
The lifespan of AudioProcessor should at least match the model
> [example] Fixes whisper model translator

- api/src/main/java/ai/djl/modality/nlp/translator/TextClassificationServingTranslator.java
- api/src/main/java/ai/djl/modality/nlp/translator/TextEmbeddingServingTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextClassificationBatchTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextClassificationTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextClassificationTranslatorFactory.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextEmbeddingTranslator.java
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/TextClassificationTranslatorTest.java
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/TextEmbeddingTranslatorTest.java
- [tokenizer] Minor refactor encoding class
- [tokenizer] Split TranslatorTest into smaller test classes.
- [tokenizer] Adds batch encoding support for text classification
> [tokenizer] Adds batch encoding support for text classification

- api/src/main/java/ai/djl/modality/nlp/translator/TokenClassificationServingTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TokenClassificationBatchTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TokenClassificationTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TokenClassificationTranslatorFactory.java
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/TokenClassificationTranslatorTest.java
- [tokenizer] Minor refactor encoding class
- [tokenizer] Split TranslatorTest into smaller test classes.
- [tokenizer] Adds batch encoding support for token classification
> [tokenizer] Adds batch encoding support for token classification

- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/FillMaskBatchTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/FillMaskTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/FillMaskTranslatorFactory.java
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/FillMaskTranslatorTest.java
> [tokenizer] Adds batch encoding support for FillMask

- api/src/main/java/ai/djl/modality/nlp/qa/QAInput.java
- api/src/main/java/ai/djl/modality/nlp/translator/QaServingTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/QuestionAnsweringBatchTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/QuestionAnsweringTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/QuestionAnsweringTranslatorFactory.java
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/QuestionAnsweringTranslatorTest.java
> [tokenizer] [tokenizer] Adds batch encoding support for question answering

- docs/README.md
- extensions/spark/.gitignore
- extensions/spark/README.md
- extensions/spark/setup/PyPiDescription.rst
- extensions/spark/setup/__init__.py
- extensions/spark/setup/djl_spark/__init__.py
- extensions/spark/setup/djl_spark/transformer.py
- extensions/spark/setup/djl_spark/translator.py
- extensions/spark/setup/setup.py
- extensions/spark/src/main/scala/ai/djl/spark/SparkModel.scala
- extensions/spark/src/main/scala/ai/djl/spark/SparkTransformer.scala
> Add pyspark support

- extensions/spark/build.gradle
- extensions/spark/setup/djl_spark/transformer.py
- extensions/spark/setup/djl_spark/translator.py
> [spark] Format python code

- api/src/main/java/ai/djl/util/passthrough/PassthroughNDArray.java
- api/src/main/java/ai/djl/util/passthrough/PassthroughNDManager.java
- extensions/fasttext/build.gradle
- extensions/fasttext/src/main/java/ai/djl/fasttext/jni/LibUtils.java
- extensions/fasttext/src/test/java/ai/djl/fasttext/CookingStackExchangeTest.java
> [fastText] fastText should not depends on any engine

- api/src/main/java/ai/djl/util/passthrough/PassthroughNDArray.java
- tools/gradle/publish.gradle
> [api] Set NDManager for PassthroughNDArray

- api/src/main/java/ai/djl/ndarray/NDList.java
- api/src/main/java/ai/djl/ndarray/NDManager.java
- api/src/main/java/ai/djl/ndarray/NDSerializer.java
- api/src/main/java/ai/djl/ndarray/types/Shape.java
> [api] Improve NDArray encode/decode performance

- api/src/main/java/ai/djl/metric/Metrics.java
- api/src/test/java/ai/djl/metric/MetricsTest.java
> [api] Adds limit and callback for Metrics

- docs/mkdocs.yml
> [docs] Adds missing DJLServing docs menu items

- api/src/main/java/ai/djl/Model.java
- engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtModel.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtModel.java
- engines/pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/PtModelTest.java
- examples/src/test/java/ai/djl/examples/training/TrainAirfoilWithTabNetTest.java
> [api] Search for model.pt or model.onnx when loading the model

- api/src/main/java/ai/djl/nn/Parameter.java
> [api] Fixes NPE if block is cleard before training

- extensions/hadoop/build.gradle
> [hdfs] Reduce hadoop extension dependencies

- docs/development/inference_performance_optimization.md
> [docs] Update pytorch graph exector optimization document

- extensions/spark/.gitignore
- extensions/spark/setup/djl_spark/task/__init__.py
- extensions/spark/setup/djl_spark/task/text/__init__.py
- extensions/spark/setup/djl_spark/task/vision/__init__.py
- extensions/spark/setup/djl_spark/task/vision/image_classifier.py
- extensions/spark/setup/djl_spark/translator/__init__.py
- extensions/spark/setup/djl_spark/translator/vision/__init__.py
- extensions/spark/setup/djl_spark/translator/vision/translator.py
- extensions/spark/setup/setup.py
- extensions/spark/src/main/scala/ai/djl/spark/ModelLoader.scala
- extensions/spark/src/main/scala/ai/djl/spark/task/BasePredictor.scala
- extensions/spark/src/main/scala/ai/djl/spark/task/text/TextEmbedder.scala
- extensions/spark/src/main/scala/ai/djl/spark/task/text/TextPredictor.scala
- extensions/spark/src/main/scala/ai/djl/spark/task/vision/ImageClassifier.scala
- extensions/spark/src/main/scala/ai/djl/spark/task/vision/ImagePredictor.scala
- extensions/spark/src/main/scala/ai/djl/spark/translator/text/TextEmbeddingTranslator.scala
- extensions/spark/src/main/scala/ai/djl/spark/translator/vision/ImageClassificationTranslator.scala
[spark] Refactor Spark extension API
> [spark] Refactor Spark extension API

- api/src/main/java/ai/djl/util/Ec2Utils.java
- extensions/sentencepiece/src/main/java/ai/djl/sentencepiece/SpProcessor.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizer.java
> [api] Adds telemtry for Huggingface and SentencePiece

- api/src/main/java/ai/djl/training/dataset/RawDataset.java
- basicdataset/src/main/java/ai/djl/basicdataset/nlp/CookingStackExchange.java
- basicdataset/src/main/java/ai/djl/basicdataset/nlp/StanfordQuestionAnsweringDataset.java
- basicdataset/src/main/java/ai/djl/basicdataset/nlp/WikiText2.java
- extensions/fasttext/build.gradle
- extensions/fasttext/src/main/java/ai/djl/fasttext/TrainFastText.java
- extensions/fasttext/src/main/java/ai/djl/fasttext/zoo/nlp/textclassification/FtTextClassification.java
- extensions/sentencepiece/build.gradle
> [api] Moves RawDataset from basicdata to api module

- android/gradle.properties
> [android] Upgrade DJL version to 0.21.0

- api/src/main/java/ai/djl/ndarray/NDArray.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
- engines/pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/PtNDArrayTest.java
- examples/src/main/java/ai/djl/examples/inference/BertQaInference.java
> [pytorch] Better handle String tensor operations

- docs/cv_utils.md
- docs/development/cache_management.md
- docs/development/configure_logging.md
- docs/development/inference_performance_optimization.md
- docs/development/troubleshooting.md
- docs/mkdocs.yml
- docs/model-zoo.md
- engines/mxnet/mxnet-engine/README.md
- engines/onnxruntime/onnxruntime-engine/README.md
- engines/pytorch/pytorch-engine/README.md
> [docs] Improve documents

- docker/spark/Dockerfile
- extensions/spark/build.gradle
- extensions/spark/src/main/scala/ai/djl/spark/ModelLoader.scala
- extensions/spark/src/main/scala/ai/djl/spark/task/BasePredictor.scala
- extensions/spark/src/main/scala/ai/djl/spark/task/text/HuggingFaceTextDecoder.scala
- extensions/spark/src/main/scala/ai/djl/spark/task/text/HuggingFaceTextEncoder.scala
- extensions/spark/src/main/scala/ai/djl/spark/task/text/HuggingFaceTextTokenizer.scala
- extensions/spark/src/main/scala/ai/djl/spark/task/vision/ImageClassifier.scala
Add HuggingFace tokenizer in Spark extension
> [spark] Integrate HuggingFace tokenizer

- api/src/main/java/ai/djl/repository/zoo/Criteria.java
- api/src/test/java/ai/djl/repository/ZooTest.java
> [api] Improve Criteria.build() error message

- .github/workflows/native_s3_sentencepiece.yml
> [sentencepiece] Adds centos 7 support

- extensions/spark/setup/djl_spark/task/binary/__init__.py
- extensions/spark/setup/djl_spark/task/binary/binary_predictor.py
- extensions/spark/src/main/scala/ai/djl/spark/task/binary/BinaryPredictor.scala
- extensions/spark/src/main/scala/ai/djl/spark/translator/binary/NpBinaryTranslator.scala
> [spark] Add Numpy binary translator

- android/README.md
- android/build.gradle
- android/core/build.gradle
- android/pytorch-native/build.gradle
> [android] Updates android dependency import

- api/README.md
- examples/pom.xml
- gradle.properties
> Bump up DJL version to 0.22.0-SNAPSHOT

- extensions/spark/setup/djl_spark/task/text/__init__.py
- extensions/spark/setup/djl_spark/task/text/huggingface_text_decoder.py
- extensions/spark/setup/djl_spark/task/text/huggingface_text_encoder.py
- extensions/spark/setup/djl_spark/task/text/huggingface_text_tokenizer.py
- extensions/spark/setup/djl_spark/task/text/text_embedder.py
- extensions/spark/setup/djl_spark/task/vision/image_classifier.py
> [spark] Add pyspark TextEmbedder and update ImageClassifier

- api/src/main/java/ai/djl/ndarray/index/NDArrayIndexer.java
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDIndexTest.java
Fix issue https://github.com/deepjavalibrary/djl/issues/2424
> Enable boolean index on mxnet

- docker/spark/Dockerfile
- extensions/spark/setup/djl_spark/util/__init__.py
- extensions/spark/setup/djl_spark/util/np_util.py
> [spark] Add np_util

- engines/pytorch/pytorch-model-zoo/src/main/java/ai/djl/pytorch/zoo/PtModelZoo.java
- engines/pytorch/pytorch-model-zoo/src/test/resources/mlrepo/model/cv/object_detection/ai/djl/pytorch/yolov5s/metadata.json
> [pytorch] Adds yolov5s to pytorch model zoo

- engines/pytorch/pytorch-engine/README.md
> [pytorch] Update pytorch engine version document

- api/src/main/java/ai/djl/ndarray/BytesSupplier.java
- api/src/main/java/ai/djl/ndarray/NDArray.java
- api/src/main/java/ai/djl/ndarray/NDSerializer.java
> [api] Fixes NDArray.toByteArray() bug

- api/src/main/java/ai/djl/ndarray/BaseNDManager.java
- api/src/main/java/ai/djl/ndarray/NDArray.java
- api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
- engines/ml/lightgbm/src/main/java/ai/djl/ml/lightgbm/LgbmNDArray.java
- engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
- engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayElementArithmeticOpTest.java
- testing/src/main/java/ai/djl/testing/Assertions.java
> [api] Adds NDArray.copyTo() support for NDArrayAdapter

- api/src/main/java/ai/djl/translate/Batchifier.java
- api/src/main/java/ai/djl/translate/PaddingStackBatchifier.java
- api/src/main/java/ai/djl/translate/SimplePaddingStackBatchifier.java
- api/src/main/java/ai/djl/translate/StackBatchifier.java
> [api] Make Batchifier serializable

- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/FillMaskTranslatorFactory.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/QuestionAnsweringTranslatorFactory.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextClassificationTranslatorFactory.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextEmbeddingTranslatorFactory.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TokenClassificationTranslatorFactory.java
Make Huggingface tokenizers translator factory serializable
> [tokenizers] Make Huggingface tokenizers translator factory serializable

- api/src/main/java/ai/djl/modality/Classifications.java
> [api] Improve Classifications.toString() print out

- engines/mxnet/mxnet-engine/build.gradle
- gradle/wrapper/gradle-wrapper.properties
> [ci] Upgrade gradle to 8.0.2

- api/src/main/java/ai/djl/modality/ChunkedBytesSupplier.java
- api/src/main/java/ai/djl/ndarray/BytesSupplier.java
- api/src/test/java/ai/djl/modality/ChunkedBytesSupplierTest.java
> [api] Adds chunked output support

- engines/mxnet/native/build.gradle
- engines/paddlepaddle/paddlepaddle-native/build.gradle
- engines/pytorch/pytorch-native/build.gradle
- engines/tensorflow/tensorflow-native/build.gradle
> [ci] Fixes gradle 8.0 native publish issue

- docs/development/troubleshooting.md
- docs/faq.md
> [docs] Update FAQ and troubleshooting documents

- api/src/main/java/ai/djl/ndarray/NDArray.java
- api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
- engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
- engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_torch_isjm.cc
- engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayShapesManipulationOpTest.java
The implementation is aligned with the document https://pytorch.org/docs/stable/generated/torch.unique.html
Solves the issue https://github.com/deepjavalibrary/djl/issues/2407.
> [api] Implement unique for PyTorch engine

- engines/mxnet/native/build.gradle
- engines/paddlepaddle/paddlepaddle-native/build.gradle
- engines/pytorch/pytorch-native/build.gradle
- engines/tensorflow/tensorflow-native/build.gradle
> [ci] Fixes gradle 8.0 publish to release issue

- api/src/main/java/ai/djl/modality/audio/translator/SpeechRecognitionTranslatorFactory.java
- api/src/main/java/ai/djl/modality/cv/output/CategoryMask.java
- api/src/main/java/ai/djl/modality/cv/translator/BigGANTranslatorFactory.java
- api/src/main/java/ai/djl/modality/cv/translator/ImageClassificationTranslatorFactory.java
- api/src/main/java/ai/djl/modality/cv/translator/ImageFeatureExtractorFactory.java
- api/src/main/java/ai/djl/modality/cv/translator/InstanceSegmentationTranslatorFactory.java
- api/src/main/java/ai/djl/modality/cv/translator/SemanticSegmentationTranslatorFactory.java
- api/src/main/java/ai/djl/modality/cv/translator/SimplePoseTranslatorFactory.java
- api/src/main/java/ai/djl/modality/cv/translator/SingleShotDetectionTranslatorFactory.java
- api/src/main/java/ai/djl/modality/cv/translator/StyleTransferTranslatorFactory.java
- api/src/main/java/ai/djl/modality/cv/translator/YoloTranslatorFactory.java
- api/src/main/java/ai/djl/modality/cv/translator/YoloV5TranslatorFactory.java
- engines/paddlepaddle/paddlepaddle-model-zoo/src/main/java/ai/djl/paddlepaddle/zoo/cv/imageclassification/PpImageClassificationTranslatorFactory.java
- engines/paddlepaddle/paddlepaddle-model-zoo/src/main/java/ai/djl/paddlepaddle/zoo/cv/imageclassification/PpWordRotateTranslatorFactory.java
Make audio and cv translator factory serializable in order for the spark extension to use them.
> [api] Make audio and cv translator factory serializable

- extensions/tokenizers/src/main/java/ai/djl/huggingface/zoo/HfModelZoo.java
> [huggingface] Makes Huggingface model zoo lazy load

- api/src/main/java/ai/djl/modality/nlp/translator/NamedEntity.java
> [api] Adds NamedEntity.toString() function

- api/src/main/java/ai/djl/util/ClassLoaderUtils.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/jni/LibUtils.java
> [huggingface] Allows tokenizer native library load from different classloader

- api/src/main/java/ai/djl/util/ZipUtils.java
- api/src/test/java/ai/djl/util/ZipUtilsTest.java
> [api] Mitigates ZipInputStream CVE.

- api/src/main/java/ai/djl/BaseModel.java
- api/src/main/java/ai/djl/Model.java
- api/src/main/java/ai/djl/repository/zoo/ZooModel.java
- extensions/fasttext/src/main/java/ai/djl/fasttext/FtModel.java
- extensions/fasttext/src/test/java/ai/djl/fasttext/CookingStackExchangeTest.java
> [api] Adds getProperties() to Model interface

- docs/development/profiler.md
- engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtModel.java
- engines/onnxruntime/onnxruntime-engine/src/test/java/ai/djl/onnxruntime/engine/OrtTest.java
> Add support for OnnxRuntime Profiler

- api/src/main/java/ai/djl/util/Ec2Utils.java
IMDSv2 doesn’t work as sagemaker block IMDSv2 calls due to security reason. So if running on sagemaker, we can read instance id from sagemaker infra metadata file. A sample metadata file looks like this:
```
{
"ResourceId": "i-0c924c144107d9273",
"VariantName": "variant1",
"EndpointArn": "arn:aws:sagemaker:us-east-1:125045733377:endpoint/opt30b-djl20-ds-2023-03-25-00-06-00-824-endpoint"
}
```
> [api] Read telemetry metadata from file for sagemaker endpoint

- api/src/main/java/ai/djl/util/Ec2Utils.java
- docs/telemetry.md
> [api] Fixes telemetry opt out

- api/src/main/java/ai/djl/repository/AbstractRepository.java
- api/src/main/java/ai/djl/repository/JarRepository.java
- api/src/main/java/ai/djl/repository/SimpleRepository.java
- api/src/main/java/ai/djl/repository/SimpleUrlRepository.java
- api/src/main/java/ai/djl/util/Hex.java
- api/src/main/java/ai/djl/util/Utils.java
- extensions/aws-ai/src/main/java/ai/djl/aws/s3/S3Repository.java
- extensions/hadoop/src/main/java/ai/djl/hadoop/hdfs/HdfsRepository.java
> [api] Uses sha-256 to avoid security warning

- api/src/main/java/ai/djl/util/NeuronUtils.java
- api/src/test/java/ai/djl/util/NeuronUtilsTest.java
> [api] Moves NeuronUtils to api package

- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtEngine.java
> Print log if graph optimizer is enabled

- engines/ml/xgboost/src/test/java/ai/djl/ml/xgboost/XgbModelTest.java
- gradle.properties
> bump up xgboost

- engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtEngine.java
- engines/onnxruntime/onnxruntime-engine/src/test/java/ai/djl/onnxruntime/engine/OrtTest.java
> [onnxruntime] Fixes OnnxRuntime version

- examples/docs/mask_detection.md
> [doc] Link fixes to doc Mask detection with YOLOv5

- api/src/main/java/ai/djl/util/NeuronUtils.java
- api/src/test/java/ai/djl/util/NeuronUtilsTest.java
> [api] Fixes neuron core detection in docker container

- api/src/main/java/ai/djl/modality/cv/translator/ObjectDetectionTranslator.java
- engines/onnxruntime/onnxruntime-engine/src/test/resources/mlrepo/model/cv/object_detection/ai/djl/onnxruntime/yolo5s/metadata.json
- engines/pytorch/pytorch-model-zoo/src/test/resources/mlrepo/model/cv/object_detection/ai/djl/pytorch/yolov5s/metadata.json
> [pytorch] Fixes yolov5s model zoo metadata

- engines/pytorch/pytorch-native/build.gradle
> [pytorch] Fixes missing libnvfuser_codegen.so

- .github/workflows/docker_publish.yml
- docker/spark/Dockerfile
> [spark] Support SageMaker processing

- android/gradle.properties
> Upgrade android project to 0.22.1

- examples/pom.xml
- gradle.properties
> Bump up DJL version to 0.23.0-SNAPSHOT

- .github/workflows/serving_publish.yml
> [ci] Fixes djl-serving release publish workflow script

- api/src/main/java/ai/djl/inference/streaming/ChunkedBytesSupplier.java
- api/src/test/java/ai/djl/inference/streaming/ChunkedBytesSupplierTest.java
> [api] Refactor ChunkedBytesSupplier to avoid unecessary convertion

- api/src/main/java/ai/djl/repository/RepositoryFactoryImpl.java
> [api] Fixes LocalRepository detection

- extensions/spark/src/main/scala/ai/djl/spark/task/audio/SpeechRecognizer.scala
- extensions/spark/src/main/scala/ai/djl/spark/task/binary/BinaryPredictor.scala
- extensions/spark/src/main/scala/ai/djl/spark/task/text/TextClassifier.scala
- extensions/spark/src/main/scala/ai/djl/spark/task/vision/ImageClassifier.scala
- extensions/spark/src/main/scala/ai/djl/spark/task/vision/ImageEmbedder.scala
- extensions/spark/src/main/scala/ai/djl/spark/task/vision/InstanceSegmenter.scala
- extensions/spark/src/main/scala/ai/djl/spark/task/vision/ObjectDetector.scala
- extensions/spark/src/main/scala/ai/djl/spark/task/vision/SemanticSegmenter.scala
Change implicit conversions to asScala() to avoid confusion and hard-to-debug issues.
> [spark] Change implicit conversions to explicit

- bom/build.gradle
This reverts commit 140eb0842c1a353560d4e9e05c7861aa0aede997.
Fixes: #2592
> Revert "[bom] Simplify BOM build script (#2438)"

- extensions/spark/README.md
> [spark] Update README

- README.md
- examples/docs/mask_detection.md
Fix typos in:
- [README.md](https://github.com/deepjavalibrary/djl/commit/69d74775243917d854ba38748ba22759bcb5c0e2) (Main example code snippet): dection -> detection
- [mask_detection.md](https://github.com/deepjavalibrary/djl/commit/5feeb9eeb7c0956581bddf9484bdac223631fdaf): whick -> which
No actual code is affected by these changes, so no tests are required.
> [docs] Fix typos

- .github/workflows/build_triton_and_ft.yml
- tools/scripts/build_ft_deps.sh
Fix the instance spinning issue
> [FT] minor fix to the instance spinning

- README.md
- docs/tensorflow/how_to_import_tensorflow_models_in_DJL.md
> [docs] Fixes markdown format

- tools/scripts/build_ft_deps.sh
> fix the dependencies issue

- gradle/wrapper/gradle-wrapper.properties
> [ci] Upgrade gradle to 8.1.1

- docs/tensorflow/how_to_import_tensorflow_models_in_DJL.md
> [docs] Update import tensorflow model README

- .github/workflows/build_triton_and_ft.yml
Publish executable from the build script
> also publish triton executable

- android/gradle.properties
> [android] Upgrade DJL version to 0.23.0

- .github/workflows/native_s3_fasttext.yml
- extensions/fasttext/build.gradle
- extensions/fasttext/build.sh
- extensions/fasttext/src/test/java/ai/djl/fasttext/CookingStackExchangeTest.java
> [fasttext] Adds maxOS M1 supports

- api/src/main/java/ai/djl/util/Platform.java
> [api] Adds more logs for platform detection

- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/IValueUtils.java
- engines/pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/jni/IValueUtilsTest.java
> [pytorch] Impoves IValue tuple of tuple support

- docs/mkdocs.yml
- index.html
- index1.0.html
- website/blog.html
- website/demo.html
- website/javadoc.html
This switches from the existing Universal Analytics to Google Analytics 4 as the former will be deprecated soon.
> Migrate google analytics

- basicdataset/src/main/java/ai/djl/basicdataset/cv/classification/AbstractImageFolder.java
open `isImage()` method to package children for reuse - enabling custom datasets
> open isImage() method to package children for reuse-enabling custom datasets

- api/src/main/java/ai/djl/util/Ec2Utils.java
> [api] Avoid exception if SecurityManager is applied

- api/src/main/java/ai/djl/repository/RepositoryFactoryImpl.java
- api/src/test/java/ai/djl/repository/DjlRepositoryTest.java
> [api] Improves DJL URL error message

- .github/workflows/nightly_publish.yml
> [ci] Removes cu102 test

- .github/workflows/nightly_publish.yml
> [ci] Fixes nightly publish ci bug

- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
https://github.com/deepjavalibrary/djl/issues/2685
> Fixes rrror message in X.dot(w)

- .github/workflows/nightly_publish.yml
> [ci] Publish pytorch 2.0.1 jni package

- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
- engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_torch_pointwise.cc
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayElementComparisonOpTest.java
Add PyTorch median operator implementation, not on the frontend
> [Pytorch] add basic median support

- examples/pom.xml
> [examples] Adds missing audio package

- README.md
- engines/pytorch/pytorch-engine/README.md
> [docs] Updates README for pytorch 2.0.1

- README.md
- android/gradle.properties
- api/README.md
- examples/pom.xml
- gradle.properties
> Update docs and Bump up version to 0.24.0

- docker/spark/Dockerfile
> [spark] Update djl version in dockerfile

- api/src/main/java/ai/djl/inference/streaming/ChunkedBytesSupplier.java
> [api] Fixes ChunkedBytesSupplier read timeout bug

- .github/workflows/native_s3_pytorch_android.yml
> [pytorch] Upgrade pytorch andorid to 2.0.1

- api/src/main/java/ai/djl/util/NeuronUtils.java
- api/src/test/java/ai/djl/util/NeuronUtilsTest.java
> [api] Makes getNeuronDevices() public

- api/src/main/java/ai/djl/repository/zoo/BaseModelLoader.java
- api/src/main/java/ai/djl/util/ClassLoaderUtils.java
> [api] Log warning message if failed to load specified class

- .github/workflows/docs.yml
- basicdataset/src/test/resources/mlrepo/dataset/nlp/ai/djl/basicdataset/amazon_reviews/metadata.json
- examples/src/main/java/ai/djl/examples/training/transferlearning/TrainAmazonReviewRanking.java
- jupyter/rank_classification_using_BERT_on_Amazon_Review.ipynb
The amazon reviews had a dependency on another s3 bucket that was removed, breaking the CI. This fixes it by uploading it to the mlrepo s3 bucket.
> Fix AmazonReviews

- api/src/main/java/ai/djl/util/NeuronUtils.java
> [api] Workaround detect neuron issue on SageMaker

- docs/development/troubleshooting.md
> [docs] Updates troubleshooting README to remove outdated content

- api/src/main/java/ai/djl/util/NeuronUtils.java
> [api] Fixes NeuronUtils issue when running as non-root user

- examples/src/main/java/ai/djl/examples/inference/whisper/WhisperModel.java
> [examples] Fixes whipser model on GPU machine

- api/src/main/java/ai/djl/training/Trainer.java
- api/src/test/java/ai/djl/nn/BlockFactoryTest.java
- gradle/wrapper/gradle-wrapper.properties
- integration/src/main/java/ai/djl/integration/IntegrationTest.java
- integration/src/main/java/ai/djl/integration/tests/inference/StreamingTest.java
- integration/src/main/java/ai/djl/integration/tests/nn/BlockFactoryTest.java
- integration/src/main/java/ai/djl/integration/tests/nn/ScaledDotProductAttentionBlockTest.java
- integration/src/main/java/ai/djl/integration/util/TestUtils.java
- testing/src/main/java/ai/djl/testing/CoverageUtils.java
- testing/src/main/java/ai/djl/testing/TestRequirements.java
- tools/conf/pmd.xml
> [ci] Fixes PMD warnings

- extensions/sentencepiece/src/main/java/ai/djl/sentencepiece/SpProcessor.java
> [SentencePiece] Make SpProcessor public

- extensions/tokenizers/src/main/python/model_zoo_importer.py
> [tokenizer] Print out warning in model_zoo_importer

- build.gradle
> [ci] Fixes gradle deprecation warnings

- tools/scripts/build_ft_deps.sh
> Build FT for sm90

- engines/ml/lightgbm/src/main/java/ai/djl/ml/lightgbm/LgbmEngine.java
- gradle.properties
> Updates LightGBM to 3.3.510

- engines/ml/lightgbm/src/main/java/ai/djl/ml/lightgbm/LgbmEngine.java
- gradle.properties
Reverts deepjavalibrary/djl#2793
> Revert "Updates LightGBM to 3.3.510"

- api/src/main/java/ai/djl/modality/Input.java
> [api] Allows cancel Input

- .github/workflows/native_jni_s3_pytorch.yml
> [ci] Fixes out of diskspace issue

- examples/pom.xml
- gradle.properties
> Bump up DJL version to 0.25.0

- .github/workflows/build_triton_and_ft.yml
Support gpu flag for triton server
> Add Triton gpu flag build on

- engines/ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbModel.java
> [xgb] Add .xgb file extension support

- .github/workflows/native_s3_xgboost.yml
- engines/ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbNDManager.java
- engines/ml/xgboost/src/main/java/ml/dmlc/xgboost4j/java/JniUtils.java
- engines/ml/xgboost/src/test/java/ai/djl/ml/xgboost/XgbModelTest.java
- gradle.properties
> Updates XGBoost to 2.0.1 

- extensions/tokenizers/src/main/python/huggingface_models.py
- extensions/tokenizers/src/main/python/requirements.txt
> [tokenizer] Update import script for huggingface_hub api change

- docs/mkdocs.yml
Updates the navigation as a followup to
https://github.com/deepjavalibrary/djl-serving/pull/1316.
> [docs] Update serving configuration nav

- examples/pom.xml
- gradle.properties
> Bump up DJL version to 0.26.0

- docs/mkdocs.yml
Large Model Inference section in DJLServing
> update master branch on the website to have large model inference guide

- docs/mkdocs.yml
> [docs] Include LMI documents

- api/src/main/java/ai/djl/repository/AbstractRepository.java
- gradle.properties
> [api] Updates common-compress version to address CVE issues

- api/src/main/java/ai/djl/repository/RemoteRepository.java
- api/src/main/java/ai/djl/util/Ec2Utils.java
- api/src/main/java/ai/djl/util/Utils.java
- build.gradle
- docs/telemetry.md
- examples/src/test/java/ai/djl/testing/TestRequirements.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/zoo/HfModelZoo.java
- extensions/tokenizers/src/test/java/ai/djl/huggingface/zoo/ModelZooTest.java
- testing/src/main/java/ai/djl/testing/TestRequirements.java
> [api] Update offline property name to avoid conflict with other app.

- integration/src/main/java/ai/djl/integration/tests/training/listener/EarlyStoppingListenerTest.java
> [ci] Fixes flaky early stopping training test

- api/src/main/java/ai/djl/util/cuda/CudaUtils.java
> [api] Handles both JNA conflict and missing case

- .github/workflows/codeql-analysis-java.yml
- .github/workflows/continuous.yml
- .github/workflows/docs.yml
- .github/workflows/native_jni_s3_paddle.yml
- .github/workflows/native_jni_s3_pytorch.yml
- .github/workflows/native_jni_s3_pytorch_android.yml
- .github/workflows/native_jni_s3_tensorrt.yml
- .github/workflows/native_publish_mxnet.yml
- .github/workflows/native_publish_paddle.yml
- .github/workflows/native_publish_pytorch.yml
- .github/workflows/native_publish_tensorflow.yml
- .github/workflows/native_publish_tflite.yml
- .github/workflows/native_s3_fasttext.yml
- .github/workflows/native_s3_huggingface.yml
- .github/workflows/native_s3_pytorch.yml
- .github/workflows/native_s3_pytorch_android.yml
- .github/workflows/native_s3_sentencepiece.yml
- .github/workflows/native_s3_tensorflow.yml
- .github/workflows/native_s3_tflite.yml
- .github/workflows/native_s3_xgboost.yml
- .github/workflows/nightly_android.yml
- .github/workflows/nightly_publish.yml
- .github/workflows/publish_android_packages.yml
- .github/workflows/serving_publish.yml
> [ci] Use JDK 17 for github actions workflow

- engines/pytorch/pytorch-model-zoo/src/main/java/ai/djl/pytorch/zoo/PtModelZoo.java
- engines/pytorch/pytorch-model-zoo/src/test/resources/mlrepo/model/cv/object_detection/ai/djl/pytorch/yolov8n/metadata.json
> [pytorch] Adds Yolov8n model to pytorch model zoo.

- engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/zoo/OrtModelZoo.java
- engines/onnxruntime/onnxruntime-engine/src/test/resources/mlrepo/model/cv/object_detection/ai/djl/onnxruntime/yolov8n/metadata.json
- examples/src/main/java/ai/djl/examples/inference/Yolov8Detection.java
> [onnx] Adds yolov8n to model zoo

- .github/workflows/native_jni_s3_paddle.yml
- .github/workflows/native_jni_s3_pytorch.yml
- .github/workflows/native_s3_fasttext.yml
- .github/workflows/native_s3_huggingface.yml
- .github/workflows/native_s3_sentencepiece.yml
- .github/workflows/native_s3_tflite.yml
- .github/workflows/native_s3_xgboost.yml
- .github/workflows/nightly_publish.yml
> [ci] Fixes github action for centos and amazonlinux

- engines/ml/xgboost/src/test/java/ai/djl/ml/xgboost/XgbModelTest.java
- gradle.properties
> [XGBoost] Updates XGBoost to 2.0.3

- .github/workflows/native_s3_pytorch_android.yml
> [pytorch] Upgrade pytorch andorid to 2.1.1

- .github/workflows/serving_publish.yml
change the build command to jar command
> [awscurl] change build to jar

- bom/build.gradle
> [bom] Adds llama engine to BOM

- engines/pytorch/pytorch-native/CMakeLists.txt
- engines/pytorch/pytorch-native/build.sh
- engines/pytorch/pytorch-native/build_android.sh
> [ci] Fixes pytorch android build

- api/src/main/java/ai/djl/modality/nlp/generate/SeqBatchScheduler.java
- api/src/main/java/ai/djl/repository/zoo/ModelZoo.java
- api/src/main/java/ai/djl/repository/zoo/ModelZooResolver.java
- api/src/test/java/ai/djl/repository/ZooTest.java
> [api] Adds ModelZooResolver interface

- .github/workflows/nightly_publish.yml
> [ci] Use macos-13 to avoid flaky test

- integration/src/main/java/ai/djl/integration/tests/training/listener/EarlyStoppingListenerTest.java
> [test] Fixes EarlyStopping flaky test

- README.md
- api/README.md
- examples/pom.xml
- gradle.properties
bump to 0.27.0 and update README with latest release
> Bump DJL version to 0.27.0

- docs/mkdocs.yml
> [doc] include trtllm convert manual

- .github/workflows/native_jni_s3_pytorch.yml
- .github/workflows/native_s3_fasttext.yml
- .github/workflows/native_s3_huggingface.yml
- .github/workflows/native_s3_llama.yml
- .github/workflows/native_s3_sentencepiece.yml
Successful run:
https://github.com/deepjavalibrary/djl/actions/runs/7562108959
> Moves to Actions hosted M1 runner

- .github/workflows/native_jni_s3_pytorch.yml
- .github/workflows/native_jni_s3_pytorch_android.yml
- .github/workflows/nightly_android.yml
- .github/workflows/no_response.yml
- .github/workflows/publish_android_packages.yml
> [ci] Disable run scheduled github actions in fork

- extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizer.java
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizerTest.java
> [tokenizer] Adds getters for HuggingfaceTokenizer

- docs/mkdocs.yml
> [doc] Make LMI a separate tab and include I/O schema

- .github/workflows/build_triton_and_ft.yml
- .github/workflows/codeql-analysis-java.yml
- .github/workflows/continuous.yml
- .github/workflows/docker_publish.yml
- .github/workflows/docs.yml
- .github/workflows/native_build_mxnet_osx.yml
- .github/workflows/native_jni_s3_paddle.yml
- .github/workflows/native_jni_s3_pytorch.yml
- .github/workflows/native_jni_s3_pytorch_android.yml
- .github/workflows/native_jni_s3_tensorrt.yml
- .github/workflows/native_publish_mxnet.yml
- .github/workflows/native_publish_paddle.yml
- .github/workflows/native_publish_pytorch.yml
- .github/workflows/native_publish_tensorflow.yml
- .github/workflows/native_publish_tflite.yml
- .github/workflows/native_s3_fasttext.yml
- .github/workflows/native_s3_huggingface.yml
- .github/workflows/native_s3_llama.yml
- .github/workflows/native_s3_pytorch.yml
- .github/workflows/native_s3_pytorch_android.yml
- .github/workflows/native_s3_sentencepiece.yml
- .github/workflows/native_s3_tensorflow.yml
- .github/workflows/native_s3_tflite.yml
- .github/workflows/native_s3_xgboost.yml
- .github/workflows/nightly_android.yml
- .github/workflows/nightly_publish.yml
- .github/workflows/publish_android_packages.yml
- .github/workflows/serving_publish.yml
> [ci] Upgrade github actions nodejs 16 to nodejs 2

- .github/workflows/codeql-analysis-java.yml
> [ci] Upgrade codeql-actions to v3

- .github/workflows/build_triton_and_ft.yml
- .github/workflows/docker_publish.yml
- .github/workflows/docs.yml
- .github/workflows/native_jni_s3_paddle.yml
- .github/workflows/native_jni_s3_pytorch.yml
- .github/workflows/native_jni_s3_pytorch_android.yml
- .github/workflows/native_jni_s3_tensorrt.yml
- .github/workflows/native_s3_fasttext.yml
- .github/workflows/native_s3_huggingface.yml
- .github/workflows/native_s3_llama.yml
- .github/workflows/native_s3_pytorch.yml
- .github/workflows/native_s3_pytorch_android.yml
- .github/workflows/native_s3_sentencepiece.yml
- .github/workflows/native_s3_tensorflow.yml
- .github/workflows/native_s3_tflite.yml
- .github/workflows/native_s3_xgboost.yml
- .github/workflows/nightly_publish.yml
- .github/workflows/publish-job-success.yml
- .github/workflows/serving_publish.yml
> [ci] Upgrade aws-actions/configure-aws-credentials to v4

- .github/workflows/publish-job-success.yml
fix typo in called workflow condition
> [fix][ci] fix typo in publish metric workflow

- android/core/build.gradle
- android/gradle.properties
> [pytorch] Upgrade android build to 0.26.0

- .github/workflows/native_jni_s3_paddle.yml
- .github/workflows/native_jni_s3_pytorch.yml
- .github/workflows/native_s3_fasttext.yml
- .github/workflows/native_s3_huggingface.yml
- .github/workflows/native_s3_llama.yml
- .github/workflows/native_s3_sentencepiece.yml
- .github/workflows/native_s3_tflite.yml
- .github/workflows/native_s3_xgboost.yml
- .github/workflows/nightly_publish.yml
> [ci] Downgrade github actions version for centos7 and amazonlinux

- basicdataset/src/test/resources/mlrepo/dataset/cv/ai/djl/basicdataset/mnist/metadata.json
> [dataset] Fixes broken link for mnist dataset

- basicdataset/src/test/resources/mlrepo/dataset/cv/ai/djl/basicdataset/mnist/metadata.json
> [database] Fixes mnist URL for local unitest

- .github/workflows/native_jni_s3_pytorch.yml
Downgrade the publish version to V3 for now
> [CI] downgrade the version to V3

- .github/workflows/native_jni_s3_pytorch.yml
change to cache V3 for PyTorch
> [CI] change to cache v3 for the versions

- docs/development/cache_management.md
> [docs] Update Huggingface tokenizer cache directory document

- basicdataset/src/main/resources/imagenet/extract_imagenet.py
- extensions/spark/setup/djl_spark/util/files_util.py
> [spark] Fixes python tarslip security concern

- .github/workflows/continuous.yml
This is to fix the flaky llama engine segfaults on CI.
> Update continuous OSX to 13

- .github/workflows/continuous.yml
Removes changes in https://github.com/deepjavalibrary/djl/pull/2983.
> Removes dependency submission

- docs/mkdocs.yml
Updates doc site with new lmi structure
> [docs] update mkdocs structure for new lmi documentation

- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java
> [pytorch] Allows to exclude certain DLL from pytorch directory

- api/src/main/java/ai/djl/modality/nlp/generate/TextGenerator.java
- api/src/main/java/ai/djl/training/tracker/LinearTracker.java
- tools/conf/checkstyle.xml
- tools/gradle/check.gradle
> Update checkstyle tool version to 10.14.2

- api/README.md
- docs/get.md
- examples/pom.xml
- gradle.properties
> Increase build version to 0.28.0

- engines/llama/build.cmd
- engines/llama/build.gradle
- engines/llama/build.sh
> [llama.cpp] Fixes llama.cpp JNI build issue

- engines/onnxruntime/onnxruntime-engine/README.md
> [docs] Update OnnxRuntime version in README.

- extensions/tokenizers/rust/Cargo.toml
- extensions/tokenizers/rust/src/lib.rs
> [tokenizer] Upgrade rs-jni to 0.21.1

- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextEmbeddingTranslator.java
- extensions/tokenizers/src/main/python/fill_mask_converter.py
- extensions/tokenizers/src/main/python/huggingface_converter.py
- extensions/tokenizers/src/main/python/metadata.py
- extensions/tokenizers/src/main/python/sentence_similarity_converter.py
> [tokenizer] Apply Dense layer for TextEmbeddingTranslator

- engines/mxnet/mxnet-model-zoo/src/test/resources/mlrepo/model/cv/object_detection/ai/djl/mxnet/yolo/metadata.json
> [model-zoo] Fixes mxnet yolo metadata.json

- .github/workflows/native_s3_pytorch_android.yml
- .github/workflows/nightly_publish.yml
- engines/pytorch/pytorch-engine/README.md
- engines/pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/MpsTest.java
- gradle.properties
> [pytorch] Updates PyTorch to 2.1.2

- api/src/main/java/ai/djl/util/ZipUtils.java
> [api] Fixes ZipUtil bug when unzip large file

- README.md
- docs/README.md
- docs/quick_start.md
> [docs] Updates javadoc link

- docs/mkdocs.yml
> [docs][lmi] add new docs pages to doc site

- api/src/main/java/ai/djl/ndarray/NDArray.java
- extensions/tokenizers/build.sh
- extensions/tokenizers/rust/Cargo.toml
- extensions/tokenizers/rust/src/lib.rs
- extensions/tokenizers/rust/src/ndarray/binary.rs
- extensions/tokenizers/rust/src/ndarray/cmp.rs
- extensions/tokenizers/rust/src/ndarray/creation.rs
- extensions/tokenizers/rust/src/ndarray/mod.rs
- extensions/tokenizers/rust/src/ndarray/other.rs
- extensions/tokenizers/rust/src/ndarray/reduce.rs
- extensions/tokenizers/rust/src/ndarray/unary.rs
- extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsEngine.java
- extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsEngineProvider.java
- extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsModel.java
- extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsNDArray.java
- extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsNDArrayEx.java
- extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsNDArrayIndexer.java
- extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsNDManager.java
- extensions/tokenizers/src/main/java/ai/djl/engine/rust/RustLibrary.java
- extensions/tokenizers/src/main/java/ai/djl/engine/rust/package-info.java
- extensions/tokenizers/src/main/resources/META-INF/services/ai.djl.engine.EngineProvider
- extensions/tokenizers/src/test/java/ai/djl/engine/rust/NDArrayTests.java
- extensions/tokenizers/src/test/java/ai/djl/engine/rust/package-info.java
> Add rust engine implemenation

- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/CrossEncoderBatchTranslator.java
- Parsing error in processOutput of CrossEncoderBatchTranslator for batch data
> [fix] fix CrossEncoderBatchTranslator processOutput

- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextEmbeddingBatchTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextEmbeddingTranslator.java
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/TextEmbeddingTranslatorTest.java
> Fixs text embedding translator regression

- extensions/tokenizers/src/main/python/huggingface_converter.py
> [tokenizer] Fixes import huggingface onnx model bug

- extensions/tokenizers/src/main/python/huggingface_converter.py
- extensions/tokenizers/src/main/python/sentence_similarity_converter.py
> [huggingface] Fixes model zoo importer include_token_types flag

- extensions/audio/src/main/java/ai/djl/audio/translator/WhisperTranslator.java
> [audio] Properly implement WhisperTokenizer

- api/src/main/java/ai/djl/repository/zoo/ModelZoo.java
- engines/onnxruntime/onnxruntime-engine/build.gradle
- engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/zoo/OrtHfModelZoo.java
- engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/zoo/OrtHfZooProvider.java
- engines/onnxruntime/onnxruntime-engine/src/main/resources/META-INF/services/ai.djl.repository.zoo.ZooProvider
- engines/onnxruntime/onnxruntime-engine/src/test/java/ai/djl/onnxruntime/zoo/OrtHfModelZooTest.java
- engines/onnxruntime/onnxruntime-engine/src/test/java/ai/djl/onnxruntime/zoo/package-info.java
- extensions/tokenizers/src/test/java/ai/djl/huggingface/zoo/ModelZooTest.java
> [onnx] Add huggingface model zoo for OnnxRuntime

- extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsEngine.java
> [tokenizer] Fixes build issue on GPU

- engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtEngine.java
> [onnxruntime] Minor update OrtEngine.toString()

- engines/llama/src/test/java/ai/djl/llama/engine/LlamaTest.java
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/BpeTokenizerBuilderTest.java
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizerTest.java
> [ci] Fixes nightly build

- extensions/tokenizers/src/main/python/huggingface_converter.py
- extensions/tokenizers/src/main/python/huggingface_models.py
- extensions/tokenizers/src/main/python/sentence_similarity_converter.py
> [tokenizer] Fixes import model zoo bug

- api/src/main/java/ai/djl/modality/cv/translator/YoloV8Translator.java
> [api] Fixes YoloV8Translator builder bug

- engines/onnxruntime/onnxruntime-engine/build.gradle
- examples/src/main/java/ai/djl/examples/inference/BertTextEmbedding.java
- extensions/tokenizers/build.sh
- extensions/tokenizers/rust/Cargo.toml
- extensions/tokenizers/rust/src/compute_cap.rs
- extensions/tokenizers/rust/src/lib.rs
- extensions/tokenizers/rust/src/models/bert.rs
- extensions/tokenizers/rust/src/models/distilbert.rs
- extensions/tokenizers/rust/src/models/mod.rs
- extensions/tokenizers/rust/src/ndarray/mod.rs
- extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsEngine.java
- extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsEngineProvider.java
- extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsModel.java
- extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsNDManager.java
- extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsSymbolBlock.java
- extensions/tokenizers/src/main/java/ai/djl/engine/rust/RustLibrary.java
> [rust] Add RsSymbolBlock

- extensions/tokenizers/rust/src/lib.rs
- extensions/tokenizers/rust/src/models/bert.rs
- extensions/tokenizers/rust/src/models/distilbert.rs
- extensions/tokenizers/rust/src/models/mod.rs
- extensions/tokenizers/rust/src/ndarray/creation.rs
- extensions/tokenizers/rust/src/ndarray/reduce.rs
- extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsEngine.java
- extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsNDManager.java
- extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsSymbolBlock.java
- extensions/tokenizers/src/main/java/ai/djl/engine/rust/RustLibrary.java
> [rust] Fixes compile warning and reformat rust code

- examples/src/main/java/ai/djl/examples/inference/BertTextEmbedding.java
> [examples] Fixes broken example

- extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizer.java
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizerTest.java
> [tokenizer] Sets default padding to true

- .gitignore
> [gitignore] Avoid checking binary files.

- api/src/main/java/ai/djl/Application.java
- api/src/main/java/ai/djl/translate/ServingTranslatorFactory.java
- api/src/test/java/ai/djl/translate/ServingTranslatorFactoryTest.java
> [api] Automatically detect translatorFactory based on task

- extensions/tokenizers/src/main/python/huggingface_converter.py
> [tokenizer] Fixes model zoo import script

- api/src/main/java/ai/djl/ndarray/BaseNDManager.java
> [api] Tries to use the same device for alternative NDManager

- extensions/tokenizers/rust/src/lib.rs
- extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizer.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/jni/TokenizersLibrary.java
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizerTest.java
> [tokenizer] Allows use HF_TOKEN to access gated model

- api/src/main/java/ai/djl/repository/SimpleUrlRepository.java
- api/src/main/java/ai/djl/repository/zoo/ModelZoo.java
- api/src/main/java/ai/djl/training/listener/MemoryTrainingListener.java
- api/src/main/java/ai/djl/util/NativeResource.java
- api/src/main/java/ai/djl/util/Platform.java
- engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/CachedOp.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtEngine.java
- engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfSymbolBlock.java
- examples/src/main/java/ai/djl/examples/inference/BertClassification.java
- examples/src/main/java/ai/djl/examples/inference/UniversalSentenceEncoder.java
- extensions/aws-ai/src/main/java/ai/djl/aws/s3/S3Repository.java
- extensions/hadoop/src/main/java/ai/djl/hadoop/hdfs/HdfsRepository.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizer.java
- integration/src/main/java/ai/djl/integration/IntegrationTest.java
> [api] Fixes logging invoke convention

- api/src/main/java/ai/djl/repository/zoo/Criteria.java
> [api] Fixes Criteria.toString() bug

- api/src/main/java/ai/djl/util/JsonUtils.java
> [api] Supports serialize NaN in json

- gradle/wrapper/gradle-wrapper.properties
> [ci] Upgrades gradle to 8.5

- .github/workflows/native_s3_sentencepiece.yml
- gradle.properties
> [sentencepiece] Updates sentencepiece to 0.2.0

- .github/workflows/serving_publish.yml
> [ci] Fixes awscurl publish location

- extensions/tokenizers/rust/src/models/mod.rs
> [rust] Fixes compile warnings

- docs/development/setup.md
> [docs] Updates docs for setup java on mac

- .github/workflows/nightly_publish.yml
- engines/pytorch/pytorch-engine/build.gradle
- engines/pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/ALibUtilsTest.java
- engines/pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/IValueTest.java
- engines/pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/MkldnnTest.java
- engines/pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/MpsTest.java
- engines/pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/ProfilerTest.java
- engines/pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/PtModelTest.java
- engines/pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/PtNDArrayTest.java
- engines/pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/TorchScriptTest.java
- engines/pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/jni/IValueUtilsTest.java
- engines/pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/jni/JniUtilsTest.java
- engines/pytorch/pytorch-jni/build.gradle
- engines/pytorch/pytorch-model-zoo/build.gradle
- engines/pytorch/pytorch-model-zoo/src/test/java/ai/djl/pytorch/zoo/nlp/textgeneration/GptTranslatorTest.java
- engines/pytorch/pytorch-native/build.gradle
- examples/src/test/java/ai/djl/examples/inference/TimeSeriesTest.java
- examples/src/test/java/ai/djl/examples/training/TrainResNetTest.java
- integration/build.gradle
- integration/src/test/java/ai/djl/integration/IntegrationTests.java
- testing/src/main/java/ai/djl/testing/TestRequirements.java
- **[ci] Fixes build on macOS aarch64 machine**
- **[pytorch] Updates PyTorch to 2.3.0**
> [pytorch] Updates PyTorch to 2.3.0

- .github/workflows/native_jni_s3_pytorch.yml
> [ci] Fixes nightly pytorch jni build

- examples/src/main/java/ai/djl/examples/inference/cv/ObjectDetection.java
- examples/src/test/java/ai/djl/examples/inference/ObjectDetectionTest.java
> [examples] Fixes ObjectDetection example for macOS m1

- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextEmbeddingTranslator.java
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/TextEmbeddingTranslatorTest.java
> [tokenizer] Process text embedding input and output in stacked NDArray

- api/src/main/java/ai/djl/util/cuda/CudaUtils.java
- api/src/test/java/ai/djl/util/cuda/CudaUtilsTest.java
> [api] Fix unitest in GPU docker running on CPU case

- engines/ml/xgboost/build.gradle.kts
- engines/pytorch/pytorch-native/build.gradle.kts
- engines/tensorflow/tensorflow-api/build.gradle.kts
- engines/tensorflow/tensorflow-native/build.gradle.kts
- jacoco/build.gradle.kts
> [jacoco] exclude spark extension since it doesnot contain test

- docker/spark/Dockerfile
- extensions/spark/src/main/scala/ai/djl/spark/task/BasePredictor.scala
> [spark] Update dependency versions

- api/src/main/java/ai/djl/metric/Metric.java
> [api] Avoid null dimensions for Metric

- extensions/tokenizers/rust/Cargo.toml
> [rust] Upgrade candle version

- extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsSymbolBlock.java
> [rust] Fix output tensor dtype

- .github/workflows/docker_publish.yml
> [ci] Update to amazon-ecr-login@v2

- engines/ml/lightgbm/src/main/java/ai/djl/ml/lightgbm/jni/JniUtils.java
fix lgbm bytebuffer native order
> [fix] fix lgbm bytebuffer native order

- engines/ml/xgboost/build.gradle.kts
> [xgb] Fixes gradle build script

- engines/pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/ALibUtilsTest.java
- engines/pytorch/pytorch-native/build.gradle.kts
- engines/tensorflow/tensorflow-native/build.gradle.kts
> [pytorch] Fixes uploadS3 gradle task

- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
- engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_torch_pointwise.cc
- examples/src/test/java/ai/djl/examples/training/TrainTimeSeriesTest.java
- extensions/timeseries/src/main/java/ai/djl/timeseries/distribution/DistributionLoss.java
> [pytorch] Implements gammaln operator for PyTorch

- engines/mxnet/native/build.gradle.kts
- engines/pytorch/pytorch-native/build.gradle.kts
- engines/tensorflow/tensorflow-native/build.gradle.kts
> [ci] Fixes publish maven native package

- .github/workflows/continuous.yml
- .github/workflows/native_jni_s3_pytorch.yml
- .github/workflows/nightly_publish.yml
- gradle/libs.versions.toml
> [pytorch] Updates PyTorch to 2.3.1

- docs/mkdocs.yml
> [doc] add release notes to docs.djl.ai

- examples/src/test/java/ai/djl/examples/training/TrainAirfoilWithTabNetTest.java
> [examples] Fixes nightly build failure on Windows

- docs/mkdocs.yml
> [doc] add output formatter schema to LMI docs.djl.ai

- engines/pytorch/pytorch-native/build.gradle.kts
> [pytorch] Fixes PyTorch 2.3.1 windows dependencies

- docs/tensorflow/how_to_import_tensorflow_models_in_DJL.md
PR #3135 moved the location of the `ObjectDetection.java` file. This PR adjusts sources to changes.
> [docs] Update example reference

- api/src/main/java/ai/djl/Application.java
* Added missing tabular, audio, and timeseries applications.
* Sorted NLP applications to align with the NLP interface definitions.
> Fix `Application.of` missing some applications

- extensions/timeseries/src/main/java/ai/djl/timeseries/timefeature/TimeOffset.java
- integration/src/main/java/ai/djl/integration/tests/training/EvaluatorTest.java
Identifier name changes
This pull request suggests minor alterations in identifier names for improved clarity and understandability.
> Refactored Identifiers

- api/src/main/java/ai/djl/ndarray/BytesSupplierImpl.java
Change to GSON output for singleline format
> use standard GSON output

- api/src/main/java/ai/djl/ndarray/NDManager.java
Optimize the additional copy overhead for two-dimensional arrays.
> [enhancement] Optimize memory copy overhead to enhance performance.

- engines/mxnet/mxnet-model-zoo/src/main/java/ai/djl/mxnet/zoo/nlp/embedding/GloveWordEmbeddingTranslatorFactory.java
> [mxnet] Fixes GloveWordEmbeddingTranslator bug

- api/src/main/java/ai/djl/modality/nlp/translator/NamedEntity.java
- api/src/main/java/ai/djl/ndarray/BytesSupplierImpl.java
- api/src/main/java/ai/djl/util/JsonUtils.java
- basicdataset/src/main/java/ai/djl/basicdataset/nlp/StanfordQuestionAnsweringDataset.java
- extensions/tokenizers/src/test/java/ai/djl/huggingface/zoo/ModelZooTest.java
> [api] Allows to control json pretty print with env var

- api/src/main/java/ai/djl/ndarray/internal/NDFormat.java
- api/src/test/java/ai/djl/ndarray/internal/NDFormatTest.java
> [api] Improve NDArray.toDebugString() output

- engines/pytorch/pytorch-model-zoo/src/main/java/ai/djl/pytorch/zoo/PtModelZoo.java
- engines/pytorch/pytorch-model-zoo/src/test/resources/mlrepo/model/cv/action_recognition/ai/djl/pytorch/Human-Action-Recognition-VIT-Base-patch16-224/metadata.json
- examples/src/main/java/ai/djl/examples/inference/cv/ActionRecognition.java
- examples/src/test/java/ai/djl/examples/inference/ActionRecognitionTest.java
> [example] Adds PyTorch action recognition model to model zoo

- extensions/tokenizers/rust/src/layers/cublaslt.rs
- extensions/tokenizers/rust/src/layers/linear.rs
- extensions/tokenizers/rust/src/layers/mod.rs
- extensions/tokenizers/rust/src/lib.rs
- extensions/tokenizers/rust/src/models/bert.rs
- extensions/tokenizers/rust/src/models/mod.rs
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/TextEmbeddingTranslatorTest.java
> [rust] Fixes test failure on GPU

- api/src/test/java/ai/djl/util/SecurityManagerTest.java
- examples/src/test/java/ai/djl/examples/inference/MaskDetectionTest.java
- examples/src/test/java/ai/djl/examples/inference/ObjectDetectionWithTensorflowSavedModelTest.java
- examples/src/test/java/ai/djl/examples/inference/SuperResolutionTest.java
- examples/src/test/java/ai/djl/examples/inference/UniversalSentenceEncoderTest.java
- examples/src/test/java/ai/djl/examples/inference/Yolov8DetectionTest.java
- examples/src/test/java/ai/djl/examples/training/TrainResNetTest.java
- examples/src/test/java/ai/djl/examples/training/TrainSentimentAnalysisTest.java
- examples/src/test/java/ai/djl/testing/TestRequirements.java
- integration/src/main/java/ai/djl/integration/tests/training/listener/EarlyStoppingListenerTest.java
> [api] Fixes nightly tests on GPU machine

- extensions/timeseries/src/main/java/ai/djl/timeseries/transform/feature/Feature.java
> [timeseries] Fixes duration format issue

- api/src/main/java/ai/djl/modality/cv/output/Rectangle.java
- api/src/main/java/ai/djl/modality/cv/translator/YoloV5Translator.java
- api/src/main/java/ai/djl/modality/cv/translator/YoloV8Translator.java
> [api] Refactor nms for yolo translator

- api/src/main/java/ai/djl/modality/cv/BufferedImageFactory.java
- api/src/main/java/ai/djl/modality/cv/output/Rectangle.java
- api/src/main/java/ai/djl/modality/cv/translator/YoloV5Translator.java
- api/src/main/java/ai/djl/modality/cv/translator/YoloV8Translator.java
- extensions/opencv/src/main/java/ai/djl/opencv/OpenCVImage.java
- **[api] Reactor nms for yolo translator**
- **[api] Improve drawJoints behavior**
> [api] Improve drawJoints behavior

- api/src/main/java/ai/djl/modality/cv/BufferedImageFactory.java
- api/src/main/java/ai/djl/modality/cv/output/Rectangle.java
- api/src/main/java/ai/djl/modality/cv/translator/YoloSegmentationTranslator.java
- api/src/main/java/ai/djl/modality/cv/translator/YoloSegmentationTranslatorFactory.java
- api/src/main/java/ai/djl/modality/cv/translator/YoloV5Translator.java
- api/src/main/java/ai/djl/modality/cv/translator/YoloV8Translator.java
- engines/pytorch/pytorch-model-zoo/src/main/java/ai/djl/pytorch/zoo/PtModelZoo.java
- engines/pytorch/pytorch-model-zoo/src/test/resources/mlrepo/model/cv/instance_segmentation/ai/djl/pytorch/yolov8n-seg/metadata.json
- examples/src/main/java/ai/djl/examples/inference/cv/InstanceSegmentation.java
- examples/src/test/java/ai/djl/examples/inference/InstanceSegmentationTest.java
- extensions/opencv/src/main/java/ai/djl/opencv/OpenCVImage.java
- **[api] Reactor nms for yolo translator**
- **[pytorch] Adds Yolov8n-seg model to model zoo**
> [pytorch] Adds Yolov8n-seg model to model zoo

- extensions/tokenizers/src/main/python/djl_converter/model_converter.py
> [tokenizer] Recover accidentally deleted file

- .github/workflows/nightly_publish.yml
> [ci] Fixes nightly publish for nodejs20 issue

- .github/workflows/native_s3_huggingface.yml
> [ci] Fixes rust jni build for nodejs20 issue

- extensions/tokenizers/src/main/python/djl_converter/huggingface_converter.py
> [tokenizer] Fixes detect include token type logic

- bom/build.gradle.kts
> [bom] Uses release version for tensorflow

- buildSrc/src/main/kotlin/ai/djl/javaProject.gradle.kts
> Add more test logging

- .github/workflows/native_s3_huggingface.yml
> [rust] Fix tokenizer cuda pipeline name

- extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/jni/LibUtils.java
> [rust] Download cu124 jni library for cuda

- engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/zoo/OrtModelZoo.java
- engines/onnxruntime/onnxruntime-engine/src/test/resources/mlrepo/model/cv/instance_segmentation/ai/djl/onnxruntime/yolov8n-seg/metadata.json
> [onnxruntime] Adds yolov8n-seg model to onnxruntime model zoo

- .github/workflows/native_s3_huggingface.yml
- extensions/tokenizers/build.gradle.kts
> [tokenizer] Adds maxos-13 support back

- gradle/libs.versions.toml
> [api] Updates slf4j version to 2.0.13

- .github/workflows/native_s3_huggingface.yml
- extensions/tokenizers/build.gradle.kts
> [tokenizers] Fixes huggingface build for Windows

- .github/workflows/continuous.yml
- .github/workflows/native_s3_huggingface.yml
- .github/workflows/nightly_publish.yml
> [ci] Minor github action workflow changes

- basicdataset/README.md
- basicdataset/src/main/java/ai/djl/basicdataset/cv/CocoDetection.java
- docs/dataset.md
- gradle/libs.versions.toml
> [ci] Updates dependency versions to latest

- .github/workflows/native_jni_s3_pytorch.yml
> [ci] Fixes pytorch JNI build

- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextClassificationTranslatorFactory.java
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/CrossEncoderTranslatorTest.java
> [tokenizer] Supports cross encoder for text classification model

- examples/pom.xml
Update snapshot examples with release version
See https://github.com/deepjavalibrary/djl/pull/3199
> [MCM 0.29.0] Remove -SNAPSHOT for release v0.29.0

- README.md
- bom/README.md
- docs/development/example_dataset.md
- docs/get.md
- docs/hybrid_engine.md
- engines/ml/lightgbm/README.md
- engines/ml/xgboost/README.md
- engines/onnxruntime/onnxruntime-engine/README.md
- engines/tensorflow/tensorflow-engine/README.md
- engines/tensorrt/README.md
- extensions/timeseries/docs/forecast_with_M5_data.md
> [docs] Updates document to use DJL 0.29.0

- README.md
> Bump release notes version

- buildSrc/src/main/kotlin/ai/djl/release.gradle.kts
> [ci] Fixes release version update script

- api/README.md
- examples/pom.xml
- gradle/libs.versions.toml
Bumps up to 0.30 using gradlew PtargetVersion
Ping me if there are other parts that need to be bumped up as well
> bump up to 0.30

- .github/workflows/continuous.yml
- api/src/main/java/ai/djl/ndarray/NDArray.java
- api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
- engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
- engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_torch_other.cc
- engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
- extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsNDArray.java
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayOtherOpTest.java
> NdArray ifft, rfft, irfft, conj implementation for PyTorch engine.

- engines/tensorflow/tensorflow-engine/README.md
- examples/pom.xml
> [docs] Fixes tensorflow version in document

- .github/workflows/native_jni_s3_pytorch.yml
- .github/workflows/native_s3_fasttext.yml
- .github/workflows/native_s3_huggingface.yml
- .github/workflows/native_s3_sentencepiece.yml
- .github/workflows/native_s3_xgboost.yml
- bom/build.gradle.kts
- engines/pytorch/pytorch-engine/README.md
- engines/pytorch/pytorch-jni/build.gradle.kts
- engines/tensorflow/tensorflow-native/build.gradle.kts
- extensions/audio/build.gradle.kts
- extensions/fasttext/build.gradle.kts
- extensions/sentencepiece/build.gradle.kts
- extensions/tokenizers/build.gradle.kts
> [ci] Removes macOS x86_64 and PyTorch cu121-precxx11 support

- engines/pytorch/pytorch-native/build.gradle.kts
> [pytorch] Includes mkl dll for all windows binary

- engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/javacpp/JavacppUtils.java
> [tensorflow] Fixes SavedModelBundle memory leak

- api/src/main/java/ai/djl/util/cuda/CudaUtils.java
> [api] Disable CudaUtils logging in fork mode

- api/src/main/java/ai/djl/training/dataset/RandomAccessDataset.java
> [javadoc]: Updates RandomAccessDataset.java

- extensions/tokenizers/src/main/python/djl_converter/model_converter.py
> [huggingface] Fixes onnx model convert issue

- .github/workflows/nightly_publish.yml
> [ci] Workaround cudnn9 issue for PyTorch 2.4.0

- extensions/tokenizers/rust/src/layers/mod.rs
- extensions/tokenizers/rust/src/models/distilbert.rs
- extensions/tokenizers/rust/src/models/mod.rs
- extensions/tokenizers/rust/src/models/xlm_roberta.rs
- extensions/tokenizers/src/main/python/djl_converter/huggingface_converter.py
> [rust] Add reranker and text classification models

- docs/mkdocs.yml
> [doc] add input formatter schema to LMI guides

- .github/workflows/nightly_publish.yml
> [ci] Updates nightly publish for PyTorch 2.4.0

- api/src/main/java/ai/djl/modality/nlp/translator/CrossEncoderServingTranslator.java
> [api] Fix list parsing in CrossEncoderServingTranslator

- .github/workflows/native_jni_s3_pytorch.yml
- engines/pytorch/pytorch-jni/build.gradle.kts
> [pytorch] build precxx11 build for cuda

- extensions/tokenizers/rust/src/models/camembert.rs
- extensions/tokenizers/rust/src/models/mod.rs
- extensions/tokenizers/rust/src/models/roberta.rs
- extensions/tokenizers/rust/src/models/xlm_roberta.rs
- extensions/tokenizers/src/main/python/djl_converter/huggingface_converter.py
> [rust] Add more embedding models

- bom/build.gradle.kts
- engines/pytorch/pytorch-engine/README.md
> [bom] Update BOM use PyTorch 2.4.0

- android/README.md
- android/gradle.properties
- engines/onnxruntime/onnxruntime-android/README.md
Bumps up android for 0.29 to prepare for android release
> android bump up

- android/build.gradle
- android/core/build.gradle
- android/core/src/main/AndroidManifest.xml
- android/pytorch-native/build.gradle
- android/pytorch-native/src/main/AndroidManifest.xml
> [android] Fixes android build issue for slf4j2.x

- extensions/tokenizers/README.md
> [docs] Updates djl model converter document

- api/build.gradle.kts
- api/src/main/java/ai/djl/util/Ec2Utils.java
> [api] Avoid non-ascii characters

- api/src/main/java/ai/djl/translate/DeferredTranslatorFactory.java
- api/src/main/java/ai/djl/translate/ServingTranslatorFactory.java
- engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtEngine.java
- extensions/tokenizers/build.gradle.kts
> [api] Fixes logging calling convention

- extensions/tokenizers/src/main/python/djl_converter/huggingface_converter.py
- extensions/tokenizers/src/main/python/djl_converter/sentence_similarity_converter.py
- extensions/tokenizers/src/main/python/requirements.txt
- extensions/tokenizers/src/main/python/setup.py
> [djl-converter] Fixes import text embedding model from local folder

- extensions/tokenizers/src/main/python/djl_converter/model_converter.py
> [djl-converter] Exit with error if convert model failed

- api/src/main/java/ai/djl/modality/nlp/TextPrompt.java
- api/src/main/java/ai/djl/modality/nlp/translator/CrossEncoderServingTranslator.java
- api/src/main/java/ai/djl/modality/nlp/translator/QaServingTranslator.java
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/CrossEncoderTranslatorTest.java
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/QuestionAnsweringTranslatorTest.java
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/TextEmbeddingTranslatorTest.java
> [api] Support TEI input format to reranking model

- examples/src/test/java/ai/djl/examples/training/TrainCaptchaTest.java
- examples/src/test/java/ai/djl/examples/training/TrainMnistWithLSTMTest.java
- examples/src/test/java/ai/djl/examples/training/TrainResNetTest.java
- examples/src/test/java/ai/djl/examples/training/TrainSentimentAnalysisTest.java
- examples/src/test/java/ai/djl/examples/training/TrainTimeSeriesTest.java
> [example] Enable PyTorch for some training example

- extensions/tokenizers/src/main/python/djl_converter/model_converter.py
> [djl-converter] Fixes djl-convert command line return code

- extensions/tokenizers/rust/src/models/bert.rs
- extensions/tokenizers/rust/src/models/camembert.rs
- extensions/tokenizers/rust/src/models/distilbert.rs
- extensions/tokenizers/rust/src/models/mod.rs
- extensions/tokenizers/rust/src/models/roberta.rs
- extensions/tokenizers/rust/src/models/xlm_roberta.rs
- extensions/tokenizers/rust/src/ndarray/mod.rs
- extensions/tokenizers/rust/src/ndarray/nn.rs
- extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsNDArray.java
- extensions/tokenizers/src/main/java/ai/djl/engine/rust/RustLibrary.java
- extensions/tokenizers/src/main/python/djl_converter/huggingface_converter.py
- extensions/tokenizers/src/test/java/ai/djl/engine/rust/NDArrayTests.java
> [rust] Adds sigmoid and softmax operator for Rust engine

- docs/mkdocs.yml
- examples/docs/mask_detection.md
- examples/docs/train_transfer_fresh_fruit.md
- extensions/timeseries/README.md
> [docs] Fixes broken links in markdown files.

- engines/mxnet/mxnet-model-zoo/src/test/java/ai/djl/mxnet/integration/MxSymbolBlockTest.java
- extensions/tokenizers/src/test/java/ai/djl/engine/rust/NDArrayTests.java
- integration/src/main/java/ai/djl/integration/tests/inference/PredictorTest.java
- integration/src/main/java/ai/djl/integration/tests/model_zoo/classification/VGGTest.java
- testing/src/main/java/ai/djl/testing/TestRequirements.java
> [test] Detect GPUs with specified engine

- .github/workflows/native_s3_huggingface.yml
- extensions/tokenizers/build.sh
- extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/jni/LibUtils.java
> [rust] Build .so file for each cuda arch

- .github/workflows/serving_publish.yml
> [ci] Fixes serving publish for awscurl release version

- extensions/tokenizers/src/main/python/djl_converter/huggingface_models.py
> [tokenizers] Add supported arch in djl-convert

- extensions/tokenizers/rust/src/models/camembert.rs
> [rust] Fix camembert model loading

- api/src/main/java/ai/djl/ndarray/NDArray.java
- api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
- engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
- engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_nn_functional.cc
- engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
- extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsNDArray.java
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayShapesManipulationOpTest.java
> [pytorch] Adds pad operator

- extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsNDArray.java
- extensions/tokenizers/src/test/java/ai/djl/engine/rust/NDArrayTests.java
> [rust] Provides better error message for unsupported ops

- examples/docs/whisper_speech_text.md
> [docs] Updates trace whisper model document

- engines/tensorflow/tensorflow-engine/README.md
> [tensorflow] Updates tensorflow document

- android/gradle.properties
> [android] Upgrade DJL version to 0.30.0

- extensions/tokenizers/rust/src/layers/cublaslt.rs
- extensions/tokenizers/rust/src/layers/linear.rs
- extensions/tokenizers/rust/src/layers/mod.rs
Make cublaslt wrapper non static to fix illegal memory access.
> [rust] Make cublaslt wrapper non static

- extensions/tokenizers/src/main/python/djl_converter/huggingface_converter.py
> [djl-convert] Exclude models in includeTokenTypes

- extensions/tokenizers/src/main/python/djl_converter/huggingface_converter.py
> [djl-convert] Fixes huggingface model converter

- extensions/tokenizers/src/main/java/ai/djl/engine/rust/zoo/RsModelZoo.java
> [rust] Adds text classification models to Rust model zoo

- api/src/main/java/ai/djl/modality/cv/BufferedImageFactory.java
- api/src/main/java/ai/djl/modality/cv/Image.java
- api/src/main/java/ai/djl/modality/cv/output/Mask.java
- api/src/main/java/ai/djl/modality/cv/translator/InstanceSegmentationTranslator.java
- api/src/main/java/ai/djl/modality/cv/translator/Sam2Translator.java
- api/src/main/java/ai/djl/modality/cv/translator/Sam2TranslatorFactory.java
- api/src/main/java/ai/djl/ndarray/internal/NDArrayEx.java
- engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArrayEx.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArrayEx.java
- engines/pytorch/pytorch-model-zoo/src/main/java/ai/djl/pytorch/zoo/PtModelZoo.java
- engines/pytorch/pytorch-model-zoo/src/test/resources/mlrepo/model/cv/object_detection/ai/djl/pytorch/sam2-hiera-large/metadata.json
- engines/pytorch/pytorch-model-zoo/src/test/resources/mlrepo/model/cv/object_detection/ai/djl/pytorch/sam2-hiera-tiny/metadata.json
- engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArrayEx.java
- examples/src/main/java/ai/djl/examples/inference/cv/SegmentAnything2.java
- examples/src/test/java/ai/djl/examples/inference/cv/SegmentAnything2Test.java
- extensions/opencv/src/main/java/ai/djl/opencv/OpenCVImage.java
- extensions/opencv/src/test/java/ai/djl/opencv/OpenCVImageFactoryTest.java
- extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsNDArrayEx.java
> [examples] Adds segment anything 2 example

- examples/README.md
- examples/docs/segment_anything_2.md
- examples/docs/trace_sam2_img.py
> [docs] Adds segment anything document

- api/src/main/java/ai/djl/modality/cv/translator/ImageFeatureExtractor.java
- api/src/main/java/ai/djl/modality/cv/translator/ImageFeatureExtractorFactory.java
- examples/src/main/java/ai/djl/examples/inference/face/FeatureExtraction.java
- examples/src/test/java/ai/djl/examples/inference/face/FeatureExtractionTest.java
> [api] Refactor ImageFeatureExtractor

- engines/ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbNDManager.java
> [xgb] Fixes alternative NDArray conversion issue

- extensions/tokenizers/src/main/python/djl_converter/zip_utils.py
> [djl-import] Improve model import speed

- extensions/tokenizers/src/main/python/djl_converter/arg_parser.py
> [djl-import] Fixes missing arguments for onnx import

- android/core/src/main/java/ai/djl/android/core/BitmapImageFactory.java
> add drawMarks to android BitMapImageFactory

- engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtModel.java
> [OnnxRuntime] Update debug log message

- gradle/wrapper/gradle-wrapper.properties
> [ci] Updates gradle to 8.10.1

- .github/workflows/native_s3_fasttext.yml
- .github/workflows/native_s3_huggingface.yml
> [ci] configure aws creds manually to avoid node20 issues for AL2

- engines/pytorch/pytorch-engine/README.md
> [docs] Updates PyTorch engine README for 2.4.0

- android/gradle.properties
> [android] Update pytorch version to 2.4.0

- extensions/tokenizers/rust/src/layers/cublaslt.rs
> [rust] Remove unnecessary clone in cublaslt

- api/src/test/java/ai/djl/util/SecurityManagerTest.java
- engines/mxnet/jnarator/build.gradle.kts
> [mxnet] Fixes build error on JDK 22

- api/src/main/java/ai/djl/modality/cv/translator/Sam2Translator.java
- api/src/main/java/ai/djl/modality/cv/translator/Sam2TranslatorFactory.java
- examples/docs/trace_sam2_img.py
- examples/src/main/java/ai/djl/examples/inference/cv/SegmentAnything2.java
- examples/src/test/java/ai/djl/examples/inference/cv/SegmentAnything2Test.java
> [api] Use encoder/decoder for Segment anython2 translator

- api/src/main/java/ai/djl/modality/Classifications.java
- api/src/main/java/ai/djl/modality/cv/output/CategoryMask.java
- api/src/main/java/ai/djl/modality/cv/output/DetectedObjects.java
- api/src/main/java/ai/djl/modality/cv/output/Joints.java
- api/src/main/java/ai/djl/modality/cv/output/Landmark.java
- api/src/main/java/ai/djl/modality/cv/output/Mask.java
- api/src/main/java/ai/djl/modality/cv/output/Point.java
- api/src/main/java/ai/djl/modality/cv/output/Rectangle.java
- api/src/main/java/ai/djl/util/JsonSerializable.java
- api/src/main/java/ai/djl/util/JsonUtils.java
- api/src/test/java/ai/djl/modality/cv/output/CategoryMaskTest.java
- api/src/test/java/ai/djl/modality/cv/output/DetectedObjectsTest.java
> [api] Standardizes CV output format

- engines/pytorch/pytorch-model-zoo/src/main/java/ai/djl/pytorch/zoo/PtModelZoo.java
> [PyTorch] Fixes sam2 model version

- api/src/main/java/ai/djl/modality/cv/output/CategoryMask.java
> [ci] Fixes java 21 compile error

- README.md
Hello. Added a link to the project site
> Docs: Added a link

- .github/workflows/nightly_publish.yml
- engines/pytorch/pytorch-engine/README.md
- engines/pytorch/pytorch-jni/build.gradle.kts
- gradle/libs.versions.toml
> [pytorch] Updates PyTorch to 2.5.1

- docs/README.md
> [doc] Add blogposts link to README

- docs/README.md
> [doc] Add blogposts link to README (#3520)

- android/core/src/main/java/ai/djl/android/core/BitmapImageFactory.java
- android/gradle.properties
Android version has not been updated in quite some time - i built the new PT deps, and also updated the BitMapImage based on the change to the Image interface in https://github.com/deepjavalibrary/djl/pull/3492
> [android] fix djl version for android

- extensions/tokenizers/src/main/python/djl_converter/fill_mask_converter.py
> [converter] Trim jit output token_str

- .github/workflows/native_jni_s3_huggingface_android.yml
- .github/workflows/publish_android_packages.yml
- android/gradle.properties
- android/tokenizer-native/build.gradle
Continuation of https://github.com/deepjavalibrary/djl/pull/3531 to add CI support.
Let me know if anything looks wrong or need changes.
cc @frankfliu
> Add CI for the hugging face tokenizers android

- examples/pom.xml
fixing the versions here based on what we have in libs.versions.toml
> fix dependency versions in examples/pom.xml

- api/README.md
- docs/get.md
- examples/pom.xml
- gradle/libs.versions.toml
> Increase build version to 0.32.0

- api/src/main/java/ai/djl/translate/Batchifier.java
- api/src/test/java/ai/djl/translate/BatchifierTest.java
- basicdataset/src/test/java/ai/djl/basicdataset/MnistTest.java
> [api] Allows to configure custom batchifer

- api/src/main/java/ai/djl/modality/cv/transform/Resize.java
- api/src/main/java/ai/djl/modality/cv/translator/BaseImageTranslator.java
- api/src/main/java/ai/djl/translate/Pipeline.java
Fixes: https://github.com/deepjavalibrary/djl/issues/3562
> [fix] Fix YoloV8Translator

- android/gradle.properties
- extensions/tokenizers/rust/Cargo.toml
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizerTest.java
- gradle/libs.versions.toml
> [tokenizer] Updates huggingface tokenizer to 0.21.0

- engines/pytorch/pytorch-engine/README.md
> Update README.md (fix typo)

- extensions/tokenizers/src/main/python/djl_converter/huggingface_converter.py
- extensions/tokenizers/src/main/python/djl_converter/huggingface_models.py
- extensions/tokenizers/src/main/python/djl_converter/model_converter.py
- extensions/tokenizers/src/main/python/djl_converter/zero_shot_classification_converter.py
> [tokenizers] Support import zero-shot-classification to model zoo

- api/src/main/java/ai/djl/modality/nlp/translator/ZeroShotClassificationServingTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/ZeroShotClassificationTranslator.java
> [tokenizers] Fixes ZeroShotClassificationTranslator bug

- api/src/main/java/ai/djl/modality/cv/transform/ResizeShort.java
- api/src/main/java/ai/djl/modality/cv/translator/BaseImageTranslator.java
- api/src/main/java/ai/djl/modality/cv/translator/InstanceSegmentationTranslator.java
- api/src/main/java/ai/djl/modality/cv/translator/SemanticSegmentationTranslator.java
- api/src/main/native/djl/utils.h
- api/src/test/java/ai/djl/modality/cv/transform/ResizeShortTest.java
- api/src/test/java/ai/djl/modality/cv/transform/package-info.java
- api/src/test/java/ai/djl/modality/cv/translator/ImageClassificationTranslatorFactoryTest.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArrayEx.java
- engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_nn_functional.cc
> [api] Refactor image processing

- engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/zoo/OrtHfModelZoo.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/zoo/HfModelZoo.java
> Adds zero-shot-classification to model zoo

- basicdataset/build.gradle.kts
- buildSrc/src/main/kotlin/ai/djl/cppFormatter.gradle.kts
- buildSrc/src/main/kotlin/ai/djl/javaFormatter.gradle.kts
- engines/ml/xgboost/build.gradle.kts
- engines/mxnet/mxnet-engine/build.gradle.kts
- engines/mxnet/mxnet-model-zoo/build.gradle.kts
- engines/mxnet/native/build.gradle.kts
- engines/onnxruntime/onnxruntime-engine/build.gradle.kts
- engines/pytorch/pytorch-jni/build.gradle.kts
- engines/pytorch/pytorch-model-zoo/build.gradle.kts
- engines/pytorch/pytorch-native/build.gradle.kts
- engines/tensorflow/tensorflow-model-zoo/build.gradle.kts
- engines/tensorflow/tensorflow-native/build.gradle.kts
- engines/tensorrt/build.gradle.kts
- extensions/fasttext/build.gradle.kts
- extensions/sentencepiece/build.gradle.kts
- extensions/spark/build.gradle.kts
- extensions/tokenizers/build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
- model-zoo/build.gradle.kts
> [ci] Upgrade gradle to 8.12

- .github/workflows/continuous.yml
- .github/workflows/native_build_mxnet_osx.yml
- .github/workflows/nightly_publish.yml
> [ci] Update upload-artifact action to v4

- api/src/main/java/ai/djl/modality/cv/transform/Pad.java
- api/src/main/java/ai/djl/modality/cv/translator/BaseImageTranslator.java
- api/src/test/java/ai/djl/modality/cv/transform/PadTest.java
> [api] Adds Pad image transform for CV

- engines/pytorch/pytorch-native/build.gradle.kts
> [fix] Fix the pytorch-native ci failure

- .github/workflows/native_s3_fasttext.yml
- extensions/fasttext/build.gradle.kts
- extensions/fasttext/build.sh
This pull request introduces support for the ARM64 architecture `linux-aarch64` in the FastText project in DJL. The addition aims to enhance compatibility with modern ARM-based systems.
Fix: #3585
> [FASTTEXT] Adds linux-aarch64 support

- .github/workflows/nightly_publish.yml
> [ci] Fix nightly publish upload artifact name

- api/src/main/java/ai/djl/ndarray/internal/NDArrayEx.java
- engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArrayEx.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArrayEx.java
- engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArrayEx.java
- extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsNDArrayEx.java
Fixes https://github.com/deepjavalibrary/djl/issues/3587
> Implement NDArray.sub operation

- examples/src/test/java/ai/djl/examples/training/TransferFreshFruitTest.java
> [ci] Fix continuous ci failure

- api/src/main/java/ai/djl/inference/Predictor.java
Fixes https://github.com/deepjavalibrary/djl/issues/3619
> [api] Provide concrete implementation of TranslatorContext

- api/src/main/java/ai/djl/Application.java
- api/src/main/java/ai/djl/modality/cv/VisionLanguageInput.java
- api/src/main/java/ai/djl/modality/cv/translator/ZeroShotObjectDetectionServingTranslator.java
- examples/src/main/java/ai/djl/examples/inference/cv/ZeroShotObjectDetection.java
- examples/src/main/python/trace_owlv2.py
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/ZeroShotObjectDetectionTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/ZeroShotObjectDetectionTranslatorFactory.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/zoo/HfModelZoo.java
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/ZeroShotObjectDetectionTranslatorTest.java
> [api] Add zero shot object detection support

- README.md
- api/README.md
- docs/get.md
- examples/pom.xml
- gradle/libs.versions.toml
> bump build version to 0.33.0

- api/src/main/java/ai/djl/modality/cv/translator/ZeroShotImageClassificationServingTranslator.java
- examples/src/main/java/ai/djl/examples/inference/cv/ZeroShotImageClassification.java
- examples/src/main/python/trace_clip_vit.py
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/ZeroShotImageClassificationTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/ZeroShotImageClassificationTranslatorFactory.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/zoo/HfModelZoo.java
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/ZeroShotImageClassificationTranslatorTest.java
> [api] Adds zero short image classification support

- engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtModel.java
Fixes https://github.com/deepjavalibrary/djl/issues/3629
> [onnxruntime] Fixes intraOpNumThreads bug

- integration/build.gradle.kts
> [ci] Fixes build.gradle for integration

- engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfSymbolBlock.java
- engines/tensorflow/tensorflow-model-zoo/src/test/java/ai/djl/tensorflow/integration/modality/cv/MobileNetTest.java
> [tensorflow] Allow retrieving available signatures for TensorFlow models

- api/src/main/java/ai/djl/repository/MRL.java
- api/src/main/java/ai/djl/repository/zoo/BaseModelLoader.java
- api/src/main/java/ai/djl/repository/zoo/ModelLoader.java
- api/src/main/java/ai/djl/repository/zoo/ModelZoo.java
- docs/load_model.md
- examples/src/main/java/ai/djl/examples/inference/ListModels.java
- examples/src/main/resources/log4j2.xml
- examples/src/test/java/ai/djl/examples/inference/ListModelsTest.java
- extensions/fasttext/src/test/java/ai/djl/fasttext/CookingStackExchangeTest.java
> [api] Improve listModel performance

- gradle/wrapper/gradle-wrapper.properties
- jacoco/build.gradle.kts
> [ci] Upgrade gradle to 8.13

- api/src/main/java/ai/djl/modality/nlp/EmbeddingOutput.java
- api/src/main/java/ai/djl/modality/nlp/translator/SparseRetrievalServingTranslator.java
- api/src/main/java/ai/djl/util/JsonSerializable.java
- api/src/main/java/ai/djl/util/PairList.java
- examples/src/main/java/ai/djl/examples/inference/nlp/SparseRetrieval.java
- examples/src/main/java/ai/djl/examples/inference/nlp/ZeroShotClassification.java
- extensions/aws-ai/src/test/resources/log4j2.xml
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/CrossEncoderTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/FillMaskTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/QuestionAnsweringTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/SparseRetrievalTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextClassificationTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextEmbeddingTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextEmbeddingTranslatorFactory.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TokenClassificationTranslator.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/ZeroShotClassificationTranslator.java
- extensions/tokenizers/src/main/python/djl_converter/sentence_similarity_converter.py
- extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/SparseRetrievalTranslatorTest.java
- integration/src/main/resources/log4j2.xml
> [tokenizers] Adds SparseRetrievalTranslator

- api/src/main/java/ai/djl/ndarray/NDArray.java
- api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
- engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
- engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_torch_pointwise.cc
- engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
- extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsNDArray.java
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayNumericOpTest.java
- this is the issue https://github.com/deepjavalibrary/djl/issues/2844
> [pytorch] Add diff support

- README.md
> docs: added a link to the continuous badge

- engines/onnxruntime/onnxruntime-engine/README.md
> [doc] Update onnxruntime readme

- README.md
> chore: added an icon to the release

- .github/workflows/nightly_publish.yml
> [onnx] use zulu jdk to fix windows issues

- .github/workflows/nightly_publish.yml
> [onnx] fix one more usage of java distribution to zulu for windows

- engines/mxnet/mxnet-model-zoo/README.md
- model-zoo/README.md
> [docs] Update model zoo document

- api/src/main/java/ai/djl/repository/RemoteRepository.java
- api/src/main/java/ai/djl/repository/RepositoryFactoryImpl.java
- api/src/main/java/ai/djl/repository/zoo/ModelZoo.java
- basicdataset/src/main/java/ai/djl/basicdataset/BasicDatasets.java
- engines/mxnet/mxnet-model-zoo/src/main/java/ai/djl/mxnet/zoo/MxModelZoo.java
- engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/zoo/OrtHfModelZoo.java
- engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/zoo/OrtModelZoo.java
- engines/pytorch/pytorch-model-zoo/src/main/java/ai/djl/pytorch/zoo/PtModelZoo.java
- engines/tensorflow/tensorflow-model-zoo/src/main/java/ai/djl/tensorflow/zoo/TfModelZoo.java
- engines/tensorrt/src/test/java/ai/djl/tensorrt/engine/TrtEngineTest.java
- extensions/fasttext/src/main/java/ai/djl/fasttext/zoo/FtModelZoo.java
- extensions/tokenizers/src/main/java/ai/djl/engine/rust/zoo/RsModelZoo.java
- extensions/tokenizers/src/main/java/ai/djl/huggingface/zoo/HfModelZoo.java
- model-zoo/src/main/java/ai/djl/basicmodelzoo/BasicModelZoo.java
> Treat model server as a remote model

- android/gradle.properties
> [android] Upgrade DJL version to 0.34.0

- api/src/main/java/ai/djl/engine/rpc/RpcClient.java
- api/src/test/java/ai/djl/engine/rpc/RpcTranslatorFactoryTest.java
> Adds jsonlines streaming support for RpcEngine

- api/src/main/java/ai/djl/engine/rpc/RpcTranslatorFactory.java
- bom/build.gradle.kts
- extensions/genai/src/main/java/ai/djl/genai/openai/ChatInput.java
- extensions/genai/src/main/java/ai/djl/genai/openai/ChatOutput.java
- extensions/genai/src/main/java/ai/djl/genai/openai/Content.java
- extensions/genai/src/main/java/ai/djl/genai/openai/Function.java
- extensions/genai/src/main/java/ai/djl/genai/openai/Message.java
- extensions/genai/src/main/java/ai/djl/genai/openai/Tool.java
- extensions/genai/src/main/java/ai/djl/genai/openai/ToolCall.java
Adds tool call to ChatInput
Adds genai module to BOM
> [genai] tool calls to ChatInput

- extensions/genai/src/main/java/ai/djl/genai/FunctionUtils.java
- extensions/genai/src/main/java/ai/djl/genai/gemini/GeminiOutput.java
- extensions/genai/src/main/java/ai/djl/genai/gemini/types/FunctionDeclaration.java
- extensions/genai/src/test/java/ai/djl/genai/gemini/GeminiTest.java
> Improve function call for genai extension

- android/build.gradle
- buildSrc/src/main/kotlin/ai/djl/javaBase.gradle.kts
- docs/get.md
- engines/pytorch/pytorch-engine/README.md
- examples/pom.xml
- settings.gradle.kts
> Update oss sonatype snapshot repository url

- android/gradle.properties
> [android] Upgrade pytorch version to 2.7.1

- .github/workflows/native_s3_fasttext.yml
> [ci] Fix fasttext native workflow

- api/README.md
- docs/get.md
- engines/pytorch/pytorch-engine/README.md
- examples/pom.xml
- gradle/libs.versions.toml
> Increase build version to 0.35.0

- .github/workflows/native_jni_s3_pytorch.yml
Add pytorch jni precxx11 job for pytorch 1.13.1 and 2.5.1.
> [ci] Build pytorch jni cpu precxx

- api/src/main/java/ai/djl/modality/cv/translator/YoloSegmentationTranslator.java
> Fixes #3774 for YoloSegmentationTranslator

- engines/ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbModel.java
> [XGBoost] Support json model for XGBoost

- api/src/main/java/ai/djl/translate/NoopServingTranslatorFactory.java
- api/src/test/java/ai/djl/translate/NoopServingTranslatorFactoryTest.java
> [api] Accept json input/output for tensor input

- .github/workflows/continuous.yml
- api/build.gradle.kts
- buildSrc/src/main/kotlin/ai/djl/cppFormatter.gradle.kts
- buildSrc/src/main/kotlin/ai/djl/javaFormatter.gradle.kts
- buildSrc/src/main/kotlin/ai/djl/stats.gradle.kts
- engines/ml/xgboost/build.gradle.kts
- engines/mxnet/mxnet-engine/build.gradle.kts
- engines/mxnet/native/build.gradle.kts
- engines/pytorch/pytorch-engine/build.gradle.kts
- engines/pytorch/pytorch-jni/build.gradle.kts
- engines/pytorch/pytorch-native/build.gradle.kts
- engines/tensorflow/tensorflow-engine/build.gradle.kts
- engines/tensorflow/tensorflow-native/build.gradle.kts
- extensions/fasttext/build.gradle.kts
- extensions/sentencepiece/build.gradle.kts
- extensions/spark/build.gradle.kts
- extensions/tokenizers/build.gradle.kts
- gradle.properties
> Update gradle build script to support configuration cache

- .github/workflows/native_jni_s3_pytorch.yml
- engines/pytorch/pytorch-native/build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
Fix https://github.com/deepjavalibrary/djl/actions/runs/17848936721/job/50753707551
> Fix pytorch native build for windows
