deepjavalibrary/djl

- docs/quick_start.md
Copy edit pass for tense and clarity. Prereqs here could list "general familiarity with Java programming language."
Copy edit to improve clarity.
> Edit pass for readability

- model-uploader/python/mxnet/gluoncv_import.py
- model-uploader/python/mxnet/requirement.txt
- model-uploader/python/tensorflow/keras_import.py
- model-uploader/python/tensorflow/requirement.txt
- model-uploader/src/main/java/ai/djl/uploader/Exporter.java
- model-uploader/src/main/java/ai/djl/uploader/ExporterArguments.java
- model-uploader/src/main/java/ai/djl/uploader/KerasMetaBuilder.java
- model-uploader/src/main/java/ai/djl/uploader/arguments/KerasArgs.java
Add a few licenses and add keras h5 formatted file upload option
> add keras upload option

- model-uploader/.gitignore
- model-uploader/python/mxnet/gluoncv_import.py
- model-uploader/src/main/java/ai/djl/uploader/Exporter.java
- model-uploader/src/main/java/ai/djl/uploader/ExporterArguments.java
- model-uploader/src/main/java/ai/djl/uploader/GluonCvMetaBuilder.java
- model-uploader/src/main/java/ai/djl/uploader/MetadataBuilder.java
- model-uploader/src/main/java/ai/djl/uploader/arguments/KerasArgs.java
- model-uploader/src/test/java/ai/djl/uploader/ExporterTest.java
- model-uploader/src/test/java/ai/djl/uploader/LocalTest.java
- model-uploader/src/test/java/ai/djl/uploader/RemoteTest.java
Change-Id: I7483461aab3975d5ab1f13ca5875cc9ea99e20b1
> Update GluonCV importer

- model-uploader/python/pytorch/huggingface_import.py
- model-uploader/python/pytorch/requirement.txt
- model-uploader/src/main/java/ai/djl/uploader/Exporter.java
- model-uploader/src/main/java/ai/djl/uploader/ExporterArguments.java
- model-uploader/src/main/java/ai/djl/uploader/GluonCvMetaBuilder.java
- model-uploader/src/main/java/ai/djl/uploader/HuggingFaceMetaBuilder.java
- model-uploader/src/main/java/ai/djl/uploader/MetaBuilder.java
- model-uploader/src/main/java/ai/djl/uploader/MetadataBuilder.java
- model-uploader/src/main/java/ai/djl/uploader/arguments/HuggingFaceArgs.java
add hugging face import option. Refactor the MetaBuilder architecture
> add huggingface exporter

- model-uploader/src/main/java/ai/djl/uploader/GluonCvMetaBuilder.java
- model-uploader/src/main/java/ai/djl/uploader/MetadataBuilder.java
Change-Id: I45cd7309cf0a390123f142d25f9a1bac6f8599a3
> Fix GluonCV importer issues

- api/README.md
- basicdataset/README.md
- docs/development/development_guideline.md
- docs/development/troubleshooting.md
- model-zoo/README.md
Some minor additions to the documentation markdown, no code.
- I did not add any information on memory management, I will write a short guide on writing custom blocks once I finished the changes to `AbstractBlock`
> Minor doc updates

- jupyter/tutorial/image_classification_with_your_model.ipynb
Added missing import and updated wording for thread-safety statement to improve clarity.
> Update image_classification_with_your_model tutorial

- jupyter/d2l-java/chapter_linear-networks/linear-regression-djl.ipynb
- jupyter/d2l-java/utils/DataPoints.java
- jupyter/d2l-java/utils/Training.java
1st Draft of Concise Implementation of Linear Regression
Added 2 utility classes (DataPoints, Training)
> Created 1st draft of 3.3 Concise Implementation of Linear Regression and added some utilities

- basicdataset/src/main/java/ai/djl/basicdataset/FashionMnist.java
- basicdataset/src/test/java/ai/djl/basicdataset/FashionMnistTest.java
- basicdataset/src/test/resources/mlrepo/dataset/cv/ai/djl/basicdataset/fashmnist/metadata.json
Addition: Adding FashionMnist dataset and the relevant test and metadata file associated with it.
> Adding FashionMnist dataset files.

- jupyter/d2l-java/chapter_convolutional-neural-networks/channels.ipynb
- jupyter/d2l-java/chapter_convolutional-neural-networks/pooling.ipynb
Addition: CNN chapter section 6.4 and 6.5.
6.4 - Multiple Input and Output Channels
6.5 - Pooling
> Section 6.4 and 6.5

- api/src/main/java/ai/djl/training/listener/CheckpointsTrainingListener.java
- api/src/main/java/ai/djl/training/listener/DivergenceCheckTrainingListener.java
- api/src/main/java/ai/djl/training/listener/EpochTrainingListener.java
- api/src/main/java/ai/djl/training/listener/EvaluatorTrainingListener.java
- api/src/main/java/ai/djl/training/listener/MemoryTrainingListener.java
- api/src/main/java/ai/djl/training/listener/TimeMeasureTrainingListener.java
- api/src/main/java/ai/djl/training/listener/TrainingListenerAdapter.java
Change-Id: I2c2d3d9f80ab53c7a40f7c16ded1318c1d9d78b4
Co-authored-by: Frank Liu<frankfliu2000@gmail.com>
> Refactor TrainingLister

- api/src/main/java/ai/djl/training/listener/LoggingTrainingListener.java
Change-Id: Ic086c976209292a8b19f93aa7bc895ca19e96a47
1. Use scientific notation for small or large values
2. does not print validation information if no validation data.
- If this change is a backward incompatible change, why must …
> fix validate listener

- jupyter/d2l-java/chapter_installation/index.ipynb
- jupyter/d2l-java/chapter_linear-networks/image-classification-dataset.ipynb
- jupyter/d2l-java/chapter_linear-networks/linear-regression-djl.ipynb
- jupyter/d2l-java/chapter_linear-networks/linear-regression-scratch.ipynb
- jupyter/d2l-java/chapter_linear-networks/linear-regression.ipynb
- jupyter/d2l-java/chapter_multilayer-perceptrons/dropout.ipynb
- jupyter/d2l-java/chapter_preliminaries/ndarray.ipynb
1. cleared outputs.
2. use 0.7.0 snapshot for consistency
3. minor update on install command line.
> clear output and minor fix on notebooks

- jupyter/d2l-java/chapter_convolutional-neural-networks/channels.ipynb
- jupyter/d2l-java/chapter_convolutional-neural-networks/conv-layer.ipynb
- jupyter/d2l-java/chapter_convolutional-neural-networks/lenet.ipynb
- jupyter/d2l-java/chapter_convolutional-neural-networks/padding-and-strides.ipynb
- jupyter/d2l-java/chapter_convolutional-neural-networks/pooling.ipynb
Fixes all the Conv2d errors in cnn chapter 6. Added comments and cleaned up LeNet ipynb.
> Added comments and fixed conv2d function errors.

- jupyter/d2l-java/chapter_convolutional-modern/alexnet.ipynb
- jupyter/d2l-java/chapter_convolutional-modern/vgg.ipynb
Addition: Cleaned AlexNet and VGG implementation (Section 7.1-7.2) after the new nightly build which fixed the Dropout problem and the Conv2d changes.
> Fix AlexNet and VGG Implementation.

- jupyter/d2l-java/chapter_convolutional-modern/nin.ipynb
Addition: NiN network implemented (Section 7.3)
> NiN network implementation.

- jupyter/d2l-java/chapter_convolutional-modern/googlenet.ipynb
Adding GoogleNet implementation ipynb. (Section 7.4)
> GoogleNet modern-cnn implementation.

- jupyter/d2l-java/chapter_convolutional-modern/resnet.ipynb
Addition: ResNet implementation of the d2l book.
> ResNet Implementation Section 7.6

- jupyter/d2l-java/chapter_convolutional-modern/densenet.ipynb
Addition: Implemented DenseNet Section 7.7
> DenseNet Implementation Section 7.7

- README.md
> add DJL's D2l Book

- docs/development/CSVDataset.java
- docs/development/how_to_use_dataset.md
> #161 adapt CSVDataset sample and documentation to latest codebase

- api/src/main/java/ai/djl/ndarray/types/Shape.java
- docs/development/how_to_use_dataset.md
update javadoc, remove confusing
> fix typo in "joins a this" and update how_to_use_dataset.md

- README.md
This PR add release link to the recent 0.8.0 release
> add 0.8.0 release content

- pytorch/pytorch-native/README.md
Add pytorch native package release process
> Add pytorch native package release process

- serving/src/main/java/ai/djl/serving/Arguments.java
- serving/src/main/java/ai/djl/serving/ModelServer.java
- serving/src/main/java/ai/djl/serving/util/ConfigManager.java
- serving/src/main/javadoc/overview.html
- tools/gradle/publish.gradle
> Add log for model server initialization

- examples/build.gradle
Previously we need to specify default_engine MXNet to use optimal config
> Set default optimal performance config for default MXNet engine

- docs/mkdocs.yml
Change-Id: Icd4753a5f5cac86858c1c55ac2cbd68a969e7fa0
This change is in sync with the most recent release of mkdocs-material on the navigation bar change
> update documentation build with mkdocs-material

- docs/README.md
- docs/mkdocs.yml
- docs/roadmap.md
> Add roadmap document

- examples/src/test/java/ai/djl/examples/training/TrainResNetTest.java
- extensions/fasttext/src/test/java/ai/djl/fasttext/CookingStackExchangeTest.java
1. add more epochs to reduce flakiness
2. skip fastText test on windows
> Fix nightly test for windows & linux

- examples/src/main/java/ai/djl/examples/training/TrainCaptcha.java
- examples/src/main/java/ai/djl/examples/training/TrainMnist.java
- examples/src/main/java/ai/djl/examples/training/TrainMnistWithLSTM.java
- examples/src/main/java/ai/djl/examples/training/TrainPikachu.java
- examples/src/main/java/ai/djl/examples/training/TrainSentimentAnalysis.java
- examples/src/main/java/ai/djl/examples/training/TrainSeq2Seq.java
- examples/src/main/java/ai/djl/examples/training/TrainTicTacToe.java
- examples/src/main/java/ai/djl/examples/training/TrainWithHpo.java
- examples/src/main/java/ai/djl/examples/training/transferlearning/TrainResnetWithCifar10.java
- examples/src/main/java/ai/djl/examples/training/util/Arguments.java
- examples/src/test/java/ai/djl/examples/training/TrainCaptchaTest.java
- examples/src/test/java/ai/djl/examples/training/TrainMnistTest.java
- examples/src/test/java/ai/djl/examples/training/TrainMnistWithLSTMTest.java
- examples/src/test/java/ai/djl/examples/training/TrainPikachuTest.java
- examples/src/test/java/ai/djl/examples/training/TrainResNetTest.java
- examples/src/test/java/ai/djl/examples/training/TrainSentimentAnalysisTest.java
- examples/src/test/java/ai/djl/examples/training/TrainSeq2SeqTest.java
- examples/src/test/java/ai/djl/examples/training/TrainTicTacToeTest.java
> Print out training examples command line options

- api/src/main/java/ai/djl/engine/Engine.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxEngine.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtEngine.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfEngine.java
> Include last exception in no deep engine found exception

- basicdataset/src/main/java/ai/djl/basicdataset/CocoDetection.java
- basicdataset/src/main/java/ai/djl/basicdataset/CocoMetadata.java
- basicdataset/src/test/java/ai/djl/basicdataset/CocoTest.java
This address github issue mentioned #190
Change-Id: Ic159b9a5a174b8d42004fed29998a41841fde33e
> Fix CocoDetection dataset metadata.

- index.html
- website/blog.html
- website/demo.html
- website/javadoc.html
Add google tag manager for events on website.
> Google Tag Manager

- api/src/main/java/ai/djl/ndarray/NDManager.java
- api/src/test/java/ai/djl/test/mock/MockNDManager.java
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayCreationOpTest.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDManager.java
- onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtNDManager.java
- pytorch/pytorch-engine/build.gradle
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDManager.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
- pytorch/pytorch-native/src/ai_djl_pytorch_jni_PyTorchLibrary_torch_creation.cc
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDManager.java
Add COO sparse NDArray creation for pytorch
> add sparse creation support for pytorch

- docs/mkdocs.yml
Add some pointer to load models
> add load model url

- api/src/main/java/ai/djl/engine/Engine.java
- integration/src/main/java/ai/djl/integration/util/DebugEnvironment.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxEngine.java
- onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtEngine.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtEngine.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfEngine.java
> Refactor debugEnvironment

- docs/mkdocs.yml
Use prebuilt index to accelerate search speed on doc site
> accelerate search speed by prebuilt index

- api/src/main/java/ai/djl/training/dataset/RandomAccessDataset.java
- basicdataset/src/main/java/ai/djl/basicdataset/AbstractImageFolder.java
- basicdataset/src/main/java/ai/djl/basicdataset/AirfoilRandomAccess.java
- basicdataset/src/main/java/ai/djl/basicdataset/AmesRandomAccess.java
- basicdataset/src/main/java/ai/djl/basicdataset/CsvDataset.java
- basicdataset/src/test/java/ai/djl/basicdataset/AirfoilRandomAccessTest.java
- basicdataset/src/test/java/ai/djl/basicdataset/AmesRandomAccessTest.java
> Add CsvDataset

- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/LibUtils.java
> Workaround JavaCPP bug

- .github/workflows/continuous_tensorflow.yml
- .github/workflows/nightly.yml
- tensorflow/tensorflow-engine/README.md
> add TF windows build

- docs/load_model.md
> Fix load model document

- api/src/main/java/ai/djl/repository/RepositoryFactoryImpl.java
> Validate url scheme on Repository creation

- .github/workflows/continuous.yml
> Add compileJNI stage on Continuous test

- .github/workflows/continuous.yml
- api/src/main/java/ai/djl/ndarray/NDManager.java
- api/src/test/java/ai/djl/test/mock/MockNDManager.java
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayCreationOpTest.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDManager.java
- onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtNDManager.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDManager.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
- pytorch/pytorch-native/src/ai_djl_pytorch_jni_PyTorchLibrary_torch_random_sampling.cc
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDManager.java
> Add randint op support

- examples/build.gradle
- integration/build.gradle
> Use tensorflow 2.3.1 for examples and integration module

- api/src/main/java/ai/djl/training/listener/LoggingTrainingListener.java
- api/src/main/java/ai/djl/training/listener/TrainingListener.java
> Allows to config how many epochs to print in the logging

- .github/workflows/continuous.yml
> Collect PyTorch and TensorFlow test reports

- bom/build.gradle
> Add classifier item in BOM

- docs/development/dependency_management.md
- docs/development/troubleshooting.md
- jupyter/tensorflow/pneumonia_detection.ipynb
- tensorflow/README.md
- tensorflow/tensorflow-native/build.gradle
> Update dependency documents

- api/src/main/java/ai/djl/modality/cv/BufferedImageFactory.java
- pytorch/pytorch-engine/build.gradle
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
- pytorch/pytorch-engine/src/test/java/integration/MkldnnTest.java
- pytorch/pytorch-engine/src/test/java/integration/ProfilerTest.java
- pytorch/pytorch-native/src/ai_djl_pytorch_jni_PyTorchLibrary_system.cc
- pytorch/pytorch-native/src/djl_pytorch_jni_utils.h
> Add PyTorch Profiler

- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
- pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/ProfilerTest.java
- pytorch/pytorch-native/src/ai_djl_pytorch_jni_PyTorchLibrary_system.cc
> [PyTorch] Add input shape and memory support

- tensorflow/tensorflow-native/build.gradle
> Support tensorflow 2.3.1 windows GPU

- docs/faq.md
- tensorflow/README.md
> Update tensorflow engine README

- api/src/main/java/ai/djl/ndarray/index/NDIndex.java
> Fix #236, make regex compatible with Android

- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/jna/PointerArray.java
> Fix ClassCastException in PointerArray

- api/src/main/java/ai/djl/modality/rl/agent/QAgent.java
- api/src/main/java/ai/djl/training/tracker/LinearTracker.java
- examples/src/main/java/ai/djl/examples/training/TrainTicTacToe.java
- examples/src/test/java/ai/djl/examples/training/TrainTicTacToeTest.java
I tried using QAgent in my personal project, based on TrainTicTacToe example, but the Agent wasn't learning at all.
After looking at the code I have found a few problems:
- trainer.step() isn't executed at all
- QAgent's trainBatch method does not use previous observation nor step.isDone method
- LinearTracker doesn't work for negative slope
- LinearTracker doesn't seem to have a dedicated test, but the negative slope variant
should be covered by TicTacToeTest
> TrainTicTacToe example is not performing any training

- api/src/main/java/ai/djl/training/ParameterStore.java
Prevent multithreading call to copies
> add synchronized block in parameter copying

- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxModel.java
> Avoid MxPredictor race condition

- .github/workflows/native_s3_tflite.yml
This is a Simple pipeline to build tflite binary from source to JNI for Linux and Mac 
> add tflite build process

- docs/onnxruntime/hybrid_engine.md
Use Microsoft provided package as a default
> update ONNX document

- .github/workflows/native_s3_tflite.yml
> fix the path issue on libtensorflowlite

- examples/src/main/java/ai/djl/examples/inference/benchmark/MultithreadedBenchmark.java
> Close model in benchmark

- examples/src/main/java/ai/djl/examples/training/TrainSentimentAnalysis.java
- examples/src/test/java/ai/djl/examples/training/TrainSentimentAnalysisTest.java
This PR trying to fix issue #257 
> apply fix to the sentiment analysis training

- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayCreationOpTest.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray16.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDManager.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxParameterServer.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/jna/FunctionInfo.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/jna/JnaUtils.java
- mxnet/mxnet-engine/src/test/java/ai/djl/mxnet/engine/MxNDArrayTest.java
> Refactor SparseFormat handling for MXNDArray

- basicdataset/src/main/java/ai/djl/basicdataset/ImageNet.java
> Fix #254, avoid InputStream leak

- tensorflow/tensorflow-model-zoo/build.gradle
> Remove -SNAPSHOT for TensorFlow 2.3.1

- api/src/main/java/ai/djl/repository/JarRepository.java
- api/src/main/java/ai/djl/repository/RepositoryFactoryImpl.java
- api/src/test/java/ai/djl/repository/JarRepositoryTest.java
- api/src/test/java/ai/djl/repository/package-info.java
- docs/load_model.md
> Support load model from jar file

- basicdataset/src/main/java/ai/djl/basicdataset/CsvDataset.java
- basicdataset/src/main/java/ai/djl/basicdataset/utils/DynamicBuffer.java
> Support variable feature length for CsvDataset.

- docs/development/cache_management.md
- docs/development/configure_logging.md
- docs/development/how_to_use_dataset.md
- docs/development/inference_performance_optimization.md
- docs/how_to_collect_metrics.md
- docs/interactive_tool.md
- docs/load_model.md
- docs/mkdocs.yml
- docs/model-zoo.md
Divide docs into sections, rename docs for better consistency
> Reorganize docs

- examples/build.gradle
> Disable close NDArray on GC for multi-threading benchmenk

- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/IValueUtils.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
- pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/TorchScriptTest.java
- pytorch/pytorch-native/CMakeLists.txt
- pytorch/pytorch-native/src/ai_djl_pytorch_jni_PyTorchLibrary_inference.cc
- pytorch/pytorch-native/src/ai_djl_pytorch_jni_PyTorchLibrary_ivalue.cc
- pytorch/pytorch-native/src/ai_djl_pytorch_jni_PyTorchLibrary_nn_functional.cc
- pytorch/pytorch-native/src/ai_djl_pytorch_jni_PyTorchLibrary_optim.cc
- pytorch/pytorch-native/src/ai_djl_pytorch_jni_PyTorchLibrary_system.cc
- pytorch/pytorch-native/src/ai_djl_pytorch_jni_PyTorchLibrary_tensor.cc
- pytorch/pytorch-native/src/ai_djl_pytorch_jni_PyTorchLibrary_torch_comparison.cc
- pytorch/pytorch-native/src/ai_djl_pytorch_jni_PyTorchLibrary_torch_creation.cc
- pytorch/pytorch-native/src/ai_djl_pytorch_jni_PyTorchLibrary_torch_isjm.cc
- pytorch/pytorch-native/src/ai_djl_pytorch_jni_PyTorchLibrary_torch_other.cc
- pytorch/pytorch-native/src/ai_djl_pytorch_jni_PyTorchLibrary_torch_pointwise.cc
- pytorch/pytorch-native/src/ai_djl_pytorch_jni_PyTorchLibrary_torch_random_sampling.cc
- pytorch/pytorch-native/src/ai_djl_pytorch_jni_PyTorchLibrary_torch_reduction.cc
- pytorch/pytorch-native/src/djl_pytorch_jni_exception.h
- pytorch/pytorch-native/src/djl_pytorch_jni_utils.h
> Support 1-D list and dict input for TorchScript

- pytorch/pytorch-native/build.gradle
Bump up pytorch version to publish 1.7.0-SNAPSHOT native
> native publish pytorch 1.7.0

- api/src/main/java/ai/djl/inference/Predictor.java
- api/src/main/java/ai/djl/ndarray/BaseNDManager.java
- api/src/main/java/ai/djl/ndarray/NDManager.java
- api/src/main/java/ai/djl/training/Trainer.java
- api/src/main/java/ai/djl/training/dataset/Batch.java
- api/src/main/java/ai/djl/training/dataset/DataIterable.java
- api/src/test/java/ai/djl/test/mock/MockNDManager.java
- basicdataset/src/main/java/ai/djl/basicdataset/Cifar10.java
- basicdataset/src/main/java/ai/djl/basicdataset/FashionMnist.java
- basicdataset/src/main/java/ai/djl/basicdataset/Mnist.java
- basicdataset/src/main/java/ai/djl/basicdataset/TextDataset.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxModel.java
- onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtModel.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtModel.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfModel.java
This change will try to make the printout cleaner. All managers inside DJL packages are assgined with names
> add names for managers

- api/src/main/java/ai/djl/training/LocalParameterServer.java
- api/src/main/java/ai/djl/training/ParameterServer.java
> Fix MxParameterServer memory leak

- integration/src/main/java/ai/djl/integration/tests/ndarray/NDIndexTest.java
setScalar with correct number should update the ndarray correctly. Thus in this PR, we will add an assertion.
> test: setScalar with a scalar should update the ndarray correctly

- .github/workflows/native_jni_s3_pytorch.yml
- examples/build.gradle
- gradle.properties
- integration/build.gradle
- onnxruntime/onnxruntime-engine/build.gradle
- pytorch/pytorch-engine/build.gradle
- pytorch/pytorch-native/README.md
- pytorch/pytorch-native/build.cmd
- pytorch/pytorch-native/build.gradle
- pytorch/pytorch-native/build.sh
- pytorch/pytorch-native/src/ai_djl_pytorch_jni_PyTorchLibrary_system.cc
> JNI publish prep

- api/src/main/java/ai/djl/modality/nlp/bert/WordpieceTokenizer.java
> Reduce object creation in WordpieceTokenizer

- .github/workflows/native_jni_s3_pytorch_android.yml
- .github/workflows/native_s3_pytorch_android.yml
- android/pytorch-native/build.gradle
- pytorch/pytorch-native/build_android.sh
Upgrade pytorch Android version to 1.7.0
> upgrade pytorch android version to 1.7.0

- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java
Loading CUDNN library by order running on PyTorch
> update windows load cndnn8 for PyTorch

- api/src/main/java/ai/djl/training/dataset/DataIterable.java
- basicdataset/src/main/java/ai/djl/basicdataset/TextDataset.java
- basicdataset/src/main/java/ai/djl/basicdataset/utils/FixedBucketSampler.java
- basicdataset/src/test/java/ai/djl/basicdataset/FixedBucketSamplerTest.java
> Fix #257, proper implement FixedBucketSampler

- api/src/main/java/ai/djl/training/listener/TimeMeasureTrainingListener.java
> Fix NullPointerException in TimeMeasureTrainingListener

- android/build.gradle
- android/gradle.properties
- android/pytorch-native/build.gradle
Fix on Android nightly publish to 0.9.0
> fix android nightly publish

- examples/build.gradle
- examples/src/main/java/ai/djl/examples/inference/benchmark/util/AbstractBenchmark.java
- onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtNDManager.java
> Support benchmark OnnxRuntime model

- api/src/main/java/ai/djl/modality/nlp/bert/WordpieceTokenizer.java
> Fix WordpieceTokenizer infinite loop

- api/src/main/java/ai/djl/training/dataset/RandomAccessDataset.java
- basicdataset/src/main/java/ai/djl/basicdataset/AbstractImageFolder.java
- basicdataset/src/main/java/ai/djl/basicdataset/BananaDetection.java
- basicdataset/src/main/java/ai/djl/basicdataset/CaptchaDataset.java
- basicdataset/src/main/java/ai/djl/basicdataset/CocoDetection.java
- basicdataset/src/main/java/ai/djl/basicdataset/PikachuDetection.java
- basicdataset/src/main/java/ai/djl/basicdataset/StanfordMovieReview.java
- basicdataset/src/main/java/ai/djl/basicdataset/TatoebaEnglishFrenchDataset.java
- basicdataset/src/test/java/ai/djl/basicdataset/RandomAccessDatasetTest.java
> Fix randomSplit dataset bug

- .github/workflows/native_s3_sentencepiece.yml
> Add missing test to create jni folder

- basicdataset/build.gradle
- gradle.properties
> Update basicdataset dependency

- api/src/main/java/ai/djl/inference/Predictor.java
- extensions/fasttext/src/main/java/ai/djl/fasttext/jni/NativeResource.java
- extensions/sentencepiece/src/main/java/ai/djl/sentencepiece/SpProcessor.java
- extensions/sentencepiece/src/main/java/ai/djl/sentencepiece/jni/NativeResource.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/jna/NativeResource.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/NativeResource.java
> Fix sentencepiece native close issue

- extensions/sentencepiece/CMakeLists.txt
> [sentencepiece] Link against static library

- api/src/main/java/ai/djl/training/dataset/Batch.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
Fix pytorch bugs in nightly tests
> fix pytorch bugs

- api/src/main/java/ai/djl/modality/Input.java
- serving/build.gradle
- serving/src/main/java/ai/djl/serving/wlm/WorkLoadManager.java
- serving/src/main/java/ai/djl/serving/wlm/WorkerThread.java
> Refactor WorkerThread exception handling

- .github/workflows/native_s3_sentencepiece.yml
- extensions/sentencepiece/CMakeLists.txt
> Disable tcmalloc for sentencepiece to avoid extra dependency

- api/src/main/java/ai/djl/repository/zoo/Criteria.java
> allow load model using path from Criteria

- api/src/main/java/ai/djl/modality/Classifications.java
- api/src/main/java/ai/djl/util/JsonUtils.java
- integration/src/main/java/ai/djl/integration/tests/model_zoo/CustomTranslatorTest.java
- serving/src/test/java/ai/djl/serving/ModelServerTest.java
> Pretty print json for Classifications

- serving/docker/config.properties
- serving/docker/serving/build.gradle
- serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
- serving/src/main/java/ai/djl/serving/util/ConfigManager.java
> Support load model on first predict request

- integration/src/main/java/ai/djl/integration/tests/training/GradientCollectorIntegrationTest.java
current testing, noise is not added to label, need to use in-place operation
> test: add noise to label in-place

- api/src/main/java/ai/djl/training/ParameterStore.java
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayCreationOpTest.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxModel.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray16.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDManager.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxParameterServer.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxSparseNDArray.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/jna/FunctionInfo.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/jna/JnaUtils.java
- mxnet/mxnet-engine/src/test/java/ai/djl/mxnet/engine/MxNDArrayTest.java
- mxnet/mxnet-engine/src/test/java/ai/djl/mxnet/test/MockMxnetLibrary.java
> Avoid copy parameters form MXNet predictor

- serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
- serving/src/main/java/ai/djl/serving/wlm/ModelManager.java
> Fix model name mismatch bug

- api/src/main/java/ai/djl/ndarray/NDSerializer.java
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayOtherOpTest.java
> Serialize NDArray name

- index.html
- website/js/init.js
Add customer story at main page
> update main page

- model-zoo/src/main/java/ai/djl/basicmodelzoo/cv/classification/MlpModelLoader.java
- model-zoo/src/main/java/ai/djl/basicmodelzoo/cv/classification/ResNetModelLoader.java
- model-zoo/src/main/java/ai/djl/basicmodelzoo/cv/object_detection/ssd/SsdModelLoader.java
- model-zoo/src/test/resources/mlrepo/model/cv/image_classification/ai/djl/zoo/mlp/metadata.json
- model-zoo/src/test/resources/mlrepo/model/cv/image_classification/ai/djl/zoo/resnet/metadata.json
- model-zoo/src/test/resources/mlrepo/model/cv/object_detection/ai/djl/zoo/ssd/metadata.json
> Update model zoo parameter encode format

- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpDataType.java
- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jna/JnaUtils.java
- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jna/NativeSize.java
- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jna/PD_Buffer.java
- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jna/PaddleLibrary.java
- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jna/package-info.java
> add paddle jna

- extensions/fasttext/src/main/resources/META-INF/native-image/ai/djl/fasttext/fasttext/jni-config.json
- extensions/sentencepiece/src/main/resources/META-INF/native-image/ai/djl/sentencepiece/sentencepiece/jni-config.json
> Remove Pointer class from graalvm config file

- mxnet/mxnet-model-zoo/src/main/java/ai/djl/mxnet/zoo/nlp/embedding/GloveWordEmbeddingModelLoader.java
- mxnet/mxnet-model-zoo/src/test/resources/mlrepo/model/nlp/word_embedding/ai/djl/mxnet/glove/metadata.json
> Update MXNet Glove model file with new NDArray encoding

- examples/build.gradle
> Save gc log in benchmark

- api/src/main/java/ai/djl/ndarray/NDList.java
- api/src/main/java/ai/djl/ndarray/NDSerializer.java
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDListTest.java
> Avoid decode corrupted NDList

- dlr/dlr-engine/build.gradle
- dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrEngine.java
- dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrEngineProvider.java
- dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrModel.java
- dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrSymbolBlock.java
- dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/package-info.java
- dlr/dlr-engine/src/main/java/ai/djl/dlr/jni/DlrLibrary.java
- dlr/dlr-engine/src/main/java/ai/djl/dlr/jni/JniUtils.java
- dlr/dlr-engine/src/main/java/ai/djl/dlr/jni/LibUtils.java
- dlr/dlr-engine/src/test/java/ai/djl/dlr/integraion/DlrTest.java
- dlr/dlr-engine/src/test/java/ai/djl/dlr/integraion/package-info.java
- dlr/dlr-native/build.sh
- dlr/dlr-native/src/main/native/ai_djl_dlr_jni_DlrLibrary.cc
> Add DLR native support part 2

- serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
> Read model_name for request body

- .github/workflows/native_build_mxnet_osx.yml
- .github/workflows/native_s3_dlr.yml
- gradle.properties
> DLR native macos build

- .github/workflows/native_s3_dlr.yml
> Fix the wrong path of DLR native file

- serving/docker/Dockerfile
- serving/docker/serving/build.gradle
> Update serving docker file

- .github/workflows/native_s3_dlr.yml
> Fix the uploaded path of DLR native

- .github/workflows/native_s3_dlr.yml
> Align the DLR native structure with other engines

- basicdataset/src/main/java/ai/djl/basicdataset/AmazonReview.java
- basicdataset/src/main/java/ai/djl/basicdataset/CsvDataset.java
- basicdataset/src/test/java/ai/djl/basicdataset/AmazonReviewsTest.java
- basicdataset/src/test/resources/mlrepo/dataset/nlp/ai/djl/basicdataset/amazon_reviews/metadata.json
- examples/src/main/java/ai/djl/examples/training/transferlearning/TrainAmazonReviewRanking.java
- examples/src/test/java/ai/djl/examples/training/TrainAmazonReviewTest.java
> Add AmazonReview dataset to basicdata

- .github/workflows/native_s3_dlr.yml
- .github/workflows/native_snapshot_dlr.yml
- dlr/dlr-native/build.gradle
> Add DLR native publish for osx

- api/src/main/java/ai/djl/ndarray/BaseNDManager.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDManager.java
- onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtNDManager.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDManager.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDManager.java
> Refactor BaseNDManager

- mxnet/mxnet-engine/README.md
- pytorch/pytorch-engine/README.md
- tensorflow/README.md
> Add Visual C++ 2019 Redistributable for Windows installation

- api/src/main/java/ai/djl/ndarray/BaseNDManager.java
- api/src/main/java/ai/djl/util/NativeResource.java
- docs/development/inference_performance_optimization.md
- docs/development/troubleshooting.md
- examples/build.gradle
- serving/docker/Dockerfile
> Permanently disable close resource in GC thread

- api/src/main/java/ai/djl/BaseModel.java
- api/src/main/java/ai/djl/Model.java
- dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrModel.java
- extensions/fasttext/src/main/java/ai/djl/fasttext/FtModel.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxModel.java
- onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtModel.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtModel.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfModel.java
> Refactor BaseModel

- docs/load_model.md
- docs/tensorflow/how_to_import_tensorflow_models_in_DJL.md
- extensions/aws-ai/README.md
- extensions/hadoop/README.md
> Update model loading document

- index.html
Users can now subscribe to our newsletter
> add email subscription form in the website

- android/build.gradle
- build.gradle
- serving/build.gradle
- tensorflow/tensorflow-engine/build.gradle
> Use DJL maven repo to speed up download dependency

- api/src/main/java/ai/djl/modality/nlp/embedding/ModelZooTextEmbedding.java
- api/src/main/java/ai/djl/translate/NoopTranslator.java
- examples/src/main/java/ai/djl/examples/training/transferlearning/TrainAmazonReviewRanking.java
- extensions/aws-ai/src/test/java/ai/djl/aws/s3/S3RepositoryTest.java
- integration/src/main/java/ai/djl/integration/tests/model_zoo/classification/ResnetTest.java
- jupyter/rank_classification_using_BERT_on_Amazon_Review.ipynb
- pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/TorchScriptTest.java
> Default NoopTranslator should not handle batch

- api/src/main/java/ai/djl/modality/cv/ImageFactory.java
- api/src/main/java/ai/djl/ndarray/index/NDIndex.java
- api/src/main/java/ai/djl/training/optimizer/Optimizer.java
- gradle/wrapper/gradle-wrapper.properties
- integration/src/main/java/ai/djl/integration/tests/modality/cv/NDImageUtilsTest.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java
- testing/src/main/java/ai/djl/testing/CoverageUtils.java
> Upgrade gradle to 6.7.1

- dlr/dlr-engine/build.gradle
- dlr/dlr-engine/src/main/java/ai/djl/dlr/jni/LibUtils.java
- dlr/dlr-engine/src/main/java/ai/djl/dlr/zoo/DlrModelZoo.java
- dlr/dlr-engine/src/main/java/ai/djl/dlr/zoo/DlrZooProvider.java
- dlr/dlr-engine/src/main/java/ai/djl/dlr/zoo/package-info.java
- dlr/dlr-engine/src/main/resources/META-INF/services/ai.djl.repository.zoo.ZooProvider
- dlr/dlr-engine/src/test/java/ai/djl/dlr/integraion/DlrTest.java
- dlr/dlr-engine/src/test/resources/mlrepo/model/cv/image_classification/ai/djl/dlr/resnet/metadata.json
> Add DLR modelzoo

- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtModel.java
Allow null as the options that passed in for loading
https://github.com/awslabs/djl/issues/312
> [PyTorch] fix null loading option

- extensions/fasttext/src/main/java/ai/djl/fasttext/FtModel.java
- extensions/fasttext/src/main/java/ai/djl/fasttext/jni/LibUtils.java
- extensions/fasttext/src/test/java/ai/djl/fasttext/CookingStackExchangeTest.java
- extensions/sentencepiece/build.gradle
- extensions/sentencepiece/src/main/java/ai/djl/sentencepiece/SpTokenizer.java
- extensions/sentencepiece/src/test/java/ai/djl/sentencepiece/SpTokenizerTest.java
- onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtModel.java
- onnxruntime/onnxruntime-engine/src/test/java/ai/djl/onnxruntime/engine/OrtTest.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtModel.java
- pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/TorchScriptTest.java
> Load model with path to the model file directly

- extensions/fasttext/README.md
> Update fastText readme

- .github/workflows/native_s3_dlr.yml
- dlr/dlr-engine/build.gradle
- dlr/dlr-engine/src/main/java/ai/djl/dlr/jni/LibUtils.java
- dlr/dlr-engine/src/test/java/ai/djl/dlr/integraion/DlrTest.java
> Implement DLR LibUtils

- .github/workflows/native_jni_s3_dlr.yml
- .github/workflows/native_s3_dlr.yml
- dlr/dlr-engine/build.gradle
- dlr/dlr-native/build.gradle
> Add DLR linux support

- dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrModel.java
- dlr/dlr-engine/src/test/java/ai/djl/dlr/integraion/DlrTest.java
- dlr/dlr-engine/src/test/resources/mlrepo/model/cv/image_classification/ai/djl/dlr/resnet/metadata.json
> Add DLR linux model

- api/src/main/java/ai/djl/modality/cv/translator/YoloV5Translator.java
- integration/build.gradle
Somehow the performance fixes did not go into latest versions. For this I commit again here.
> YoloV5Translator performance fix

- examples/src/main/java/ai/djl/examples/inference/ObjectDetection.java
> Fix ObjectDetection example for TensorFlow engine

- dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrEngine.java
- dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrNDArray.java
- dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrNDManager.java
> Add DlrNDArray & DlrNDManager to make DLR work alone

- api/src/main/java/ai/djl/ndarray/BaseNDManager.java
- dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrNDManager.java
- dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrSymbolBlock.java
- dlr/dlr-engine/src/main/java/ai/djl/dlr/jni/JniUtils.java
- dlr/dlr-engine/src/main/java/ai/djl/dlr/jni/LibUtils.java
- dlr/dlr-engine/src/test/java/ai/djl/dlr/engine/DlrNDManagerTest.java
- dlr/dlr-engine/src/test/java/ai/djl/dlr/engine/package-info.java
- dlr/dlr-engine/src/test/java/ai/djl/dlr/integraion/DlrTest.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDManager.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxParameterServer.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/jna/LibUtils.java
- mxnet/mxnet-engine/src/test/java/ai/djl/mxnet/engine/CachedOpTest.java
- mxnet/mxnet-engine/src/test/java/ai/djl/mxnet/engine/MxNDArrayTest.java
- onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtNDManager.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDManager.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/LibUtils.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDManager.java
> Refactor DLR NDManager

- integration/build.gradle
> Allow attach profiler to integration test

- dlr/README.md
- dlr/dlr-engine/README.md
- dlr/dlr-engine/build.gradle
- dlr/dlr-engine/src/main/javadoc/overview.html
- dlr/dlr-native/README.md
- docs/README.md
- docs/hybrid_engine.md
- onnxruntime/onnxruntime-engine/README.md
- tools/gradle/publish.gradle
> Add DLR publish & doc

- basicdataset/src/test/java/ai/djl/basicdataset/CaptchaTest.java
- basicdataset/src/test/java/ai/djl/basicdataset/Cifar10Test.java
- basicdataset/src/test/java/ai/djl/basicdataset/FashionMnistTest.java
- basicdataset/src/test/java/ai/djl/basicdataset/ImageNetTest.java
- basicdataset/src/test/java/ai/djl/basicdataset/MnistTest.java
- integration/src/main/java/ai/djl/integration/IntegrationTest.java
- integration/src/main/java/ai/djl/integration/tests/model_zoo/ImperativeModelZooTest.java
- integration/src/main/java/ai/djl/integration/tests/model_zoo/ModelZooTest.java
- integration/src/main/java/ai/djl/integration/tests/model_zoo/object_detection/SingleShotDetectionTest.java
- integration/src/main/java/ai/djl/integration/tests/training/DatasetTest.java
- integration/src/main/java/ai/djl/integration/tests/training/GradientCollectorIntegrationTest.java
> Reduce dataset test time

- api/src/main/java/ai/djl/util/NativeResource.java
> Remove NativeResource finalize

- pytorch/pytorch-native/CMakeLists.txt
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_nn_functional.cc
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_system.cc
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_tensor.cc
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_cache.cc
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_cache.h
- pytorch/pytorch-native/src/main/native/djl_pytorch_jni_exception.h
- pytorch/pytorch-native/src/main/native/djl_pytorch_jni_log.cc
> [PyTorch] Cache all java classes

- basicdataset/src/main/java/ai/djl/basicdataset/utils/FixedBucketSampler.java
- docs/mkdocs.yml
Change-Id: I0d340e7603389e7ffb52dc1ed5bf268d1cde791d
> fix slack link and typo

- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayCreationOpTest.java
wrong number used in assertion
> test: wrong number in assertion

- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_inference.cc
> Remove print

- .github/workflows/native_jni_s3_dlr.yml
- dlr/dlr-engine/build.gradle
- dlr/dlr-engine/src/main/java/ai/djl/dlr/jni/LibUtils.java
- dlr/dlr-engine/src/test/resources/mlrepo/model/cv/image_classification/ai/djl/dlr/resnet/metadata.json
- dlr/dlr-native/build.gradle
> Fix GPU nightly build

- dlr/dlr-engine/src/test/resources/mlrepo/model/cv/image_classification/ai/djl/dlr/resnet/metadata.json
> Make TVM model compatable with Ubuntu 16.04

- api/src/main/java/ai/djl/ndarray/CustomOp.java
- index.html
- website/blog.html
- website/demo.html
- website/javadoc.html
> fix slack urls

- api/src/main/java/ai/djl/Device.java
- api/src/main/java/ai/djl/Model.java
- api/src/main/java/ai/djl/engine/Engine.java
- api/src/main/java/ai/djl/ndarray/BaseNDManager.java
- dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrNDManager.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxModel.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDManager.java
- mxnet/mxnet-model-zoo/src/main/java/ai/djl/mxnet/zoo/nlp/embedding/utils/BuildModelZooWordEmbedding.java
- onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtNDManager.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtModel.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDManager.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfModel.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDManager.java
> Fix default device bug

- mxnet/mxnet-engine/build.gradle
> Disable MXNet header file check

- build.gradle
- tools/gradle/stats.gradle
> Print unit-test time after gradle build

- api/src/main/java/ai/djl/inference/Predictor.java
- dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrModel.java
- dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrNDArray.java
- dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrNDManager.java
- dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrPredictor.java
- dlr/dlr-engine/src/test/java/ai/djl/dlr/engine/DlrNDManagerTest.java
- examples/build.gradle
> [DLR] Create a new DlrPredictor to copy the model

- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfModel.java
> Fix TfModel loading bug

- README.md
- index.html
- website/blog.html
- website/demo.html
- website/javadoc.html
Add D2L java book in website nav bar and readme.
Add external community repos in readme
> Add book url and external community repo links

- docs/development/benchmark_with_djl.md
- docs/mkdocs.yml
This is the documentation for the benchmark instruction
> add DJL benchmark instruction

- dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrEngine.java
- dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrModel.java
- dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrPredictor.java
> Fix DLR device error

- dlr/dlr-engine/src/test/java/ai/djl/dlr/engine/DlrNDManagerTest.java
> Fix window nightly test

- dlr/dlr-engine/src/test/java/ai/djl/dlr/engine/DlrNDManagerTest.java
> Fix nightly window build

- bom/build.gradle
- docs/development/dependency_management.md
> [pytorch] Add pytorch-native-cu110 to bom

- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayOtherOpTest.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_tensor.cc
> [PyTorch] Refactor the set method to use ByteBuffer

- bom/build.gradle
> [dlr] Add dlr to bom

- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_torch_creation.cc
The PR only tackles the tensor creation.
> [PyToch] Optimize the PyTorch tensor creation

- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_tensor.cc
- tools/conf/findbugs-exclude.xml
- tools/conf/suppressions.xml
> [PyTorch] Fix set method crash on GPU

- jupyter/README.md
- jupyter/docker-compose.yml
We can build a djl jupyter env with Docker Compose.
> Add a docker-compose.yml file

- pytorch/pytorch-engine/README.md
> [pytorch] update README to use pytorch 1.7.0

- dlr/dlr-engine/README.md
- dlr/dlr-engine/build.gradle
- dlr/dlr-engine/src/test/java/ai/djl/dlr/integration/DlrTest.java
- dlr/dlr-engine/src/test/java/ai/djl/dlr/integration/package-info.java
- docs/development/inference_performance_optimization.md
> Add DLR multithreading doc

- jupyter/paddlepaddle/face_mask_detection_paddlepaddle.ipynb
- paddlepaddle/paddlepaddle-model-zoo/src/test/java/ai/djl/paddlepaddle/zoo/MaskDetectionTest.java
Add demo for mask classification
> [PaddlePaddle] add paddle demo: Mask classification

- dlr/dlr-engine/src/main/java/ai/djl/dlr/jni/LibUtils.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/jna/LibUtils.java
> [dlr] user cloudfront url for DLR downloading

- mxnet/mxnet-engine/src/main/include/mxnet/c_api.h
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxEngine.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxModel.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxSymbolBlock.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/Symbol.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/jna/JnaUtils.java
- mxnet/mxnet-engine/src/test/java/ai/djl/mxnet/integration/MxBackendOptimizationTest.java
This change is intended to bring the accelerator to the DJL MXNet project. User can add addtional options to set the accelerator.
> add optimize for method on MXNet for future optimization

- .github/workflows/release.yml
> Use release branch to release

- dlr/dlr-native/build.gradle
- pytorch/pytorch-native/build.gradle
> Fix wrong version name in dlr-native build.gradle

- api/src/main/java/ai/djl/repository/Artifact.java
- api/src/main/java/ai/djl/repository/RepositoryFactoryImpl.java
- api/src/main/java/ai/djl/repository/zoo/BaseModelLoader.java
- api/src/main/java/ai/djl/repository/zoo/Criteria.java
- api/src/main/java/ai/djl/repository/zoo/ModelZoo.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxModel.java
> Improve Model loading debug log message

- .github/workflows/native_release_dlr.yml
> Add DLR native release action

- dlr/dlr-engine/build.gradle
- examples/build.gradle
> Remove DLR snapshot

- dlr/dlr-engine/README.md
- docs/development/cache_management.md
- docs/development/dependency_management.md
> Update README for dlr engine

- api/README.md
- examples/pom.xml
- gradle.properties
> Bump up master branch to 0.10.0-SNAPSHOT

- tflite/tflite-native/build.gradle
> Fix build error on JDK11 with spotbugs

- jupyter/tensorflow_lite/inference_with_tensorflow_lite.ipynb
> Add jupyter notebook for tflite

- jupyter/mxnet/load_your_own_mxnet_bert.ipynb
- jupyter/pytorch/load_your_own_pytorch_bert.ipynb
> Fix Jupyter Notebook Vocabulary refactoring

- examples/build.gradle
> Fix tensorflow benchmark configuration

- README.md
> Add 0.9.0 release content to README

- basicdataset/build.gradle
- build.gradle
- dlr/dlr-engine/build.gradle
- examples/build.gradle
- extensions/aws-ai/build.gradle
- extensions/hadoop/build.gradle
- integration/build.gradle
- mxnet/mxnet-engine/build.gradle
- mxnet/mxnet-model-zoo/build.gradle
- onnxruntime/onnxruntime-engine/build.gradle
- paddlepaddle/paddlepaddle-engine/build.gradle
- paddlepaddle/paddlepaddle-model-zoo/build.gradle
- pytorch/pytorch-engine/build.gradle
- serving/docker/serving/build.gradle
- tensorflow/tensorflow-engine/build.gradle
- tensorflow/tensorflow-model-zoo/build.gradle
- tensorflow/tensorflow-native/build.gradle
- tflite/tflite-engine/build.gradle
> Centeralize snapshot maven repo definition

- api/src/main/java/ai/djl/modality/nlp/SimpleVocabulary.java
- api/src/main/java/ai/djl/nn/LambdaBlock.java
- api/src/main/java/ai/djl/training/evaluator/Accuracy.java
- examples/src/main/java/ai/djl/examples/inference/BertClassification.java
- examples/src/main/java/ai/djl/examples/training/transferlearning/TrainAmazonReviewRanking.java
- examples/src/test/java/ai/djl/examples/training/TrainAmazonReviewTest.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
- pytorch/pytorch-model-zoo/src/main/java/ai/djl/pytorch/zoo/nlp/qa/PtBertQATranslator.java
- pytorch/pytorch-model-zoo/src/main/java/ai/djl/pytorch/zoo/nlp/sentimentanalysis/PtDistilBertTranslator.java
Add PyTorch model for Amazon ranking classification
> add pytorch change for Amazon Ranking classification

- paddlepaddle/paddlepaddle-engine/build.gradle
- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jni/LibUtils.java
- paddlepaddle/paddlepaddle-engine/src/test/java/ai/djl/paddlepaddle/jni/JniUtilsTest.java
- paddlepaddle/paddlepaddle-engine/src/test/java/ai/djl/paddlepaddle/jni/package-info.java
- paddlepaddle/paddlepaddle-native/build.gradle
Add a few paddlepaddle JNI mechanism
> add paddle jni download

- jupyter/tensorflow/rank_classification_using_BERT_on_Amazon_Review.ipynb
> Add tensorflow amazon review jupyter notebook

- api/src/main/java/ai/djl/modality/nlp/SimpleVocabulary.java
- examples/src/main/java/ai/djl/examples/inference/BertClassification.java
- examples/src/main/java/ai/djl/examples/training/transferlearning/TrainAmazonReviewRanking.java
- mxnet/mxnet-model-zoo/src/main/java/ai/djl/mxnet/zoo/nlp/qa/MxBertQATranslator.java
- pytorch/pytorch-model-zoo/src/main/java/ai/djl/pytorch/zoo/nlp/qa/PtBertQATranslator.java
- pytorch/pytorch-model-zoo/src/main/java/ai/djl/pytorch/zoo/nlp/sentimentanalysis/PtDistilBertTranslator.java
> Refactor Vocabulary builder API

- model-zoo/README.md
- mxnet/mxnet-model-zoo/README.md
> Fixs #440, fix documentation error.

- paddlepaddle/paddlepaddle-native/CMakeLists.txt
Use recommended find_library than link_directories
> Use recommended find_library

- bom/build.gradle
> Add dlr-native-cpu to bom

- api/src/main/native/shared/utils.h
- pytorch/pytorch-native/CMakeLists.txt
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_inference.cc
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_ivalue.cc
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_nn_functional.cc
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_system.cc
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_tensor.cc
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_torch_creation.cc
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_torch_isjm.cc
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_torch_random_sampling.cc
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_torch_reduction.cc
- pytorch/pytorch-native/src/main/native/djl_pytorch_jni_exception.h
- pytorch/pytorch-native/src/main/native/djl_pytorch_jni_utils.h
> Move the common utilities to project root for all jni usage

- api/src/main/java/ai/djl/modality/nlp/EncoderDecoder.java
- api/src/main/java/ai/djl/nn/AbstractBlock.java
- api/src/main/java/ai/djl/nn/convolutional/Convolution.java
- api/src/main/java/ai/djl/nn/convolutional/Deconvolution.java
- api/src/main/java/ai/djl/nn/core/Linear.java
- api/src/main/java/ai/djl/nn/norm/BatchNorm.java
- api/src/main/java/ai/djl/nn/recurrent/RecurrentBlock.java
- examples/src/main/java/ai/djl/examples/training/TrainTicTacToe.java
- examples/src/test/java/ai/djl/examples/training/TrainTicTacToeTest.java
> Fix AbstractBlock inputNames and inputShapes mismatch bug

- paddlepaddle/paddlepaddle-model-zoo/src/main/java/ai/djl/paddlepaddle/zoo/PpFaceDetection.java
- paddlepaddle/paddlepaddle-model-zoo/src/main/java/ai/djl/paddlepaddle/zoo/PpMaskClassification.java
- pytorch/pytorch-model-zoo/src/main/java/ai/djl/pytorch/zoo/cv/objectdetection/PtSsdModelLoader.java
- tensorflow/tensorflow-model-zoo/src/main/java/ai/djl/tensorflow/zoo/cv/objectdetction/TfSsdModelLoader.java
> Remove unnecessary SuppressWarnings annotation

- paddlepaddle/paddlepaddle-native/src/main/native/ai_djl_paddlepaddle_jni_PaddleLibrary_inference.cc
> Fix paddle jni build

- api/src/main/java/ai/djl/training/util/ProgressBar.java
> Improve progress bar display on non utf-8 console

- api/src/main/java/ai/djl/training/hyperparameter/EasyHpo.java
- api/src/main/java/ai/djl/training/hyperparameter/package-info.java
- examples/src/main/java/ai/djl/examples/training/TrainWithHpo.java
This creates an Abstract class that can be extended to train with hyper parameters. Because it requires so many custom methods (especially building a model given the hyperparameters), I decided to just make it a class to extend rather than a builder.
> Create EasyHpo to simplify training with hyperparameters

- tools/gradle/java-formatter.gradle
> Fixes: #493, fix verify-java plugin charset bug

- onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtModel.java
> Close OrtSymbolBlock while close model

- .github/workflows/codeql-analysis-java.yml
It will brings some automatic code security check during the PR stage. https://securitylab.github.com/tools/codeql
> add codeql

- pytorch/pytorch-native/CMakeLists.txt
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_cache.h
> Fix Android JNI build

- api/src/main/java/ai/djl/ndarray/types/Shape.java
- api/src/main/java/ai/djl/repository/AbstractRepository.java
- api/src/main/java/ai/djl/util/ZipUtils.java
> Fix CodeQL warnings.

- android/gradle.properties
> Bump up Android DJL version

- djl-easy/README.md
- docs/hybrid_engine.md
- onnxruntime/onnxruntime-engine/README.md
- onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtEngine.java
- serving/docker/serving/build.gradle
Minor fix on some unneccesary manager settings for MNIST with some documentation and other version bump-ups.
> add minor fix and version bump ups

- .github/workflows/native_jni_s3_pytorch.yml
- .github/workflows/native_jni_s3_pytorch_android.yml
- .github/workflows/native_s3_pytorch_android.yml
- android/pytorch-native/build.gradle
- dlr/dlr-engine/build.gradle
- examples/build.gradle
- gradle.properties
- integration/build.gradle
- onnxruntime/onnxruntime-engine/build.gradle
- paddlepaddle/paddlepaddle-engine/build.gradle
- paddlepaddle/paddlepaddle-model-zoo/build.gradle
- pytorch/pytorch-engine/build.gradle
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtEngine.java
- pytorch/pytorch-native/build.cmd
- pytorch/pytorch-native/build.gradle
- pytorch/pytorch-native/build.sh
- pytorch/pytorch-native/build_android.sh
- tflite/tflite-engine/build.gradle
> Upgrade pytorch to 1.7.1

- api/src/main/java/ai/djl/Device.java
- api/src/main/java/ai/djl/training/DefaultTrainingConfig.java
- djl-easy/build.gradle
- djl-easy/src/main/java/ai/djl/easy/DatasetFactory.java
- djl-easy/src/main/java/ai/djl/easy/Performance.java
- djl-easy/src/main/java/ai/djl/easy/cv/ImageClassification.java
- djl-easy/src/main/java/ai/djl/easy/cv/ImageClassificationDatasetFactory.java
This implements the training of ResNet with various numbers of layers in the
DJL-Easy along with a few simple refactors.
It creates a new interface of DatasetFactory in order to manage creating
multiple datasets with different usages and storing metadata for the
application.
> [Easy] Sample ResNet training

- docs/mkdocs.yml
- paddlepaddle/paddlepaddle-engine/README.md
- paddlepaddle/paddlepaddle-model-zoo/README.md
- paddlepaddle/paddlepaddle-native/README.md
Add PaddlePaddle documentation It will add a section in DJL's documentation website
> add paddlepaddle documentation

- basicdataset/src/main/java/ai/djl/basicdataset/AbstractImageFolder.java
- basicdataset/src/main/java/ai/djl/basicdataset/ImageClassificationDataset.java
- basicdataset/src/test/java/ai/djl/basicdataset/ImageFolderTest.java
- djl-easy/src/main/java/ai/djl/easy/cv/ImageClassification.java
- djl-easy/src/main/java/ai/djl/easy/cv/ImageClassificationDatasetFactory.java
This dataset adds some help to creating image classification datasets,
especially for users less familiar with DJL in DJL-Easy.
> Add ImageClassificationDataset for clearer requirements

- examples/src/main/java/ai/djl/examples/inference/SentimentAnalysis.java
- examples/src/test/java/ai/djl/examples/inference/SentimentAnalysisTest.java
> Add SentimentAnalysis unit test

- dlr/dlr-engine/build.gradle
- examples/build.gradle
- integration/build.gradle
- jupyter/BERTQA.ipynb
- jupyter/load_pytorch_model.ipynb
- jupyter/pytorch/load_your_own_pytorch_bert.ipynb
- jupyter/rank_classification_using_BERT_on_Amazon_Review.ipynb
- onnxruntime/onnxruntime-engine/build.gradle
- paddlepaddle/paddlepaddle-model-zoo/build.gradle
- pytorch/pytorch-engine/README.md
- pytorch/pytorch-engine/build.gradle
- tflite/tflite-engine/build.gradle
> [pytorch] Upgrade pytorch 1.7.1

- api/src/main/java/ai/djl/nn/transformer/BertBlock.java
- api/src/main/java/ai/djl/nn/transformer/BertMaskedLanguageModelBlock.java
- api/src/main/java/ai/djl/nn/transformer/BertNextSentenceBlock.java
- api/src/main/java/ai/djl/nn/transformer/BertPretrainingBlock.java
- api/src/main/java/ai/djl/nn/transformer/IdEmbedding.java
- api/src/main/java/ai/djl/nn/transformer/PointwiseFeedForwardBlock.java
- api/src/main/java/ai/djl/nn/transformer/TransformerEncoderBlock.java
> Fix the broken BERT

- tflite/tflite-engine/src/test/java/ai/djl/tflite/engine/TfLiteTest.java
> [TFLite] Enable test only for linux and mac

- api/src/main/java/ai/djl/repository/zoo/Criteria.java
> Fixes #486, add javadoc for Criteria builder

- index.html
This adds an iframe embedding that includes the contents of the DJL twitter into
our site. Because that is where new DJL content is mostly added, it is the best
source for latest content and can be effortlessly put into making our site also
feature the latest DJL content.
> Add deepjavalibrary twitter to website

- tflite/tflite-engine/README.md
> Add tflite engine README

- bom/README.md
> Fix typo in BOM readme

- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
- tensorflow/tensorflow-model-zoo/src/main/java/ai/djl/tensorflow/zoo/cv/objectdetction/TfSsdTranslator.java
> Fixes #552, support different output data type for TF SSD model

- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jni/LibUtils.java
- paddlepaddle/paddlepaddle-model-zoo/src/test/java/ai/djl/paddlepaddle/zoo/ImageClassificationTest.java
- paddlepaddle/paddlepaddle-model-zoo/src/test/java/ai/djl/paddlepaddle/zoo/MaskDetectionTest.java
- paddlepaddle/paddlepaddle-native/build.gradle
- paddlepaddle/paddlepaddle-native/build.sh
Currently PaddlePaddle 2.0 has gflags loading issues on MKL dependencies. We will pick openblas for Linux CPU. After 2.0.1 come out, MKL will be repicked...
> [PaddlePaddle] use openblas

- api/src/main/java/ai/djl/training/tracker/CosineTracker.java
- api/src/main/java/ai/djl/training/tracker/FactorTracker.java
- api/src/main/java/ai/djl/training/tracker/FixedTracker.java
- api/src/main/java/ai/djl/training/tracker/LinearTracker.java
- api/src/main/java/ai/djl/training/tracker/MultiFactorTracker.java
- api/src/main/java/ai/djl/training/tracker/PolynomialDecayTracker.java
- api/src/main/java/ai/djl/training/tracker/Tracker.java
- examples/src/main/java/ai/djl/examples/training/TrainTicTacToe.java
This updates the tracker builders to match the DJL convention.
> Use builder methods in Trackers

- jupyter/mxnet/load_your_own_mxnet_bert.ipynb
> Fix jupyter notebook error

- .github/workflows/continuous.yml
- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jni/LibUtils.java
- paddlepaddle/paddlepaddle-native/build.cmd
- paddlepaddle/paddlepaddle-native/build.gradle
- paddlepaddle/paddlepaddle-native/build.sh
Add Paddle 2.0.0 official packages (without mkldnn, openblas only)
> add paddle 2.0 official packages

- .github/workflows/native_s3_tflite.yml
> bump tflite to 2.4.1 and update s3 location

- leaders.md
Reorder to ensure alphabetical order, add contact links next to name, proofread descriptions.
> Minor edits to community page

- .github/workflows/native_jni_s3_dlr.yml
- .github/workflows/native_jni_s3_paddle.yml
- .github/workflows/native_jni_s3_pytorch.yml
- .github/workflows/native_jni_s3_pytorch_android.yml
- pytorch/pytorch-native/build.gradle
> Refactor PyTorch JNI build

- .github/workflows/native_jni_s3_dlr.yml
- .github/workflows/native_jni_s3_pytorch.yml
> Add missing credential config

- .github/workflows/native_jni_s3_pytorch.yml
> Install aws cli

- docs/mkdocs.yml
- paddlepaddle/paddlepaddle-native/build.gradle
Make community section as a tab
> add community tab

- api/src/main/java/ai/djl/engine/Engine.java
- examples/build.gradle
- integration/build.gradle
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxEngine.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtEngine.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfEngine.java
> Make default engine deterministic

- .github/workflows/native_jni_s3_dlr.yml
- .github/workflows/native_jni_s3_pytorch.yml
> Fix wrong path of  precxx11 on s3 command

- .github/workflows/native_jni_s3_pytorch.yml
> Remove integration test on precxx11

- examples/.mvn/wrapper/MavenWrapperDownloader.java
- examples/.mvn/wrapper/maven-wrapper.properties
- examples/mvnw
- examples/mvnw.cmd
> Upgrade mvn wrapper to 0.5.6

- gradlew.bat
> Fix Windows gradlew for TLS 1.2 protocol

- .github/workflows/docs.yml
- .github/workflows/native_jni_s3_dlr.yml
- .github/workflows/native_jni_s3_paddle.yml
- .github/workflows/native_jni_s3_pytorch.yml
- .github/workflows/native_jni_s3_pytorch_android.yml
> Fixes the invalidate command

- docs/mkdocs.yml
- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jni/LibUtils.java
- paddlepaddle/paddlepaddle-native/build.gradle
> Fix PaddlePaddle native file loading issue

- dlr/dlr-engine/src/main/java/ai/djl/dlr/zoo/DlrModelZoo.java
- onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/zoo/OrtModelZoo.java
- tflite/tflite-engine/src/main/java/ai/djl/tflite/zoo/TfLiteModelZoo.java
> Fix model zoo supported engine bug

- .github/workflows/nightly_publish.yml
> Fix nightly publish github action

- build.gradle
- dlr/dlr-native/build.gradle
- mxnet/native/build.gradle
- paddlepaddle/paddlepaddle-native/build.gradle
- pytorch/pytorch-native/build.gradle
- tensorflow/tensorflow-native/build.gradle
- tflite/tflite-native/build.gradle
- tools/gradle/jacoco.gradle
> Add automatic module to each jar manifest

- central/src/main/webapp/components/ModelNavigator.jsx
- central/src/main/webapp/components/ModelView.jsx
This is just an addendum to PR #596. Doing the same fix except with the arguments attribute.
> Model View Arguments Fix

- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jni/LibUtils.java
Currently there is no mechanism to fallback.
> [PaddlePaddle] fix fallback to CPU

- build.gradle
- dlr/dlr-native/build.gradle
- mxnet/native/build.gradle
- paddlepaddle/paddlepaddle-native/build.gradle
- pytorch/pytorch-native/build.gradle
- tensorflow/tensorflow-native/build.gradle
- tflite/tflite-native/build.gradle
> Fix duplicate module name for native package

- central/src/main/webapp/components/DynForm.jsx
- central/src/main/webapp/components/ModelView.jsx
Fixing the ModelView interface TextField attributes making them readonly. Also fixing the issue with the ModelView not showing the most recently selected model..
Quick Fix of #630.
> Model View Update Fix

- .github/workflows/native_jni_s3_pytorch.yml
> Fix windows lib_name not found during the uploading

- .github/workflows/native_jni_s3_pytorch.yml
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArrayEx.java
> Fix nightly build & JNI pipeline

- jupyter/tensorflow_lite/inference_with_tensorflow_lite.ipynb
Fixed the 0.9.0 pytorch notebook
> fix notebook

- docs/mkdocs.yml
> Add a new section in community tab

- .github/workflows/native_publish_tflite.yml
> add tflite publish action

- docs/development/dependency_management.md
> Add paddlepaddle and tflite to dependency management document

- jupyter/paddlepaddle/face_mask_detection_paddlepaddle.ipynb
- jupyter/paddlepaddle/paddle_ocr_java.ipynb
- paddlepaddle/paddlepaddle-engine/README.md
- paddlepaddle/paddlepaddle-model-zoo/build.gradle
Release the official version of PaddlePaddle 2.0.0 native jars
> Release PaddlePaddle 2.0.0

- examples/src/main/java/ai/djl/examples/inference/benchmark/util/AbstractBenchmark.java
> Print rss and heap with absolute value

- examples/src/main/java/ai/djl/examples/inference/benchmark/util/AbstractBenchmark.java
> Fix benchmark rss value

- examples/src/main/java/ai/djl/examples/inference/benchmark/MultithreadedBenchmark.java
> Revert partial of multithreading benchmark changes

- examples/build.gradle
- integration/build.gradle
> Only load required engine for examples and integration module

- .github/workflows/continuous.yml
- .github/workflows/nightly_publish.yml
- integration/build.gradle
- tools/gradle/jacoco.gradle
> Fix jacoco report

- dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrNDArray.java
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayCreationOpTest.java
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayOtherOpTest.java
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayShapesManipulationOpTest.java
- integration/src/main/java/ai/djl/integration/util/TestUtils.java
- tflite/tflite-engine/src/main/java/ai/djl/tflite/engine/TfLiteNDArray.java
> Fix precision problem with assertAlmostEquals

- examples/build.gradle
> Fix paddlepaddle dependency in build.gradle

- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpSymbolBlock.java
> make paddlepaddle compatible with any engines

- integration/src/test/java/ai/djl/integration/IntegrationTests.java
> Fix nightly build

- api/src/main/java/ai/djl/training/EasyTrain.java
- integration/src/main/java/ai/djl/integration/tests/training/EvaluateDatasetTest.java
Added a utility evaluateDataset method so that users can run evaluation of their datasets seperately.
> Adding evaluation for test dataset in EasyTrain

- .github/workflows/continuous.yml
> add codecov

- extensions/fasttext/src/main/native/ai_djl_fasttext_jni_FastTextLibrary.cc
- extensions/sentencepiece/src/main/native/ai_djl_sentencepiece_jni_SentencePieceLibrary.cc
- paddlepaddle/paddlepaddle-native/src/main/native/ai_djl_paddlepaddle_jni_PaddleLibrary_inference.cc
- paddlepaddle/paddlepaddle-native/src/main/native/ai_djl_paddlepaddle_jni_PaddleLibrary_tensor.cc
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_ivalue.cc
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_nn_functional.cc
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_tensor.cc
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_torch_isjm.cc
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_torch_random_sampling.cc
- tools/gradle/cpp-formatter.gradle
> Format Cpp

- integration/build.gradle
- integration/src/test/java/ai/djl/integration/IntegrationTests.java
windows cpu build is still having OOM issue even on CPU if we run test with 3 engines together.
We have PyTorch and TensorFlow integration covered in contineous GitHub Action.
> fix nightly test

- extensions/aws-ai/build.gradle
- extensions/aws-ai/src/main/java/ai/djl/aws/sagemaker/SageMaker.java
- extensions/aws-ai/src/main/java/ai/djl/aws/sagemaker/package-info.java
- extensions/aws-ai/src/main/resources/ai/djl/aws/sagemaker/assume_role_policy.json
- extensions/aws-ai/src/main/resources/ai/djl/aws/sagemaker/execution_policy.json
- extensions/aws-ai/src/test/java/ai/djl/aws/sagemaker/SageMakerTest.java
- extensions/aws-ai/src/test/java/ai/djl/aws/sagemaker/package-info.java
- extensions/aws-ai/src/test/resources/log4j2.xml
> Add utilties to make it easy to deploy DJL model to SageMaker

- leaders.md
> Fixing typo in my last name

- api/src/main/java/ai/djl/modality/nlp/embedding/TrainableWordEmbedding.java
- api/src/main/java/ai/djl/ndarray/internal/NDArrayEx.java
- api/src/main/java/ai/djl/nn/core/Embedding.java
- api/src/main/java/ai/djl/nn/recurrent/RecurrentBlock.java
- api/src/test/java/ai/djl/modality/nlp/embedding/TrainableWordEmbeddingTest.java
- extensions/fasttext/src/main/native/ai_djl_fasttext_jni_FastTextLibrary.cc
- integration/src/main/java/ai/djl/integration/tests/modality/nlp/SimpleTextEncoderTest.java
- integration/src/main/java/ai/djl/integration/tests/nn/BlockCoreTest.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArrayEx.java
- mxnet/mxnet-model-zoo/src/main/java/ai/djl/mxnet/zoo/nlp/embedding/GloveWordEmbeddingModelLoader.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArrayEx.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_inference.cc
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_ivalue.cc
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_nn_functional.cc
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_cache.cc
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArrayEx.java
- tools/gradle/cpp-formatter.gradle
1. Make embedding generic
2. formatCpp
> Make embedding generic

- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxSymbolBlock.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/Symbol.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtSymbolBlock.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
- pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/TorchScriptTest.java
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_inference.cc
Serialization effort for MXNet and PyTorch Symbol blocks
> SymbolBlock Serialization

- README.md
- Adding 0.10.0 release entry into README.md
> Adding 0.10.0 release to readme

- api/src/main/java/ai/djl/modality/nlp/EncoderDecoder.java
- api/src/main/java/ai/djl/nn/transformer/BertBlock.java
- api/src/main/java/ai/djl/nn/transformer/BertMaskedLanguageModelBlock.java
- api/src/main/java/ai/djl/nn/transformer/BertMaskedLanguageModelLoss.java
- api/src/main/java/ai/djl/nn/transformer/BertNextSentenceBlock.java
- api/src/main/java/ai/djl/nn/transformer/BertNextSentenceLoss.java
- api/src/main/java/ai/djl/nn/transformer/BertPretrainingBlock.java
- api/src/main/java/ai/djl/nn/transformer/BertPretrainingLoss.java
- api/src/main/java/ai/djl/nn/transformer/IdEmbedding.java
- api/src/main/java/ai/djl/nn/transformer/MemoryScope.java
- api/src/main/java/ai/djl/nn/transformer/PointwiseFeedForwardBlock.java
- api/src/main/java/ai/djl/nn/transformer/ScaledDotProductAttentionBlock.java
- api/src/main/java/ai/djl/nn/transformer/TransformerEncoderBlock.java
> Remove unnessary overloading forward

- extensions/aws-ai/src/test/java/ai/djl/aws/sagemaker/SageMakerTest.java
> Skip SageMakerTest

- .github/workflows/continuous.yml
> Upload DJL serving test report

- docs/engine.md
> fix broken links

- paddlepaddle/paddlepaddle-engine/build.gradle
> Fix paddlepaddle engine test dependency

- jupyter/tensorflow_lite/inference_with_tensorflow_lite.ipynb
TF Lite version should be 2.4.1
> Fix the notebook crash issue

- jupyter/tutorial/02_train_your_first_model.ipynb
> fix the mnist dataset on notebook

- serving/src/test/java/ai/djl/serving/ModelServerTest.java
> close socket properly in serving unitest

- serving/src/test/java/ai/djl/serving/ModelServerTest.java
> Fix DJL serving flaky test for mac

- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxEngine.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/jna/JnaUtils.java
> Configure verbose of mxnet extra libraries

- api/src/main/java/ai/djl/nn/Activation.java
- integration/src/main/java/ai/djl/integration/tests/training/ActivationTest.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArrayEx.java
> Add softSign missing test & remove the unused rnn ops

- api/src/main/java/ai/djl/ndarray/NDArray.java
- api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
- api/src/main/java/ai/djl/nn/Parameter.java
- api/src/main/java/ai/djl/nn/core/Embedding.java
- api/src/main/java/ai/djl/training/ParameterStore.java
- api/src/main/java/ai/djl/training/Trainer.java
- api/src/main/java/ai/djl/util/Utils.java
- dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrNDArray.java
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayElementArithmeticOpTest.java
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayOtherOpTest.java
- integration/src/main/java/ai/djl/integration/tests/training/GradientCollectorIntegrationTest.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/jna/JnaUtils.java
- mxnet/mxnet-engine/src/test/java/ai/djl/mxnet/integration/MxGradientCollectorIntegrationTest.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_tensor.cc
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
detach & stop_gradient are doing the same thing (correct me if I am wrong). The former one is for dynamic graph while the later is for static graph
> Use detach c api instead of stop_gradient

- api/src/main/java/ai/djl/ndarray/NDArray.java
- api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
- api/src/main/java/ai/djl/nn/Parameter.java
- api/src/main/java/ai/djl/training/ParameterStore.java
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayElementArithmeticOpTest.java
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayOtherOpTest.java
- integration/src/main/java/ai/djl/integration/tests/training/GradientCollectorIntegrationTest.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
- mxnet/mxnet-engine/src/test/java/ai/djl/mxnet/integration/MxGradientCollectorIntegrationTest.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
> Use setter for requiresGrad()

- docs/paddlepaddle/how_to_create_paddlepaddle_model.md
> add docs for paddle

- .github/workflows/docs.yml
- docs/engine.md
- docs/mkdocs.yml
> fix doc build pipeline

- examples/src/main/java/ai/djl/examples/inference/BertClassification.java
> Update BERT Classification example

- .github/workflows/nightly_publish.yml
- serving/build.gradle
Added extra statement to add djl-serving tar file to s3 bucket. Made changes to the serving build.gradle file.
*Major review needed for the cloudfront line - Line 90* since I could not test it.
> Adding build.gradle and changes to nightly publish

- .github/workflows/nightly_publish.yml
- Fixed the double quote in if condition that threw error when running nightly build
> Fix nightly build by removing double quotes

- .github/workflows/nightly_publish.yml
> Fix nightly publish pipeline

- serving/build.gradle
> Fixed build.gradle bug to run serving script

- extensions/aws-ai/src/main/java/ai/djl/aws/s3/S3RepositoryFactory.java
> Avoid runtime exception thrown at S3RepositoryFactory constructor

- .github/workflows/nightly_publish.yml
> Adding onnxruntime and pytorch test report

- api/src/main/java/ai/djl/engine/Engine.java
- api/src/main/java/ai/djl/repository/AbstractRepository.java
- api/src/main/java/ai/djl/util/Utils.java
- dlr/dlr-engine/src/main/java/ai/djl/dlr/jni/LibUtils.java
- extensions/fasttext/src/main/java/ai/djl/fasttext/jni/LibUtils.java
- extensions/sentencepiece/src/main/java/ai/djl/sentencepiece/jni/LibUtils.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/jna/LibUtils.java
- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jni/LibUtils.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/LibUtils.java
- tflite/tflite-engine/src/main/java/ai/djl/tflite/engine/LibUtils.java
> Refactor get cache directory

- .github/workflows/nightly_publish.yml
> Adding Tensorflow test result to nightly upload

- serving/src/main/java/ai/djl/serving/Arguments.java
- serving/src/main/java/ai/djl/serving/util/ConfigManager.java
- serving/src/test/java/ai/djl/serving/ConfigManagerTest.java
> Load config.properties relative to model server home

- serving/build.gradle
- serving/src/main/conf/config.properties
- serving/src/main/java/ai/djl/serving/util/ConfigManager.java
- serving/src/test/java/ai/djl/serving/ConfigManagerTest.java
> Include conf directory into distribution tar file

- serving/build.gradle
- serving/src/main/conf/config.properties
- serving/src/main/conf/log4j2.xml
- serving/src/main/java/ai/djl/serving/Arguments.java
- serving/src/main/resources/log4j2.xml
- serving/src/test/resources/config.properties
> Fix config.properties lookup

- api/src/main/java/ai/djl/repository/FilenameUtils.java
- serving/src/main/java/ai/djl/serving/ModelServer.java
- serving/src/main/java/ai/djl/serving/http/ManagementRequestHandler.java
- serving/src/main/java/ai/djl/serving/wlm/ModelInfo.java
- serving/src/main/java/ai/djl/serving/wlm/ModelManager.java
> Fix null registration message

- serving/build.gradle
- serving/src/main/conf/log4j2.xml
> Use environment variable for model server home

- api/src/main/java/ai/djl/util/Platform.java
> Fix platform mismatch bug for MXNet

- bom/build.gradle
> Add missing classifier for paddle, dlr and tflite in bom

- serving/build.gradle
- serving/src/test/java/ai/djl/serving/ConfigManagerTest.java
- serving/src/test/java/ai/djl/serving/ModelServerTest.java
> Try to fix windows flaky test

- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfDataType.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArrayEx.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArrayIndexer.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDManager.java
PR 1 Refactor TensorFlow operators
* There are several complicate ops implementation, will re-implement those using new arch
> Refactor TensorFlow operators

- paddlepaddle/paddlepaddle-engine/README.md
- paddlepaddle/paddlepaddle-model-zoo/README.md
> Remove -SNAPSHOT for PaddlePaddle readme

- .github/workflows/native_jni_s3_pytorch.yml
- dlr/dlr-engine/build.gradle
- examples/build.gradle
- gradle.properties
- integration/build.gradle
- onnxruntime/onnxruntime-engine/build.gradle
- paddlepaddle/paddlepaddle-model-zoo/build.gradle
- pytorch/pytorch-engine/build.gradle
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtEngine.java
- pytorch/pytorch-native/README.md
- pytorch/pytorch-native/build.cmd
- pytorch/pytorch-native/build.gradle
- pytorch/pytorch-native/build.sh
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_system.cc
- pytorch/pytorch-native/src/main/native/djl_pytorch_utils.h
Upgrading PyTorch to v1.8.0
```
$ ./gradlew compileJNI 
> Task :pytorch:pytorch-native:compileJNI
~/djl/pytorch/pytorch-native ~/djl/pytorch/pytorch-native
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Building djl_torch with the host...
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- …
```
> Upgrade PyTorch to 1.8.0

- docs/mkdocs.yml
- docs/paddlepaddle/how_to_create_paddlepaddle_model.md
- docs/paddlepaddle/how_to_create_paddlepaddle_model_zh.md
- serving/central/gradlew
Paddle model loading instruction in both Chinese and english
> add Paddle documentation to load the model

- docs/development/how_to_use_dataset.md
Updating the documentation for creating your own dataset
> Updating the documentation for creating your own dataset

- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayElementArithmeticOpTest.java
- tensorflow/tensorflow-api/build.gradle
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/SavedModelBundle.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArrayEx.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfOpExecutor.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/javacpp/JavacppUtils.java
- testing/src/main/java/ai/djl/testing/Assertions.java
> Fix TensorFlow memory leak & inplace flaky test

- docs/paddlepaddle/how_to_create_paddlepaddle_model.md
- docs/paddlepaddle/how_to_create_paddlepaddle_model_zh.md
- website/demo.html
Retire the demodocs.djl.ai site and use the one we built from docs.
> minor fix on docs

- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_tensor.cc
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfEngine.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfModel.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDManager.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfOpExecutor.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/javacpp/JavacppUtils.java
> Add TensorFlow GPU functionality

- .github/workflows/native_jni_s3_pytorch.yml
- gradle.properties
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtEngine.java
- pytorch/pytorch-native/build.cmd
- pytorch/pytorch-native/build.gradle
- pytorch/pytorch-native/build.sh
Upgrade the pytorch version to 1.8.1 
I ran `./gradlew compileJNI`  and `./gradlew compileJNIGPU` on linux machine and the build was successful.
> Upgrade PyTorch to 1.8.1

- pytorch/pytorch-native/build.cmd
- pytorch/pytorch-native/build.sh
Adding the correct url for cu102 binaries
Adding -x format in build.sh so that we can see the real error
> Fixing the url for cu102

- serving/serving/src/main/conf/config.properties
- serving/serving/src/main/java/ai/djl/serving/ModelServer.java
- serving/serving/src/main/java/ai/djl/serving/plugins/FolderScanPluginManager.java
- serving/serving/src/main/java/ai/djl/serving/util/ConfigManager.java
> Load models for brew installation package

- serving/serving/src/test/java/ai/djl/serving/ModelServerTest.java
> Workaround djl-serving flaky test on Windows

- examples/README.md
> Add link to demo repo in examples README

- api/src/main/java/ai/djl/ndarray/NDManager.java
- gradle.properties
- ml/xgboost/build.gradle
- ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbEngine.java
- ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbEngineProvider.java
- ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbModel.java
- ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbNDArray.java
- ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbNDManager.java
- ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbSymbolBlock.java
- ml/xgboost/src/main/java/ai/djl/ml/xgboost/package-info.java
- ml/xgboost/src/main/java/com/sun/jna/PointerProxy.java
- ml/xgboost/src/main/java/com/sun/jna/package-info.java
- ml/xgboost/src/main/java/ml/dmlc/xgboost4j/java/JniUtils.java
- ml/xgboost/src/main/java/ml/dmlc/xgboost4j/java/package-info.java
- ml/xgboost/src/main/resources/META-INF/services/ai.djl.engine.EngineProvider
- ml/xgboost/src/test/java/ai/djl/ml/xgboost/XgbModelTest.java
- ml/xgboost/src/test/java/ai/djl/ml/xgboost/package-info.java
- settings.gradle
Add support for XGBoost model. Now only supports for Mac and Linux.
> [XGBoost] add XGBoost inference support

- ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbEngine.java
- ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbEngineProvider.java
> Fix XgbEngine merge issue

- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java
- pytorch/pytorch-native/build.gradle
> adding torch_cuda*

- onnxruntime/onnxruntime-engine/build.gradle
- onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/zoo/tabular/softmax_regression/IrisClassificationModelLoader.java
> Remove 2nd engine dependency from IrisTranslator

- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java
Clean up CU111 library loading issue. Add some libraries to whitelist
> add libraries to whitelist

- ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbModel.java
- ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbSymbolBlock.java
Add option to XGBoost model. User can define treelimit and Mode during definition
> [XGBoost] add option to Model

- ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbModel.java
> format code

- website/blog.html
- website/demo.html
- website/javadoc.html
> switch back to 1.0 css

- examples/build.gradle
- integration/build.gradle
- tensorflow/tensorflow-model-zoo/build.gradle
> Update tensorflow native to 2.4.1 release version

- pytorch/pytorch-native/build.gradle
> Fix pytorch cu111 native build

- api/src/main/java/ai/djl/modality/cv/BufferedImageFactory.java
> Fix BufferOverflowException for handling subimage

- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java
> [pytorch] Allow run cpu package on gpu machine

- docs/development/dependency_management.md
- mxnet/mxnet-engine/README.md
- pytorch/pytorch-engine/README.md
- tensorflow/tensorflow-engine/README.md
> Update native library to new cuda version

- ml/xgboost/build.gradle
> [xgboost] filter out unnecessary files 

- .github/workflows/continuous.yml
> Update codecov action to release 1.4.0

- serving/serving/build.gradle
> [serving] include all jars in lib folder

- bom/build.gradle
> [bom] Fix xgboost package name

- docs/development/dependency_management.md
> [doc] Add xgboost to dependency document

- ml/xgboost/build.gradle
> [xgboost] include required class in jar

- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayOtherOpTest.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
> Fix TensorFlow tile error

- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayOtherOpTest.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfSymbolBlock.java
> Fix tensorflow NullPointerException

- .github/workflows/continuous.yml
- examples/src/test/java/ai/djl/examples/inference/ListModelsTest.java
- extensions/hadoop/src/test/java/ai/djl/hadoop/hdfs/HdfsRepositoryTest.java
- integration/src/main/java/ai/djl/integration/tests/model_zoo/ModelZooTest.java
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayOtherOpTest.java
- pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/LibUtilsTest.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfSymbolBlock.java
> Fix unit test engine cache location

- api/src/main/java/ai/djl/ndarray/NDArray.java
- api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayElementArithmeticOpTest.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
Adding batch dot product operator to MXNet
> Adding batch dot product operator

- serving/serving/build.gradle
> Include all engines in djl-serving

- api/src/main/java/ai/djl/ndarray/BaseNDManager.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfDataType.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfEngine.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfEngineProvider.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfModel.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArrayEx.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDManager.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfSymbolBlock.java
- tensorflow/tensorflow-model-zoo/src/main/java/ai/djl/tensorflow/zoo/TfModelZoo.java
- tensorflow/tensorflow-model-zoo/src/main/java/ai/djl/tensorflow/zoo/cv/objectdetction/TfSsdModelLoader.java
> [tensorflow] create an EagerSession per NDManager

- pytorch/pytorch-engine/README.md
> [pytorch] update pytorch engine document

- .github/workflows/native_build_mxnet_osx.yml
- gradle.properties
- mxnet/mxnet-engine/README.md
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/jna/LibUtils.java
- mxnet/mxnet-model-zoo/src/test/java/ai/djl/mxnet/integration/MxSymbolBlockTest.java
- mxnet/native/build.gradle
> [mxnet] Upgrade MXNet to 1.8.0

- api/src/main/java/ai/djl/util/Platform.java
> Allows run mxnet-native-mkl on GPU machine

- api/src/main/java/ai/djl/util/Platform.java
> Fix MXNet gpu platform mismatch

- .github/workflows/native_jni_s3_paddle.yml
Change JNI pipeline to point to 2.02
> [Paddle] update JNI pipeline

- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfEngine.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDManager.java
> Revert c23e2916481fcf2b61bf48460b3fe24aa1039b4f

- pytorch/pytorch-engine/README.md
> Fix pytorch document

- .github/workflows/continuous.yml
- paddlepaddle/paddlepaddle-native/build.gradle
- paddlepaddle/paddlepaddle-native/build.sh
Update paddlepaddle package to make it compatible
> update paddlepaddle linux package

- docs/development/inference_performance_optimization.md
> fix on documentation levels

- examples/build.gradle
- tensorflow/tensorflow-api/build.gradle
- tensorflow/tensorflow-engine/README.md
> [tensorflow] Fix tensorflow-api dependency

- .github/workflows/native_jni_s3_dlr.yml
- djl-zero/README.md
> [dlr] fix dlr publish location

- docs/development/troubleshooting.md
- paddlepaddle/paddlepaddle-engine/build.gradle
- paddlepaddle/paddlepaddle-model-zoo/build.gradle
> [paddle] use paddlepaddle 2.0.2 release version

- .github/workflows/native_jni_s3_pytorch_android.yml
- .github/workflows/native_s3_pytorch_android.yml
Add PyTorch Android native publish updates
> update pytorch android native

- api/README.md
- examples/pom.xml
- gradle.properties
> Update DJL version 0.12.0-SNSPSHOT

- .github/workflows/native_jni_s3_pytorch_android.yml
- .github/workflows/native_s3_pytorch_android.yml
- pytorch/pytorch-native/CMakeLists.txt
- pytorch/pytorch-native/build_android.sh
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_inference.cc
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_nn_functional.cc
> Fix PyTorch Android

- .github/workflows/native_s3_pytorch_android.yml
> PyTorch Android  path fix

- pytorch/pytorch-native/build_android.sh
Fix folder issue on android site. Tested locally
> PyTorch Android fix folder issue

- README.md
> Update REAME to include 0.11.0 release

- .github/workflows/native_publish_pytorch_android.yml
- README.md
- android/gradle.properties
- android/pytorch-native/build.gradle
Bump up Android package versions
> Android version bump up

- docs/development/benchmark_with_djl.md
- examples/src/main/java/ai/djl/examples/inference/benchmark/util/AbstractBenchmark.java
- examples/src/main/java/ai/djl/examples/inference/benchmark/util/Arguments.java
- examples/src/test/java/ai/djl/examples/inference/BenchmarkTest.java
> [benchmark] support non-float32 datatype

- serving/central/package-lock.json
> [central] Update package-lock.json

- serving/central/package-lock.json
- serving/central/package.json
> [central] upgrade css-loader version

- examples/src/main/java/ai/djl/examples/inference/benchmark/util/Arguments.java
> Fix benchmark shape parsing error

- examples/src/main/java/ai/djl/examples/inference/benchmark/util/Arguments.java
> Fix NPE issue in benchmark

- api/src/main/java/ai/djl/ndarray/NDArray.java
- api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayOtherOpTest.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_tensor.cc
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
Reverts deepjavalibrary/djl#958
> Revert "[PyTorch] Set and override shape API for NDArray"

- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayOtherOpTest.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
> Re-apply PR #958

- integration/src/main/java/ai/djl/integration/tests/nn/BlockFactoryTest.java
- integration/src/main/java/ai/djl/integration/tests/training/EvaluateDatasetTest.java
- integration/src/main/resources/log4j2.xml
> Close resource in integration test

- mxnet/mxnet-model-zoo/src/test/resources/mlrepo/model/cv/action_recognition/ai/djl/mxnet/action_recognition/metadata.json
> Added auto softmax metadata for action_recognition

- .github/workflows/continuous.yml
- api/src/main/java/ai/djl/util/ClassLoaderUtils.java
> Avoid error log in non-directory case

- onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtEngine.java
- onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtModel.java
Change-Id: If7f36310a8370c8cb89776e92faa37e0c7517edf
> [onnx] Add GPU support for OnnxRuntime

- api/src/main/java/ai/djl/repository/zoo/BaseModelLoader.java
- api/src/main/java/ai/djl/repository/zoo/Criteria.java
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- integration/build.gradle
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArrayEx.java
- serving/central/build.gradle
- serving/serving/build.gradle
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDManager.java
- tools/gradle/check.gradle
> Upgrade to gradle 7.0.2

- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtEngine.java
> [pytorch] Load extran shared library for pytorch engine

- bom/build.gradle
- ml/xgboost/build.gradle
> Fix gradle 7.0 publish issue

- serving/central/package-lock.json
> [central] update dns-packet to 1.3.4

- serving/central/package-lock.json
- serving/central/package.json
> Upgrade ws to 7.4.6

- README.md
- build.gradle
- tools/conf/findbugs-exclude.xml
- tools/gradle/check.gradle
Change-Id: Icc4b83ab921adfe94b438fa970c3f12c84acf0cd
> Upgrade spotbugs to 4.7.1, this support JDK 11 officially

- .github/workflows/continuous.yml
Change-Id: I213dcb8b4ebc850780a17b633c430ebe313360ab
> Donot fail the build if upload codecov failed

- api/src/main/java/ai/djl/modality/cv/translator/ImageClassificationTranslatorFactory.java
- api/src/main/java/ai/djl/repository/zoo/BaseModelLoader.java
Change-Id: Ia453afdd61b42578ecfaa712d975e1caafa542bb
> Add ImageClassificationTraslator to default translator

- gradle.properties
> upgrade xgboost

- docs/tensorflow/how_to_import_tensorflow_models_in_DJL.md
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfSymbolBlock.java
Change-Id: Ie044839cf082d63010a5c26d3f2f8833447919c6
> [tensorflow] fix optOption usage document

- jupyter/load_pytorch_model.ipynb
Change-Id: I1889aa93d2002e6ce02c740d2d1d3517bf586760
> [pytorch] Update load model jupyter notebook

- integration/src/main/java/ai/djl/integration/tests/model_zoo/ModelZooTest.java
Change-Id: I7c0109c6e5fc0ece16288082fd830718f20ad489
> Fix model zoo test typo

- paddlepaddle/paddlepaddle-native/build.gradle
- tensorflow/tensorflow-native/build.gradle
- tflite/tflite-native/build.gradle
Change-Id: I74effbf45492a5cf50e09ba8af0223d2b1bcb5a5
> Enable spotbugs for java 11+

- serving/serving/src/test/java/ai/djl/serving/ModelServerTest.java
Change-Id: I13b89e04516c59a3d28ecafd49f4f808630b22fb
> [serving] Fix flaky test

- api/src/main/java/ai/djl/repository/zoo/Criteria.java
- docs/development/benchmark_with_djl.md
- examples/src/main/java/ai/djl/examples/inference/LoadModel.java
- examples/src/main/java/ai/djl/examples/inference/benchmark/util/AbstractBenchmark.java
- examples/src/main/java/ai/djl/examples/inference/benchmark/util/Arguments.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtModel.java
Change-Id: I95887895e1aafdda65b16a2f90753b4939a484af
> Improve benchmark input arguments

- serving/central/package-lock.json
- serving/central/package.json
Change-Id: Id2b2197795f6b31ae618adfdad6b75807579a87c
> [center] upgrade glob-parent version

- serving/serving/docker/serving/build.gradle
- serving/serving/docker/serving/gradle/wrapper/gradle-wrapper.properties
- serving/serving/docker/serving/gradlew
Change-Id: I1c9ff370c95cdb9752cb239dd16e380a9dbe7a50
> Upgrade djl-serving docker to 0.11.0

- .github/workflows/native_jni_s3_paddle.yml
- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpModel.java
- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jni/JniUtils.java
- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jni/LibUtils.java
- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jni/PaddleLibrary.java
- paddlepaddle/paddlepaddle-native/build.gradle
- paddlepaddle/paddlepaddle-native/build.sh
- paddlepaddle/paddlepaddle-native/src/main/native/ai_djl_paddlepaddle_jni_PaddleLibrary_inference.cc
> Enable Paddle GPU

- .github/workflows/native_jni_s3_pytorch.yml
- .github/workflows/native_jni_s3_pytorch_android.yml
- .github/workflows/native_s3_pytorch_android.yml
- dlr/dlr-engine/build.gradle
- examples/build.gradle
- gradle.properties
- integration/build.gradle
- ml/xgboost/build.gradle
- onnxruntime/onnxruntime-engine/build.gradle
- paddlepaddle/paddlepaddle-model-zoo/build.gradle
- pytorch/pytorch-engine/build.gradle
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtEngine.java
- pytorch/pytorch-native/build.cmd
- pytorch/pytorch-native/build.gradle
- pytorch/pytorch-native/build.sh
- pytorch/pytorch-native/build_android.sh
- serving/serving/build.gradle
> update pytorch version

- paddlepaddle/paddlepaddle-engine/build.gradle
- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpEngine.java
- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jni/LibUtils.java
- paddlepaddle/paddlepaddle-native/build.gradle
> add paddle gpu in engine

- docs/mkdocs.yml
Change-Id: Icf5f0b6107531e24391f3571bf58a1b01f3c0cac
> Update docs link

- api/src/main/java/ai/djl/Device.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/jna/JnaUtils.java
- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jni/JniUtils.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
Change-Id: I6a7083e44f6176b772cebd33e3a029a519141cdd
> Refactor Device.getDeviceId()

- api/src/main/java/ai/djl/Application.java
- examples/src/main/java/ai/djl/examples/inference/BigGAN.java
- pytorch/pytorch-model-zoo/src/main/java/ai/djl/pytorch/zoo/PtModelZoo.java
- pytorch/pytorch-model-zoo/src/test/resources/mlrepo/model/cv/image-generation/ai/djl/pytorch/biggan-deep/metadata.json
Change the name of the application to show a problem such as Image Generation rather than a DL technique.
> Change application from GAN to image-generation

- paddlepaddle/paddlepaddle-engine/README.md
- paddlepaddle/paddlepaddle-engine/build.gradle
- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jni/LibUtils.java
- paddlepaddle/paddlepaddle-native/build.gradle
- paddlepaddle/paddlepaddle-native/build.sh
Add paddlepaddle CU102 package
> [Paddle] add cu102

- .github/workflows/native_jni_s3_pytorch.yml
- .github/workflows/native_jni_s3_pytorch_android.yml
- dlr/dlr-engine/build.gradle
- examples/build.gradle
- extensions/benchmark/build.gradle
- gradle.properties
- integration/build.gradle
- paddlepaddle/paddlepaddle-model-zoo/build.gradle
- pytorch/pytorch-engine/build.gradle
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtEngine.java
- pytorch/pytorch-native/build.cmd
- pytorch/pytorch-native/build.gradle
- pytorch/pytorch-native/build.sh
- pytorch/pytorch-native/build_android.sh
- serving/serving/build.gradle
Change-Id: I9a2a62d2e3ce7f1c0845d70e14a6a0eee91b4bb1
> Use pytorch 1.8.1 for 0.12.0 release

- .github/workflows/native_jni_s3_pytorch.yml
Change-Id: Iec9dc9d2808c22bd8b18b87777f12162bfe454da
> Fix pytorch jni publish pipeline

- extensions/sentencepiece/src/test/java/ai/djl/sentencepiece/SpTextEmbeddingTest.java
> [SentencePiece] add new test

- examples/src/test/java/ai/djl/examples/inference/UniversalSentenceEncoderTest.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfEngine.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDManager.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfOpExecutor.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/javacpp/JavacppUtils.java
Change-Id: Ib15ec1568a96f8984e1c7c124b2d7e10a2d9bd71
Fixes: #1056
> [tensorflow] Fix bug in string tensor implementation

- docs/development/dependency_management.md
Change-Id: Ib1f22175a8a2cb2a23844cdc3b07135c8e4067e9
> Update document for paddle GPU native package

- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/jna/LibUtils.java
- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jni/LibUtils.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/javacpp/LibUtils.java
- tflite/tflite-engine/src/main/java/ai/djl/tflite/engine/LibUtils.java
Change-Id: I3c6386831fd5e427ac0ad96ae4d2cc104afd3860
> [paddle] workaround native packaging bug

- pytorch/pytorch-model-zoo/src/test/resources/mlrepo/model/nlp/question_answer/ai/djl/pytorch/bertqa/metadata.json
Change-Id: I96239831e184a2654c724ad4a4f8d70d17dc2ae8
> Add missing argument in pytorch model zoo

- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpEngine.java
- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpModel.java
Change-Id: I52a58e00f25e5652730bb6449f5fc2325a69f161
> [paddle] Allows load paddle model on GPU

- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jni/LibUtils.java
Change-Id: I64ad87fbb9c222bcd9d21aeac29c1612d263e4e1
> [paddle] fallback to cpu if package mismatch

- pytorch/pytorch-engine/README.md
Change-Id: I4be0344d9180be0ad83114dcc546af51b6f8873e
> [pytorch] Fix pytorch engine README

- extensions/aws-ai/build.gradle
- extensions/hadoop/build.gradle
- extensions/hadoop/src/test/java/ai/djl/hadoop/hdfs/HdfsRepositoryTest.java
- gradle.properties
- ml/xgboost/build.gradle
- serving/serving/build.gradle
- tensorflow/tensorflow-api/build.gradle
- tensorflow/tensorflow-native/build.gradle
Change-Id: I317a05d2b7ee2861dab376d8f2e18875532c6e93
> Update DJL depenedency to latest version

- README.md
- api/README.md
- examples/pom.xml
- gradle.properties
Change-Id: Ic66b0ee296a066c2136136b542b78b513244cc64
> Increase build version to 0.13.0-SNAPSHOT

- examples/build.gradle
- extensions/benchmark/build.gradle
- integration/build.gradle
- serving/central/build.gradle
- serving/serving/build.gradle
Change-Id: If2eaa27b4c692971c5297aef576928e312e7287e
> Fix gradle build warnings

- android/pytorch-native/build.gradle
- dlr/dlr-engine/build.gradle
- examples/build.gradle
- extensions/benchmark/build.gradle
- gradle.properties
- integration/build.gradle
- paddlepaddle/paddlepaddle-model-zoo/build.gradle
- pytorch/pytorch-engine/README.md
- pytorch/pytorch-engine/build.gradle
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtEngine.java
- pytorch/pytorch-native/build.cmd
- pytorch/pytorch-native/build.sh
- pytorch/pytorch-native/build_android.sh
- serving/serving/build.gradle
Change-Id: Iacd4adf32cf215016ccb42afa5be3b34cc0f4743
> Upgrade pytorch to 1.9.0

- .github/workflows/continuous.yml
- .github/workflows/docs.yml
- .github/workflows/native_jni_s3_dlr.yml
- .github/workflows/native_jni_s3_paddle.yml
- .github/workflows/native_jni_s3_pytorch.yml
- .github/workflows/native_jni_s3_pytorch_android.yml
- .github/workflows/native_publish_dlr.yml
- .github/workflows/native_publish_mxnet.yml
- .github/workflows/native_publish_paddle.yml
- .github/workflows/native_publish_pytorch.yml
- .github/workflows/native_publish_pytorch_android.yml
- .github/workflows/native_publish_tensorflow.yml
- .github/workflows/native_publish_tflite.yml
- .github/workflows/native_s3_dlr.yml
- .github/workflows/native_s3_fasttext.yml
- .github/workflows/native_s3_sentencepiece.yml
- .github/workflows/native_s3_tensorflow.yml
- .github/workflows/native_s3_tflite.yml
- .github/workflows/nightly_publish.yml
Change-Id: I3a1bba3825956e3bffb6b05c30169c2b86194841
> Fixes #1027, upgrade ubuntu 16.04 to 18.04

- .github/workflows/continuous.yml
- .github/workflows/docs.yml
- .github/workflows/native_jni_s3_dlr.yml
- .github/workflows/native_jni_s3_paddle.yml
- .github/workflows/native_jni_s3_pytorch.yml
- .github/workflows/native_jni_s3_pytorch_android.yml
- .github/workflows/native_publish_dlr.yml
- .github/workflows/native_publish_mxnet.yml
- .github/workflows/native_publish_paddle.yml
- .github/workflows/native_publish_pytorch.yml
- .github/workflows/native_publish_pytorch_android.yml
- .github/workflows/native_publish_tensorflow.yml
- .github/workflows/native_publish_tflite.yml
- .github/workflows/native_s3_dlr.yml
- .github/workflows/native_s3_fasttext.yml
- .github/workflows/native_s3_sentencepiece.yml
- .github/workflows/native_s3_tensorflow.yml
- .github/workflows/native_s3_tflite.yml
- .github/workflows/nightly_publish.yml
This reverts commit 27a1ad1d5cc566f209e7210b2ec272f6912e204e.
> Revert "Fixes #1027, upgrade ubuntu 16.04 to 18.04 (#1091)"

- extensions/benchmark/build.gradle
- serving/serving/build.gradle
- serving/serving/src/main/conf/config.properties
- serving/serving/src/main/java/ai/djl/serving/util/ConfigManager.java
- serving/serving/src/test/resources/config.properties
Change-Id: Ic20d1228bfb518221e774bebd52b380eaebad277
> Create deb package for djl-serving

- extensions/benchmark/README.md
- extensions/benchmark/src/main/java/ai/djl/benchmark/AbstractBenchmark.java
Change-Id: I9ad66c1c30b9851e247819e8a14710aa33400e33
> [djl-bench] Update benchmark readme

- serving/serving/README.md
- serving/serving/docs/configuration.md
- serving/serving/docs/inference_api.md
- serving/serving/docs/management_api.md
- serving/serving/docs/plugin_management.md
Change-Id: I242e6b40186854ff2da6c5b5caf762f83517e392
> [serving] Update DJL Serving documents

- .github/workflows/continuous.yml
- .github/workflows/native_jni_s3_dlr.yml
- .github/workflows/native_jni_s3_paddle.yml
- .github/workflows/native_jni_s3_pytorch.yml
- .github/workflows/native_jni_s3_pytorch_android.yml
- .github/workflows/native_publish_dlr.yml
- .github/workflows/native_publish_mxnet.yml
- .github/workflows/native_publish_paddle.yml
- .github/workflows/native_publish_pytorch.yml
- .github/workflows/native_publish_pytorch_android.yml
- .github/workflows/native_publish_tensorflow.yml
- .github/workflows/native_publish_tflite.yml
- .github/workflows/native_s3_dlr.yml
- .github/workflows/native_s3_fasttext.yml
- .github/workflows/native_s3_pytorch_android.yml
- .github/workflows/native_s3_sentencepiece.yml
- .github/workflows/native_s3_tensorflow.yml
- .github/workflows/native_s3_tflite.yml
- .github/workflows/nightly_publish.yml
- extensions/fasttext/build.gradle
- extensions/sentencepiece/build.gradle
> Use amazonlinux/centos to build native libraries

- api/src/main/java/ai/djl/inference/Predictor.java
- api/src/main/java/ai/djl/translate/ServingTranslatorFactory.java
- serving/serving/src/main/java/ai/djl/serving/ModelServer.java
- serving/serving/src/main/java/ai/djl/serving/http/ManagementRequestHandler.java
- serving/serving/src/main/java/ai/djl/serving/wlm/BatchAggregator.java
- serving/serving/src/main/java/ai/djl/serving/wlm/Job.java
- serving/serving/src/main/java/ai/djl/serving/wlm/ModelInfo.java
- serving/serving/src/main/java/ai/djl/serving/wlm/ModelManager.java
- serving/serving/src/main/java/ai/djl/serving/wlm/WorkerThread.java
1. Update register model API
2. Improve error message for invalid input data
3. Fix bug in unregsiter model
4. Update default number of workers
Change-Id: I5c293d26f830f5fe37708ee039ad9918c4fa5c2e
tt
Change-Id: Id3c022793d8ab335992044a2b5d6b8648f4694a0
> [serving] Fix unregister model regression

- .github/workflows/native_jni_s3_pytorch.yml
Change-Id: I645739bb44028fbe102989b6b0a503a08c1660e5
> Fix pytorch jni build pipeline

- .github/workflows/native_jni_s3_paddle.yml
Change-Id: Ifedd63e0e3b51f6842fa5906a2f02103e9a93f13
> Fix paddlepaddle cpu native build pipeline

- api/src/main/java/ai/djl/util/Platform.java
- dlr/dlr-engine/src/main/java/ai/djl/dlr/jni/LibUtils.java
- extensions/benchmark/src/main/java/ai/djl/benchmark/Benchmark.java
- extensions/fasttext/src/main/java/ai/djl/fasttext/jni/LibUtils.java
- extensions/sentencepiece/src/main/java/ai/djl/sentencepiece/jni/LibUtils.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/jna/LibUtils.java
- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jni/LibUtils.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/javacpp/LibUtils.java
- tflite/tflite-engine/src/main/java/ai/djl/tflite/engine/LibUtils.java
Change-Id: I3bb8955a6058440dc0f1a94eb4ac540a0f3a0ba0
> Detect os architecture

- extensions/benchmark/build.gradle
- serving/serving/.gitignore
- serving/serving/build.gradle
- serving/serving/src/main/java/ai/djl/serving/plugins/FolderScanPluginManager.java
- serving/serving/src/main/java/ai/djl/serving/plugins/PluginMetaData.java
- serving/serving/src/main/java/ai/djl/serving/plugins/PropertyFilePluginMetaDataReader.java
Change-Id: Iccbc44e532e09d8b152b66d1efb27f1ea12c2381
> [serving] handle duplicate plugin issue

- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpDataType.java
> fix paddle bug

- serving/serving/README.md
- serving/serving/src/main/puml/architecture.puml
Change-Id: Ib76ca2836701ec7a499a7df52873192e680a70f7
> [serving] Add architecture diagram

- .github/workflows/native_jni_s3_paddle.yml
- paddlepaddle/paddlepaddle-engine/build.gradle
- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jni/LibUtils.java
- paddlepaddle/paddlepaddle-native/build.gradle
Change-Id: Ie2e42fd91c4e2403fe957d5f399dcf37d0cece97
> Fix paddlepaddle jni build

- .github/workflows/native_jni_s3_pytorch.yml
Change-Id: Ia0b3daf88264fcaeef1d3fe2b4756dfa6da9f629
> Fix pytorch GPU JNI build pipeline

- examples/docs/biggan.md
- examples/docs/super_resolution.md
Here I add the documentation and explanation on the Super Resolution example.
I also fix a typo in the BigGAN docs.
> Add docs for Super-Resolution example

- .github/workflows/continuous.yml
- .github/workflows/native_jni_s3_paddle.yml
Change-Id: I1f226ae6c12e2f7ff3eb2e0dbfde534640a79de7
> Fix paddle jni build workflow

- .github/workflows/native_jni_s3_paddle.yml
Change-Id: Id9da3a34683788737663985990cb858f0cd7caec
> Fix paddle jni build workflow - part2

- api/src/main/java/ai/djl/BaseModel.java
- api/src/main/java/ai/djl/repository/AbstractRepository.java
- api/src/main/java/ai/djl/repository/JarRepository.java
- api/src/main/java/ai/djl/repository/RemoteRepository.java
- api/src/main/java/ai/djl/repository/SimpleRepository.java
- api/src/main/java/ai/djl/repository/SimpleUrlRepository.java
- api/src/main/java/ai/djl/util/Utils.java
- api/src/main/java/ai/djl/util/ZipUtils.java
- basicdataset/src/main/java/ai/djl/basicdataset/tabular/CsvDataset.java
- examples/src/main/java/ai/djl/examples/inference/ObjectDetectionWithTensorflowSavedModel.java
- mxnet/mxnet-model-zoo/src/main/java/ai/djl/mxnet/zoo/nlp/qa/MxBertQATranslator.java
Change-Id: I5e270e2ed6d8878bdff624b7a8bb829b8bf1e671
> Add buffer to file IO

- api/src/main/java/ai/djl/modality/Input.java
- api/src/main/java/ai/djl/translate/ServingTranslatorFactory.java
- serving/serving/src/main/java/ai/djl/serving/http/RequestParser.java
- serving/serving/src/main/java/ai/djl/serving/wlm/WorkerThread.java
1. make it easy to get content-type header
2. improve error handling
Change-Id: I12a1ea9f12e3565649d0f218870fff6d111bc2fe
> [serving] make input header key case-insensitive

- extensions/benchmark/build.gradle
Change-Id: I8d854c0d0353767cae81d999bf4f7fd9616ff5fc
> [djl-bench] Add missing tensorflow model zoo dependency

- api/src/main/java/ai/djl/repository/RepositoryFactoryImpl.java
- serving/serving/src/main/java/ai/djl/serving/wlm/ModelManager.java
Change-Id: Ic08dce837f667a90b14d9caed23f4bcd5473d935
> [serving] Log model loading device id

- serving/serving/src/main/conf/log4j2.xml
- serving/serving/src/main/resources/log4j2.xml
Change-Id: I51f53056a152592cffbcf1e40ceca83c44e9c068
> [djl-serving] update log4j configuration

- extensions/benchmark/snapcraft/snapcraft.yaml
Change-Id: I3afc67d68efbabeaf9268743de2951e4bb9377d3
> [djl-bench] Add snapcraft back

- extensions/benchmark/README.md
- extensions/benchmark/build.gradle
- serving/serving/README.md
Change-Id: I52cc1b27ba88b733fbb8bbc76e88fbf46c0bfe76
> Update benchmark readme

- dlr/dlr-engine/build.gradle
- examples/build.gradle
- extensions/benchmark/build.gradle
- extensions/fasttext/build.gradle
- extensions/sentencepiece/build.gradle
- integration/build.gradle
- paddlepaddle/paddlepaddle-model-zoo/build.gradle
- pytorch/pytorch-engine/build.gradle
- serving/serving/build.gradle
Change-Id: I3f935707bb7395f2b3c0403335784b875d708165
> Use pytorch 1.9.0 release version

- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpModel.java
- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jni/JniUtils.java
- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jni/PaddleLibrary.java
- paddlepaddle/paddlepaddle-native/src/main/native/ai_djl_paddlepaddle_jni_PaddleLibrary_inference.cc
Add more options to the AnalysisConfig
> [Paddle] add more options

- api/src/main/java/ai/djl/modality/cv/translator/StyleTransferTranslatorFactory.java
Change-Id: I4b9326725981c3e72b1d8252b68401c729dd6d4d
> Fix StyleTransferTranslatorFactory bug

- docs/development/inference_performance_optimization.md
Change-Id: I38ce893911852a8414ecff36437545eec3e6e9f6
> Fix inference_performance_optimization.md broken link

- extensions/benchmark/src/main/java/ai/djl/benchmark/AbstractBenchmark.java
Change-Id: Ibc47727ebc3dd729a0031362867430efd83f330e
> [benchmark] update device information print message

- .github/ISSUE_TEMPLATE/feature_request.md
- README.md
- dlr/dlr-native/README.md
- docs/development/memory_management.md
- docs/development/troubleshooting.md
Change-Id: I75076faf6a24281dde591bc16fa79f32db77efd9
> Fix markdown format

- .github/workflows/docs.yml
Change-Id: I6958b1fe609b76d8be8dcc118a447f9588dfe9ee
> Fix docs build failure

- paddlepaddle/paddlepaddle-native/src/main/native/ai_djl_paddlepaddle_jni_PaddleLibrary_inference.cc
- paddlepaddle/paddlepaddle-native/src/main/native/ai_djl_paddlepaddle_jni_PaddleLibrary_tensor.cc
- paddlepaddle/paddlepaddle-native/src/main/native/djl_paddle_utils.h
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_cache.h
- pytorch/pytorch-native/src/main/native/djl_pytorch_jni_exception.h
- pytorch/pytorch-native/src/main/native/djl_pytorch_utils.h
- tools/gradle/cpp-formatter.gradle
Change-Id: Id8c933aacdfda9620f05868954047bbf93cee660
> Reformat .cc and .h file

- extensions/fasttext/src/main/java/ai/djl/fasttext/jni/FtWrapper.java
- extensions/fasttext/src/test/java/ai/djl/fasttext/CookingStackExchangeTest.java
Change-Id: I06ea826ea37d367ea75ca257bd640583b1660fc2
> [fasttext] keep __label__ prefix

- .gitignore
- pytorch/pytorch-engine/build.gradle
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtSymbolBlock.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/IValue.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/IValueUtils.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
- pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/IValueTest.java
- pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/PtModelTest.java
- pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/TorchScriptTest.java
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_inference.cc
- pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_ivalue.cc
Change-Id: Ifdbf35297073d9f105e6819bd632c77df4782940
> [pytorch] expose IValue for custom input data type

- extensions/fasttext/src/test/java/ai/djl/fasttext/CookingStackExchangeTest.java
Change-Id: Ic0b70dd89ae606748f9cea38e16da183abb01d55
> Fix fasttest nightly test

- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/IValue.java
Change-Id: Ie3008c23f80f332c187eee7b2c710dfe897934ed
> [pytorch] add list and tuple support to ivalue

- .github/workflows/continuous.yml
- .github/workflows/native_jni_s3_dlr.yml
- .github/workflows/native_jni_s3_pytorch.yml
- .github/workflows/native_s3_fasttext.yml
- .github/workflows/native_s3_sentencepiece.yml
- dlr/dlr-engine/build.gradle
- dlr/dlr-native/build.gradle
- extensions/fasttext/.gitignore
- extensions/fasttext/build.gradle
- extensions/sentencepiece/.gitignore
- extensions/sentencepiece/build.gradle
- paddlepaddle/paddlepaddle-engine/build.gradle
- paddlepaddle/paddlepaddle-native/build.gradle
- pytorch/pytorch-engine/build.gradle
- pytorch/pytorch-native/build.gradle
Change-Id: Ia9fcf2aa40429090563586a7bcd42060afd8a4a9
> Refactor native engine build scripts.

- model-zoo/src/main/resources/META-INF/native-image/ai/djl/basicmodelzoo/reflect-config.json
Fixes #1204
Change-Id: Ia42b3c2f6ec651d647e48f4e8cc536ee4668c727
> Fixes typo in reflect-config.json

- extensions/benchmark/src/main/java/ai/djl/benchmark/Arguments.java
Change-Id: I7dd0a4892abbe24eb64f540983f47f52f9210cca
> [djl-bench] fix --help command line option print out

- .github/workflows/native_jni_s3_pytorch.yml
Change-Id: I08c6d87e21ccd01b5eb351eeef712ebbd135832d
> Fix pytorch github actions yaml file

- api/src/main/java/ai/djl/inference/Predictor.java
- api/src/main/java/ai/djl/modality/cv/translator/BaseImageTranslator.java
- api/src/main/java/ai/djl/modality/cv/translator/ImageClassificationTranslator.java
- api/src/main/java/ai/djl/modality/cv/translator/InstanceSegmentationTranslator.java
- api/src/main/java/ai/djl/modality/cv/translator/ObjectDetectionTranslator.java
- api/src/main/java/ai/djl/modality/cv/translator/wrapper/FileTranslator.java
- api/src/main/java/ai/djl/modality/cv/translator/wrapper/InputStreamTranslator.java
- api/src/main/java/ai/djl/modality/cv/translator/wrapper/UrlTranslator.java
- api/src/main/java/ai/djl/translate/ServingTranslatorFactory.java
- api/src/main/java/ai/djl/translate/Translator.java
- api/src/main/java/ai/djl/translate/TranslatorContext.java
- examples/src/main/java/ai/djl/examples/inference/BertClassification.java
- examples/src/main/java/ai/djl/examples/inference/ObjectDetectionWithTensorflowSavedModel.java
- examples/src/main/java/ai/djl/examples/inference/sr/SuperResolutionTranslator.java
- mxnet/mxnet-model-zoo/src/main/java/ai/djl/mxnet/zoo/nlp/embedding/GloveWordEmbeddingTranslatorFactory.java
- mxnet/mxnet-model-zoo/src/main/java/ai/djl/mxnet/zoo/nlp/qa/MxBertQATranslator.java
- paddlepaddle/paddlepaddle-model-zoo/src/main/java/ai/djl/paddlepaddle/zoo/cv/wordrecognition/PpWordRecognitionTranslator.java
- pytorch/pytorch-model-zoo/src/main/java/ai/djl/pytorch/zoo/cv/objectdetection/PtSsdTranslator.java
- pytorch/pytorch-model-zoo/src/main/java/ai/djl/pytorch/zoo/nlp/qa/PtBertQATranslator.java
- pytorch/pytorch-model-zoo/src/main/java/ai/djl/pytorch/zoo/nlp/sentimentanalysis/PtDistilBertTranslator.java
- tensorflow/tensorflow-model-zoo/src/main/java/ai/djl/tensorflow/zoo/cv/objectdetction/TfSsdTranslator.java
1. Add default implemenation to getBatchifier()
2. pass TranslatorContext to prepare()
3. Add getBlock() and getPredictorManager() to TranslatorContext
Change-Id: I1e23fcae60d92905597d5e1f8dd583e58bc79eeb
> [api] Refactor Predictor API

- api/src/main/java/ai/djl/ndarray/NDArray.java
- api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
- api/src/main/java/ai/djl/ndarray/NDManager.java
- api/src/main/java/ai/djl/nn/transformer/BertBlock.java
- api/src/main/java/ai/djl/nn/transformer/BertMaskedLanguageModelBlock.java
- api/src/main/java/ai/djl/nn/transformer/BertMaskedLanguageModelLoss.java
- api/src/main/java/ai/djl/nn/transformer/BertNextSentenceLoss.java
- api/src/main/java/ai/djl/nn/transformer/BertPretrainingBlock.java
- dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrNDManager.java
- ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbNDManager.java
- ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbSymbolBlock.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArrayIndexer.java
- mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDManager.java
- onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtNDManager.java
- onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtSymbolBlock.java
- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpNDManager.java
- paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpSymbolBlock.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArrayIndexer.java
- pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDManager.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArrayIndexer.java
- tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDManager.java
- tflite/tflite-engine/src/main/java/ai/djl/tflite/engine/TfLiteNDManager.java
Change-Id: I89dc8c2aa05c0986f5172ae10757c072561d16f9
> Address NDArrayAdapter comments.

- engines/tensorrt/build.gradle
- engines/tensorrt/src/main/java/ai/djl/tensorrt/engine/TrtEngine.java
- engines/tensorrt/src/test/java/ai/djl/tensorrt/engine/TrtEngineTest.java
- engines/tensorrt/src/test/java/ai/djl/tensorrt/engine/TrtNDManagerTest.java
- engines/tensorrt/src/test/java/ai/djl/tensorrt/integration/TrtTest.java
Change-Id: I302da588b465be79e108860e0a72011d4a8767c0
> Add uff model unit test

- .github/workflows/native_jni_s3_tensorrt.yml
Change-Id: Id4dde195be8f55174689a6f107101f94be47123b
> Add tensorrt jni publish workflow

- docs/mkdocs.yml
Change-Id: I237c0acc122bcd55f001b140fdf699ca8a4e1e22
> Add TensorRT to docs website

- extensions/benchmark/build.gradle
- extensions/benchmark/src/main/java/ai/djl/benchmark/AbstractBenchmark.java
- extensions/benchmark/src/main/java/ai/djl/benchmark/Arguments.java
- extensions/benchmark/src/main/java/ai/djl/benchmark/Benchmark.java
- extensions/benchmark/src/test/java/ai/djl/benchmark/BenchmarkTest.java
Change-Id: I57b29e01b7f0c6f2696b67852b52466266f4352b
> Add tensorRT to benchmark

- bom/build.gradle
Change-Id: Ibe4d6d5136f43205f2ed130d81b0fdf9deb05e5e
> Add tensorrt to bom

- .github/workflows/native_jni_s3_tensorrt.yml
Change-Id: Ia8bb1f07b82953526b70e64e354c7d0dceb599e3
> Fix tensorrt JNI publish workflow

- api/src/main/java/ai/djl/repository/RepositoryFactoryImpl.java
- api/src/test/java/ai/djl/repository/TfhubRepositoryTest.java
- extensions/benchmark/README.md
Fixes #1122
Change-Id: Ia1a2fafc502cb07878ed23dea66f1914b8b3159a
> Add tfhub url support

- api/src/main/java/ai/djl/inference/Predictor.java
Change-Id: Iabfc1666caddbd8f423713e7324be2cadebae36b
> [api] Make Predictor.predictInternal() protected

- engines/tensorrt/src/main/native/ai_djl_tensorrt_jni_model.cc
Change-Id: I1fd7b61e436000dd04ba9997ed325c75aa5597b4
> [tensorrt] Fix onnx model NaN issue

- api/src/main/java/ai/djl/util/Platform.java
- api/src/test/java/ai/djl/util/PlatformTest.java
- engines/dlr/dlr-engine/src/main/java/ai/djl/dlr/jni/LibUtils.java
- engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/jna/LibUtils.java
- engines/paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jni/LibUtils.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java
- engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/javacpp/LibUtils.java
- engines/tflite/tflite-engine/src/main/java/ai/djl/tflite/engine/LibUtils.java
Change-Id: I892125a82ecd2c79e11ca808d57ae5d4a1cf5092
> Allow match platform with cuda minor version different

- api/src/main/java/ai/djl/inference/Predictor.java
- gradle.properties
Change-Id: Ibb001eae4ddaae670eb1d4023cf894b38d9cafaf
> [api] Refactor predictor.predictInternal()

- api/src/main/java/ai/djl/repository/zoo/Criteria.java
Change-Id: I975f72f9c9a914595ead0c26a321584a81a3e168
> Avoid throw MalformedURLException in Criteria.optModelPath()

- .github/workflows/native_jni_s3_pytorch.yml
Change-Id: I700b615ea1745b3484dad987e8bc9995e248f39e
> [ci] Fix pytorch jni nightly workflow

- docs/README.md
- docs/engine.md
- docs/hybrid_engine.md
- engines/dlr/dlr-engine/README.md
- engines/mxnet/mxnet-engine/README.md
- engines/mxnet/mxnet-model-zoo/README.md
- engines/onnxruntime/onnxruntime-engine/README.md
- engines/paddlepaddle/paddlepaddle-engine/README.md
- engines/paddlepaddle/paddlepaddle-model-zoo/README.md
- engines/pytorch/pytorch-engine/README.md
- engines/pytorch/pytorch-model-zoo/README.md
- engines/tensorflow/tensorflow-engine/README.md
- engines/tensorflow/tensorflow-model-zoo/README.md
- engines/tensorrt/README.md
- engines/tflite/tflite-engine/README.md
- model-zoo/README.md
Change-Id: Id6ee4dd96da8fe61f4dfb44d6a1e742fbf3d2560
> [doc] Update hybrid engine documentation

- docs/development/setup.md
Change-Id: Ibcb122e57f012522a9c74091d4228e84d1419df8
> [doc] update setup java8 command line

- examples/src/main/java/ai/djl/examples/training/TrainBertOnCode.java
- examples/src/main/java/ai/djl/examples/training/util/BertCodeDataset.java
This just moves functions around so they are closer to their actual usages. Many
are only used in subClasses so the functions are moved into the respective subclasses.
> Reorganize BertCodeDataset

- examples/build.gradle
- extensions/benchmark/build.gradle
- integration/build.gradle
- tools/gradle/check.gradle
- tools/gradle/jacoco.gradle
Change-Id: Ieb0743f349e2498eb7eb22499e473b6055281d61
> Fix gradle deprecation warnings

- gradle/wrapper/gradle-wrapper.properties
- tools/conf/pmd.xml
Change-Id: I4f27b783078f112fca6f484f360f8c62b9ec5a49
> Upgrade gradle to 7.2

- engines/tensorrt/src/main/native/ai_djl_tensorrt_jni_model.cc
- engines/tensorrt/src/main/native/ai_djl_tensorrt_jni_model.h
Change-Id: Ib9b219b773a6fa52cac6dd6d59a2541530c91a43
> [tensorrt] Fix multi gpu issue

- engines/ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbModel.java
- engines/paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpModel.java
- engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfModel.java
- engines/tensorrt/src/main/java/ai/djl/tensorrt/engine/TrtModel.java
- engines/tflite/tflite-engine/src/main/java/ai/djl/tflite/engine/TfLiteModel.java
- integration/src/main/java/ai/djl/integration/tests/model_zoo/classification/AlexNetTest.java
- integration/src/main/java/ai/djl/integration/tests/model_zoo/classification/GoogLeNetTest.java
- integration/src/main/java/ai/djl/integration/tests/model_zoo/classification/LeNetTest.java
- integration/src/main/java/ai/djl/integration/tests/model_zoo/classification/NiNTest.java
- integration/src/main/java/ai/djl/integration/tests/model_zoo/classification/VGGTest.java
- integration/src/main/java/ai/djl/integration/tests/nn/BlockCoreTest.java
- integration/src/main/java/ai/djl/integration/tests/nn/BlockFactoryTest.java
- integration/src/main/java/ai/djl/integration/tests/training/EvaluateDatasetTest.java
Change-Id: I5ff882caa1c24a71fbc282bb638a3e5736a77408
> Fix model close() NPE issue

- api/src/main/java/ai/djl/repository/zoo/BaseModelLoader.java
Change-Id: I7e360dc9899e047444eb93c0af9605495b0882a9
> Fix issue when use file name to load model.

- bom/build.gradle
Change-Id: Idc9718282ed66835621a078b8b1d784cb45b9002
> Add python engine to bom

- api/src/main/java/ai/djl/modality/Input.java
- api/src/main/java/ai/djl/modality/Output.java
- api/src/main/java/ai/djl/ndarray/BytesSupplier.java
- api/src/main/java/ai/djl/ndarray/BytesSupplierImpl.java
- api/src/main/java/ai/djl/ndarray/NDArray.java
- api/src/main/java/ai/djl/ndarray/NDList.java
- api/src/main/java/ai/djl/translate/NDArraySupplier.java
- api/src/main/java/ai/djl/translate/ServingTranslatorFactory.java
- api/src/main/java/ai/djl/util/PairList.java
- api/src/test/java/ai/djl/DeviceTest.java
- api/src/test/java/ai/djl/modality/InputOutputTest.java
- api/src/test/java/ai/djl/modality/package-info.java
- integration/src/main/java/ai/djl/integration/tests/model_zoo/CustomTranslatorTest.java
- integration/src/test/translator/MyTranslator.java
- tools/gradle/jacoco.gradle
Change-Id: I695054aa63a8366b1b1160953faa37c608bc2fee
> [api] refactor input/output interface

- .github/workflows/serving_publish.yml
Change-Id: Ic3faf71f9af87beb1563bdf13477acd2cf616227
> [ci] Add publish python engine and serving wlm pipeline

- api/src/main/java/ai/djl/translate/ServingTranslatorFactory.java
Change-Id: I4602ce54fde5832b3816c75b7aecf34271c67fa0
> Fix Resource closed exception

- api/src/main/java/ai/djl/ndarray/NDArray.java
- If this change is a backward incompatible change, why must this change be made? Yes
- Interesting edge cases to note here: no, it is just a simple doc error
> [doc] fix error in example doc of NDArray.sort

- .github/workflows/serving_publish.yml
Change-Id: I94f10838296f37ac81a169f81ecbb17355882ce2
> Fix serving publish workflow

- api/src/main/java/ai/djl/modality/cv/translator/BaseImageTranslator.java
- api/src/main/java/ai/djl/repository/AbstractRepository.java
- engines/mxnet/mxnet-model-zoo/src/test/resources/mlrepo/model/cv/image_classification/ai/djl/mxnet/resnet/metadata.json
- engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/zoo/OrtModelZoo.java
- engines/onnxruntime/onnxruntime-engine/src/test/resources/mlrepo/model/cv/image_classification/ai/djl/onnxruntime/resnet/metadata.json
- engines/pytorch/pytorch-model-zoo/src/test/resources/mlrepo/model/cv/image_classification/ai/djl/pytorch/resnet/metadata.json
Change-Id: I39bb5c181d0c2722b524ff87760c4af11777764a
> Add resnet101 to modelzoo

- api/src/main/java/ai/djl/modality/Input.java
Debugging input for uses including https://github.com/deepjavalibrary/djl-serving/pull/26
> Add debugging toString to Input and Output

- extensions/benchmark/README.md
- extensions/benchmark/src/main/java/ai/djl/benchmark/Arguments.java
- extensions/benchmark/src/main/java/ai/djl/benchmark/MultithreadedBenchmark.java
Change-Id: I67c7b0f7ef1c80d9056dd9ddb546fc9d1ec0d50c
> [benchmark] Add support for inferentia

- api/src/main/java/ai/djl/repository/JarRepository.java
- api/src/main/java/ai/djl/repository/RepositoryFactoryImpl.java
- api/src/test/java/ai/djl/repository/JarRepositoryTest.java
fixes #1333
Change-Id: Iee96a8e9fd1104ba4865db6b94709dba5882a371
> [api] Fix jar model url download bug

- api/src/main/java/ai/djl/repository/FilenameUtils.java
Change-Id: I58294d1d90469566464cccb28308450625e37865
> Add support for downloading .mar file

- api/src/main/java/ai/djl/training/loss/SigmoidBinaryCrossEntropyLoss.java
> Fix calculation for SigmoidBinaryCrossEntropyLoss from sigmoid

- examples/build.gradle
- extensions/opencv/build.gradle
- extensions/opencv/src/test/java/ai/djl/opencv/OpenCVImageFactoryTest.java
Change-Id: Id92b6694c93b858f7f136a2ac8b1ef293748096b
> [opencv] workaround windows build failure

- api/src/main/java/ai/djl/BaseModel.java
- engines/dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrModel.java
- engines/ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbModel.java
- engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxModel.java
- engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtModel.java
- engines/paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpModel.java
- engines/paddlepaddle/paddlepaddle-model-zoo/src/main/java/ai/djl/paddlepaddle/zoo/cv/wordrecognition/PpWordRecognitionTranslator.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtModel.java
- engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfModel.java
- engines/tensorrt/src/main/java/ai/djl/tensorrt/engine/TrtModel.java
- engines/tflite/tflite-engine/src/main/java/ai/djl/tflite/engine/TfLiteModel.java
Change-Id: I9b3d6e310f342cd9e25bd448fb80a549e0b257b0
> [api] Handle model archive file contains folder name

- engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxDataType.java
Change-Id: I495fb7a52fba4dd8adf2c2f602779a4dfa82a2da
> [mxnet] allow create boolean NDArray

- engines/tflite/tflite-engine/src/main/java/ai/djl/tflite/engine/TfLiteNDArray.java
Change-Id: Ib08a79c473bd897d6f43981d5924bbf46943a0a4
> [tflite] Fixes 2nd inference throw exception bug

- docs/development/dependency_management.md
- engines/pytorch/pytorch-engine/README.md
Change-Id: Icc52edee8b067b710f638ffaf8ee001adb3e71e8
> [docs] Update PyTorch engine document

- examples/build.gradle
- examples/src/test/java/ai/djl/testing/TestRequirements.java
- examples/src/test/java/ai/djl/testing/package-info.java
1. remove ai.djl:testing dependency
2. Create symbolic link of testing source code into example project
Change-Id: I102434c28a0fdf1dc405af3e6945366b22563749
> [examples] Fix maven build

- api/src/main/java/ai/djl/modality/cv/BufferedImageFactory.java
- api/src/main/java/ai/djl/modality/cv/Image.java
- extensions/opencv/src/main/java/ai/djl/opencv/OpenCVImage.java
- extensions/opencv/src/test/java/ai/djl/opencv/OpenCVImageFactoryTest.java
Change-Id: Ic45f668591f4677708e40090f3ea9487a098e3fb
> [api] Adds Image.duplicate() back

- engines/pytorch/pytorch-native/build.gradle
Change-Id: I796878ab6b97eabd578bef0b67969601d73f0bb3
> [ci] fix pytorch nightly build

- extensions/benchmark/snapcraft/snapcraft.yaml
Change-Id: I7c0fdf9ce3b430390bc3bfdd94e9efeca3639d31
> [djl-bench] Upgrade snapcraft to use DJL 0.14.0

- README.md
- api/README.md
- examples/pom.xml
- gradle.properties
Change-Id: Idba882a6bf3b85a5cad0cb97479d2e10a31c9507
> Bump up version to 0.15.0

- .github/workflows/codeql-analysis-java.yml
- .github/workflows/serving_publish.yml
Avoids running the workflow on existing forks.
> Add missing actions repository checks

- .github/workflows/native_jni_s3_pytorch.yml
Change-Id: Idee98e3e7d5f2b6709adf2a5ef7792f7ca7ce498
> [ci] Fix pytorch jni windows build

- extensions/opencv/build.gradle
Change-Id: Ie1b62b437184743339a31b7bd00c85b0f0efab15
> [opencv] Expose api from opencv

- jupyter/rank_classification_using_BERT_on_Amazon_Review.ipynb
- jupyter/tensorflow/rank_classification_using_BERT_on_Amazon_Review.ipynb
Change-Id: I5a4b72008aca0811ff590de5f3a8ded688ce684c
> [jupyter] Fixes rank classification jupyter notebook

- .github/workflows/native_jni_s3_pytorch.yml
- engines/pytorch/pytorch-engine/build.gradle
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java
- engines/pytorch/pytorch-native/build.cmd
- engines/pytorch/pytorch-native/build.gradle
- engines/pytorch/pytorch-native/build.sh
- gradle.properties
Change-Id: I2b9fa7b31c7b7a627b176bb98370ecd2ca026000
> [pytorch] Updates PyTorch engine to 1.10.0

- api/src/main/java/ai/djl/util/Platform.java
- engines/dlr/dlr-engine/src/main/java/ai/djl/dlr/jni/LibUtils.java
- engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/jna/LibUtils.java
- engines/paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jni/LibUtils.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java
- engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/javacpp/LibUtils.java
- engines/tensorrt/src/main/java/ai/djl/tensorrt/jni/LibUtils.java
- engines/tflite/tflite-engine/src/main/java/ai/djl/tflite/engine/LibUtils.java
- extensions/fasttext/src/main/java/ai/djl/fasttext/jni/LibUtils.java
- extensions/sentencepiece/src/main/java/ai/djl/sentencepiece/jni/LibUtils.java
Change-Id: I2047b8d7be4fe401f94ba4e92b4054d11608d026
> Refactor LibUtils

- api/src/main/java/ai/djl/engine/Engine.java
- build.gradle
Change-Id: Iad43af6e80ef23f8a292ed310e63c53d424a72cf
> Add djl version to manifest

- .github/workflows/continuous.yml
- .github/workflows/native_build_mxnet_osx.yml
- .github/workflows/native_jni_s3_paddle.yml
- .github/workflows/native_jni_s3_pytorch_android.yml
- .github/workflows/nightly_publish.yml
Change-Id: I6b6c46ef68718bd47dd93f0b5c9a3f73cddd1f8e
> [ci] Upload all test reports in single task

- api/src/main/java/ai/djl/engine/Engine.java
Change-Id: If7b4f79ca56057a96aea09d541a0e742fa4b143c
> [api] Allows regiter engine at runtime

- .github/workflows/codeql-analysis-java.yml
Change-Id: I76d2dc581ef67dba4e0eb57a454baafbd2c2f060
Workaround codeql issue: https://github.com/github/codeql-action/issues/824#issuecomment-977159900
> [ci] Workaround codeql build issue

- api/src/main/java/ai/djl/repository/zoo/ModelZoo.java
Change-Id: I3209f9d8a7b16915d6417013cba7e87b19e0e954
> [api] Allows dynamic add model zoo

- extensions/sentencepiece/src/main/java/ai/djl/sentencepiece/SpProcessor.java
- extensions/sentencepiece/src/main/java/ai/djl/sentencepiece/SpTokenizer.java
- extensions/sentencepiece/src/main/java/ai/djl/sentencepiece/jni/SentencePieceLibrary.java
- extensions/sentencepiece/src/main/native/ai_djl_sentencepiece_jni_SentencePieceLibrary.cc
- extensions/sentencepiece/src/test/java/ai/djl/sentencepiece/SpTokenizerTest.java
Add SentencePiece load from byte array method.
> add sentencepiece load from bytes method

- api/src/main/java/ai/djl/BaseModel.java
- api/src/main/java/ai/djl/Model.java
- api/src/main/java/ai/djl/repository/zoo/ZooModel.java
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtModel.java
- extensions/fasttext/src/main/java/ai/djl/fasttext/FtModel.java
Change-Id: I2106712d175ea1c6ec31d9561f2809473df2fbc9
> [api] Adds load model from Inpustream to public API

- engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtModel.java
- engines/onnxruntime/onnxruntime-engine/src/test/java/ai/djl/onnxruntime/engine/OrtTest.java
- engines/tflite/tflite-engine/src/main/java/ai/djl/tflite/engine/TfLiteModel.java
- engines/tflite/tflite-engine/src/test/java/ai/djl/tflite/engine/TfLiteTest.java
Change-Id: I5485c87f9dedf88acf5fa2e5f74c66e799c28319
> Adds load model from InputStream for OnnxRuntime and TFLite

- .github/workflows/native_s3_sentencepiece.yml
Change-Id: I978a2a12cce0710856b2b4784a902f2cff8f87dd
> [ci] Invalidate cloudfront cache after sentencepiece build

- .github/workflows/continuous.yml
- .github/workflows/native_s3_sentencepiece.yml
- extensions/sentencepiece/CMakeLists.txt
- extensions/sentencepiece/build.cmd
- extensions/sentencepiece/build.gradle
- extensions/sentencepiece/build.sh
- extensions/sentencepiece/src/main/java/ai/djl/sentencepiece/jni/LibUtils.java
- extensions/sentencepiece/src/main/native/ai_djl_sentencepiece_jni_SentencePieceLibrary.cc
- extensions/sentencepiece/src/test/java/ai/djl/sentencepiece/SpTextEmbeddingTest.java
- extensions/sentencepiece/src/test/java/ai/djl/sentencepiece/SpTokenizerTest.java
- extensions/sentencepiece/src/test/java/ai/djl/sentencepiece/SpVocabularyTest.java
> [sentencepiece] Adds Windows support

- .github/CODEOWNERS
Change-Id: I7066806d8f40b6067a4ed9257782d38d8ca92859
> Add djl-admin as codeowners

- extensions/benchmark/README.md
Change-Id: I7c5cdb1ca47cf023ab61a0359c01f396b446147f
> Update djl-bench version to 0.14.1

- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/IValue.java
- engines/pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/IValueTest.java
Change-Id: If6bebfef02efb1d42b65b1dd58b591df8274ff24
> [pytorch] Fixes #1437, check empty IValue[]

- website/demo.html
Change-Id: Icc136256c2cf23784e0b7758dd4c4e0932141b7d
> Update demo blockrunner example code

- engines/pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/PtModelTest.java
Change-Id: Ia2d1271ad97ccc2f59059981a7534e2470160943
> [pytorch] Fixes unit test failure on GPU.

- engines/pytorch/pytorch-native/README.md
Change-Id: I58d58fff96dcf93b2513b4b7264c47bcb3878442
> [pytorch] Update pytorch native library README

- extensions/hadoop/build.gradle
- gradle.properties
- testing/build.gradle
Change-Id: I4b0a730857c42e6b1bf879226fcac1fc443f7bbd
> Upgrade testng to 7.5

- docs/development/dependency_management.md
- engines/dlr/dlr-engine/README.md
- engines/ml/xgboost/README.md
- engines/mxnet/mxnet-engine/README.md
- engines/mxnet/mxnet-model-zoo/README.md
- engines/onnxruntime/onnxruntime-engine/README.md
- engines/paddlepaddle/paddlepaddle-engine/README.md
- engines/paddlepaddle/paddlepaddle-model-zoo/README.md
- engines/pytorch/pytorch-engine/README.md
- engines/pytorch/pytorch-model-zoo/README.md
- engines/tensorflow/tensorflow-api/README.md
- engines/tensorflow/tensorflow-engine/README.md
- engines/tensorflow/tensorflow-model-zoo/README.md
- engines/tensorrt/README.md
- engines/tflite/tflite-engine/README.md
Change-Id: Ia4188c0cd8af7e549e8a7bd1cf6b3c760c8ffdad
> [docs] Update engine documents to remove -auto package

- .github/workflows/nightly_publish.yml
- engines/pytorch/pytorch-jni/build.gradle
Change-Id: Ia9e67836e0edde32ab79ea2961ccdf055f03b692
> [pytorch] Publish 1.8.1 and 1.9.1 JNI in nightly build

- docs/development/dependency_management.md
- engines/pytorch/pytorch-engine/README.md
Change-Id: Ia60d64f3fba25ee9c7b025368776f98c3cf9df72
> [pytorch] Update PyTorch engine dependency document

- engines/dlr/dlr-native/build.gradle
- engines/mxnet/native/build.gradle
- engines/paddlepaddle/paddlepaddle-native/build.gradle
- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java
- engines/tensorflow/tensorflow-native/build.gradle
- engines/tflite/tflite-native/build.gradle
Change-Id: I87a40e4f30e427b8ec72b6fa09f4784535dca0c2
> [pytorch] Fix pytorch engine version string

- docs/create_serving_ready_model.md
Change-Id: I432a4f6267b4c970e79d163cc375801b0ccc2c6d
> [docs] Update package model document

- docker/windows/Dockerfile
Change-Id: Id38b1c86072a7e47e955da34f727a048e964287e
> Upgrade windows docker to use opendjk11

- extensions/benchmark/build.gradle
- extensions/benchmark/snapcraft/snapcraft.yaml
Change-Id: If4e231be7318f9829e106dff627704b7e3ab5017
> [djl-bench] Upgrade djl-bench to 0.15.0

- integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayElementArithmeticOpTest.java
Change-Id: If1a2a5cf58214f0cacee362e2806936ca6e271b3
> [test] Fix flaky test for tensorflow 2.7.0 on GPU

- api/README.md
- examples/pom.xml
- gradle.properties
Change-Id: Ib5fb28284b4a6c8dfb0d3ef64e4072059a8e2ef9
> Bump up version to 0.16.0

- README.md
- extensions/benchmark/README.md
Change-Id: I7aed0ff04166a9a33b5b497d9f497c72e3174ad5
> Update README for 0.15.0 release

- engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtModel.java
- engines/onnxruntime/onnxruntime-engine/src/test/java/ai/djl/onnxruntime/engine/OrtTest.java
Change-Id: I99890422056a3a68f7419088cf5cf849e75d4da9
> [onnx] Add SessionOptions support for OnnxRuntime

- .github/workflows/android_core_publish.yml
- .github/workflows/native_jni_s3_pytorch_android.yml
- .github/workflows/native_s3_pytorch_android.yml
- android/build.gradle
- android/core/build.gradle
- android/core/src/androidTest/java/ai/djl/android/core/BitmapWrapperTest.java
- android/core/src/main/java/ai/djl/android/core/BitmapImageFactory.java
- android/gradle.properties
- android/pytorch-native/build.gradle
- engines/pytorch/pytorch-native/build_android.sh
- engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_nn_functional.cc
Change-Id: I77f27b7271b96f2094cc9d24e4e15014d94541eb
> [android] Update to 0.15.0

- engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java
Change-Id: Ic255c90bcba5a99aa467a104305f5fe4d7af5620
> [pytorch] Fix load native library failure on Android

- android/README.md
Change-Id: Id299b82f7120785b143d2c8a38f8f469faa6279b
> [android] Update README to use 0.16.0-SNAPSHOT version

- bom/build.gradle
Change-Id: I0cf95bffef55942fd7fefed66f45c934586c2c17
> [tokenizers] Adding huggingface tokenizer extension to BOM

- .github/workflows/continuous.yml
- .github/workflows/native_jni_s3_dlr.yml
- .github/workflows/native_jni_s3_paddle.yml
- .github/workflows/native_jni_s3_pytorch.yml
- .github/workflows/native_jni_s3_pytorch_android.yml
- .github/workflows/native_jni_s3_tensorrt.yml
- .github/workflows/native_publish_dlr.yml
- .github/workflows/native_publish_mxnet.yml
- .github/workflows/native_publish_paddle.yml
- .github/workflows/native_publish_pytorch.yml
- .github/workflows/native_publish_tensorflow.yml
- .github/workflows/native_publish_tflite.yml
- .github/workflows/native_s3_dlr.yml
- .github/workflows/native_s3_fasttext.yml
- .github/workflows/native_s3_huggingface.yml
- .github/workflows/native_s3_pytorch_android.yml
- .github/workflows/native_s3_sentencepiece.yml
- .github/workflows/native_s3_tensorflow.yml
- .github/workflows/native_s3_tflite.yml
- .github/workflows/nightly_publish.yml
- .github/workflows/publish_android_packages.yml
- .github/workflows/serving_publish.yml
Change-Id: Iad394eae481145e11f682443bc6202dac202b0e8
> [ci] Use JDK 11 for github actions build.

- index.html
- website/blog.html
- website/javadoc.html
Should fix bug on djl.ai homepage.
> Fix djl site vue version

- engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtModel.java
- engines/onnxruntime/onnxruntime-engine/src/test/java/ai/djl/onnxruntime/engine/OrtTest.java
Add arena allocator boolean setter
Related to #1507
> arena allocator setter

- .github/workflows/native_build_mxnet_osx.yml
- engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/jna/LibUtils.java
- engines/mxnet/native/build.gradle
- gradle.properties
Change-Id: I17f0fb861093cd2b09c21cf063d5a39d213dc4a9
> [mxnet] Updates MXNet engine to 1.9.0

- .github/workflows/native_publish_mxnet.yml
- engines/mxnet/native/build.gradle
Change-Id: I4904178bd0e4bb3d8bed86752eaa8a272ffdd1c3
> [mxnet] Upgrade native build mxnet version

- basicdataset/src/main/java/ai/djl/basicdataset/nlp/AmazonReview.java
- basicdataset/src/main/java/ai/djl/basicdataset/tabular/AirfoilRandomAccess.java
- basicdataset/src/main/java/ai/djl/basicdataset/tabular/AmesRandomAccess.java
- examples/src/main/java/ai/djl/examples/training/transferlearning/TrainAmazonReviewRanking.java
- gradle.properties
Change-Id: I92f75844b8380740c853214efb8ca8f2add401c5
> Upgrade dependency versions

- api/README.md
- examples/pom.xml
- gradle.properties
Change-Id: Ia2a6857589104ceb97e55a0ddac1fd99451d8391
> Bump up version to 0.17.0

- engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/Symbol.java
- engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/jna/JnaUtils.java
- engines/paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpModel.java
- extensions/fasttext/src/main/java/ai/djl/fasttext/FtModel.java
- extensions/fasttext/src/main/java/ai/djl/fasttext/FtTrainingConfig.java
- gradle/wrapper/gradle-wrapper.properties
- testing/src/main/java/ai/djl/testing/CoverageUtils.java
- tools/conf/pmd.xml
Change-Id: I318e20cb905cbb36019d431c68ab63051ff4aa23
> [ci] Upgrade gradle wrapper to 7.4.1

- examples/pom.xml
Change-Id: I4955ceb18dfa87f9c7d7d0d03589f0ebd03ee260
> [examples] Update maven pom file dependency version

- README.md
This adds a new note of the approximate time for the next release.
> Add release note to README

- engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfEngine.java
> Add better error message for libstdc++ tf errors

- engines/ml/xgboost/build.gradle
Change-Id: I79645d18cd26aba2e8e4dff482b7efebbcecc096
> [xgb] Fixes missing anonymous classes

- engines/paddlepaddle/paddlepaddle-model-zoo/README.md
> [Paddle] fix naming

- examples/src/test/java/ai/djl/examples/training/TrainMnistTest.java
Change-Id: I6d11d1602e6b0a7a34bb39fb2f6c6349e59fe798
> [unittest] Avoid flaky test

- docs/development/troubleshooting.md
Add a PaddlePaddle troubleshoot error page
> [PaddlePaddle] add troubleshoot issue

- engines/paddlepaddle/paddlepaddle-engine/README.md
- engines/paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jni/LibUtils.java
- engines/paddlepaddle/paddlepaddle-native/build.cmd
- engines/paddlepaddle/paddlepaddle-native/build.gradle
Add Paddle CU110 Support
Compiled on Windows and found it equivalent to the CPU JNI
> [PaddlePaddle] add paddle CU110

- api/src/main/java/ai/djl/inference/Predictor.java
- api/src/main/java/ai/djl/metric/Dimension.java
- api/src/main/java/ai/djl/metric/Metric.java
- api/src/main/java/ai/djl/metric/Metrics.java
- api/src/main/java/ai/djl/metric/Unit.java
- api/src/main/java/ai/djl/training/listener/MemoryTrainingListener.java
- api/src/test/java/ai/djl/metric/MetricsTest.java
- extensions/benchmark/src/main/java/ai/djl/benchmark/AbstractBenchmark.java
- extensions/benchmark/src/main/java/ai/djl/benchmark/Benchmark.java
- extensions/benchmark/src/main/java/ai/djl/benchmark/MultithreadedBenchmark.java
Change-Id: I271ec2b5b89034d837949eee4829016321550e34
> [api] Refactor metrics API

- integration/src/main/java/ai/djl/integration/tests/training/GradientCollectorIntegrationTest.java
> Fix testFreezeParameters for multi-gpu

- .github/workflows/native_jni_s3_pytorch_android.yml
> [PyTorch] bump up Android version

- android/gradle.properties
- android/pytorch-native/build.gradle
Prepare DJL 0.17.0 Android releases
> [Android] update android package versions

- docs/development/dependency_management.md
- engines/paddlepaddle/paddlepaddle-engine/README.md
- engines/pytorch/pytorch-engine/README.md
Change-Id: Ibd14ad2143c41c73c642dab5ad384915c1522fc2
> [docs] Update pytorch and paddle version

- integration/src/main/java/ai/djl/integration/tests/ndarray/NDIndexTest.java
Change-Id: I2e34015b4e28b195ba1509ee3900b876250a7bfb
> [integration] Enable gather unit test for windows

- api/src/main/java/ai/djl/modality/Classifications.java
- api/src/main/java/ai/djl/modality/cv/output/DetectedObjects.java
- api/src/main/java/ai/djl/modality/cv/output/Joints.java
- api/src/main/java/ai/djl/modality/cv/output/Landmark.java
- api/src/main/java/ai/djl/modality/cv/output/Rectangle.java
Change-Id: I4d4e024ee8ebad1f124d9618788c80be8896dc4a
> [api] Fixes JDK 18 compiler warnings

- engines/tensorrt/src/main/java/ai/djl/tensorrt/jni/LibUtils.java
Change-Id: I1d72d6961622b4ccfeb12db9bc4f93cc402763b3
> [tensorrt] Fixes native library path

- api/src/main/java/ai/djl/modality/cv/translator/ObjectDetectionTranslator.java
- api/src/main/java/ai/djl/modality/cv/translator/SingleShotDetectionTranslator.java
- api/src/main/java/ai/djl/modality/cv/translator/YoloTranslator.java
- api/src/main/java/ai/djl/modality/cv/translator/YoloV5Translator.java
Provide a new function for Width/Height conversion for Bounding box. 
https://github.com/deepjavalibrary/djl/issues/1563
> add width/height conversion to ObjectDetection

- api/src/main/java/ai/djl/modality/cv/BufferedImageFactory.java
- api/src/main/java/ai/djl/modality/cv/Image.java
- engines/paddlepaddle/paddlepaddle-model-zoo/build.gradle
- engines/paddlepaddle/paddlepaddle-model-zoo/src/main/java/ai/djl/paddlepaddle/zoo/cv/objectdetection/PpWordDetectionTranslator.java
- engines/paddlepaddle/paddlepaddle-model-zoo/src/test/java/ai/djl/paddlepaddle/zoo/OCRTest.java
- extensions/opencv/src/main/java/ai/djl/opencv/OpenCVImage.java
- extensions/opencv/src/main/java/ai/djl/opencv/OpenCVImageFactory.java
- extensions/opencv/src/test/java/ai/djl/opencv/OpenCVImageFactoryTest.java
Add OpenCV mechanism to do the rectangle findings
> [PaddleOCR] add openCV find rectangle method

- engines/tensorflow/tensorflow-engine/README.md
Update TensorFlow version document
> update TF versions

- engines/paddlepaddle/paddlepaddle-model-zoo/src/test/java/ai/djl/paddlepaddle/zoo/OCRTest.java
Remove uncessary logics for OpenCVImageFactory
> [Paddle] remove unnecessary logics

- api/src/main/java/ai/djl/training/tracker/CyclicalTracker.java
- api/src/main/java/ai/djl/training/tracker/Tracker.java
- api/src/test/java/ai/djl/training/LearningRateTest.java
Add Cyclical Tracker according to cyclical learning rate policy, as detailed in the paper [Cyclical Learning Rates for Training Neural Networks](https://arxiv.org/abs/1506.01186).
close #37.
> [training] Add Cyclical Tracker

- examples/docs/action_recognition.md
Changed line in documentation from saying that it detected "dogs" to detecting "human actions"
> [docs] Clarified typo in example documentation

- engines/ml/xgboost/build.gradle
- engines/ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbEngine.java
- engines/ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbNDManager.java
- engines/ml/xgboost/src/main/java/ml/dmlc/xgboost4j/java/JniUtils.java
- engines/ml/xgboost/src/test/java/ai/djl/ml/xgboost/XgbModelTest.java
- gradle.properties
Upgrade XGBoost to 1.6.1
Change-Id: Id6a6cc911e4a382ccaa94a962d89fad6208c48fc
> [xgb] Add GPU support for XGBoost

- api/src/main/java/ai/djl/util/Utils.java
> Follow symlinks when loading models.

- api/build.gradle
- api/src/test/java/ai/djl/repository/DjlRepositoryTest.java
- basicdataset/build.gradle
- extensions/aws-ai/build.gradle
- extensions/aws-ai/src/test/java/ai/djl/aws/s3/S3RepositoryTest.java
Change-Id: Ib490eb8c4e026a3c4dee94d76700b1e9744812f8
> [pytorch] Uses pytorch to test API and aws-ai module

- engines/ml/xgboost/build.gradle
Change-Id: I35a5b5cf91cda9095369f35b7b609a78070b50b3
> [xgb] Avoid download cudf dependency at build time
