api/src/main/java/ai/djl/nn/Blocks.java

It seems that the documentation of the `batchFlatten` method in class `Blocks`, [at this URL](https://github.com/awslabs/djl/blob/fadf64824036d9c570c7a98a559f92989639f47a/api/src/main/java/ai/djl/nn/Blocks.java#L38), is not correct. Normally one deals with "flattening" a data structure when converting it from multi-dimensional to one-dimensional. If I have well understood the purpose of this method, the input is a a flattened (1-D array) and one wants to "inflate" it to get a (batch, size)-shape array, i.e. to batch a flattened batch of inputs that comes in the form of a 1-D array. The original description of this method seemed misleading.  Also, term "singleton" was confusing, I simply replaced it by "1-D array". 
- For …

Correction/clarification of the doc of batchFlatten

---

api/src/main/java/ai/djl/training/DefaultTrainingConfig.java

It seems that the `DefaultTrainingConfig`'s constructor, [at this URL](https://github.com/awslabs/djl/blob/03794b71c83b3e1292546c7d3ea942fb839506ce/api/src/main/java/ai/djl/training/DefaultTrainingConfig.java#L45), has changed, it takes now solely a `Loss` object as argument, and not an `Initializer` anymore. I have therefore changed and improved its documentation to comply with its new version.

Documentation of DefaultTrainingConfig outdated

---

model-uploader/src/main/java/ai/djl/uploader/MetadataBuilder.java
model-uploader/src/test/java/ai/djl/uploader/LocalTest.java
model-uploader/src/test/java/ai/djl/uploader/RemoteTest.java
model-uploader/src/test/java/ai/djl/uploader/util/TestUtils.java

This PR brings some tests for remote merge functionalites of `MetadataBuilder`.

add remote tests for model uploader

---

api/src/main/java/ai/djl/nn/convolutional/Conv1D.java
api/src/main/java/ai/djl/nn/convolutional/Conv2D.java
api/src/main/java/ai/djl/nn/convolutional/Conv3D.java
api/src/main/java/ai/djl/nn/convolutional/Convolution.java
api/src/main/java/ai/djl/nn/norm/BatchNorm.java
api/src/main/java/ai/djl/nn/norm/Dropout.java

Fixes some of #44 and contains improved documentation on the following classes:
- For `Conv1D`, `Conv2D`, and `Conv3D`, I was quite unsure of what else to include since these three share common operations as specified in `Convolution` class, so if anything is missing please let me know so the missing aspects can be obtained.
- `Dropout` has different …

Improve docs

---

api/src/main/java/ai/djl/modality/nlp/preprocess/HyphenNormalizer.java
api/src/main/java/ai/djl/modality/nlp/preprocess/UnicodeNormalizer.java
api/src/test/java/ai/djl/modality/nlp/preprocess/HyphenNormalizerTest.java
api/src/test/java/ai/djl/modality/nlp/preprocess/UnicodeNormalizerTest.java

This is PR contains two TextProcessors for NLP preprocessing. One does Unicode normalization which is necessary especially when working in non-English languages (e.g. German). The other implements functionality not done by normal unicode normalization and also normalizes hyphens. An exotic task, but necessary when e.g. processing HTML text or text that comes from an OCR engine.
- [x ] Changes are complete (i.e. I finished coding on this PR)
- [ x] All changes have test coverage:
- [ x] Code is well-documented: 
- [ x] To the my best knowledge, [examples](https://github.com/awslabs/djl/tree/master/examples) and [jupyter …

Some simple Unicode preprocessing

---

api/src/main/java/ai/djl/nn/ParallelBlock.java
api/src/main/java/ai/djl/nn/SequentialBlock.java

So I found an issue with the string formatting of nested block structures when printing it to console. My laptop is not able to handle the load of some of the tests so I couldn't test the whole suite
Here's an example with Resnet18 block:
Left: new Right: old
- Properly indent nested blocks

Fix toString formatting of nested Parallel/Sequential Block

---

api/src/main/java/ai/djl/training/listener/EvaluatorTrainingListener.java

Addition: 
- When performing EasyTrain.fit() and gathering the validation epoch metrics, the number of occurrences of a particular evaluator collected are more than the number of epochs run. This change fixes the bug in the EvaluatorTrainingListener class.

Fixing Validation Epoch Result bug.

---

examples/docs/object_detection_with_tensorflow_saved_model.md
examples/src/main/java/ai/djl/examples/inference/ObjectDetectionWithTensorflowSavedModel.java
examples/src/test/java/ai/djl/examples/inference/ObjectDetectionWithTensorflowSavedModelTest.java

Added a simple example to use DJL to perform object detection using models trained in Tensorflow and exported to SavedModel format. The example includes a custom translator to correctly load models from the [TensorFlow 2 Detection Model Zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md) 
- For new examples, [README.md](https://github.com/uniquetrij/djl/blob/master/examples/docs/object_detection_with_tensorflow_saved_model.md) is added to explain what the example does.

Added Example for Object Detection using Trained Tensorflow Models (SavedModel Format) 

---

serving/src/main/java/ai/djl/serving/Arguments.java
serving/src/main/java/ai/djl/serving/util/ConfigManager.java
serving/src/main/javadoc/overview.html
tools/gradle/publish.gradle

Change-Id: Ia748d6a0db8315d092691f33c3c570993b5b581a
- Load config.properties by default from current working folder
- publish serving package to maven

Load config.properties from current folder by default

---

api/src/main/java/ai/djl/util/cuda/CudaUtils.java

On windows the env variable `CUDA_PATH` is always set by the cuda installer. I think the better default behavior is to search that path first before looking into other paths. 
- Added CUDA_PATH to `CudaUtils.loadLibrary()` search

Add CUDA_PATH env variable to windows cuda loader

---

api/src/main/java/ai/djl/training/dataset/RandomAccessDataset.java
basicdataset/src/test/java/ai/djl/basicdataset/ImageFolderTest.java

Fix issue #201, set limit to MAX_VALUE for SubDataset

---

.github/workflows/docs.yml

In the most recent mknotebook version upgrade, the nbconvert 6.0.1 is supported.

remove version limitation

---

.github/workflows/docs.yml
docs/mkdocs.yml

Current mknotebooks build is broken, just fix the version for now until we managed to fix this: https://github.com/greenape/mknotebooks/issues/90

rollback mknotebooks version

---

integration/src/main/java/ai/djl/integration/IntegrationTest.java

Suppress UnsupportedOperationException stacktrace in integration test

---

pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java
pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/LibUtilsTest.java
pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/MkldnnTest.java
pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/ProfilerTest.java
pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/package-info.java
pytorch/pytorch-native/src/main/java/ai/djl/pytorch/jni/NativeHelper.java
pytorch/pytorch-native/src/main/java/ai/djl/pytorch/jni/package-info.java

Workaround #179, allow load shared library from different ClassLoader

---

api/src/main/java/ai/djl/ndarray/index/NDIndex.java

Fix typo in NDIndex javadoc

---

examples/src/main/java/ai/djl/examples/inference/benchmark/MultithreadedBenchmark.java
examples/src/main/java/ai/djl/examples/inference/benchmark/util/Arguments.java

Add delay thread execution to multithreaded benchmark.

---

mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/jna/FunctionInfo.java
mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/jna/JnaUtils.java

Use MXImperativeInvoke instead of MXImperativeInvokeEx

---

api/src/main/java/ai/djl/modality/cv/translator/YoloV5Translator.java

adds support for YoloV5 object detection models via ONNX
added YoloV5Translator with following features: input squeezer, output parser and non max suppression boxes
YoloV5 supports at least two output formats, to use models here it is important to specify model.model[-1].export = False  in export.py.
An ONNX export can be done like this: https://github.com/ultralytics/yolov5/issues/251
```
final YoloV5Translator translator = new YoloV5Translator(YoloV5Translator.builder().optSynsetArtifactName("synset.txt"));
Criteria<Image, DetectedObjects> criteria = Criteria.builder()
.setTypes(Image.class, DetectedObjects.class) // defines input and output data type
.optDevice(Device.cpu())
.optTranslator(translator)
.optModelUrls("file:///path-to-model/") // search models in specified path …
```

YoloV5 inference support of ONNX models

---

api/src/main/java/ai/djl/training/dataset/Batch.java
api/src/main/java/ai/djl/training/dataset/DataIterable.java
basicdataset/src/test/java/ai/djl/basicdataset/DatasetUtilsTest.java
integration/src/main/java/ai/djl/integration/tests/model_zoo/classification/AlexNetTest.java
integration/src/main/java/ai/djl/integration/tests/model_zoo/classification/GoogLeNetTest.java
integration/src/main/java/ai/djl/integration/tests/model_zoo/classification/LeNetTest.java
integration/src/main/java/ai/djl/integration/tests/model_zoo/classification/NiNTest.java
integration/src/main/java/ai/djl/integration/tests/model_zoo/classification/ResnetTest.java
integration/src/main/java/ai/djl/integration/tests/model_zoo/classification/SqueezenetTest.java
integration/src/main/java/ai/djl/integration/tests/model_zoo/classification/VGGTest.java
integration/src/main/java/ai/djl/integration/tests/training/OptimizerTest.java
mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java

Fix DataIterable memory leak

---

examples/README.md
examples/build.gradle
integration/build.gradle
onnxruntime/onnxruntime-engine/build.gradle
pytorch/pytorch-engine/README.md
pytorch/pytorch-engine/build.gradle
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtEngine.java

bump up pytorch instruction to 1.7.0
Note: PyTorch 1.7.0 only works on 0.9.0-SNAPSHOT and official 0.9.0. So there is no changes to examples until we release 0.9.0

bump up pytorch version

---

api/src/main/java/ai/djl/nn/AbstractBlock.java

Not override inputShapes if initialized

---

pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtEngine.java
tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfEngine.java

Make Engine.setRandomSeed() consistent across engines

---

android/pytorch-native/build.gradle
extensions/fasttext/build.gradle
extensions/sentencepiece/build.gradle
mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/jna/LibUtils.java
mxnet/native/build.gradle
pytorch/pytorch-engine/build.gradle
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java
pytorch/pytorch-native/build.gradle
pytorch/pytorch-native/build_android.sh
tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/LibUtils.java
tensorflow/tensorflow-native/build.gradle

Replace native download url to cloudfront url

---

api/src/main/java/ai/djl/training/evaluator/TopKAccuracy.java
integration/src/main/java/ai/djl/integration/tests/training/EvaluatorTest.java

In TopKAccuracy, pred and label could accept data type both int32 and int64.

TopKAccuracy accepts both int32 and int64 for pred and label

---

pytorch/pytorch-engine/README.md

Revert pytorch engine document to use 1.6.0

---

.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

The templates right now are quite long and may deter potential contributors. I
think we can remove much of the content without detracting from the meaningful
information we expect to be conveyed.

Simplify the PR and feature request templates

---

jupyter/BERTQA.ipynb
jupyter/load_pytorch_model.ipynb
jupyter/onnxruntime/machine_learning_with_ONNXRuntime.ipynb
jupyter/pytorch/load_your_own_pytorch_bert.ipynb
pytorch/pytorch-engine/README.md

Update jupyter notebook to use pytorch 1.7.0

---

pytorch/pytorch-engine/build.gradle

[PyTorch] Correct the precxx jni download path

---

jupyter/paddlepaddle/face_mask_detection_paddlepaddle.ipynb

[paddle] Update jupyter notebook to 0.10.0-SNAPSHOT version

---

api/src/main/java/ai/djl/nn/AbstractSymbolBlock.java
api/src/main/java/ai/djl/nn/SymbolBlock.java
api/src/main/java/ai/djl/util/NativeResource.java
dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrSymbolBlock.java
mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxSymbolBlock.java
onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtSymbolBlock.java
paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpSymbolBlock.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtSymbolBlock.java
tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfModel.java
tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfSymbolBlock.java
tflite/tflite-engine/src/main/java/ai/djl/tflite/engine/TfLiteModel.java
tflite/tflite-engine/src/main/java/ai/djl/tflite/engine/TfLiteSymbolBlock.java

Reafactor SymbolBlock with AbstractSymbolBlock

---

mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/jna/LibUtils.java

By default, JNA will load in RTLD_GLOBAL on Linux. This change wil make it to RTLD_LOCAL, which means its loaded native binaries will have no impact to the other packages loaded.

Making MXNet load on linux under RTLD_LOCAL

---

paddlepaddle/paddlepaddle-native/CMakeLists.txt

Current rpath settings in paddlepaddle are absolute paths. This will make the jni not usable if we build from one place and use it in different places. This changes follows the modification we did on pytorch to add the rpath to Paddle JNI.

[Paddle] fix linux rpath issue

---

.github/workflows/native_jni_s3_pytorch_android.yml
.github/workflows/native_release_pytorch_android.yml
.github/workflows/native_s3_pytorch_android.yml
.github/workflows/nightly.yml

PyTorch Android native build only works on NDK version 20.
Action uses version 22 by default.

Use custom NDK version instead of action default NDK

---

.github/workflows/nightly.yml
.github/workflows/snapshot_pytorch_android.yml

We should use separate pipeline to publish android snapshot as the action here didn't really recompile the JNI

Remove snapshot PyTorch Android build from nightly

---

basicdataset/src/main/java/ai/djl/basicdataset/cv/classification/ImageClassificationDataset.java
djl-zero/src/main/java/ai/djl/zero/cv/ImageClassification.java

This pattern builds translators that match the behavior of a dataset. It works
best inside the abstract datasets that represent an Application.

Start dataset.makeTranslator pattern

---

api/src/main/java/ai/djl/ndarray/NDArray.java
dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrNDArray.java
mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtNDArray.java
paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpNDArray.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
tflite/tflite-engine/src/main/java/ai/djl/tflite/engine/TfLiteNDArray.java

Add NDArray stopGradient and scaleGradient

---

docs/development/setup.md

Updated command in documentation to install adoptopenjdk8 since previous one was deprecated and disabled on the latest brew release.
More info:
https://github.com/Homebrew/discussions/discussions/340#discussioncomment-232364

Docs: Updated 'brew install' command for adoptopenjdk8

---

api/src/main/java/ai/djl/ndarray/index/full/NDIndexFullSlice.java
integration/src/main/java/ai/djl/integration/tests/ndarray/NDIndexTest.java

When slicing an NDArray, the result shape should be the ceiling rather than the
floor of the shapes. Or, even if the shape can't be perfectly divided then it
should take the additional value.
fixes #383

Fix NDArray slice size

---

api/src/main/java/ai/djl/nn/recurrent/LSTM.java
api/src/main/java/ai/djl/nn/recurrent/RecurrentBlock.java

1. Recurrent block implementation has a memory leak in `opInputs(...)` function, line 240:
`parameterList.add(array.flatten());`
`array.flatten()` is creating new array in model's NDManager, thus this array lives as long as the model. The analogical problem is also present in LSTM block.
2. Recurrent block's `getOutputShapes(...)` function returns incorrect shapes. Block accepts NTC not TNC (which is wrongly assumed as input shape in `getOutputShapes(...)` function).

Fix recurrent block memory leak and output shape calculation

---

api/src/main/java/ai/djl/ndarray/NDArray.java

Replaced `minimum` for `sum` in the `sum` method api documentation.

Fixing typo on doc for NDArray.java

---

api/src/main/java/ai/djl/training/listener/SaveModelTrainingListener.java
examples/src/main/java/ai/djl/examples/training/TrainCaptcha.java
examples/src/main/java/ai/djl/examples/training/TrainMnist.java
examples/src/main/java/ai/djl/examples/training/TrainMnistWithLSTM.java
examples/src/main/java/ai/djl/examples/training/TrainPikachu.java
examples/src/main/java/ai/djl/examples/training/TrainSentimentAnalysis.java
examples/src/main/java/ai/djl/examples/training/TrainSeq2Seq.java
examples/src/main/java/ai/djl/examples/training/TrainWithHpo.java
examples/src/main/java/ai/djl/examples/training/TrainWithOptimizers.java
examples/src/main/java/ai/djl/examples/training/transferlearning/TrainAmazonReviewRanking.java
jupyter/rank_classification_using_BERT_on_Amazon_Review.ipynb

This better clarifies the purpose of the training listener as the default is not
to have checkpoints. Instead, the checkpointing is an optional feature of the
SaveModel listener.

Rename CheckpointsTrainingListener to SaveModelTrainingListener

---

api/src/main/java/ai/djl/modality/nlp/Decoder.java
api/src/main/java/ai/djl/modality/nlp/EncoderDecoder.java
api/src/main/java/ai/djl/ndarray/internal/NDArrayEx.java
api/src/main/java/ai/djl/ndarray/types/Shape.java
api/src/main/java/ai/djl/nn/recurrent/GRU.java
api/src/main/java/ai/djl/nn/recurrent/LSTM.java
api/src/main/java/ai/djl/nn/recurrent/RNN.java
api/src/main/java/ai/djl/nn/recurrent/RecurrentBlock.java
api/src/main/native/djl/utils.h
examples/src/main/java/ai/djl/examples/training/TrainMnistWithLSTM.java
examples/src/main/java/ai/djl/examples/training/TrainSentimentAnalysis.java
examples/src/main/java/ai/djl/examples/training/TrainSeq2Seq.java
integration/src/main/java/ai/djl/integration/tests/modality/nlp/SimpleTextEncoderTest.java
integration/src/main/java/ai/djl/integration/tests/nn/BlockCoreTest.java
model-zoo/src/main/java/ai/djl/basicmodelzoo/nlp/SimpleTextDecoder.java
model-zoo/src/main/java/ai/djl/basicmodelzoo/nlp/SimpleTextEncoder.java
mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArrayEx.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArrayEx.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_nn_functional.cc
tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArrayEx.java

Make RNN op generic

---

.github/workflows/native_s3_tflite.yml

Accidentally removed the `//` before build flags. 
Now test build pass on Ubuntu 16.04 and Mac OS with tflite 2.4.1
```
INFO: Analyzed 2 targets (242 packages loaded, 19609 targets configured).
INFO: Found 2 targets...
INFO: Elapsed time: 1550.101s, Critical Path: 148.79s
INFO: 8086 processes: 8086 local.
INFO: Build completed successfully, 8444 total actions
```

fix tflite build flag

---

api/src/main/java/ai/djl/modality/cv/BufferedImageFactory.java
api/src/main/java/ai/djl/modality/cv/util/NDImageUtils.java
paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpModel.java
paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpNDArray.java
paddlepaddle/paddlepaddle-model-zoo/src/test/java/ai/djl/paddlepaddle/zoo/BoundFinder.java
paddlepaddle/paddlepaddle-model-zoo/src/test/java/ai/djl/paddlepaddle/zoo/OCRTest.java

This PR used three models to run the OCR task
- detection: find the word blocks
- direction: find the direction of the words
- recognition: recognize the words inside

Add DJL Paddle OCR Example

---

central/src/main/webapp/components/ModelView.jsx

This Pr is to close the issue with the ModelView page failing when a model has a null attribute. It utilizes error handling on the front end to simply display a more information to the user.
Fix:
fix #596

Fixing model view bugs

---

api/src/main/java/ai/djl/training/listener/MemoryTrainingListener.java
examples/src/main/java/ai/djl/examples/inference/benchmark/MultithreadedBenchmark.java
examples/src/main/java/ai/djl/examples/inference/benchmark/util/AbstractBenchmark.java

* Collects used memory instead of committed for the JVM. The committed memory amount is [guaranteed](https://docs.oracle.com/javase/7/docs/api/java/lang/management/MemoryUsage.html) to be available to the JVM and not the currently used amount.
* Runs memory collection on a separate thread. Memory collection can be slow compared to inference which significantly affects the throughput measurement of the first worker thread.
* Collects memory before and after model loading to print separate base, model, and inference memory usage.

Various fixes and improvements for MultiThreadedBenchmark

---

api/src/main/java/ai/djl/repository/zoo/BaseModelLoader.java

This will list the input and output classes when trying to find a model in the
model zoo. It works either when no classes are specified or invalid classes are
specified. This will help users who don't know what the possible classes are to
resolve the question without looking at the code.

List input and output classes in ModelZoo lookup

---

pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_tensor.cc

Use PyTorch index to improve the performance

---

api/src/main/java/ai/djl/training/loss/SoftmaxCrossEntropyLoss.java
integration/src/main/java/ai/djl/integration/tests/nn/BlockCoreTest.java
integration/src/main/java/ai/djl/integration/tests/training/LossTest.java

fix softmax flag behavior

---

api/src/main/java/ai/djl/engine/Engine.java
docs/engine.md
docs/mkdocs.yml
docs/quick_start.md
website/demo.html

Explains what an engine is, what engines we support, and default engines.
This includes a few miscellaneous doc fixes.

Add guide to engines

---

api/src/main/java/ai/djl/util/Platform.java
mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/jna/JnaUtils.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/TorchScriptTest.java
pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_inference.cc
pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_nn_functional.cc
pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_system.cc
pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_tensor.cc

This PR will cover several major components to allow DJL to load/save parameter smoothly. Now you can do InputStream/OutputStream to Pytorch model.
Stages
- Stage 1: Create saving functions for MXNet and PyTorch [Done]
- Stage 2: Make model saving and loading all in one file [In next PR]
Here is the plan:
Assume you have a block architecture like this:
```
SequentialBlock
SymbolBlock
SequentialBlock
```
What we will do to save is adding SymbolBlocks original Artifacts (e.g MXNet symbol params, PyTorch .pt TorchScript) into the `.params` file we generate. It will make the whole thing like a zip.
So, in the end, we will expect to have `block.params` standalone file.
To load all of them back. Instead of the current detour way to load Symbolic model first and replace all the content later, we …

DJL parameter saving

---

api/src/main/java/ai/djl/ndarray/NDArray.java
api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
api/src/main/java/ai/djl/nn/transformer/BertMaskedLanguageModelLoss.java
api/src/main/java/ai/djl/nn/transformer/BertNextSentenceLoss.java
api/src/main/java/ai/djl/nn/transformer/MissingOps.java
integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayOtherOpTest.java
mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java

Adding the one hot operator. This is similar to https://mxnet.apache.org/versions/1.6/api/r/docs/api/mx.nd.one.hot.html
- Implemented using MXNet and Tensorflow engine.

Adding one hot operator

---

api/src/main/java/ai/djl/modality/nlp/EncoderDecoder.java
api/src/main/java/ai/djl/nn/AbstractBlock.java
api/src/main/java/ai/djl/nn/Block.java
api/src/main/java/ai/djl/nn/Parameter.java
api/src/main/java/ai/djl/nn/SequentialBlock.java
api/src/main/java/ai/djl/nn/convolutional/Convolution.java
api/src/main/java/ai/djl/nn/convolutional/Deconvolution.java
api/src/main/java/ai/djl/nn/core/Embedding.java
api/src/main/java/ai/djl/nn/core/Linear.java
api/src/main/java/ai/djl/nn/core/Prelu.java
api/src/main/java/ai/djl/nn/norm/BatchNorm.java
api/src/main/java/ai/djl/nn/recurrent/RecurrentBlock.java
api/src/main/java/ai/djl/nn/transformer/BertBlock.java
api/src/main/java/ai/djl/nn/transformer/BertMaskedLanguageModelBlock.java
api/src/main/java/ai/djl/nn/transformer/BertPretrainingBlock.java
api/src/main/java/ai/djl/nn/transformer/IdEmbedding.java
api/src/main/java/ai/djl/nn/transformer/PointwiseFeedForwardBlock.java
model-zoo/src/main/java/ai/djl/basicmodelzoo/cv/object_detection/ssd/SingleShotDetection.java
mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxSymbolBlock.java
tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfSymbolBlock.java

Refactor the way to build the block. Reference: [TensorFlow](https://www.tensorflow.org/tutorials/customization/custom_layers)
1. Replace the shape callback with setShape which is more intuitive
2. remove the output of initialize to reduce users' responsibility
3. Ideally to implement a custom block, we should only ask user to implement 1. ctor 2. forwardInternal 3. prepare 
To split the PR into smaller PRs, now we still leverage getOutputs. I will address this in next PR

Refactor initialize method

---

examples/src/main/java/ai/djl/examples/training/TrainBertOnCode.java
examples/src/main/java/ai/djl/examples/training/TrainCaptcha.java
examples/src/main/java/ai/djl/examples/training/TrainMnist.java
examples/src/main/java/ai/djl/examples/training/TrainMnistWithLSTM.java
examples/src/main/java/ai/djl/examples/training/TrainPikachu.java
examples/src/main/java/ai/djl/examples/training/TrainSentimentAnalysis.java
examples/src/main/java/ai/djl/examples/training/TrainSeq2Seq.java
examples/src/main/java/ai/djl/examples/training/TrainTicTacToe.java
examples/src/main/java/ai/djl/examples/training/TrainWithHpo.java
examples/src/main/java/ai/djl/examples/training/TrainWithOptimizers.java
examples/src/main/java/ai/djl/examples/training/transferlearning/TrainAmazonReviewRanking.java
examples/src/main/java/ai/djl/examples/training/transferlearning/TrainResnetWithCifar10.java
examples/src/main/java/ai/djl/examples/training/util/Arguments.java
examples/src/test/java/ai/djl/examples/training/TrainBertTest.java

- Add TrainBertTest
- Add try-with-resources to model and trainer
- Add progress when creating batches
- Use arguments in BERT
- Add missing training listener notifications
Also updated:
- Make example train Arguments class inheritable to update both default values
and number of options. Before, defaults were not modifiable and it was more
difficult to use derivative arguments.

Update BERT example

---

integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayOtherOpTest.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_torch_reduction.cc

Added norm operator to PtNDArray and PyTorch.

Adding norm operator to PyTorch

---

pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java

One of the enhancements in 0.10.0 was "Adds the NDArray stopGradient and scaleGradient functions (#548)".
It works great on MXNet. Thanks for the feature. 
To benefit from one of the 0.10.0 key features "Upgrades PyTorch to 1.7.1" I wired up the stopGradient for PyTorch which makes up the line of change in this pull request.
It works for me ... I have tested it with 
```
@Test
void testStopGradient() {
try (NDManager manager = NDManager.newBaseManager()) {
NDArray x = manager.create(new float[] {1.0f}, new Shape(1));
x.attachGradient();
try (GradientCollector gc = Engine.getInstance().newGradientCollector()) {
NDArray y = x.mul(x);
gc.backward(y);
NDArray grad = x.getGradient();
System.out.println("grad: " + grad);
assertEquals(2f, grad.getFloat(0));
}
x = manager.create(new float[] …
```

stopGradient on PyTorch

---

integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayOtherOpTest.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java

Adding a test to "stopGradient on PyTorch (#708)"

stopGradient Test added

---

pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_torch_isjm.cc

Added nonzero operator for PyTorch. Added a Scalar check in JniUtils as PyTorch behaves differently in comparison to MXNet when passed a scalar value for nonzero operator.

Non zero operator for PyTorch

---

extensions/aws-ai/src/main/java/ai/djl/aws/sagemaker/SageMaker.java
extensions/aws-ai/src/test/java/ai/djl/aws/sagemaker/SageMakerTest.java

We want to re-use model name in case if user doesn't specify the endpoint and endpointconfig name. 

Minor fix in SageMaker SDK

---

api/src/main/java/ai/djl/engine/Engine.java
api/src/main/java/ai/djl/nn/BlockFactory.java
api/src/main/java/ai/djl/nn/SymbolBlock.java
dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrEngine.java
integration/src/main/java/ai/djl/integration/tests/nn/BlockFactoryTest.java
mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxEngine.java
mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxSymbolBlock.java
onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtEngine.java
paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpEngine.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtEngine.java
tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfEngine.java
tflite/tflite-engine/src/main/java/ai/djl/tflite/engine/TfLiteEngine.java

The block factory is a class that provides easy access to recover DJL based model for inference with DJLServing. It contains a single function `getBlock()`  and essentially just recover the block.
Apart from that, there is a new `SymbolBlock.newInstance()` method that only create a empty SymbolBlock holder. It can now be used in PyTorch and MXNet to recover the Symbolic model information from combined params file. In this case, we no longer needs to load the SymbolBlock from the model, instead, everything is loaded from 1 file.

DJL BlockFactory

---

api/src/main/java/ai/djl/training/listener/MemoryTrainingListener.java
api/src/main/java/ai/djl/training/listener/SaveModelTrainingListener.java

Added javadoc and relevant links for TrainingListeners

[DOCS] Fixing TrainingListener documentation

---

docs/development/profiler.md
docs/mkdocs.yml

Add profiler doc

---

docs/mkdocs.yml
docs/mxnet/mxnet_backend_optimizer.md
mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxEngine.java

Add EI documentation for MXNet

add EI documentation

---

api/src/main/java/ai/djl/Application.java
jupyter/onnxruntime/machine_learning_with_ONNXRuntime.ipynb
onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/zoo/OrtModelZoo.java
onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/zoo/tabular/softmax_regression/IrisClassificationModelLoader.java
onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/zoo/tabular/softmax_regression/IrisFlower.java
onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/zoo/tabular/softmax_regression/package-info.java
onnxruntime/onnxruntime-engine/src/test/java/ai/djl/onnxruntime/engine/OrtTest.java
onnxruntime/onnxruntime-engine/src/test/resources/mlrepo/model/tabular/softmax_regression/ai/djl/onnxruntime/iris_flowers/metadata.json

The application in the only place used was changed to the more accurate softmax_regression (matching
the terminology from the D2L book).

Remove erroneous random forest application

---

api/src/main/java/ai/djl/ndarray/NDArrays.java
integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayShapesManipulationOpTest.java

Fix one array case for concat

---

tensorflow/tensorflow-engine/build.gradle
tensorflow/tensorflow-engine/src/test/java/ai/djl/tensorflow/integration/TfCoverageTest.java
tensorflow/tensorflow-engine/src/test/java/ai/djl/tensorflow/integration/package-info.java
tools/gradle/jacoco.gradle

Add PyTorch and TensorFlow back to Jacoco report

remove exclusion for pytorch and tf from jacoco

---

tensorflow/tensorflow-native/build.gradle

Upgrade TensorFlow native to 2.4.1

---

examples/src/main/java/ai/djl/examples/training/TrainSentimentAnalysis.java

We do the double embedding (one in the model for training, the other in the Translator for prediction).
The PR removes the embedding part in Translator and just convert the token to indices without duplicate embedding

Fix LSTM nightly build failure

---

.github/workflows/continuous.yml
.github/workflows/docs.yml

Remove Github Actions jobs that require tokens for forked repositories. Currently forked repositories run Github Actions but always fail. In addition, docs is ran on a cron job so every week the forked repositories receive an failure build.

Remove Github Actions jobs that require tokens for forks

---

serving/src/main/java/ai/djl/serving/util/Connector.java

Fix TCP port range

---

api/src/main/java/ai/djl/ndarray/NDArray.java
api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
api/src/main/java/ai/djl/ndarray/index/NDArrayIndexer.java
integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayOtherOpTest.java
mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArrayEx.java
mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArrayIndexer.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArrayIndexer.java

Boolean set method for DJL use cases. Also added TF where method.
This PR also introduced the NDArray.intern(): This method aimed to inplace change the reference of NDArray and kill the old reference owner. Typically useful if user would like to reduce object creation in Java.

add boolean set method to DJL

---

paddlepaddle/paddlepaddle-model-zoo/src/main/java/ai/djl/paddlepaddle/zoo/cv/wordrecognition/PpWordRecognitionTranslator.java

The word recognition OCR model from PaddlePaddle require height to be fixed 32 or an error will be thrown.

fix paddleOCR size issue

---

api/src/main/java/ai/djl/training/loss/ElasticNetWeightDecay.java
api/src/main/java/ai/djl/training/loss/L1WeightDecay.java
api/src/main/java/ai/djl/training/loss/L2WeightDecay.java
api/src/main/java/ai/djl/training/loss/Loss.java
integration/src/main/java/ai/djl/integration/tests/training/WeightDecayTest.java

As per the discussion [here](https://github.com/awslabs/djl/discussions/769) I have:
* Added class for weigh decay: `L1WeightDecay`, `L2WeightDecay` and `ElasticNetWeightDecay`
* Added a test class `WeightDecayTest` with 3 tests (one for each class above)
All tests are in the loss package. Don't think this interferes with anything else in the project. I also did not find additional tests using `SimpleCompositeLoss` so I did not add these.

Regularization: adding weight decay to Loss

---

api/src/main/java/ai/djl/engine/Engine.java
integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayElementArithmeticOpTest.java
mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxEngine.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtEngine.java
tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/SavedModelBundle.java
tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfEngine.java
tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArrayEx.java
tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDManager.java
tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfOpExecutor.java
tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfSymbolBlock.java
tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/javacpp/JavacppUtils.java
tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/javacpp/LibUtils.java
tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/javacpp/package-info.java
testing/src/main/java/ai/djl/testing/Assertions.java

1. move the EagerSession to engine level
2. add operators back
3. use cached input metatdata so we don't do session feed and fetch on every inference but only on the first one
4. TfOpExecutor requires users to specify the # of outputs (99% op have only 1 ouput and the rest should be easy to infer the # output from the operator & parameters itself) for better memory usage & potential performance gain

Improve TensorFlow new architecture refactoring

---

docs/paddlepaddle/how_to_create_paddlepaddle_model.md

update the method of getting inference model from paddle hub

update the method of getting inference model from paddle hub

---

api/src/test/java/ai/djl/nn/convolutional/Conv1dTest.java
api/src/test/java/ai/djl/nn/convolutional/Conv1dTransposeTest.java
api/src/test/java/ai/djl/nn/convolutional/Conv2dTest.java
api/src/test/java/ai/djl/nn/convolutional/Conv2dTransposeTest.java
api/src/test/java/ai/djl/nn/convolutional/Conv3dTest.java

Currently, the convolution testing tests with a range of inputs across a number
of variables. This increases the test duration a bit much for the standard unit
test suite.
Instead, I reduce down to only two tests for unit testing. During nightly, the
full combination of ranges will be used.

Reduce the Conv testing during normal run

---

mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java

Fixing #802 . I received response from MXNet team that indeed this was just a typo. We can see the check that throws error only if n=1 here https://github.com/apache/incubator-mxnet/blob/master/src/operator/sequence_reverse-inl.h#L235

Fixing SequenceMask bug related to Issue #802

---

api/src/main/java/ai/djl/ndarray/BaseNDManager.java
api/src/main/java/ai/djl/nn/transformer/PointwiseFeedForwardBlock.java
mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDManager.java

fixes #763
This first fixes the PointwiseFeedForwardBlock and simplifies it by having it
extend the SequentialBlock.
Then, it fixes an issue with the NDManager when a resource that was tempAttached
is then tempAttached again. So, the resource moves from managers A -> B -> C. It
was attached in A, got tempAttached to B, then tempAttached to C. When C was
closed, the resource was normal attached in B so it was closed too early. This
PR makes B remember detached temp resources, so even when it is returned from C
to B, B still knows that it should be tempAttached to return to A.

Fixes TrainBertOnCode and temp attach chains

---

api/src/main/java/ai/djl/BaseModel.java
api/src/main/java/ai/djl/util/ClassLoaderUtils.java
api/src/main/java/ai/djl/util/Utils.java
integration/src/main/java/ai/djl/integration/tests/nn/BlockFactoryTest.java
mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxModel.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtModel.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtSymbolBlock.java

Support BlockFactory searching and loading in the current Model directory. This method should work on:
```
factory.class
my_fancy_jar.jar
```
We will scan through this and figure out if there is a class implements BlockFactory.

add finding BlockFactory feature in model loading

---

api/src/main/java/ai/djl/engine/Engine.java
api/src/main/java/ai/djl/engine/EngineProvider.java
dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrEngine.java
dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrEngineProvider.java
mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxEngine.java
mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxEngineProvider.java
onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtEngine.java
onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtEngineProvider.java
paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpEngine.java
paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpEngineProvider.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtEngine.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtEngineProvider.java
tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfEngine.java
tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfEngineProvider.java
tflite/tflite-engine/src/main/java/ai/djl/tflite/engine/TfLiteEngine.java
tflite/tflite-engine/src/main/java/ai/djl/tflite/engine/TfLiteEngineProvider.java
tools/conf/findbugs-exclude.xml

In current implementation, all the engines are initialized at the beginning. This behavior isn't ideal when multiple engine jar files are included in the project. Some project may not need all the engines at runtime. This change provide flexibility that allows a project include all the jars in the class and only load required engine when needed.

Defer engine initialization

---

examples/src/main/java/ai/djl/examples/training/TrainBertOnCode.java
examples/src/main/java/ai/djl/examples/training/util/BertCodeDataset.java
examples/src/test/java/ai/djl/examples/training/TrainBertTest.java

Before, the example managed the data in a more ad-hoc fashion. While it still is
not a random access dataset, using the Dataset interface at least allows it to
integrate with EasyTrain.
This mostly splits the existing Dataset management code into the new
BertCodeDataset. The BertCodeDataset was not changed too much from it's original
design. Some simple cleanups were made to the remaining code in the
TrainBertOnCode example.

Converts Bert example to use Dataset class

---

dlr/dlr-engine/build.gradle
examples/build.gradle
integration/build.gradle
ml/xgboost/build.gradle
onnxruntime/onnxruntime-engine/build.gradle
paddlepaddle/paddlepaddle-model-zoo/build.gradle
pytorch/pytorch-engine/build.gradle

[pytorch] Use 1.8.1 release version of pytorch native

---

api/src/main/java/ai/djl/ndarray/BaseNDManager.java

Close temp resource properly

---

docs/development/inference_performance_optimization.md

Adds information about graph executor optimization and how to disable it. It also outlines to upsides and downsides of disabling it as well as considerations when using multiple threads for inference on GPU.

Added docs for disabling graph executor optimization via JNI for torchscript.

---

extensions/sentencepiece/build.gradle

Currently, we will download from the S3 and use that to upload. It is not performing correctly and just make the shared library not updating.

[SP] avoid uploading cached shared library

---

api/src/main/java/ai/djl/ndarray/NDArray.java
api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayOtherOpTest.java
mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_tensor.cc
tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java

Introducing a new `NDArray::set` API that overrides the shape and relaxing the size check to allow the use of larger buffers.
The use case is a high-throughput inference service that needs to support variable batch sizes. This change will reduce the number of memory allocations by allowing the reuse of the buffer and `NDArray` between inference calls.
Limitation:
* The new set API is only implemented for PyTorch

[PyTorch] Set and override shape API for NDArray

---

api/src/main/java/ai/djl/modality/cv/BufferedImageFactory.java

Match OpenCV to grayscale algorithm, #964

---

android/build.gradle
build.gradle

jcenter() is deprecated, using mavenCentral

---

gradlew

Fix gradlew in case JAVA_HOME is not set

---

serving/serving/src/main/java/ai/djl/serving/ModelServer.java
serving/serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
serving/serving/src/main/java/ai/djl/serving/http/ManagementRequestHandler.java
serving/serving/src/main/java/ai/djl/serving/wlm/ModelManager.java

[serving] allow load model with specified engine

---

api/src/main/java/ai/djl/BaseModel.java

[api] Fix saveModel NPE bug

---

jupyter/load_pytorch_model.ipynb

Used optModelPath() in the Criteria instead of setting a system variable for the model zoo location.

Updated PyTorch Docs 

---

api/src/main/java/ai/djl/ndarray/BaseNDManager.java
api/src/main/java/ai/djl/ndarray/NDManager.java
tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDManager.java

Add support for the [Truncated Normal ](https://www.tensorflow.org/api_docs/python/tf/random/truncated_normal) operation to TensorFlow only. An UnsupportedOperationException is thrown for all other engines.

[tensoflow] Add truncated-normal operation

---

integration/src/main/java/ai/djl/integration/tests/model_zoo/ModelZooTest.java

Change-Id: I1c73df17cb077b9ce8905fcc2fc8bbb37b9688d8

Make model zoo test weekly

---

api/src/main/java/ai/djl/ndarray/NDArray.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_inference.cc
pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_nn_functional.cc

Add [one-hot operator](https://sparrow.dev/pytorch-one-hot-encoding/) for PyTorch engine. This operation is already fully supported for TensorFlow and MxNet. However, PyTorch does not support the onValue and offValue parameters [natively](https://pytorch.org/cppdocs/api/function_namespacetorch_1_1nn_1_1functional_1abfccd00762b084cb116c3a53c3386c83.html), so that feature of the operator will stay unsupported.

[pytorch] Add oneHot operator

---

api/src/main/java/ai/djl/ndarray/BaseNDManager.java
integration/src/main/java/ai/djl/integration/tests/model_zoo/ModelZooTest.java

The same as https://github.com/deepjavalibrary/djl/pull/1005 but for other engines.

Truncated-Normal Operation

---

api/src/main/java/ai/djl/repository/zoo/Criteria.java
api/src/main/java/ai/djl/repository/zoo/ModelZoo.java

Change-Id: Ie5c9f59ec283c780c323b2a99c440f416369c5fb

[api] add loadModel() to Critiera

---

integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayCreationOpTest.java

Add the integration test for the truncated-normal operation. This test verifies the sample mean is within a certain range from the theoretical mean. It also checks the truncation, testing if all the sample points are within 2 standard deviations from the mean.

Add integration test for truncated-normal op

---

tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDManager.java
tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/javacpp/JavacppUtils.java

Change-Id: I7b3f326669dec6739d24131d7507984390817226

Fixes #1024, Add back string tensor support

---

api/src/main/java/ai/djl/repository/RepositoryFactoryImpl.java
serving/serving/src/main/java/ai/djl/serving/ModelServer.java
serving/serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
serving/serving/src/main/java/ai/djl/serving/http/ManagementRequestHandler.java
serving/serving/src/main/java/ai/djl/serving/wlm/Endpoint.java
serving/serving/src/main/java/ai/djl/serving/wlm/Job.java
serving/serving/src/main/java/ai/djl/serving/wlm/ModelInfo.java
serving/serving/src/main/java/ai/djl/serving/wlm/ModelManager.java
serving/serving/src/main/java/ai/djl/serving/wlm/WorkLoadManager.java
serving/serving/src/test/java/ai/djl/serving/wlm/ModelInfoTest.java
serving/serving/src/test/resources/config.properties

- [serving] Remove GpuAssignmentStrategy.java
- [serving] support load multiple version of a model on the same endpoint

[serving] support load multiple version of a model on the same endpoint

---

api/src/main/java/ai/djl/training/listener/MemoryTrainingListener.java
serving/serving/build.gradle

Change-Id: I9b654322e2b7505dbaa8569b6480a4f5ab19c981

[serving] set ai.djl.pytorch.num_interop_threads

---

extensions/sentencepiece/src/main/java/ai/djl/sentencepiece/SpProcessor.java
extensions/sentencepiece/src/main/java/ai/djl/sentencepiece/SpTokenizer.java

Per customer demand, make SpProcessor public to achieve better performance

make SpProcessor public

---

.github/workflows/native_jni_s3_pytorch.yml

Change-Id: I0c5a3216a9b15d9ba1f9b8be49cdff57abbfb6b2

Fix pytorch jni publish pipeline

---

.github/workflows/native_jni_s3_pytorch.yml

Change-Id: I8d34e2e799a2a0b67fa97fe5a39eba6a69c214b0

Fix pytorch s3 jni publish pipeline

---

api/src/main/java/ai/djl/ndarray/internal/NDArrayEx.java
api/src/main/java/ai/djl/nn/norm/LayerNorm.java
integration/src/main/java/ai/djl/integration/tests/nn/BlockCoreTest.java
mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArrayEx.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArrayEx.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_nn_functional.cc
tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArrayEx.java

Similar to BatchNormalization there exist some other variants of normalizing data flowing through the network that have been implemented by the underlying ai frameworks. Here LayerNorm as one of them has been wired up to be used with PyTorch.
This PullRequest would close https://github.com/deepjavalibrary/djl/issues/1057.

LayerNorm using PyTorch

---

api/src/main/java/ai/djl/nn/AbstractBlock.java

Change-Id: I2aa8bc6c8d36d01cc00c02778907b040d782330c

Fix NPE bug in block.toString() function

---

docs/development/inference_performance_optimization.md

Add a note on the need to use a fixed size thread pool when using MxNet with multi-threaded inference.

Add note on MxNet thread_local storage

---

api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrNDArray.java
integration/build.gradle
integration/src/main/java/ai/djl/integration/tests/nn/BlockFactoryTest.java
integration/src/main/java/ai/djl/integration/tests/training/WeightDecayTest.java
integration/src/test/java/ai/djl/integration/IntegrationTests.java
ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbNDArray.java
ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbNDManager.java
onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtUtils.java

1. Remove default implemenation from NDArrayAdapter for required API
2. Throw Unsupported exception for OrtNDArray
Change-Id: Ifab71491610c145ad67dc43dffcf72e080023433

Refactor NDArrayAdapter

---

integration/src/main/java/ai/djl/integration/tests/nn/BlockCoreTest.java

Change-Id: Iff9c8f0cfb6ca56d035436c6278e34d3590fbe78

Workaroun mixed device issue in multiple engine case

---

api/src/main/java/ai/djl/repository/Artifact.java
api/src/main/java/ai/djl/repository/JarRepository.java
api/src/main/java/ai/djl/repository/Metadata.java
api/src/main/java/ai/djl/repository/SimpleRepository.java
api/src/main/java/ai/djl/repository/SimpleUrlRepository.java
serving/serving/src/main/java/ai/djl/serving/ModelServer.java
serving/serving/src/test/resources/config.properties

Change-Id: Ief11f4df5d7f1622d42385842dacadefc118e7d4

[serving] auto detect number of GPUs

---

api/src/main/java/ai/djl/engine/Engine.java
api/src/main/java/ai/djl/modality/cv/util/NDImageUtils.java
api/src/main/java/ai/djl/repository/zoo/BaseModelLoader.java
api/src/main/java/ai/djl/training/listener/LoggingTrainingListener.java
extensions/benchmark/src/main/java/ai/djl/benchmark/Arguments.java
extensions/fasttext/src/main/java/ai/djl/fasttext/zoo/FtModelZoo.java

Change-Id: I9c14b470306d9c1c7226c50952e439e2842ad01c

Avoid load default engine if not being used

---

api/src/main/native/djl/utils.h
examples/build.gradle
extensions/benchmark/build.gradle
gradle.properties
paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpNDArray.java
paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jni/JniUtils.java
paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jni/PaddleLibrary.java
paddlepaddle/paddlepaddle-engine/src/test/java/ai/djl/paddlepaddle/jni/JniUtilsTest.java
paddlepaddle/paddlepaddle-native/src/main/native/ai_djl_paddlepaddle_jni_PaddleLibrary_tensor.cc
paddlepaddle/paddlepaddle-native/src/main/native/djl_paddle_utils.h
tensorflow/tensorflow-engine/README.md

For LoD functionalities addition.

add lod functionalities to paddle

---

paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpModel.java
paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jni/JniUtils.java
paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jni/PaddleLibrary.java
paddlepaddle/paddlepaddle-native/src/main/native/ai_djl_paddlepaddle_jni_PaddleLibrary_inference.cc

Add remove pass option to paddle
Usage:
```
Criteria<NDList, NDList> criteria = Criteria.builder()
.setTypes(NDList.class, NDList.class)
.optEngine("PaddlePaddle")
.optModelPath(Paths.get("inference.zip"))
.optModelName("pig")
.optOption("removePass", "repeated_fc_relu_fuse_pass")
.optDevice(Device.cpu())
.optProgress(new ProgressBar())
.build();
```

[Paddle] add remove pass option

---

api/src/main/java/ai/djl/ndarray/NDArray.java
api/src/main/java/ai/djl/ndarray/internal/NDFormat.java
dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrNDArray.java
extensions/benchmark/build.gradle
ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbNDArray.java
mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtNDArray.java
paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpNDArray.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
tflite/tflite-engine/src/main/java/ai/djl/tflite/engine/TfLiteNDArray.java

Change-Id: I4c0b29e56fd6ed214656cf2681337e595ecda4e3

Change NDArray.toString() output

---

extensions/benchmark/src/main/java/ai/djl/benchmark/AbstractBenchmark.java
extensions/benchmark/src/main/java/ai/djl/benchmark/Arguments.java
extensions/benchmark/src/main/java/ai/djl/benchmark/Benchmark.java
extensions/benchmark/src/main/java/ai/djl/benchmark/MultithreadedBenchmark.java

Change-Id: Ie27e090699695526df42fefd01db2aba78dc3f73

[djl-bench] Run benchmark on multiple GPUs

---

api/src/main/java/ai/djl/repository/AbstractRepository.java
api/src/main/java/ai/djl/repository/Artifact.java
api/src/main/java/ai/djl/repository/JarRepository.java
api/src/main/java/ai/djl/repository/LocalRepository.java
api/src/main/java/ai/djl/repository/Metadata.java
api/src/main/java/ai/djl/repository/RemoteRepository.java
api/src/main/java/ai/djl/repository/RepositoryFactoryImpl.java
api/src/main/java/ai/djl/repository/SimpleRepository.java
api/src/main/java/ai/djl/repository/SimpleUrlRepository.java
extensions/aws-ai/src/main/java/ai/djl/aws/s3/S3Repository.java
extensions/aws-ai/src/main/java/ai/djl/aws/s3/S3RepositoryFactory.java
extensions/aws-ai/src/test/java/ai/djl/aws/s3/S3RepositoryTest.java
extensions/hadoop/src/main/java/ai/djl/hadoop/hdfs/HdfsRepository.java
extensions/hadoop/src/main/java/ai/djl/hadoop/hdfs/HdfsRepositoryFactory.java

1. allows pass arguments from url query string
2. Move some logic from RepositoryFactory into AbstractRepository.
Change-Id: If8f1821bf556c96f522810f45a13cb42d98f0ab4

Refactor repository implemenation

---

api/src/main/java/ai/djl/repository/zoo/Criteria.java
extensions/benchmark/build.gradle
onnxruntime/onnxruntime-engine/README.md
serving/serving/build.gradle
serving/serving/src/main/java/ai/djl/serving/wlm/ModelManager.java

Change-Id: I5c2b18b06202941fe6cac3b9d538ba74405a9677

Support benchmark onnx on GPU machine

---

extensions/benchmark/README.md
extensions/benchmark/src/main/java/ai/djl/benchmark/AbstractBenchmark.java
extensions/benchmark/src/main/java/ai/djl/benchmark/Arguments.java
extensions/benchmark/src/test/java/ai/djl/benchmark/BenchmarkTest.java

Change-Id: I222f75fad4c14e470fa0a92c9d1d61ffc729f697

[djl-bench] remove artificat_id and criteria arguments in favor of using djl:// url

---

serving/serving/src/main/java/ai/djl/serving/http/DescribeModelResponse.java
serving/serving/src/main/java/ai/djl/serving/wlm/ModelManager.java
serving/serving/src/main/java/ai/djl/serving/wlm/WorkLoadManager.java

Change-Id: Ib7b8d1dd4f2df95e928967f417dc872040e7e81e

[djl-serving] Update auto scale algorithm

---

api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
tflite/tflite-engine/src/main/java/ai/djl/tflite/engine/TfLiteNDArray.java

Change-Id: I2bc4bc7ad97abe32e7fa065b42be7e1f4f886952

Fix NDArrayAdapter.getSparseFormat()

---

extensions/benchmark/src/main/java/ai/djl/benchmark/AbstractBenchmark.java
extensions/benchmark/src/main/java/ai/djl/benchmark/Benchmark.java
extensions/benchmark/src/main/java/ai/djl/benchmark/MultithreadedBenchmark.java

Change-Id: I3f5e5ec3bc6d9c4f2c4ad09c6695775f50981ebd

[djl-bench] Add warmup to benchmark

---

extensions/benchmark/src/main/java/ai/djl/benchmark/AbstractBenchmark.java
extensions/benchmark/src/main/java/ai/djl/benchmark/Arguments.java
extensions/benchmark/src/main/java/ai/djl/benchmark/MultithreadedBenchmark.java
serving/serving/src/main/java/ai/djl/serving/ModelServer.java
serving/serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
serving/serving/src/main/java/ai/djl/serving/http/ManagementRequestHandler.java
serving/serving/src/main/java/ai/djl/serving/util/ConfigManager.java
serving/serving/src/main/java/ai/djl/serving/wlm/ModelInfo.java
serving/serving/src/main/java/ai/djl/serving/wlm/WorkLoadManager.java

Change-Id: If06e2311ade12ce7a4bcbf8daddb7e98032fc418

Config number worker threads for GPU inference

---

paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpNDArray.java
paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jni/JniUtils.java

Avoid random crashes during the bytebuffer early catch

let paddle hold the creation buffer

---

extensions/benchmark/src/main/java/ai/djl/benchmark/AbstractBenchmark.java
extensions/benchmark/src/main/java/ai/djl/benchmark/Arguments.java
extensions/benchmark/src/main/java/ai/djl/benchmark/Benchmark.java
extensions/benchmark/src/main/java/ai/djl/benchmark/NDListGenerator.java
extensions/benchmark/src/test/java/ai/djl/benchmark/BenchmarkTest.java
extensions/benchmark/src/test/java/ai/djl/benchmark/NDListGeneratorTest.java

Change-Id: I37c1fe468a5b4784a83e9be4ce62f9b6f10e2b49

[djl-bench] Add a tool to genreate NDList file

---

api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java

Change-Id: I75e32ba17bdab38d04318ae72cf18a45a1e1b5c3

Avoid exception in NDArray.toString()

---

examples/build.gradle

Add model zoo dependency in build.gradle: examples. Without this line there was a "No deep learning engine found" error.

Include TF model zoo for examples

---

api/src/main/java/ai/djl/util/Platform.java

Change-Id: Ia5ae7545a78ff66b728298e3a6768462cad33ead

Fix platform matching bug

---

api/src/main/java/ai/djl/modality/Output.java
api/src/main/java/ai/djl/translate/ServingTranslatorFactory.java
integration/src/main/java/ai/djl/integration/tests/model_zoo/CustomTranslatorTest.java
integration/src/test/translator/MyTranslator.java
serving/serving/src/main/java/ai/djl/serving/http/ManagementRequestHandler.java
serving/serving/src/main/java/ai/djl/serving/wlm/BatchAggregator.java
serving/serving/src/main/java/ai/djl/serving/wlm/ModelManager.java
serving/serving/src/main/java/ai/djl/serving/wlm/PermanentBatchAggregator.java
serving/serving/src/main/java/ai/djl/serving/wlm/TemporaryBatchAggregator.java

Change-Id: I5a70eb894e749f02377a534509881ce25211c2e8

[djl-serving] Add dynamic batch feature back

---

pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/IValue.java
pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/IValueTest.java
pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_ivalue.cc

Change-Id: I41761821f2a605b2c69be95cff109b0761ba4990

Add nested IValue list and tuple support

---

extensions/fasttext/src/main/java/ai/djl/fasttext/FtModel.java
extensions/fasttext/src/main/java/ai/djl/fasttext/jni/FtWrapper.java
extensions/fasttext/src/main/java/ai/djl/fasttext/zoo/nlp/textclassification/TextClassificationModelLoader.java
extensions/fasttext/src/test/java/ai/djl/fasttext/CookingStackExchangeTest.java

1. This reverts commit 887bc6f136706efbaeb1cad783e710ec16293078.
2. This reverts commit 3198f656b228322eb38e03ed1d80d92cc0c14d2b.
3. Add options to set label prefix
Change-Id: I022352a8ecd4156ce08a92543db934710fa2a865

[fasttext] allow specify label preifx

---

engines/ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbNDArray.java

Change-Id: Icb1d8e2906e63e22e1efecabe34853a9c2edefc6

[xgb] Fix NDArray multiple read issue

---

api/src/main/java/ai/djl/ndarray/NDSerializer.java
api/src/main/java/ai/djl/ndarray/types/DataType.java
api/src/test/java/ai/djl/ndarray/types/DataTypeTest.java

Change-Id: Id6191a0124140dd12de6ac22b463b2c6dfd83527

Properly handle byte order in NDArray serialization

---

api/src/main/java/ai/djl/modality/cv/translator/BaseImageTranslator.java
api/src/main/java/ai/djl/modality/cv/translator/InstanceSegmentationTranslator.java
api/src/main/java/ai/djl/translate/PreProcessor.java

The pipeline is not a universal part of the PreProcessor and is rarely used. So,
it shouldn't be part of the main API but could be used by various
implementations.
This also cleans up the InstanceSegmentationTranslator a bit. It no longer
creates a new pipeline every time preprocess is called but uses a single
pipeline. It also no longer extends Transform but moves the necessary Transform
functionality to a nested class. Making it extend transform is odd and
potentially confusing, while the separation helps clarify the purpose of the
Transform.

Removes getPipeline from PreProcessor

---

api/src/main/java/ai/djl/inference/Predictor.java
api/src/main/java/ai/djl/ndarray/BaseNDManager.java
api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
docs/hybrid_engine.md
engines/dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrNDArray.java
engines/dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrNDManager.java
engines/dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrPredictor.java
engines/dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrSymbolBlock.java
engines/dlr/dlr-engine/src/main/java/ai/djl/dlr/jni/JniUtils.java
engines/dlr/dlr-engine/src/test/java/ai/djl/dlr/engine/DlrNDManagerTest.java
engines/ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbNDArray.java
engines/ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbNDManager.java
engines/ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbSymbolBlock.java
engines/ml/xgboost/src/test/java/ai/djl/ml/xgboost/XgbModelTest.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDManager.java
engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtNDManager.java
engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtSymbolBlock.java
engines/paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpDataType.java
engines/paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpNDManager.java
engines/paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpSymbolBlock.java
engines/paddlepaddle/paddlepaddle-model-zoo/src/main/java/ai/djl/paddlepaddle/zoo/cv/objectdetection/PpFaceDetectionTranslator.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDManager.java
engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDManager.java
engines/tensorrt/src/main/java/ai/djl/tensorrt/engine/TrtNDManager.java
engines/tensorrt/src/main/java/ai/djl/tensorrt/engine/TrtSession.java
engines/tflite/tflite-engine/src/main/java/ai/djl/tflite/engine/TfLiteNDManager.java

Change-Id: I269de88ca49f9042813f576a0c00586d3984ac92

[api] NDArray creation should not use alternative engine by default

---

api/src/main/java/ai/djl/ndarray/BaseNDManager.java
api/src/main/java/ai/djl/ndarray/NDArray.java
api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
api/src/main/java/ai/djl/ndarray/NDManager.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtNDArray.java
engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtNDManager.java
engines/onnxruntime/onnxruntime-engine/src/test/java/ai/djl/onnxruntime/engine/OrtTest.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
engines/tensorflow/tensorflow-engine/build.gradle
engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDManager.java
engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/javacpp/JavacppUtils.java
engines/tensorflow/tensorflow-engine/src/test/java/ai/djl/tensorflow/engine/TfNDManagerTest.java
engines/tensorflow/tensorflow-engine/src/test/java/ai/djl/tensorflow/engine/package-info.java

1. Add create(String[], Shape) to NDArray interface
2. Implemented full string tensor for TF
3. Fixed Onnx NDManager.create(String) implementation
Change-Id: If51e55373ac800bd2df0ed1deb937fc60fca8b70

[tensorflow] Fixes string tensor implemenation

---

extensions/benchmark/README.md
extensions/benchmark/build.gradle

Change-Id: Ib6b852fb08d3714bd30c3ada81b0c09118843ae7

Add python/tensorrt to benchmark

---

api/src/main/java/ai/djl/inference/Predictor.java
api/src/main/java/ai/djl/modality/Input.java

Change-Id: I9bcb5aab336f553f979b58523051af75ea134d90

[api] input property key should be case-insensitive

---

engines/dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrNDManager.java
engines/ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbNDManager.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDManager.java
engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtNDManager.java
engines/paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpNDManager.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArrayEx.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDManager.java
engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDManager.java
engines/tensorrt/src/main/java/ai/djl/tensorrt/engine/TrtNDManager.java
engines/tflite/tflite-engine/src/main/java/ai/djl/tflite/engine/TfLiteNDManager.java

Change-Id: If0d602c897937b25a9d1b1808568a9bb4fbc582e

[pytorch] Fix PtNDArray interoperability with other engine

---

api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java

Change-Id: I428826df885e1742c7776d840ec5692d2422ee34

[api] Use engine specific split()

---

api/src/main/java/ai/djl/modality/cv/translator/BaseImageTranslator.java

Change-Id: I79144cd8b1353a08b8232ee0372641abb6c6b55e

Update default image preprocessing

---

api/src/main/java/ai/djl/modality/cv/BufferedImageFactory.java

I made this PR based on this [comment](https://github.com/deepjavalibrary/djl/issues/1278#issuecomment-957994060) by @steinhae in #1278.
I also ran a quick experiment to verify the findings:
```java
try (NDManager manager = NDManager.newBaseManager()) {
NDArray array = manager.randomInteger(0, 255, new Shape(3, 400, 400), DataType.INT32).toType(DataType.UINT8, true);
ImageFactory factory = ImageFactory.getInstance();
for (int i=0; i<5000; i++) {
factory.fromNDArray(array);
}
}
```
Found that this change would reduce the time to run this test from about 62 seconds to about 22 seconds.

Make BufferedImageFactory.fromNDArray synchronous

---

engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArrayEx.java
integration/src/main/java/ai/djl/integration/tests/nn/BlockCoreTest.java

Adds LayerNorm support for MXNet (for PyTorch it already exists).
See https://github.com/deepjavalibrary/djl/issues/1341

LayerNorm for MXNet

---

api/src/main/java/ai/djl/BaseModel.java
api/src/main/java/ai/djl/Model.java
api/src/main/java/ai/djl/inference/Predictor.java
api/src/main/java/ai/djl/repository/zoo/ZooModel.java
engines/dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrModel.java
engines/dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrPredictor.java
engines/paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpModel.java
engines/paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpPredictor.java
engines/tensorrt/src/main/java/ai/djl/tensorrt/engine/TrtModel.java
engines/tensorrt/src/main/java/ai/djl/tensorrt/engine/TrtPredictor.java
extensions/fasttext/src/main/java/ai/djl/fasttext/FtModel.java
integration/src/main/java/ai/djl/integration/tests/inference/PredictorTest.java
integration/src/main/java/ai/djl/integration/tests/inference/package-info.java

Adds a new API to create a predictor with a specified device. This makes it easier to create multiple predictors with different devices from the same model to support use cases like multiple GPU.

Predictor with device

---

api/src/main/java/ai/djl/modality/cv/translator/ImageServingTranslator.java
api/src/main/java/ai/djl/modality/nlp/translator/QaServingTranslator.java

Change-Id: I6032a92bc119c1db98eeebe8b088a3c95ea5084d

[api] improve error message

---

examples/src/test/java/ai/djl/testing/TestRequirements.java
examples/src/test/java/ai/djl/testing/package-info.java

Symblic link does not work well on Windows
Change-Id: Icc4cabc71d7ce00c81b26b3364053e5d83aec50e

[examples] Avoid using symbolic link

---

extensions/benchmark/README.md

Change-Id: I20779c76d8994b3220adaa6173daff1cb248dace

[benchmark] Fixes benchmark README version

---

api/src/main/java/ai/djl/training/DefaultTrainingConfig.java
api/src/main/java/ai/djl/training/evaluator/AbstractAccuracy.java
api/src/main/java/ai/djl/training/evaluator/Accuracy.java
api/src/main/java/ai/djl/training/evaluator/BinaryAccuracy.java
api/src/main/java/ai/djl/training/evaluator/IndexEvaluator.java
api/src/main/java/ai/djl/training/evaluator/TopKAccuracy.java
api/src/main/java/ai/djl/training/loss/IndexLoss.java
api/src/main/java/ai/djl/training/loss/SimpleCompositeLoss.java
examples/src/main/java/ai/djl/examples/training/TrainCaptcha.java
examples/src/main/java/ai/djl/examples/training/TrainSeq2Seq.java

Right now, there is inconsistent handling for how evaluators and losses can be
applied to only a single array within an NDList. This can happen often when
using multiple losses such as with the AbstractCompositeLoss cases.
Before, we had indexing through SimpleCompositeLoss. However, this would not
work with the trainer evaluators as well. So, the solution must be to move the
tracking of indices into the evaluators/losses.
This creates the indexed variations as a wrapper class so it requires less
updating for existing classes and keeps them simpler. As part of it, the classes
that already had indexing support including some accuracy evaluators and
SimpleCompositeLoss had it removed.

Create IndexEvaluator and IndexLoss

---

engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/IValueUtils.java
engines/pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/jni/IValueUtilsTest.java
engines/pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/jni/package-info.java

This PR adds support for Tuples as input values for PyTorch models.
It is a simple PR which combines input values to Tuples if NDArray's name have '\w+()` syntax . Also there is a test.

Support for Tuples as input values for PyTorch models

---

api/src/main/java/ai/djl/repository/RepositoryFactoryImpl.java
api/src/main/java/ai/djl/repository/zoo/BaseModelLoader.java
api/src/main/java/ai/djl/translate/ServingTranslatorFactory.java
api/src/main/java/ai/djl/util/ClassLoaderUtils.java
api/src/main/java/ai/djl/util/Platform.java
basicdataset/src/main/java/ai/djl/basicdataset/cv/classification/ImageNet.java
testing/src/main/java/ai/djl/testing/CoverageUtils.java

Change-Id: Icae3ae41116bcb79c8d665794cab787848f9583e

[api] Fix NPE bug in getContextClassLoader().

---

api/src/main/java/ai/djl/repository/RepositoryFactoryImpl.java

Change-Id: Iafb83bb8176f3f92dec90f78bf07468171b20e97

[api] Fix model name detection in loading model from jar

---

tools/gradle/java-formatter.gradle

Change-Id: I9d8614e5680ce11c8c6c2b8a450c0fca4b4672a5

Add mavenCentral() to buildscript repository

---

extensions/hadoop/build.gradle

Change-Id: I2f67efdb758e13087598a5f922871cf12b71ea3d

[hadoop] Exclude log4j dependency from hadoop extension

---

engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java

Change-Id: Id2fc3a7cab1646fe921df3cc0e6c619e8857eeda

[pytorch] workaround libtorch.dylob 1.8.1 loading issue

---

api/src/main/java/ai/djl/modality/Classifications.java
api/src/main/java/ai/djl/modality/cv/output/DetectedObjects.java
api/src/main/java/ai/djl/modality/cv/translator/ImageClassificationTranslator.java

Change-Id: I4ffd29cff5205f32ee18afa5269d70491634936e

[api] Fixes topK items for DetectedObjects and make it configurable to Classifications

---

api/src/main/java/ai/djl/Device.java
api/src/test/java/ai/djl/DeviceTest.java

This adds support for device names to the Device class and the ability to parse
those names.

Device Name parsing

---

extensions/sentencepiece/src/main/java/ai/djl/sentencepiece/SpTokenizer.java
extensions/sentencepiece/src/test/java/ai/djl/sentencepiece/SpTokenizerTest.java

Change-Id: Ib86efb38def0bcb21862c5493683395071eb3592
Fixes #1491 

[sentencepiece] Fixes #1491, fix NPE bug

---

engines/pytorch/pytorch-engine/README.md

Change-Id: Ie8a35287676762c53af3e65b253e8d7af3f384fc

[pytorch] Fixes jni dependency in README document

---

api/src/main/java/ai/djl/ndarray/BaseNDManager.java
api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
engines/dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrNDManager.java
engines/ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbNDManager.java
engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtNDManager.java
engines/paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpNDManager.java
engines/tensorrt/src/main/java/ai/djl/tensorrt/engine/TrtNDManager.java
engines/tflite/tflite-engine/src/main/java/ai/djl/tflite/engine/TfLiteNDManager.java

Change-Id: I63f76479ea5acc55cd7725cedf13563157cac6d4
Fixes #1516

[api] Fixes memory leak in hybrid engine

---

api/src/main/java/ai/djl/util/passthrough/PassthroughNDArray.java
api/src/main/java/ai/djl/util/passthrough/PassthroughNDManager.java
api/src/main/java/ai/djl/util/passthrough/PassthroughTranslator.java
api/src/main/java/ai/djl/util/passthrough/package-info.java
extensions/fasttext/README.md
extensions/fasttext/src/main/java/ai/djl/fasttext/FtAbstractBlock.java
extensions/fasttext/src/main/java/ai/djl/fasttext/FtModel.java
extensions/fasttext/src/main/java/ai/djl/fasttext/TrainFastText.java
extensions/fasttext/src/main/java/ai/djl/fasttext/jni/FastTextLibrary.java
extensions/fasttext/src/main/java/ai/djl/fasttext/jni/FtWrapper.java
extensions/fasttext/src/main/java/ai/djl/fasttext/zoo/nlp/textclassification/FtTextClassification.java
extensions/fasttext/src/main/java/ai/djl/fasttext/zoo/nlp/textclassification/TextClassificationModelLoader.java
extensions/fasttext/src/main/java/ai/djl/fasttext/zoo/nlp/word_embedding/FtWord2VecWordEmbedding.java
extensions/fasttext/src/main/java/ai/djl/fasttext/zoo/nlp/word_embedding/FtWordEmbeddingBlock.java
extensions/fasttext/src/main/java/ai/djl/fasttext/zoo/nlp/word_embedding/package-info.java
extensions/fasttext/src/main/native/ai_djl_fasttext_jni_FastTextLibrary.cc
extensions/fasttext/src/test/java/ai/djl/fasttext/CookingStackExchangeTest.java

This makes a few changes, specifically to fasttext, but it can apply to other
DJL ml wrappers as well. First, it creates several passthrough utility classes
with the goal that ml models can be loaded through the model zoo and run through
the predictor.
Next, it modifies the base of the ml construct to better support engines that
have multiple applications. Each application now manifests as a type of
SymbolBlock rather than a model. Then, the single model class can run any of
them. The model is still created for each engine because it contains general
loading functionality that can determine which block should be used to load the
given target.
It also has to update the fasttext JNI to support this. First, it fixes the
modelType to actually return different results. Then, it modifies the …

Refactor ml extension support

---

api/src/main/java/ai/djl/Device.java
api/src/test/java/ai/djl/DeviceTest.java

This makes the names "" and null return the default device (with potentially
specified engine) instead of CPU.

Parse default device with Device.fromName

---

.github/workflows/native_jni_s3_pytorch.yml

There is an error reported from
`/.github/workflows/native_jni_s3_pytorch.yml`
The problem happens at line 74-75 with the error message:
```
ERROR: This script does not work on Python 3.6 The minimum supported Python version is 3.7. Please use https://bootstrap.pypa.io/pip/3.6/get-pip.py instead.
```
This error is reported from the file 
'https://bootstrap.pypa.io/get-pip.py'
It is fixed by downloading from the compatible source
`curl -O https://bootstrap.pypa.io/pip/3.6/get-pip.py`

Fix the python version bug in the benchmark workflow files

---

.github/workflows/native_jni_s3_pytorch.yml
engines/pytorch/pytorch-native/build.gradle
engines/pytorch/pytorch-native/build.sh
gradle.properties

This PR adds support for compiling/building Pytorch JNI for ```aarch64``` ARM architecture.
* Adding aarch64 cross-compiler dependencies to ```build-pytorch-jni-linux``` in github action
* Get Python 3.6 to make ```python3 get-pip.py``` to get the github action to work (open to just making the script compatible with the latest version)
* Moved ```files.each``` in ```prepareNativeLib(...)``` to a separate function
* Download the necessary dependencies and copy native lib if ```aarch64``` specific
* Updated Pytorch version to ```1.10.2```
* Ran ```CXX=aarch64-linux-gnu-gcc ./gradlew compileJNI -Paarch64 -Ppt_version=$PYTORCH_VERSION``` locally to verify build succeeded. 
* Ran github actions in private repository and succeeded up to the AWS Credentials step (at this point it's been built …

Building DJL For aarch64

---

jupyter/pytorch/load_your_own_pytorch_bert.ipynb

Change-Id: I159a7321f3d66aebf193063532ab70ccb9d657cb

[jupyter] remove unecessary maven import

---

engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java
engines/pytorch/pytorch-native/build.gradle

Fixes #1422
Change-Id: I477d85725e84f30a7a79733b16d0224abe83f3ce

[pytorch] Allows multiple native jars to package into fat jar

---

api/src/main/java/ai/djl/nn/Block.java
api/src/main/java/ai/djl/nn/Parameter.java
integration/src/main/java/ai/djl/integration/tests/training/GradientCollectorIntegrationTest.java

This adds a method to support freezing and unfreezing a parameter for transfer
learning. There is also a helper to (un)freeze all paremters in a block, but
without filtering. For more advanced use cases of (un)freezing part of the
parameters in a block, it should be implemented using block.getChildren(),
block.getDirectParameters() and/or block.getParameters().
fixes #392
fixes #1494

Support freeze parameters

---

api/src/main/java/ai/djl/repository/zoo/BaseModelLoader.java
api/src/main/java/ai/djl/util/ClassLoaderUtils.java

Change-Id: I9fe68ae6af4be85bcd8a626cfa28534f8d141798

[api] Fixes loading BlockFactory bug

---

engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfModel.java
engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfOpExecutor.java
engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/javacpp/JavacppUtils.java

Change-Id: I52632b1eb6a1ec6a3c47d14fd57abf269162f683

[tensorflow] Fixes tensorflow session always on gpu(0) bug

---

basicdataset/src/main/java/ai/djl/basicdataset/nlp/StanfordQuestionAnsweringDataset.java
basicdataset/src/test/java/ai/djl/basicdataset/StanfordQuestionAnsweringDatasetTest.java
basicdataset/src/test/resources/mlrepo/dataset/nlp/ai/djl/basicdataset/stanford-question-answer/metadata.json

Added Stanford Question Answering Dataset into the project.
Closed #47.

[basicdataset] Add Stanford Question Answering Dataset

---

engines/ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbNDManager.java
engines/ml/xgboost/src/test/java/ai/djl/ml/xgboost/XgbModelTest.java
gradle.properties

Upgrade XGBoost to 1.5.2
Change-Id: Ie47428f3c0a3dd5fadcb25ea05e655073a40f81f

[xgb] Set default missing value to NaN

---

.github/workflows/native_jni_s3_pytorch.yml

Change-Id: I3301525131a3d0e4c1637fe7d625c677f1258516

[ci] Use cuda 11.3.1 to build pytorch jni

---

.github/workflows/native_jni_s3_pytorch.yml
.github/workflows/nightly_publish.yml
engines/pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/MkldnnTest.java
engines/pytorch/pytorch-jni/build.gradle
engines/pytorch/pytorch-native/CMakeLists.txt
engines/pytorch/pytorch-native/build.cmd
engines/pytorch/pytorch-native/build.gradle
engines/pytorch/pytorch-native/build.sh
engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_system.cc
engines/pytorch/pytorch-native/src/main/native/djl_pytorch_utils.h
engines/pytorch/pytorch-native/src/main/patch/cuda.cmake
gradle.properties
integration/build.gradle

[pytorch] Upgrade to pytorch 1.11.0

---

engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java

Change-Id: Ic87302a880564027bed1f213088baac1ee543d9e
the default PyTorch pip package contains both cpu and gpu native binaries. Currently DJL can only load cpu/gpu only pip package:
```
pip install torch==1.10.0+cu113 -f https://download.pytorch.org/whl/torch_stable.html
or
pip install torch==1.10.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
```
This PR allows DJL to load libtorch from default pip package on CPU machine. However load on GPU machine will still fail due to missing `libtorch_cuda_cpp.so` file in the default pip pacakge.

[pytorch] Allows load libtroch from pip installation package

---

extensions/tokenizers/rust/src/lib.rs
extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/CharSpan.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/Encoding.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizer.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/jni/CharSpan.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/jni/TokenizersLibrary.java
extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizerTest.java

This PR extends the hugging face Java/Rust interface. I added a method to return the original char spans for each token result, together with the encoding object. 
This function is useful in Named Entity Recognition tasks (NER), specifically to reconstruct entities together, since the tokens retrieved from the tokenization lose whitespace information.

HF Tokenizer: get charspans 

---

extensions/benchmark/src/main/java/ai/djl/benchmark/AbstractBenchmark.java
extensions/benchmark/src/main/java/ai/djl/benchmark/Benchmark.java
extensions/benchmark/src/main/java/ai/djl/benchmark/NDListGenerator.java

Change-Id: Ic598d884e63eedafaf4539295b9b927cc73479ac

[benchmark] Allows benchmark run on aarch64 for PyTorch

---

docs/development/inference_performance_optimization.md
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtEngine.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_inference.cc

Inspired from PyTorch performance tuning thread: https://pytorch.org/tutorials/recipes/recipes/tuning_guide.html#enable-cudnn-auto-tuner
Adding for Resnet and YOLO V5 related model speed up with this flag

[PyTorch] add cuDNN acceleration

---

engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtSymbolBlock.java

Fixed the bug on the name where user has placed name inside.

[ONNXRuntime] fix naming

---

basicdataset/src/main/java/ai/djl/basicdataset/nlp/StanfordQuestionAnsweringDataset.java
basicdataset/src/test/java/ai/djl/basicdataset/StanfordQuestionAnsweringDatasetTest.java

In Stanford Question Answering Dataset the limit is specially handled, and there exists a severe bug that if the limit is too large (or the limit is set as default) it will cause an `IndexOutOfBoundException`.
This PR fixed this bug and changed the test cases into a more strict one so that this bug will be detected.

[basicdataset] Fixed out of bound limit

---

engines/onnxruntime/onnxruntime-engine/README.md
engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtModel.java

Allow user to specify TensorRT mode under GPU.

[ONNXRuntime] add tensorRT option

---

api/src/main/java/ai/djl/metric/Metric.java
api/src/test/java/ai/djl/metric/MetricsTest.java

Change-Id: Idb7048e33c22e4cee3cc8bd5eac5d91cf9b94e01

[api] Fixes metric dimension

---

engines/pytorch/pytorch-jni/build.gradle
engines/pytorch/pytorch-native/build.gradle

Change-Id: I39f6da3444eb7ba5205bfde11f6c36e9baa76eab

[pytorch] Use precxx11 build for aarch64 native library

---

engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java

Change-Id: I4a3e4705037b75855f5c0227ecf39657fbb21fa9

[pytorch] use precxx11 for aarch64

---

docs/development/inference_performance_optimization.md

Add optimization methods for ONNXRuntime

[ONNXRuntime] Update inference_performance_optimization.md

---

api/src/main/java/ai/djl/metric/Metric.java

Change-Id: I5dae8088aff74f5d77558ab30aa5e8d0fb96926b

[api] Avoid NPE in Metric.toString()

---

.github/workflows/native_s3_pytorch_android.yml
engines/pytorch/pytorch-native/build_android.sh

[PyTorch] update pytorch build instruction on android

---

.github/workflows/native_publish_pytorch.yml
engines/pytorch/pytorch-native/build.gradle

This adds the install name tool rpath fix to downloading the pytorch native libraries.
It also updates the gradle script that runs the publish to run on osx which has
the fixer tool instead of osx.
It does have a minor breaking aspect as now the publish must be run from osx. I
did add an early error in case it is run from a different os.

Add rpath fix to Native Publish PyTorch

---

api/src/main/java/ai/djl/ndarray/NDArray.java
api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_tensor.cc
engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
integration/src/main/java/ai/djl/integration/tests/ndarray/NDIndexTest.java

This is a follow-up on PR https://github.com/deepjavalibrary/djl/pull/1622. The `take` feature will enable more advanced indexing.
It's the same as `take` in [numpy ](https://numpy.org/doc/stable/reference/generated/numpy.take.html#numpy.take) and [ pytorch](https://pytorch.org/docs/1.11/generated/torch.take.html?highlight=take#torch.take).
Defination of `NDArray take(NDArray index)`:
Returns a partial pointed by the index array, according to row-major-ordering linear indexing.
The shape of the output is decided by that of `index`.

Support of take from pytorch

---

api/src/main/java/ai/djl/ndarray/NDList.java
api/src/main/java/ai/djl/translate/ServingTranslatorFactory.java
api/src/test/java/ai/djl/translate/BatchifierTest.java
api/src/test/java/ai/djl/translate/ServingTranslatorTest.java
api/src/test/java/ai/djl/translate/package-info.java

The output content-type will match the input content-type.
Change-Id: I06d864449b89e8e416371f2e2b32b91406ee4883

[api] Improves ServingTranslator output handling

---

engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java
engines/pytorch/pytorch-jni/build.gradle

Change-Id: I5fb7f2bc1ba07626fb8dcc45e1daf77d4b31765b

[pytorch] Add macOS M1 chip support.

---

basicdataset/src/main/java/ai/djl/basicdataset/tabular/DailyDelhiClimate.java
basicdataset/src/test/java/ai/djl/basicdataset/DailyDelhiClimateTest.java
basicdataset/src/test/resources/mlrepo/dataset/tabular/ai/djl/basicdataset/daily-delhi-climate/metadata.json

Added Daily Delhi Climate Dataset, which is a time series dataset into DJL.
Since the dataset is not uploaded to s3 yet, the download process and the correctness of URI is not tested.
Close #1590.

[basicdataset] Add Daily Delhi Climate Dataset

---

api/src/main/java/ai/djl/training/dataset/ArrayDataset.java
api/src/main/java/ai/djl/training/dataset/Dataset.java
api/src/main/java/ai/djl/training/dataset/RandomAccessDataset.java
basicdataset/README.md
basicdataset/src/main/java/ai/djl/basicdataset/cv/CocoDetection.java
basicdataset/src/main/java/ai/djl/basicdataset/cv/PikachuDetection.java
basicdataset/src/main/java/ai/djl/basicdataset/cv/classification/AbstractImageFolder.java
basicdataset/src/main/java/ai/djl/basicdataset/cv/classification/Cifar10.java
basicdataset/src/main/java/ai/djl/basicdataset/cv/classification/FashionMnist.java
basicdataset/src/main/java/ai/djl/basicdataset/cv/classification/ImageFolder.java
basicdataset/src/main/java/ai/djl/basicdataset/cv/classification/Mnist.java
basicdataset/src/main/java/ai/djl/basicdataset/nlp/StanfordQuestionAnsweringDataset.java
docs/dataset.md
docs/development/add_dataset_to_djl.md
docs/development/add_model_to_model-zoo.md
docs/development/example_dataset.md
docs/development/how_to_use_dataset.md
docs/mkdocs.yml
engines/mxnet/mxnet-engine/README.md

This makes a number of updates to the dataset documentation. It moves the list
of datasets to the main guide which is more accessible that basicdataset's README
and could contain future datasets not in basic dataset.
It also updates the list of built-in datasets and adds a list of dataset
helpers. It improves the page for creating a custom dataset. Finally, there are
a few other miscellaneous doc improvements.

Update the Dataset documentation

---

api/src/main/java/ai/djl/nn/norm/BatchNorm.java
api/src/main/java/ai/djl/nn/norm/GhostBatchNorm.java
api/src/test/java/ai/djl/nn/norm/GhostBatchNormTest.java
api/src/test/java/ai/djl/nn/norm/package-info.java
integration/src/main/java/ai/djl/integration/tests/nn/BlockCoreTest.java

`GhostBatchNormalization` is one of the components that build up TabNet. It works similar to `BatchNorm` except that it splits each batch into smaller mini-batches and each of them is normalized separately.
Changes:
* **BatchNorm**: remove the final notation from the builder class as GhostBatchNormalization extends BatchNorm and the builder is required to be extended with it for usage.
*  **GhostBatchNorm**: Extends BatchNorm and overrides `internalForward()` such that it splits the batch into mini-batches using `StackBatchifier` before applying batch normalization. `split()` divides the size of the original batch and ceil it so if the original batch size isn't divisible by the virtual batch size, the remaining samples will be placed in the last mini-batch (this behaviour is inspired from …

[TabNet/WIP] Implement GhostBatchNorm

---

basicdataset/src/main/java/ai/djl/basicdataset/tabular/AirfoilRandomAccess.java
basicdataset/src/main/java/ai/djl/basicdataset/tabular/AmesRandomAccess.java
basicdataset/src/main/java/ai/djl/basicdataset/tabular/TabularDataset.java
basicdataset/src/main/java/ai/djl/basicdataset/tabular/utils/Featurizers.java
basicdataset/src/test/java/ai/djl/basicdataset/AirfoilRandomAccessTest.java

Earlier, the AirfoilRandomAccess had to use custom code to add normalizing
functionality and couldn't rely on the featurizers. This creates a new
normalizing featurizer using the new PreparedFeaturizer and brings it into line
with the standard tabular dataset.
The changes in testAirfoilRemotePreprocessing come from an update to the
normalization. Before, it was normalized by calculating using the size (limited
to top 1500 elements in the dataset for the test). Instead, it normalizes using
the full dataset availableSize(). I feel like this would make more sense to not
have your data preprocessing be different between a limited dataset and the full
one and would be unexpected for users if it were.

Normalized Numeric Featurizer

---

api/src/main/java/ai/djl/ndarray/BaseNDManager.java
api/src/main/java/ai/djl/ndarray/NDManager.java
api/src/main/java/ai/djl/ndarray/NDResource.java
api/src/main/java/ai/djl/util/passthrough/PassthroughNDManager.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDManager.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDManager.java
integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayAttachmentTest.java

This change adds the capability to "cap" a NDManager instance.
In the capped state, it is not possible to add new resources to the manager (except for submanagers).
The model developer would choose to do so when he is sure that all resources (usually NDArray) that are supposed to be attached are attached and he expects no new resources to be added in the future, thus preventing unintentional addition of resources that could go undetected otherwise and could pose memory leaks.
Sub managers are by design still allowed to be attached and have an independent "cap" status.

Added "capped" state to NDManager

---

api/src/main/java/ai/djl/nn/core/LinearCollection.java
integration/src/main/java/ai/djl/integration/tests/nn/BlockCoreTest.java

This change enables the execution of multiple linear transformations using only one block as opposed to using multiple Linear blocks in a more complex setup.
I measured a speed-up of at least 10 for my scenario as the linear transformations are handled within one ndarray.
This PR is 2nd try, I messed up my original branch trying to rebase commits

added LinearCollection block

---

engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfEngine.java

Fixes #1733
Change-Id: I445f25e376accc84f12ce5ef324fcc4b06f4497c

[tensorflow] Avoid NPE in TfEngine

---

api/src/main/java/ai/djl/repository/zoo/Criteria.java
api/src/test/java/ai/djl/repository/ZooTest.java

Creates a new method Criteria.toBuilder() to go from a working criteria to a Criteria builder to modify that criteria. It is intended for use for a new method in the DJL Serving WLM `new ModelInfo(String id, Criteria criteria)` which can be used for non-serving usages of the WLM.

Criteria.toBuilder()

---

api/src/main/java/ai/djl/nn/AbstractBaseBlock.java
api/src/main/java/ai/djl/nn/AbstractBlock.java
api/src/main/java/ai/djl/nn/Block.java
api/src/main/java/ai/djl/nn/Blocks.java
api/src/main/java/ai/djl/nn/LambdaBlock.java
api/src/main/java/ai/djl/nn/ParallelBlock.java
api/src/main/java/ai/djl/nn/SequentialBlock.java
api/src/main/java/ai/djl/nn/norm/Dropout.java
api/src/main/java/ai/djl/util/Utils.java

This feature adds Utils.decribe() which describes the created neural net based on the block naming used in AbstractBlock.addChildBlock()
For the TrainMnist example, we can get now a nicer textual description:
```
Mlp(1, 784) {
Flatten(1, 784) -> (1, 784)
Linear(1, 784) -> (1, 128)
Relu(1, 128) -> (1, 128)
Linear(1, 128) -> (1, 64)
Relu(1, 64) -> (1, 64)
Linear(1, 64) -> (1, 10)
} -> (1, 10)
```
that is much easier to read than Block.toString() :
```
Sequential(
Lambda()
Linear(1 -> 128)
Lambda()
Linear(1 -> 64)
Lambda()
Linear(1 -> 10)
)
```
by following code in Mlp.java:
```
addChildBlock("Flatten", Blocks.batchFlattenBlock(input));
for (int hiddenSize : hidden) {
add(Linear.builder().setUnits(hiddenSize).build());
addChildBlock("Relu", activation);
} …
```

Enable better textual description of neural net

---

.github/workflows/no_response.yml

This creates an action that runs daily after midnight. It will look for actions
with a given label (defaults to more-information-needed) that have not been
updated for 14 days and will close them.

Create action to auto-close issues without response

---

api/src/main/java/ai/djl/training/dataset/Batch.java
api/src/main/java/ai/djl/training/dataset/DataIterable.java

Stores the indices that are used to extract a batch from a dataset in the batch itself.
This enables to pinpoint the predictions in `BatchData`  passed into
`TrainingListenerAdapter/onTrainingBatch  `and `TrainingListenerAdapter/onValidationBatch `
within the source dataset and thus can make better use of them.

store indices with batch

---

engines/pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/jni/IValueUtilsTest.java

The testing code can be used as example as well
Change-Id: I693624fd111afb0a5547d619a03d2cb15831af1b

[pytorch] Add NDList to IValue unit test

---

engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/IValue.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
engines/pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/IValueTest.java
engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_ivalue.cc

Change-Id: I277ff2f07383d6389c6865ba0e3e77aef3190d0a

[pytorch] Adds IValue Dict(str, IValue) support

---

api/src/main/java/ai/djl/ndarray/NDArray.java
api/src/main/java/ai/djl/ndarray/index/NDArrayIndexer.java
api/src/main/java/ai/djl/ndarray/index/NDIndex.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArrayIndexer.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_tensor.cc
integration/src/main/java/ai/djl/integration/tests/ndarray/NDIndexTest.java

Add tensor setter feature with advanced indexing on PyTorch engine. This is the counterpart of  the getter feature in one previous PR. [Advanced indexing that supports all indexing features on PyTorch #1719](https://github.com/deepjavalibrary/djl/pull/1719)
This PR succeeds [Add put feature with linear indexing on PyTorch engine #1749](https://github.com/deepjavalibrary/djl/pull/1749).
The relavant preceding PRs
[Advanced indexing that supports all indexing features on PyTorch #1719](https://github.com/deepjavalibrary/djl/pull/1719)
[Add put feature with linear indexing on PyTorch engine #1749](https://github.com/deepjavalibrary/djl/pull/1749)

Add tensor setter feature with advanced indexing on PyTorch engine

---

extensions/aws-ai/src/main/java/ai/djl/aws/sagemaker/SageMaker.java
extensions/aws-ai/src/test/java/ai/djl/aws/sagemaker/SageMakerTest.java

[aws-ai] change the sagemaker model to s3

---

api/src/main/java/ai/djl/modality/cv/translator/SemanticSegmentationTranslator.java

- Added random color array to remove need for specifying specific id's for objects
- Improved efficiency of coloring algorithm
- Resize array in translator to original image dimensions

Improvements to image coloring

---

api/src/main/java/ai/djl/ndarray/NDArray.java
docs/get.md
integration/src/main/java/ai/djl/integration/tests/ndarray/NDIndexTest.java

1. Fix [issue 1773](https://github.com/deepjavalibrary/djl/issues/1773) and [issue 1774](https://github.com/deepjavalibrary/djl/issues/1774)
In `NDArray.set(NDArray index, Number value)` add the feature of setting array values with integer indices, as shown in the use case https://github.com/deepjavalibrary/djl/issues/1773 as well as https://github.com/deepjavalibrary/djl/issues/1774.
This is similar to [pr#1755](https://github.com/deepjavalibrary/djl/pull/1755) and is based on the advanced indexing [pr#1719](https://github.com/deepjavalibrary/djl/pull/1719).
2. Fix an issue in the document of built-from-source

Issue fix 1773 and 1774

---

api/src/main/java/ai/djl/ndarray/index/NDIndex.java
api/src/main/java/ai/djl/ndarray/types/DataType.java
integration/src/main/java/ai/djl/integration/tests/ndarray/NDIndexTest.java

This fixes [issue](https://github.com/deepjavalibrary/djl/issues/1799). 
The fix is to allow other datatype of index than just integer. The dataType conversion to `Long` has already implemented before in JniUtils

[BugFix] Fix breaking behaviour in 0.18.0

---

api/src/main/java/ai/djl/ndarray/index/full/NDIndexFullPick.java
api/src/main/java/ai/djl/ndarray/types/Shape.java

This solves the bug reported in [issue](https://github.com/deepjavalibrary/djl/issues/1800). 
The new feature of indexing is not completely backward compatible, since `NDIndexPick` has been replaced by `NDIndexTake`. Now this problem is solved.
However, this is a temporary solution, only to make it backward compatible. `NDIndexPick` does not have the same definition as `NDIndexTake` when used to index array elements. For example, `NDIndexPick` cannot support larger-than-1-rank indexing array, while `NDIndexTake` can. So, as NDIndexElement,  `NDIndexPick` should be deprecated in the future.

Backward compatible with MXNet indexing.

---

api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
engines/onnxruntime/onnxruntime-engine/build.gradle
engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtNDArray.java
engines/onnxruntime/onnxruntime-engine/src/test/java/ai/djl/onnxruntime/engine/OrtTest.java

1. Fixes #1804
2. Fixes crash caused by double close OrtNDArray
3. NDArray.get() should use alternativeManager if available
4. getNDArrayInternal() should fail with alternativeManager is disabled
Change-Id: I37767394f3c68dc8a48ba21ae589dfa81407bdb8

[onnx] Fixes OrtNDArray double close issue

---

android/core/src/main/java/ai/djl/android/core/BitmapImageFactory.java
api/src/main/java/ai/djl/modality/cv/translator/SemanticSegmentationTranslator.java

Adds compatibility for the DJL-Demo Semantic Segmentation app
- Transposes NDArray if dimensions matchup in BitmapImageFactory
- DataType for NDArray would change from the app due to using BitmapImageFactory and not BufferImageFactory, so added line to change DataType back to `UINT8` before returning image.

Compatibility changes for Semantic Segmentation app

---

android/gradle.properties

Change-Id: I03d27ba222755c292b04a59fb6bf59864f8767b0

[android] Bumpup android version to 0.19.0-SNAPSHOT

---

api/src/main/java/ai/djl/translate/PostProcessor.java

This doc change originates from [issue 1774](https://github.com/deepjavalibrary/djl/issues/1774). It reminds user that the output array during inference mode is immutable. When they need to change the output NDArray in a implementation of postProcessor, they will know.

[doc] Immutable array output from InferenceMode PyTorch

---

engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtModel.java
extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/TranslatorTest.java

Change-Id: Id4c8b734ffc0ad07685e1df1f977c8dcb50dec79

[pytorch] Allows block only model for PyTorch

---

engines/pytorch/pytorch-engine/README.md

Change-Id: I1cb87d399d05f9f9a49b7d4507d1f2e16f4348ce

[doc] Remove pytorch cu102 package for Windows in README file

---

android/core/src/androidTest/java/ai/djl/android/core/BitmapWrapperTest.java
android/core/src/main/java/ai/djl/android/core/BitmapImageFactory.java
api/src/main/java/ai/djl/modality/cv/BufferedImageFactory.java
integration/src/main/java/ai/djl/integration/tests/modality/cv/BufferedImageFactoryTest.java

Both image factories now handle HWC and CHW formats
- Transpose is not available for all engines so we must handle the different formats without transposing to a single format type
- Test on the apps and within DJL repo

Updated image factories for HWC and CHW

---

api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java

Change-Id: Iaf90c609a832f3f7bc2a863bdb44cfc7df34dbae

[api] Fixes NDArrayAdapter toDevice() and toType() behavior

---

extensions/tokenizers/build.gradle
extensions/tokenizers/src/main/python/arg_parser.py
extensions/tokenizers/src/main/python/huggingface_converter.py
extensions/tokenizers/src/main/python/metadata.py
extensions/tokenizers/src/main/python/requirements.txt
extensions/tokenizers/src/main/python/shasum.py
extensions/tokenizers/src/main/python/zip_utils.py

This feature allows users to import huggingface models into DJL model zoo.
- It will download huggingface models and use pytorch jit to trace the model. It also saves the model in DJL model zoo format.
- The script can allows you to limit the amount of models that are loaded so that you don't have to import all of the models at once. Previously imported models will be ignored. 
- The traced model will be validated using sample input and output. If the model validation fails, the model will not be imported and will be marked as import failure.
- If the machine has GPU, the validation will use GPU to run the inference and make sure the model works on GPU.
This program is only tested for the question answering model. The top 20 question answering on huggingface have been tested.
The exported …

Add script to import huggingface model into djl model zoo

---

api/src/main/java/ai/djl/repository/JarRepository.java
api/src/main/java/ai/djl/repository/RepositoryFactoryImpl.java
api/src/test/java/ai/djl/repository/JarRepositoryTest.java

Change-Id: I2c5e92bbb1da52db2298d90f1c36cbef33873151

[api] Support queryString for JarRepository

---

api/src/main/java/ai/djl/engine/Engine.java
api/src/main/java/ai/djl/training/util/ProgressBar.java
api/src/main/java/ai/djl/util/Utils.java
api/src/main/java/ai/djl/util/cuda/CudaUtils.java
api/src/test/java/ai/djl/util/UtilsTest.java
engines/dlr/dlr-engine/src/main/java/ai/djl/dlr/jni/LibUtils.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxEngine.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/jna/LibUtils.java
engines/paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/jni/LibUtils.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtEngine.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java
engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/javacpp/LibUtils.java
engines/tensorrt/src/main/java/ai/djl/tensorrt/engine/TrtEngine.java
extensions/aws-ai/src/main/java/ai/djl/aws/sagemaker/SageMaker.java

This PR is to fix https://github.com/deepjavalibrary/djl/discussions/1848
The customer run into the get environment security issue. This PR put the environment call into a utility function and catch the exception.

Catch security exception in get environment call

---

api/src/main/java/ai/djl/repository/zoo/BaseModelLoader.java

Change-Id: I777e04d723afd0edf0dc7227ac6b6abf933a9d81

[api] Set arguments in serving.properties as model properties

---

engines/onnxruntime/onnxruntime-engine/src/test/java/ai/djl/onnxruntime/engine/OrtTest.java

Add ARM support for ONNXRuntime update unit test
I have tested it in an aarch64 machine and the unit tests passed.

Add ARM support for ONNXRuntime update unit test

---

extensions/tokenizers/rust/src/lib.rs
extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizer.java
extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizerTest.java

The tokenizer python and rust apis allow users to pass boolean flags to encode and decode methods to override special token behavior set during initialization. 
This change adds apis for the user to override the behavior in java similar to python and rust.
I also updated the naming of this flag for the decoding method to match the tokenizers naming.

Allow overriding special token flags in encode and decode methods

---

gradle.properties
gradle/wrapper/gradle-wrapper.properties

Fixes same problem as https://github.com/deepjavalibrary/djl-serving/issues/184
using workaround described in https://github.com/diffplug/spotless/issues/834
and found in
https://github.com/diffplug/spotless/tree/main/plugin-gradle#google-java-format.

Updates gradle version to 7.5 and fix format

---

engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtNDArray.java

Fix crash caused by double close OrtNDArray

[ONNX Runtime] Fix OrtNDArray double close issue

---

extensions/tokenizers/rust/src/lib.rs
extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizer.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/jni/TokenizersLibrary.java
extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizerTest.java

Adds truncation and padding support in parity with the fast tokenizers provided by hugging face tokenizers and transformers library.
This change adds the relevant java apis and makes it possible for users to configure truncation and padding behavior after loading their tokenizer model. 
The rust APIs allow for more customization than this implementation, the python tokenizer implementation, and python transofrmer implementation allow. If users need more customization than what we provide, we can extend our api to allow it.
After this change, the next step is to add functionality to load truncation and padding behavior from the serving.properties file so that these configurations can be set during initialization. A subsequent PR will address that functionality.

Add truncation and padding setter APIs to tokenizers

---

.github/workflows/native_s3_huggingface.yml

Change-Id: I253d024756373d277e51ae1cf61d2582939aacf9

[tokenizer] Build tokenizer use centos7

---

api/src/main/java/ai/djl/util/cuda/CudaUtils.java
api/src/test/java/ai/djl/util/SecurityManagerTest.java

CudaUtils throws SecurityException if read from system location is not allowed. This change catches exception if access denied during loading cudart library.

Catch SecurityException if access denied

---

engines/dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrNDManager.java
engines/ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbNDManager.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDManager.java
engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtNDManager.java
engines/paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpNDManager.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDManager.java
engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDManager.java
engines/tensorrt/src/main/java/ai/djl/tensorrt/engine/TrtNDManager.java
engines/tflite/tflite-engine/src/main/java/ai/djl/tflite/engine/TfLiteNDManager.java

…DManager (#1886)
When using pytorch-engine:0.18.0 `NDManager.newBaseManager()`, it will call `attachUncappedInternal` to attach the created PtNDManger to PtNDManager$SystemManager's `resources` field, but never detach it, thus cause memory leak.
By implementing `attachUncappedInternal` in PtNDManager$SystemManager without doing anything, avoid PtNDManager cannot be sweeped by JVM

Fixes memory leak when using NDManager.newBaseManager()

---

gradle/wrapper/gradle-wrapper.properties
tools/gradle/check.gradle

Change-Id: Ida3c741c30923b8238ee409357216af62d46b24c

[ci] Upgrade gradle to 7.5.1 and support JDK18

---

engines/mxnet/native/build.gradle
gradle.properties

Canary for cuda112 mxnet engine is failing https://github.com/deepjavalibrary/djl-demo/runs/7794346123?check_suite_focus=true

Update to mxnet 1.9.1

---

engines/ml/lightgbm/build.gradle

To match xgboost and file path, should use artifact id "lightgbm"

Fix changed name for LightGBM publishing

---

.github/workflows/native_s3_pytorch.yml
engines/pytorch/pytorch-native/build.gradle

Upgrade to PyTorch 1.12.1 Canary

Upgrade to PyTorch 1.12.1 Canary

---

.github/workflows/nightly_publish.yml

Add nightly tests for aarch64, cuda102, cuda113. These mirror the previous tests in codebuild, and have been updated to work with pytorch 1.12.1.
Here's the latest run with the new jobs all working https://github.com/deepjavalibrary/djl/actions/runs/2870780589
~With pytorch 1.12.1, I noticed something strange with the binaries. This was the error I was seeing when testing pytorch gpu builds (across all cuda versions):~
~`
Caused by: java.lang.UnsatisfiedLinkError: /root/.djl.ai/pytorch/1.12.1-cu116-linux-x86_64/libtorch_cuda_cu.so: libcublas-2854e16e.so.11: cannot open shared object file: No such file or directory
`~
~Seems like the `libtorch_cuda_cu.so` binary we published is expecting a dependent binary `libcublas-2854e16e.so.11`, which doesn't exist because the real library is …

add nightly aarch64 and gpu builds

---

api/src/main/java/ai/djl/Application.java

Change-Id: Ib5f46fe09e7e5c18d625e9ba5eca06459de24aba

[api] Add missing text_embedding application in Application.of()

---

api/src/main/java/ai/djl/ndarray/NDArray.java
api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_nn_functional.cc
engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayOtherOpTest.java

Change-Id: I877cd924ecada008a53b852092dc224fa1cfa70b

[api] Adds NDArray normalize() operator

---

engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java

Change-Id: I9a8c70df7b5ca2cac39f7c652d7f0fbf6e741aa8

[pytorch] Handles PYTORCH_VERSION is empty case

---

extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizer.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/FillMaskTranslatorFactory.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/QuestionAnsweringTranslatorFactory.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TokenClassificationTranslatorFactory.java

This makes it easier to use a manager to manage the tokenizer lifecycle. It is written as a follow up to #1941

Add manager option to HuggingFaceTokenizer Builder

---

extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/Encoding.java

Allow subclasses of Encoding to be created outside of the package.
The relevant discussion is in https://github.com/deepjavalibrary/djl/issues/1938

Make the constructor of Encoding protected.

---

api/src/main/java/ai/djl/nn/SequentialBlock.java
integration/src/main/java/ai/djl/integration/tests/model_zoo/classification/ResnetTest.java
model-zoo/src/main/java/ai/djl/basicmodelzoo/cv/classification/ResNetV1.java

This makes it so that SequentialBlocks can be used to get the internal results
required for models such as yolo.

Adds support for intermediate sequential block results

---

extensions/sentencepiece/src/main/java/ai/djl/sentencepiece/SpTokenizer.java
extensions/sentencepiece/src/test/java/ai/djl/sentencepiece/SpTokenizerTest.java

Add SP InputStream loading option

add sentence piece IS loading option

---

engines/ml/lightgbm/src/main/java/ai/djl/ml/lightgbm/LgbmNDArray.java
engines/ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbNDArray.java
engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java

This is to fix a problem in the capped manager feature which is triggered when running `gradle :integration::test` on TensorFlow engine. In `testIndexationUsesSpecificUncappedManager`, the resource, whose original manager is capped, is temporarily attached to a submanager. At the end of the try block, it will be attached back to the original capped manager. (So this error doesn't trigger test failure, but only appears as an exception).  The fix is to apply `attachUncappedInternal` which circumvents capping protection.

Fix capped manager on Tf engine

---

api/src/main/java/ai/djl/repository/zoo/Criteria.java

Fixes #1961
Change-Id: Ic3b1ca69ddbfffc030a9f301ca129d4ee7fedd2b

[api] Fixes bug in Criteria

---

engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArrayIndexer.java
integration/src/main/java/ai/djl/integration/tests/ndarray/NDIndexTest.java

This is to fix the resource closing issue in MXNet engine:
MXNetError: Check failed: delay_alloc:
which happened in the following code
```
try (NDManager manager = NDManager.newBaseManager()) {
NDArray dumb1 = manager.create(new Shape(2, 2)).get(":4, 3:4");
NDArray dumb2 = manager.create(new Shape(2)).get("3:3");
NDArray dumb3 = manager.create(new Shape(2)).get("2:3");
}
```
The fix is to check the indices within java.

[Fix] Closing error in MXNet when indexing results in an empty array

---

api/src/main/java/ai/djl/ndarray/NDArray.java
api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
api/src/main/java/ai/djl/ndarray/index/NDArrayIndexer.java
api/src/main/java/ai/djl/ndarray/index/full/NDIndexFullPick.java
api/src/main/java/ai/djl/ndarray/index/full/NDIndexFullTake.java
api/src/main/java/ai/djl/training/dataset/ArrayDataset.java
api/src/main/java/ai/djl/training/dataset/BulkDataIterable.java
api/src/main/java/ai/djl/training/dataset/DataIterable.java
api/src/main/java/ai/djl/training/dataset/RandomAccessDataset.java
basicdataset/src/test/java/ai/djl/basicdataset/MnistTest.java
basicdataset/src/test/java/ai/djl/basicdataset/RandomAccessDatasetTest.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArrayIndexer.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArrayIndexer.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArrayIndexer.java
integration/src/main/java/ai/djl/integration/tests/ndarray/NDIndexTest.java
integration/src/main/java/ai/djl/integration/tests/nn/BlockCoreTest.java

This pull requests optimizes Batch creation for ArrayDataset when using StackBatchifier .
My DJL application learns the data now in 58550ms  rather than 79843ms so 36% faster!
For applications not using range-based indexing but indices-based indexing, my DJL application would run in 66341ms , so still 20% faster. This is true for PyTorch, i get a test failure for MxNet, so this solution maybe restricted to PyTorch

Bulk Batch creation

---

engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java

The cached "files.txt" ensures DJL will still run when the machine is offline, and the native torch jar is not added to the classpath.
Projects that run DJL pytorch models might not work if the machine cannot access "https://publish.djl.ai/pytorch/files.txt" when the "detected" platform is a placeholder (for example the native torch jar is not added to the project).

Cache the PyTorch "files.txt".

---

api/src/main/java/ai/djl/ndarray/BaseNDManager.java
api/src/main/java/ai/djl/ndarray/NDArray.java
api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
engines/dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrNDManager.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtNDManager.java
engines/paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpNDManager.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDManager.java
engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDManager.java
engines/tensorrt/src/main/java/ai/djl/tensorrt/engine/TrtNDArray.java
engines/tensorrt/src/main/java/ai/djl/tensorrt/engine/TrtNDManager.java
engines/tflite/tflite-engine/src/main/java/ai/djl/tflite/engine/TfLiteNDManager.java

Fix https://github.com/deepjavalibrary/djl/issues/1970. The test code is therein.
A poential place to convert the datatype from the input data type to the target array data type is in
https://github.com/deepjavalibrary/djl/blob/aeb9135686605aab846ada67df800c954b5ebf63/api/src/main/java/ai/djl/ndarray/BaseNDManager.java#L428
Here it does the job of:
> 2\. Multiple dataType maps to the same Buffer type, we have to handle them differently
But it is not ideal to conver the Buffer type inside java
https://stackoverflow.com/questions/38745123/bytebufferasshortbuffer-cannot-be-cast-to-java-nio-floatbuffer
Cannot cast 'java.nio.HeapIntBuffer' to 'java.nio.FloatBuffer'
So here we simply throw an exception when datatypes don't match.

[fix] add data type check to array setter

---

api/src/main/java/ai/djl/Application.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/zoo/HfModelZoo.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/zoo/HfZooProvider.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/zoo/package-info.java
extensions/tokenizers/src/main/resources/META-INF/services/ai.djl.repository.zoo.ZooProvider
extensions/tokenizers/src/test/java/ai/djl/huggingface/zoo/ModelZooTest.java
extensions/tokenizers/src/test/java/ai/djl/huggingface/zoo/package-info.java

Change-Id: Ief99e4b5449c95a75582ded9a9e2549e582387c5

[huggingface] Adds Huggingface ModelZoo

---

engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArrayEx.java

Memory leaks in mxnet NDArrays when using layerNorm() because of reshaping parameters right in the model NDManager.

Fix memory leak in mxnet layerNorm().

---

api/src/main/java/ai/djl/ndarray/BaseNDManager.java
api/src/main/java/ai/djl/ndarray/NDArray.java
api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
api/src/main/java/ai/djl/ndarray/NDManager.java
api/src/main/java/ai/djl/util/passthrough/PassthroughNDManager.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDManager.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayCreationOpTest.java
integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayNumericOpTest.java

This PR implements several function. 
**gammaln** is the same as the log gamma function of [torch.lgamma](https://pytorch.org/docs/stable/generated/torch.lgamma.html), [mxnet.nd.gammaln](https://mxnet.apache.org/versions/1.9.1/api/python/docs/api/ndarray/ndarray.html?highlight=gammaln#mxnet.ndarray.gammaln).
It is used in the distributions package of torch and mxnet to calculate the probability density at the value, and this result can be used for the loss function calculation of the predicting probability distribution model.  This is the training process.
**sample** is the same as the sample distribution function of [torch.distributions.Distribution.sample](https://pytorch.org/docs/stable/distributions.html#torch.distributions.distribution.Distribution.sample), …

[api] add NDArray gammaln and sample distribution function support.

---

api/src/main/java/ai/djl/nn/recurrent/LSTM.java

This is a bug fix patch.
LSTM requires two inputs.
Tested with https://d2l.djl.ai/chapter_recurrent-modern/lstm.html and https://d2l.djl.ai/chapter_recurrent-modern/deep-rnn.html

LSTM : padding when the size of input is 2

---

extensions/timeseries/src/main/java/ai/djl/timeseries/timefeature/Lag.java
extensions/timeseries/src/main/java/ai/djl/timeseries/timefeature/TimeFeature.java
extensions/timeseries/src/main/java/ai/djl/timeseries/timefeature/TimeOffset.java
extensions/timeseries/src/test/java/ai/djl/timeseries/timefeature/TimeFeatureTest.java

Now user can use all frequencies for time series inference including "10min", "12D", "24M", "7W" etc.
And taking into account the precision problem, turn float multiple into double multiple in the get lags process

[timeseries] add all frequencies support.

---

extensions/tokenizers/rust/src/lib.rs
extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/Encoding.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizer.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/jni/TokenizersLibrary.java
extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizerTest.java

This PR adds support for utilizing the stride parameter in truncation. Users can now pass in the stride value and get the overflowing encodings. See https://github.com/deepjavalibrary/djl/issues/1996
One thought I had is whether we should add a flag to the tokenizer that indicates whether a user wants overflows returned. I'm not sure how often these overflows are used in practice, but I imagine there are cases where tokenization results in overflow but the user doesn't care about them. We could avoid JNI calls in these situations by adding a flag.

[tokenizers] support stride in tokenizers

---

basicdataset/src/main/java/ai/djl/basicdataset/tabular/utils/DynamicBuffer.java
basicdataset/src/test/java/ai/djl/basicdataset/DatasetUtilsTest.java

When the DynamicBuffer exapnd for the first time, its FloatBuffer.position would incorrectly increase by 1 resulting in an error in the location of subsequent data.
**details** 
This can reproduce the error
```java
DynamicBuffer bb = new DynamicBuffer();
for (int i = 0; i < 129; i++) {
bb.put((float) i);
}
FloatBuffer buf = bb.getBuffer();
float value = buf.get(128); // This value should be 128f but got 0f.
```
This problem arises because DynamicBuffer expands when it is about to be full but not yet full, and adds the content before the expansion to the expanded Buffer, **but because it is not yet full, the last position before the expansion of the element is not filled, and it is also added to the new Buffer**, resulting in the position error of subsequent elements

[fix] DynamicBuffer position error when expand for the firtst time

---

api/src/main/java/ai/djl/ndarray/BaseNDManager.java
api/src/main/java/ai/djl/ndarray/NDManager.java
engines/dlr/dlr-engine/src/main/java/ai/djl/dlr/engine/DlrNDManager.java
engines/ml/lightgbm/src/main/java/ai/djl/ml/lightgbm/LgbmNDManager.java
engines/ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbNDManager.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDManager.java
engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtNDManager.java
engines/paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpNDManager.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDManager.java
engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDManager.java
engines/tensorrt/src/main/java/ai/djl/tensorrt/engine/TrtNDManager.java
engines/tflite/tflite-engine/src/main/java/ai/djl/tflite/engine/TfLiteNDManager.java

fixes #1886
This creates an interface for SystemNDManagers. That way, the behavior of
skipping over various functions can be moved to the BaseNDManager instead of
each individual SystemManager

Creates a SystemNDManager interface

---

api/src/main/java/ai/djl/modality/cv/translator/BigGANTranslator.java
api/src/main/java/ai/djl/modality/cv/translator/StyleTransferTranslator.java
examples/src/main/java/ai/djl/examples/inference/StyleTransfer.java

While changing to PyTorch as the default engine I noticed some bugs in examples that rely on PyTorch engine related to https://github.com/deepjavalibrary/djl/issues/1774. 
This changes fixes those examples. I guess this also shows that we are skipping some tests in our current CI, since this issue would have been caught before had the tests run automatically.

fix some bugs in pytorch based examples

---

.github/workflows/serving_publish.yml

[ci] Publish serving tar and zip

---

engines/dlr/dlr-native/build.sh

Fix dlr-native build script. The gradle.properties should be 3 levels up instead of 2.

Fix dlr-native build script

---

extensions/timeseries/src/main/java/ai/djl/timeseries/distribution/AffineTransformed.java
extensions/timeseries/src/main/java/ai/djl/timeseries/distribution/Distribution.java
extensions/timeseries/src/main/java/ai/djl/timeseries/distribution/DistributionLoss.java
extensions/timeseries/src/main/java/ai/djl/timeseries/distribution/NegativeBinomial.java
extensions/timeseries/src/main/java/ai/djl/timeseries/distribution/StudentT.java
extensions/timeseries/src/main/java/ai/djl/timeseries/distribution/output/ArgProj.java
extensions/timeseries/src/main/java/ai/djl/timeseries/distribution/output/DistributionOutput.java
extensions/timeseries/src/main/java/ai/djl/timeseries/distribution/output/NegativeBinomialOutput.java
extensions/timeseries/src/main/java/ai/djl/timeseries/distribution/output/StudentTOutput.java
extensions/timeseries/src/main/java/ai/djl/timeseries/distribution/output/package-info.java
extensions/timeseries/src/main/java/ai/djl/timeseries/distribution/package-info.java
extensions/timeseries/src/test/java/ai/djl/timeseries/distribution/DistributionTest.java
extensions/timeseries/src/test/java/ai/djl/timeseries/distribution/package-info.java

The distribution package provides the DJL implementations of distribution in mxnet and pytorch. It contains parameterizable probability distributions and sampling functions, which allows the construction of probability prediction. This package generally follows the design of the [gluonts](https://ts.gluon.ai/stable/api/gluonts/gluonts.mx.distribution.html) package.

[timeseries] add probability distribution support for timeseries

---

engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java

Change-Id: I03070f80a0d6a73bbf209bd1de9f31e348e7c142

[pytorch] Fixes folder not exist bug when use external pytorch native library

---

api/src/main/java/ai/djl/Device.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtDeviceType.java
engines/pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/MpsTest.java

Pytorch 1.12 supports Apple’s Metal Performance Shaders (MPS) for accelerated training/inference. A simple test on HuggingFace models shows 2x-3x improvements on the inference latency over the CPU cores on an Apple M1Pro with 8 CPU and 14 GPU cores:
```
--------------------------------------------------------------------------------
Model:              roberta-hf
Device:             cpu()
Samples:            34
Model Input Length: 384
Metrics:
Total: 140.206 ± 5.880      msec
Inference: 138.794 ± 5.713      msec
Preprocess: 0.441 ± 0.553      msec
Postprocess: 0.824 ± 0.567      msec
--------------------------------------------------------------------------------
Model:              roberta-hf
Device:             mps(-1)
Samples:            34
Model Input Length: 384
Metrics:
Total: …
```

Add support for Apples' Metal Performance Shaders (MPS) in pytorch

---

api/src/main/java/ai/djl/modality/Classifications.java
api/src/main/java/ai/djl/translate/Ensembleable.java
api/src/test/java/ai/djl/modality/EnsembleTest.java

This creates a new interface Ensembleable to be used for translator outputs that can be ensembled or averaged together. The interface will later be used as part of workflows within DJL Serving.

Creates Ensembleable

---

examples/src/main/java/ai/djl/examples/inference/ObjectDetectionWithTensorflowSavedModel.java

Fixes an issue with the model path in the criteria for this example. Seems like this example has been broken since https://github.com/deepjavalibrary/djl/commit/51b38b6b165aece86cb9952b3122abe25f8d428b, which added functionality that resolves to a subdir if only 1 exists under the top level modeldir.

Fix bug in OD TF saved model example

---

extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextEmbeddingTranslator.java

Signed-off-by: Yaliang Wu <ylwu@amazon.com>
Current huggingface text embedding can work if not padding to max length. For padding to max length, the output will be wrong. Check details on https://github.com/deepjavalibrary/djl/issues/2041

enhance huggingface text embedding translator to support max length padding

---

api/src/main/java/ai/djl/nn/Parameter.java
api/src/main/java/ai/djl/nn/UninitializeParameterException.java
api/src/main/java/ai/djl/nn/UninitializedParameterException.java
api/src/main/java/ai/djl/training/Trainer.java

This throws an error with a much clearer error message in case someone fails to initialize a child block. It should help greatly reduce the time it takes to debug the error in this situation.

Handle error when forget to initialize a child block

---

engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java

[pytorch] Disables mapLocation when using MPS device

---

api/src/main/java/ai/djl/training/loss/YOLOv3Loss.java
basicdataset/src/main/java/ai/djl/basicdataset/cv/BananaDetection.java
basicdataset/src/main/java/ai/djl/basicdataset/cv/CocoDetection.java
basicdataset/src/main/java/ai/djl/basicdataset/cv/ObjectDetectionDataset.java
basicdataset/src/main/java/ai/djl/basicdataset/cv/PikachuDetection.java
djl-zero/src/main/java/ai/djl/zero/cv/ObjectDetection.java
examples/src/main/java/ai/djl/examples/training/TrainPikachu.java
examples/src/main/java/ai/djl/examples/training/TrainPikachuWithYOLOV3.java
integration/src/main/java/ai/djl/integration/tests/model_zoo/object_detection/YOLOv3Test.java
model-zoo/src/main/java/ai/djl/basicmodelzoo/cv/object_detection/yolo/YOLOV3.java
model-zoo/src/main/java/ai/djl/basicmodelzoo/cv/object_detection/yolo/package-info.java

This PR is mainly about yolov3 model in ObjectDetection.
1. add Yolov3 Model in basic model zoo and can be trained with a simple loss function for Pytorch engine. And corresponding test.
2. add Yolov3 Loss function, maybe still have some bugs to fix
3. add an example of yolov3Training: TrainPikachuWithYOLOV3
4. About ObjectDetectionDataSet, add a new function getClasses() because for most ObjectDetection Models and Translators, we need to know how many types of objects in the dataset.
5. Add ObjectDetection for DJL-Zero, and due to small bugs for yolov3, currently just train a SingleShotDetection Model.
TODO List:
1. Translator of Yolov3(actually I'm written a demo but it can't pass the code check so I stash it.
2. For COCODataSet, we should update synset.

Object Detection

---

api/src/main/java/ai/djl/modality/cv/output/CategoryMask.java

Fix CategoryMask
1. Replace Color.BLACK.getRGB() with value because Android doesn't have java.awt package.
2. Update the transparency of the background as well.

Fix CategoryMask

---

android/build.gradle
android/core/src/main/java/ai/djl/android/core/BitmapImageFactory.java
android/gradle.properties

Add draw mask for BitMapWrapper

Add draw mask for BitMapWrapper

---

android/core/src/main/java/ai/djl/android/core/BitmapImageFactory.java

Fix randomColor because Random.nextInt() upper bound is exclusive, upper bound has to be 256 to have values from 0 to 255.

Fix randomColor

---

api/src/main/java/ai/djl/modality/cv/output/CategoryMask.java

Rename transparency to opacity in CategoryMask, opacity=0 is completely transparent and opacity=255 means completely opaque.

[api] Rename transparency to opacity in CategoryMask

---

api/src/main/java/ai/djl/ndarray/internal/NDFormat.java
api/src/test/java/ai/djl/ndarray/internal/NDFormatTest.java
docs/development/development_guideline.md

The previous solution still suffers from a slowing down when printing the string outside the debugger mode. Here the solution is to utillize the existing pruning mechanism, and put the execution of `init(array)` also under the condition that the array is not too large.
A testing code is added.

[api] Allow to show NDArray content in Debugger 2

---

djl-zero/README.md
djl-zero/src/main/java/ai/djl/zero/tabular/TabularRegression.java
docs/mkdocs.yml
tools/gradle/publish.gradle

As DJL Zero now features three applications, it probably makes sense to at least make it available through Maven Central. This change begins publishing it. It also improves the documentation and README to explain DJL Zero.
While it is added to the docs site, it is only added with a relatively low-key location within the extensions section. In the future as DJL Zero is improved, it may be worth giving it a more prominent place within the Home tab.

Begin publishing DJL Zero

---

api/src/main/java/ai/djl/ndarray/index/NDArrayIndexer.java

Brief description of what this PR is about 
Requested change is in response to issue https://github.com/deepjavalibrary/djl/issues/2088, where a warning is logging constantly during training.
The log is a warning mentioning a change in default behavior. The PR removes this log, and suggests the communication of the behavior change be handled in a different way. Alternative option if this is not an acceptable solution is that we create a wrapper for the logger to consolidate certain logs, and make it so that this log appears only once.

fix: remove warning spam during training

---

api/src/main/java/ai/djl/modality/cv/translator/ImageFeatureExtractor.java
api/src/main/java/ai/djl/modality/cv/translator/ImageFeatureExtractorFactory.java
engines/pytorch/pytorch-model-zoo/src/main/java/ai/djl/pytorch/zoo/PtModelZoo.java
engines/pytorch/pytorch-model-zoo/src/test/resources/mlrepo/model/cv/image_classification/ai/djl/pytorch/resnet18_embedding/metadata.json

[pytorch] Adds image classification resnet18 base model to model zoo

---

api/src/main/java/ai/djl/ndarray/BaseNDManager.java
api/src/main/java/ai/djl/ndarray/NDArray.java
api/src/main/java/ai/djl/ndarray/NDList.java
api/src/main/java/ai/djl/ndarray/NDManager.java
api/src/main/java/ai/djl/ndarray/NDResource.java
api/src/main/java/ai/djl/training/GradientCollector.java
api/src/main/java/ai/djl/util/passthrough/PassthroughNDManager.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxGradientCollector.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtGradientCollector.java
integration/src/main/java/ai/djl/integration/tests/training/GradientCollectorIntegrationTest.java

It also adds a new function GradientCollector.zeroGradients().
As part of this, it adds a new feature to get the arrays managed by an NDManager or an NDResource. This is so all arrays can be found and have their gradients cleared when the PtGradientCollector is started.
It also means that the System NDManagers are modified to now begin tracking resources. As most things created under them are BaseNDManagers, it shouldn't be a big issue. Then, operations that don't make sense under the SystemNDManagers such as tempAttach or close have been changed to throw an exception rather than work silently.
fixes #2024

Ensure GradientCollector can clear gradients

---

engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtEngine.java
engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtModel.java
engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtNDManager.java
engines/onnxruntime/onnxruntime-engine/src/test/java/ai/djl/onnxruntime/engine/OrtTest.java

[onnxruntime] Adds disablePerSessionThreads option to model loading

---

extensions/opencv/src/test/java/ai/djl/opencv/OpenCVImageFactoryTest.java

Adds missing TestRequirements to opencv unit test

Add missing test requirements to opencv test

---

api/src/main/java/ai/djl/training/GradientCollector.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtGradientCollector.java
examples/src/test/java/ai/djl/examples/training/TrainAirfoilWithTabNetTest.java
integration/src/main/java/ai/djl/integration/tests/training/GradientCollectorIntegrationTest.java

This adds additional documentation and testing to define the API for the gradient collector. Specifically, it focuses on the gradient accumulating behavior and adds a restriction to creating multiple simultaneous global gradient collectors.
It also raises an issue for dealing with MXNet to accumulate gradients. I investigated both the setRequiresGradient with ADD mode and backwards with retainGrads and neither was correctly implementing the gradient accumulation behavior.
As this is not a terribly significant use case, I will just leave it as a TODO until there are any users who specifically request it.

Test accumulating gradient collector

---

djl-zero/src/test/java/ai/djl/zero/cv/ImageClassificationTest.java
engines/ml/xgboost/src/test/java/ai/djl/ml/xgboost/XgbModelTest.java
engines/mxnet/mxnet-model-zoo/src/test/java/ai/djl/mxnet/integration/MxSymbolBlockTest.java
engines/paddlepaddle/paddlepaddle-engine/src/test/java/ai/djl/paddlepaddle/jni/JniUtilsTest.java
engines/paddlepaddle/paddlepaddle-model-zoo/src/test/java/ai/djl/paddlepaddle/zoo/OCRTest.java
engines/tensorflow/tensorflow-model-zoo/src/test/java/ai/djl/tensorflow/integration/modality/cv/TfSsdTest.java
extensions/fasttext/src/test/java/ai/djl/fasttext/CookingStackExchangeTest.java
extensions/opencv/src/test/java/ai/djl/opencv/OpenCVImageFactoryTest.java
extensions/timeseries/src/test/java/ai/djl/timeseries/block/BlockTest.java
extensions/timeseries/src/test/java/ai/djl/timeseries/dataset/M5ForecastTest.java
extensions/timeseries/src/test/java/ai/djl/timeseries/distribution/DistributionTest.java
extensions/timeseries/src/test/java/ai/djl/timeseries/evaluator/RmsseTest.java
extensions/timeseries/src/test/java/ai/djl/timeseries/model/DeepARTest.java
extensions/timeseries/src/test/java/ai/djl/timeseries/transform/TransformTest.java
extensions/timeseries/src/test/java/ai/djl/timeseries/translator/DeepARTranslatorTest.java
extensions/timeseries/src/test/java/ai/djl/timeseries/translator/TransformerTranslatorTest.java

Two sets of changes in this PR:
- Remove duplicate usage of TestRequirements.someRequirement() in unit tests and move them to a setUp method.
- Adds missing TestRequirements on some timeseries unit tests to not run on Arm

Refactor unit test TestRequirements, add missing TestRequirements

---

examples/pom.xml

Added missing maven dependency to `timeseries` as several examples depend on that.
Current state prevents maven to compile due to the missing dependency.

[example] Add missing dependency to `timeseries`

---

engines/ml/lightgbm/src/main/java/ai/djl/ml/lightgbm/LgbmNDManager.java
engines/ml/lightgbm/src/main/java/ai/djl/ml/lightgbm/LgbmSymbolBlock.java
engines/ml/lightgbm/src/main/java/ai/djl/ml/lightgbm/jni/JniUtils.java
engines/ml/lightgbm/src/test/java/ai/djl/ml/lightgbm/LgbmModelTest.java

This makes the LightGBM inference return the same as the input type (either float32 or float64) rather than always returning float64 per the API.
In addition, it adds a bit nicer handling for creation from a Buffer in that it will also accept either a FloatBuffer or a DoubleBuffer.

LightGBM inference result matches input type

---

docs/mkdocs.yml

The broken links might be caused by the relative configuration of `docs_dir`

[doc] Add `repo_url` in order to fix broken edit links (#2140)

---

engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_inference.cc
engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_torch_reduction.cc

[pytorch] apply no_optimizer_guard only for Android

---

extensions/tokenizers/rust/src/lib.rs
extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizer.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/jni/TokenizersLibrary.java
extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizerTest.java

Add batch decoding functionality from tokenizers

[tokenizers] Add batch decoding methods for tokenizers

---

api/src/main/java/ai/djl/modality/cv/translator/ImageClassificationTranslator.java
api/src/main/java/ai/djl/modality/cv/translator/ImageClassificationTranslatorFactory.java
api/src/main/java/ai/djl/training/dataset/Dataset.java
api/src/main/java/ai/djl/translate/ExpansionTranslatorFactory.java
api/src/main/java/ai/djl/translate/Translator.java
api/src/main/java/ai/djl/translate/TranslatorOptions.java
basicdataset/src/main/java/ai/djl/basicdataset/cv/classification/ImageClassificationDataset.java
djl-zero/src/main/java/ai/djl/zero/cv/ImageClassification.java
engines/paddlepaddle/paddlepaddle-model-zoo/src/main/java/ai/djl/paddlepaddle/zoo/cv/imageclassification/PpImageClassificationTranslatorFactory.java

This creates a new tool for TranslatorOptions based on the characteristic function ((InputClass, OutputClass) -> Translator). Unlike the TranslatorFactory, it doesn't require arguments or a model. So, the TranslatorFactory is mainly used as part of model loading where the TranslatorOptions can be more broad.
In particular, it connects to both Dataset and Translator. Both of them gain a new function that will return a TranslatorOptions (matchingTranslatorOptions for the Dataset and getExpansions for the translator). Right now, I made both of these optional with a default value of null so that users don't have to define them, it is just a possibility.
To connect the TranslatorOptions and TranslatorFactory, I created a class ExpansionTranslatorFactory. This is used for the common abstraction …

Create translator options

---

.github/workflows/continuous.yml

[ci] Speed up continuous build by not uploading jacoco report

---

index.html

Made the copyright year dynamic rather than static,hence the year will be updating itself automatically.

made the sites copyright year dyanamic

---

android/pytorch-native/README.md

Increase DJL version to 0.20.0 for pytorch-native

---

engines/pytorch/pytorch-engine/README.md
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java

archlinux install pytorch in /usr/lib64/ folder, we should only
load libtorch.so when user explicitly set PYTORCH_LIBRARY_PATH.

[pytorch] No longer search java.library.path

---

examples/src/test/java/ai/djl/examples/training/TransferFreshFruitTest.java

Set random seed in unit test to ensure consistent test results. Without this, `./gradlew build` can sometimes fail locally if the accuracy dips below specified threshold in test.

Set seed in TransferFreshFruitTest for consistent results

---

api/src/main/java/ai/djl/modality/cv/ImageFactory.java

In M1 mac, `ai.djl.opencv.OpenCVImageFactory` is not supported yet but when Initialization of ImageFactory class, it tries to initialize that first and cause the Exception. 
This makes not able to use this class also when I implemented the new supported way.
To solve this bug, I think to handle UnsupportedException on ImageFactory::newInstance() is the best way. 
Due UnsupportedException is private on `nu.pattern.OpenCV`, Handle of its super class will be the solution.

Handle RuntimeException on ImageFactory::newInstance

---

extensions/audio/build.gradle
extensions/audio/src/test/java/ai/djl/audio/FFmpegAudioFactoryTest.java
extensions/audio/src/test/java/ai/djl/audio/processor/AudioProcessorTest.java

updates dependencies and adds aarch64 support for audio extension

[audio] aarch64 support for audio extension

---

.devcontainer/Dockerfile

- The package `fontconfig` is lost in Codespace Dockerfile configured with `VARIANT 11` (i.e.`mcr.microsoft.com/vscode/devcontainers/java:11`), which will cause issue #2256.
- This PR adds the lost package for the `VARIANT 11` in the Dockerfile.

Add lost package for Codespaces Dockerfile

---

basicdataset/src/main/java/ai/djl/basicdataset/nlp/TextDataset.java

[dataset] Makes TestDataset constructor protected

---

engines/ml/lightgbm/src/main/java/ai/djl/ml/lightgbm/LgbmNDManager.java

[LightGBM] Fixes byte order for fp32 and fp64 array creation

---

api/src/main/java/ai/djl/nn/AbstractBlock.java
api/src/main/java/ai/djl/nn/Block.java

[api]Fix typo in javadoc of Block and AbstractBlock

---

api/src/main/java/ai/djl/nn/AbstractBaseBlock.java

[api] Fixes typo in javadoc

---

engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_tensor.cc

A patch to the memory leak issue https://github.com/deepjavalibrary/djl/issues/2283, https://github.com/deepjavalibrary/djl/issues/2283, https://github.com/deepjavalibrary/djl/issues/2289
As pointed out in https://github.com/deepjavalibrary/djl/issues/2283, the native resources allocated by `ai.djl.pytorch.jni.PyTorchLibrary#torchIndexInit` was not released. This pr fixes it.

memory leak in Pt indexing

---

api/src/main/java/ai/djl/ndarray/BaseNDManager.java
api/src/main/java/ai/djl/ndarray/NDArray.java
api/src/main/java/ai/djl/ndarray/NDList.java
api/src/main/java/ai/djl/ndarray/NDManager.java
api/src/main/java/ai/djl/ndarray/NDResource.java
api/src/main/java/ai/djl/training/GradientCollector.java
api/src/main/java/ai/djl/util/passthrough/PassthroughNDManager.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxGradientCollector.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtGradientCollector.java
examples/src/test/java/ai/djl/examples/training/TrainAirfoilWithTabNetTest.java
integration/src/main/java/ai/djl/integration/tests/training/GradientCollectorIntegrationTest.java

This PR aims to solve the issue https://github.com/deepjavalibrary/djl/issues/2210.  As mentioned in https://github.com/deepjavalibrary/djl/pull/2232, the issue originates from `zeroGradients()` call, which was added in PR https://github.com/deepjavalibrary/djl/pull/2101 in order to solve issue https://github.com/deepjavalibrary/djl/issues/2024. As attempted in PR https://github.com/deepjavalibrary/djl/pull/2232, specifying the block to a PtGradientCollector does not really solve the problem, but it is more of adding a feature. In that PR, by default, creation of PtGradientCollector doesn't call zeroGradients(), which means the zeroGradients feature introduced in PR https://github.com/deepjavalibrary/djl/pull/2101 has been effectively reverted in the solution proposed there.
Since there …

A temporary solution to issue 2210 

---

api/src/main/java/ai/djl/ndarray/NDArray.java
api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java

[api] Fixes toDebugString() IllegalStateException if NDArray is closed

---

api/src/main/java/ai/djl/ndarray/BaseNDManager.java
api/src/main/java/ai/djl/ndarray/NDManager.java
api/src/main/java/ai/djl/util/passthrough/PassthroughNDManager.java

[api] Falls back to PassthroughNDManager if there is no engine

---

basicdataset/src/main/java/ai/djl/basicdataset/tabular/CsvDataset.java
basicdataset/src/main/java/ai/djl/basicdataset/tabular/ListFeatures.java
basicdataset/src/main/java/ai/djl/basicdataset/tabular/MapFeatures.java
basicdataset/src/main/java/ai/djl/basicdataset/tabular/MovieLens100k.java
basicdataset/src/main/java/ai/djl/basicdataset/tabular/TabularDataset.java
basicdataset/src/main/java/ai/djl/basicdataset/tabular/TabularResults.java
basicdataset/src/main/java/ai/djl/basicdataset/tabular/TabularTranslator.java
basicdataset/src/main/java/ai/djl/basicdataset/tabular/TabularTranslatorFactory.java
basicdataset/src/main/java/ai/djl/basicdataset/tabular/utils/Feature.java
basicdataset/src/main/java/ai/djl/basicdataset/tabular/utils/Featurizer.java
basicdataset/src/main/java/ai/djl/basicdataset/tabular/utils/Featurizers.java
basicdataset/src/test/java/ai/djl/basicdataset/AirfoilRandomAccessTest.java
basicdataset/src/test/java/ai/djl/basicdataset/AmesRandomAccessTest.java
basicdataset/src/test/java/ai/djl/basicdataset/MovieLens100kTest.java
basicdataset/src/test/java/ai/djl/basicdataset/tabular/TabularTranslatorFactoryTest.java
basicdataset/src/test/java/ai/djl/basicdataset/tabular/package-info.java
djl-zero/src/main/java/ai/djl/zero/tabular/TabularRegression.java
examples/src/main/java/ai/djl/examples/training/transferlearning/TrainAmazonReviewRanking.java
extensions/tablesaw/src/main/java/ai/djl/tablesaw/TablesawDataset.java
extensions/timeseries/src/main/java/ai/djl/timeseries/dataset/TimeFeaturizer.java

This creates a standard TabularTranslator based on the Featurizer and Feature interface. Accompanying it is an ExpansionTranslatorFactory so it has two possible inputs (MapFeatures or ListFeatures) and three outputs (TabularResults, Regression, and Classification).
The MapFeatures and ListFeatures are created to help avoid complications with class lookups. Otherwise, it would require weird unchecked casting: (Class<List<String>>)(Class<?>)List.class.
As part of this, it also expands the Featurizer to also include capabilities for deFeaturizing. The helper of DataFeaturizer is still around for Featurizers that don't support the label deFeaturization.

Creates the TabularTranslator

---

api/src/main/java/ai/djl/ndarray/NDScope.java
api/src/main/java/ai/djl/util/NativeResource.java
api/src/test/java/ai/djl/ndarray/NDScopeTest.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java

If you are trying to use an NDArray that is already closed you get the error message "Native resource has been released already. ".
If you know which NDArray it is - where it was created and where it was closed - you should have no problem solving the problem. But imagine the case where you are not the one trying to use the already closed NDArray, but some generic code does, maybe you have set an NDScope somewhere, so you know who closed it, but still don't know where it was created. In such cases where you do not have a clue it would be helpful if you could set a switch at compile time to get information about the NDArray:
- uid + creation time
- name
- creation stack trace
- closing stack trace
This PR adds code to provide such info if you set the switch …

if native resource closed, on demand info to identify NDArray

---

api/src/main/java/ai/djl/BaseModel.java
api/src/main/java/ai/djl/modality/nlp/embedding/TrainableWordEmbedding.java
api/src/main/java/ai/djl/nn/Block.java
api/src/main/java/ai/djl/nn/core/ConstantEmbedding.java
api/src/main/java/ai/djl/nn/core/Embedding.java
engines/ml/lightgbm/src/main/java/ai/djl/ml/lightgbm/LgbmModel.java
engines/ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbModel.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxModel.java
engines/mxnet/mxnet-model-zoo/src/main/java/ai/djl/mxnet/zoo/nlp/embedding/utils/BuildModelZooWordEmbedding.java
engines/mxnet/mxnet-model-zoo/src/test/java/ai/djl/mxnet/integration/MxSymbolBlockTest.java
engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtModel.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtModel.java
engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfModel.java
engines/tensorrt/src/main/java/ai/djl/tensorrt/engine/TrtModel.java
examples/src/main/java/ai/djl/examples/training/transferlearning/TrainResnetWithCifar10.java
extensions/fasttext/src/main/java/ai/djl/fasttext/zoo/nlp/word_embedding/FtWord2VecWordEmbedding.java

This changes the standard for DJL behavior with preTrained blocks. As of now, they should also start out with frozen parameters. This has been applied to the embeddings.
It was previously applied only to PyTorch, but as of now applies to all models. However, I did leave a carveout for models. It adds a boolean "wasLoaded" so that if you load a model and then create a Trainer directly from it, it will not be frozen. If you load a model and then append some new layers to it (as we have several examples of), then it will need to be unfrozen to retrain.
fixes #2351

Creates standard for PreTrained behavior

---

api/src/main/java/ai/djl/translate/Batchifier.java
api/src/main/java/ai/djl/translate/PaddingStackBatchifier.java
api/src/main/java/ai/djl/translate/SimplePaddingStackBatchifier.java
integration/src/main/java/ai/djl/integration/tests/translate/SimplePaddingStackBatchifierTest.java

Creates a SimplePaddingStackBatchifier that will pad all of the dimensions rather than requiring the dimensions to be manually specified.
It is also supported by Batchifier.fromString.

Creates SimplePaddingStackBatchifier

---

extensions/spark/src/main/scala/ai/djl/spark/task/BasePredictor.scala
extensions/spark/src/main/scala/ai/djl/spark/task/text/TextEmbedder.scala
extensions/spark/src/main/scala/ai/djl/spark/task/text/TextPredictor.scala
extensions/spark/src/main/scala/ai/djl/spark/task/vision/ImageClassifier.scala
extensions/spark/src/main/scala/ai/djl/spark/task/vision/ImagePredictor.scala
extensions/spark/src/main/scala/ai/djl/spark/translator/text/TextEmbeddingTranslator.scala
extensions/spark/src/main/scala/ai/djl/spark/translator/vision/ImageClassificationTranslator.scala

Change Spark extension API
- Implement HasInputCol/HasInputCols, HasOutputCol/HasOutputCols in each specific task
- Add prediction column to the input dataframe instead of replacing the columns
- ImageClassifier output struct type output
- TextTokenizer output struct type output

[spark] Change Spark extension API

---

api/src/main/java/ai/djl/ndarray/BaseNDManager.java
api/src/main/java/ai/djl/ndarray/NDArray.java
api/src/main/java/ai/djl/ndarray/NDList.java
api/src/main/java/ai/djl/ndarray/NDManager.java
api/src/main/java/ai/djl/ndarray/NDResource.java
api/src/main/java/ai/djl/training/GradientCollector.java
api/src/main/java/ai/djl/util/passthrough/PassthroughNDManager.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxGradientCollector.java
engines/mxnet/mxnet-model-zoo/src/test/java/ai/djl/mxnet/integration/modality/nlp/WordEmbeddingTest.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtGradientCollector.java
examples/src/test/java/ai/djl/examples/training/TrainAirfoilWithTabNetTest.java
integration/src/main/java/ai/djl/integration/tests/training/GradientCollectorIntegrationTest.java
integration/src/main/java/ai/djl/integration/util/TestUtils.java
testing/src/main/java/ai/djl/testing/TestRequirements.java

The support was removed as part of "A temporary solution to issue 2210  (#2304)". This then reverts that commit while making a smaller change. It keeps the tests designating the desired behavior but notes the problematic engines that fail them.

Adds back support for getting managed Arrays

---

engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxModel.java
examples/src/main/java/ai/djl/examples/training/transferlearning/TrainResnetWithCifar10.java

In #2360, the behavior of using pre-trained models was to freeze parameters. However freezing the parameters on MXNet seems to cause a significant performance regression for training. This removes those changes for a temporary workaround until a deeper investigation can take place with possible changes to the behavior of freeze and requiresGrad

Remove performance issues from freezing MXNet

---

bom/build.gradle

[bom] Simplify BOM build script

---

.github/workflows/docker_publish.yml
docker/spark/Dockerfile
extensions/spark/setup/setup.py

[spark] Add docker_publish action

---

api/src/main/java/ai/djl/nn/AbstractBaseBlock.java
api/src/main/java/ai/djl/nn/core/Linear.java

This aims to solve the issue https://github.com/deepjavalibrary/djl/issues/2446
As pointed out there in the issue, the loadMetadata method in Linear missed the inputShapes (plural). In this PR it is added.

Load inputShapes in the loadMetadata method of Linear block

---

android/build.gradle
android/pytorch-native/build.gradle
basicdataset/build.gradle
engines/mxnet/mxnet-engine/build.gradle
engines/mxnet/mxnet-model-zoo/build.gradle
engines/mxnet/native/build.gradle
engines/paddlepaddle/paddlepaddle-model-zoo/build.gradle
engines/paddlepaddle/paddlepaddle-native/build.gradle
engines/pytorch/pytorch-model-zoo/build.gradle
engines/pytorch/pytorch-native/build.gradle
engines/tensorflow/tensorflow-model-zoo/build.gradle
engines/tensorflow/tensorflow-native/build.gradle
engines/tensorrt/build.gradle
engines/tflite/tflite-native/build.gradle
examples/build.gradle
extensions/fasttext/build.gradle
extensions/sentencepiece/build.gradle
extensions/spark/build.gradle
extensions/tokenizers/build.gradle
integration/build.gradle
model-zoo/build.gradle
tools/gradle/release.gradle

[ci] Uses recommended way to create task in build.gradle

---

.github/workflows/serving_publish.yml

[ci] Refresh gradle dependency when publishing djl-serving

---

api/src/main/java/ai/djl/ndarray/NDArray.java
api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_torch_pointwise.cc
engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayElementArithmeticOpTest.java

Added support for Tensor.unique (for tests). Solves issue https://github.com/deepjavalibrary/djl/issues/2407
Added support for Tensor.bmm and Tensor.xlogy (pytorch impls only). Solves issue https://github.com/deepjavalibrary/djl/issues/2349
The unique feature in this PR is not as updated as that in PR https://github.com/deepjavalibrary/djl/pull/2417

Add support for unique, bmm, xlogy

---

extensions/spark/src/main/scala/ai/djl/spark/task/binary/BinaryPredictor.scala
extensions/spark/src/main/scala/ai/djl/spark/task/vision/ImageClassifier.scala
extensions/spark/src/main/scala/ai/djl/spark/task/vision/ImageEmbedder.scala
extensions/spark/src/main/scala/ai/djl/spark/task/vision/InstanceSegmenter.scala
extensions/spark/src/main/scala/ai/djl/spark/task/vision/ObjectDetector.scala
extensions/spark/src/main/scala/ai/djl/spark/task/vision/SemanticSegmenter.scala

[spark] Change image predictors to return complex struct type

---

.github/workflows/serving_publish.yml

Upload new serving tarball will break homebrew djl-serving package signature

[ci] Avoid re-publish serving tarball

---

api/src/main/java/ai/djl/util/Platform.java
api/src/test/java/ai/djl/util/PlatformTest.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java

[pytorch] Respect PYTORCH_FLAVOR override to download libtorch

---

api/src/main/java/ai/djl/inference/Predictor.java
api/src/main/java/ai/djl/inference/streaming/ChunkedBytesSupplier.java
api/src/main/java/ai/djl/inference/streaming/IteratorBytesSupplier.java
api/src/main/java/ai/djl/inference/streaming/PublisherBytesSupplier.java
api/src/main/java/ai/djl/inference/streaming/StreamingBlock.java
api/src/main/java/ai/djl/inference/streaming/StreamingTranslator.java
api/src/main/java/ai/djl/inference/streaming/package-info.java
api/src/main/java/ai/djl/nn/SequentialBlock.java
api/src/main/java/ai/djl/translate/ServingTranslator.java
api/src/test/java/ai/djl/inference/streaming/ChunkedBytesSupplierTest.java
api/src/test/java/ai/djl/inference/streaming/IteratorBytesSupplierTest.java
api/src/test/java/ai/djl/inference/streaming/PublisherBytesSupplierTest.java
api/src/test/java/ai/djl/inference/streaming/package-info.java
integration/src/main/java/ai/djl/integration/tests/inference/StreamingTest.java

This is to replace #2447 to add support for an iterable streaming version of predict. It creates a StreamingBlock and a streamingTranslator. Then, both are added as part of a new call on Predictor.
In addition, it also adds two new BytesSupplier: a pull based IterableBytesSupplier and a asynchronous Pub-Sub based PublisherBytesSupplier.

Streaming Predict and streamable BytesSupplier

---

docker/spark/Dockerfile
examples/src/main/java/ai/djl/examples/inference/whisper/WhisperModel.java
extensions/audio/src/main/java/ai/djl/audio/translator/WhisperTranslator.java
extensions/audio/src/main/java/ai/djl/audio/translator/WhisperTranslatorFactory.java
extensions/audio/src/main/java/ai/djl/audio/translator/package-info.java
extensions/spark/build.gradle
extensions/spark/src/main/scala/ai/djl/spark/task/BasePredictor.scala
extensions/spark/src/main/scala/ai/djl/spark/task/audio/BaseAudioPredictor.scala
extensions/spark/src/main/scala/ai/djl/spark/task/audio/SpeechRecognizer.scala
extensions/spark/src/main/scala/ai/djl/spark/task/audio/WhisperSpeechRecognizer.scala

[spark] Add audio predictors

---

api/src/main/java/ai/djl/modality/Input.java
api/src/main/java/ai/djl/modality/Output.java
api/src/main/java/ai/djl/util/PairList.java
api/src/test/java/ai/djl/modality/InputOutputTest.java
extensions/timeseries/src/main/java/ai/djl/timeseries/TimeSeriesData.java

This adds a full serialization rather than just part of content or properties to the Input and Output. It also requires adding equals and hash to them as well.

Add encode and decode to Input and Output

---

extensions/tokenizers/README.md

With help from @frankfliu ([discussion](https://github.com/deepjavalibrary/djl/discussions/2507#discussioncomment-5548949)), added `DeferredTranslatorFactory` to the example code in the
Hugging Face Tokenizers README so it will run as-is.

[docs] add DeferredTranslatorFactory to tokenizers example

---

api/src/main/java/ai/djl/translate/ServingTranslatorFactory.java

[api] Fail model loading if specified translator not found

---

docker/spark/Dockerfile
extensions/spark/setup/djl_spark/task/text/text_generator.py

Add text generation in pyspark. Since text generation models are not traceable. So it's only supported in pyspark now.

[spark] Add text generation in pyspark

---

api/src/main/java/ai/djl/inference/Predictor.java
integration/src/main/java/ai/djl/integration/tests/inference/StreamingTest.java
integration/src/main/java/ai/djl/integration/tests/model_zoo/classification/ResnetTest.java

Adds a way to check if streaming is supported

---

extensions/spark/setup/djl_spark/task/text/text2text_generator.py

Add text2text generation, see example: https://github.com/deepjavalibrary/djl-demo/pull/331

[spark] Add text2text generation

---

docs/development/inference_performance_optimization.md

Fixes some grammar, adds additional explanation, links to the WorkLoadManager and list of configurations.

Cleans inference performance optimization doc

---

extensions/spark/src/main/scala/ai/djl/spark/task/text/HuggingFaceTextDecoder.scala
extensions/spark/src/main/scala/ai/djl/spark/task/text/HuggingFaceTextEncoder.scala
extensions/spark/src/main/scala/ai/djl/spark/task/text/HuggingFaceTextTokenizer.scala

Set default translator factory to null for tokenizers because tokenizers don't use translatorFactory.

[spark] Set default translator factory to null for tokenizers

---

api/src/main/java/ai/djl/util/Platform.java
api/src/test/java/ai/djl/util/PlatformTest.java

[api] Fixed detect platform for different CUDA version

---

.github/workflows/nightly_publish.yml
api/src/main/java/ai/djl/util/Platform.java
api/src/test/java/ai/djl/util/PlatformTest.java
engines/pytorch/pytorch-engine/README.md
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java
engines/pytorch/pytorch-jni/build.gradle
engines/pytorch/pytorch-native/build.gradle
engines/pytorch/pytorch-native/build.sh
gradle.properties

[pytorch] Upgrade PyTorch to 2.0.0

---

extensions/spark/build.gradle

Change spark dependencies to api so that these dependencies can be exported to downstream apps.

[spark] Change spark dependencies to api

---

engines/pytorch/pytorch-engine/README.md
gradle.properties

[pytorch] Changes default pytorch version to 1.13.1

---

docker/spark/Dockerfile

[spark] Upgrade dependency version in Dockerfile

---

extensions/tokenizers/rust/src/lib.rs
extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizer.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/jni/TokenizersLibrary.java
extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/BpeTokenizerBuilderTest.java

This PR allows creating huggingface tokenizers using the BPE model. It also adds some entrypoint that can then be used when other models will need to be added.
Related to https://github.com/deepjavalibrary/djl/issues/2533
I will need some help, since there is some point I must have missed: I have link errors even after building the jni lib.
This is new functionality, the existing apis will continue to work as-is

[huggingface] allow creating BPE huggingface tokenizers

---

api/src/main/java/ai/djl/ndarray/NDArray.java

[api] Adds support for unsigned datatype

---

.github/workflows/nightly_android.yml

[ci] Upgrade github action gradle plugin to v3

---

.github/workflows/serving_publish.yml

[ci] Avoid upload djl-serving.tar to S3 if already exist

---

api/src/main/java/ai/djl/inference/Predictor.java

[api] Allows subclass access member variable of Predictor

---

api/src/main/java/ai/djl/util/cuda/CudaUtils.java

[api] Add 0 padding to cuda version if lower than 10.x

---

api/src/main/java/ai/djl/inference/Predictor.java

[api] Makes PredictorContext constructor public

---

api/src/main/java/ai/djl/modality/cv/transform/RandomFlipLeftRight.java
api/src/main/java/ai/djl/modality/cv/transform/RandomFlipTopBottom.java
api/src/main/java/ai/djl/training/dataset/RandomSampler.java
build.gradle
engines/ml/lightgbm/src/main/java/ai/djl/ml/lightgbm/LgbmEngineProvider.java
engines/ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbEngineProvider.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxEngineProvider.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxSymbolBlock.java
engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtEngineProvider.java
engines/paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpEngineProvider.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtEngineProvider.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtSymbolBlock.java
engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfEngineProvider.java
engines/tensorrt/src/main/java/ai/djl/tensorrt/engine/TrtEngineProvider.java
engines/tflite/tflite-engine/src/main/java/ai/djl/tflite/engine/TfLiteEngineProvider.java
engines/tflite/tflite-engine/src/main/java/org/tensorflow/lite/Tensor.java
extensions/timeseries/src/main/java/ai/djl/timeseries/transform/ExpectedNumInstanceSampler.java
tools/conf/findbugs-exclude.xml

[ci] Upgrade spotbugs to 5.0.14

---

.github/workflows/nightly_android.yml

Android Continuous action is failing due to being unable to find v3 of gradle/gradle-build-action, reverting to gradle/gradle-build-action@v2, referencing https://github.com/gradle/gradle-build-action it looks like latest release is still v2, so we will monitor

[fix] ci fails looking for v3 reverting to v2

---

api/src/main/java/ai/djl/translate/ServingTranslatorFactory.java
api/src/main/java/ai/djl/util/ClassLoaderUtils.java

[api] Move compileJava() into ClassLoaderUtils

---

engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java

[pytorch] Load dependencies with specific order

---

.github/workflows/build_triton_and_ft.yml
tools/scripts/build_ft_deps.sh

build these two deps from source

add Triton and FasterTransformers source build instruction

---

engines/pytorch/pytorch-native/README.md

[docs] Update pytorch native JNI development document

---

api/src/main/java/ai/djl/inference/Predictor.java
api/src/main/java/ai/djl/inference/streaming/StreamingTranslator.java
api/src/main/java/ai/djl/translate/ServingTranslator.java
integration/src/main/java/ai/djl/integration/tests/inference/StreamingTest.java

This creates a new StreamOutput to manage the results of predictStreaming, that can either can iterative or asynchronous outputs.

Creates asynchronous predictStreaming

---

api/src/main/java/ai/djl/training/loss/TabNetClassificationLoss.java
api/src/main/java/ai/djl/training/loss/TabNetRegressionLoss.java
basicdataset/src/main/java/ai/djl/basicdataset/tabular/TabularDataset.java
basicdataset/src/main/java/ai/djl/basicdataset/tabular/TabularTranslator.java
examples/src/main/java/ai/djl/examples/training/TrainAirfoilWithTabNet.java
model-zoo/src/main/java/ai/djl/basicmodelzoo/tabular/TabNet.java

Fixes the tabnet model which pre-calculates loss to return the loss per element rather than the mean. Otherwise, it can't be unbatched.
Also, adds helper getRowDirect to make it easier to test predictor from a dataset and adds prediction to the tabnet example.

Fix tabnet predictor

---

docs/development/setup.md

This is clarifying the setup for running Example classes on M1 macs. 
We want to give new users the best experience possible. The context is, as a new user - the need to change engines is not clear, not is it clear that MXNet (the default Engine) doesn't work on M1 Macs.

[doco] Setup - Running on M1 Macs

---

api/src/main/java/ai/djl/engine/Engine.java
api/src/test/java/ai/djl/DeviceTest.java

[api] Masks sensitive env vars in debug print out

---

.github/workflows/native_s3_xgboost.yml
engines/ml/xgboost/build.gradle
engines/ml/xgboost/src/test/java/ai/djl/ml/xgboost/XgbModelTest.java

[xgboost] Adds xgboost aarch64 support

---

docs/pytorch/pytorch-djl-ndarray-cheatsheet.md

Add a comparison table and a cheatsheet between djl NDArray and  PyTorch tensor.
see https://github.com/i10416/djl/blob/docs/pytorch-djl-ndarray-cheatshet/docs/pytorch/pytorch-djl-ndarray-cheatsheet.md to check rendered md.
rel https://github.com/deepjavalibrary/djl/issues/2647

docs: add pytorch vs djl ndarray cheatsheet

---

engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/javacpp/LibUtils.java

Fixes: https://github.com/deepjavalibrary/djl/issues/2318

[tensorflow] Reload javacpp properties

---

extensions/timeseries/README.md

[timeseries] Updates timeseries README

---

docs/pytorch/pytorch-djl-ndarray-cheatsheet.md

`{{` is a reserved tag by Liquid, which parses the .md file before it gets rendered as markdown. I changed all `{{` into `{ {` to get around the Liquid parsing stuff, and fixed some missing instances of closing/opening braces as well.

Fix liquid parsing issues in pytorch ndarray cheatsheet

---

api/src/main/java/ai/djl/modality/cv/output/BoundingBox.java
api/src/main/java/ai/djl/modality/cv/output/Rectangle.java
api/src/test/java/ai/djl/modality/cv/output/RectangleTest.java
api/src/test/java/ai/djl/modality/cv/output/package-info.java

Add handling on the corner case that two boxes are not intersected

fix getIOU bug

---

engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/IValueUtils.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_inference.cc

This PR is an attempt to support running inference on separate cuda streams for pytorch engine. By doing this, we can maximize GPU utilization when running concurrent inference requests on GPU.
Also added a boolean flag `inferenceSeparateCudaStream` controlled through system properties `"ai.djl.pytorch.inference_separate_cuda_stream"` to determine whether this new feature is enabled.
I considered exposing the full cuda stream related pytorch api through JNI but in the end decided to only expose a high level boolean flag, mainly because:
- it's much easier to expose only this boolean flag
- there's no other use case that requires the full cuda stream api

pytorch support inference on separate cuda stream

---

.github/workflows/build_triton_and_ft.yml
tools/scripts/build_ft_deps.sh

- Clones FT backend from forked repo - https://github.com/rohithkrn/fastertransformer_backend.git which adds llama support. Backend repo [points](https://github.com/rohithkrn/fastertransformer_backend/blob/llama_support/CMakeLists.txt#L113) to FT repo with model implementation which taken from void-main's PR to FT repo.
- Added `is_llama_build` flag to isolate from existing setup so that it will be easy to switch. This also pushes binaries to a new s3 path (`fastertransformer/llama`) which probably needs creation.

Setup custom ft build for Llama support

---

api/src/main/java/ai/djl/util/Utils.java

Adds the Utils.getEnvOrSystemProperty that also supports a default value.

Adds Utils.getEnvOrSystemProperty with default

---

extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextEmbeddingTranslator.java

Fixes #2744, support onnx model for TextEmbeddingTranslator

---

api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArrayEx.java

[api] Implements NDArray.toType() for NDArrayAdapter

---

api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java

[api] Fixes NDArray.toDevice() missing name issue

---

engines/pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/PtNDArrayTest.java
engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_tensor.cc

[pytorch] Avoid toByteBuffer() crash for large tensor

---

api/src/main/java/ai/djl/nn/Block.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtModel.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArrayEx.java
examples/src/test/java/ai/djl/examples/training/TrainPikachuTest.java
integration/src/main/java/ai/djl/integration/tests/model_zoo/object_detection/SingleShotDetectionTest.java
model-zoo/src/main/java/ai/djl/basicmodelzoo/BasicModelZoo.java

The big goal here is to implement `PtNDArrayEx.multiBoxDetection()` (currently throws `NotImplementException`) so that you can run `PikachuTraining` with Pytorch and so you can run SSD Training on M1 Macs.
The implementation for this is derived from:
https://github.com/apache/mxnet/blob/master/src/operator/contrib/multibox_detection.cc
and
https://github.com/apache/mxnet/blob/master/src/operator/contrib/multibox_detection-inl.h
This implementation is based on implementing the unit test on the C++ side and comparing the steps internally.

PtndArrayEx.multiboxDetection() implementation

---

api/src/main/java/ai/djl/ndarray/NDList.java
api/src/test/java/ai/djl/ndarray/NDSerializerTest.java

[api] Fixed NDList decode numpy file bug

---

CODE_OF_CONDUCT.md
docker/README.md
docs/development/example_dataset.md
docs/development/external_libraries.md
docs/development/profiler.md
docs/mxnet/how_to_convert_your_model_to_symbol.md
docs/pytorch/how_to_convert_your_model_to_torchscript.md
docs/pytorch/pytorch-djl-ndarray-cheatsheet.md
examples/docs/stable_diffusion.md
extensions/timeseries/docs/forecast_with_M5_data.md

This fixes the markdown headers to be h1 so they render correctly in docs.

[docs] Fixes markdown headers

---

api/src/main/java/ai/djl/training/listener/EarlyStoppingListener.java
integration/src/main/java/ai/djl/integration/tests/training/listener/EarlyStoppingListenerTest.java
integration/src/main/java/ai/djl/integration/tests/training/listener/package-info.java

This PR implements a listener for early stopping as described in #38. And takes the code @gforman44  and implements that in a `TrainingListener`
resolves #38

[api] Added Early stopping configuration (#38)

---

api/src/main/java/ai/djl/Device.java
api/src/main/java/ai/djl/training/ParameterStore.java
api/src/test/java/ai/djl/DeviceTest.java

This creates an abstraction for combining devices into a single device. The main use case for now is in DJL Serving TP_parallel. It will allow us to create a WorkerGroup and a PyPredictor for a set of devices and then track the usage of devices properly. It could also be used later for multi-gpu training or other multi-device cases.

Creates MultiDevice

---

api/src/main/java/ai/djl/inference/streaming/PublisherBytesSupplier.java
api/src/test/java/ai/djl/inference/streaming/PublisherBytesSupplierTest.java

[api] Refactor PublisherBytesSupplier.java

---

extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizer.java
extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizerTest.java

[tokenizer] Fixes tokenizer bug

---

api/src/main/java/ai/djl/ndarray/NDArray.java
api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
api/src/main/java/ai/djl/ndarray/NDArrays.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_torch_pointwise.cc
engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayNumericOpTest.java
integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayOtherOpTest.java

Added erf and atan2 operators for arrays

Add erf and atan2

---

api/src/main/java/ai/djl/ndarray/NDArray.java
api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_torch_other.cc
engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayOtherOpTest.java

- Added 2-dimensional FFT
- Added 2-dimensional inverse FFT

Add FFT2 and FFT2 inverse

---

extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizer.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/FillMaskBatchTranslator.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/FillMaskTranslator.java
extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizerTest.java

[tokenizer] Not returns overflow tokens by default

---

engines/mxnet/native/build.gradle
engines/paddlepaddle/paddlepaddle-native/build.gradle
engines/tensorflow/tensorflow-native/build.gradle
engines/tflite/tflite-native/build.gradle

This property is necessary to avoid conflicts in building multiple flavors which can be observed in the native properties file not matching the jar for some engine builds.

Fixes archiveBaseName in native builds

---

integration/src/main/java/ai/djl/integration/tests/training/listener/EarlyStoppingListenerTest.java

This changes the test from requiring the early stopping at a particular epoch to ensuring that it stops early due to time constraints. This should help reduce the chances of being flaky due to race conditions.

[CI] Fixes flaky early stopping test

---

engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtEngineProvider.java

[pytorch] Revert InstanceHolder for PyTorch engine

---

extensions/tokenizers/src/main/python/huggingface_converter.py
extensions/tokenizers/src/main/python/huggingface_models.py
extensions/tokenizers/src/main/python/model_zoo_importer.py

[tokenizer] Handles import huggingface model zoo exception case

---

extensions/tokenizers/src/main/python/huggingface_models.py

This updates huggingface_models.py to support converting Safetensors models as well as pytorch when running the Model Zoo importer

Tokenizers: Updated huggingface_models.py to support Safetensors models as well as pytorch

---

extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextEmbeddingTranslator.java

[tokenizer] Uses fp32 for TextembeddingTranslator clip()

---

api/src/main/java/ai/djl/util/cuda/CudaUtils.java
api/src/test/java/ai/djl/util/SecurityManagerTest.java
api/src/test/java/ai/djl/util/cuda/CudaUtilsTest.java

[api] Use folk java process to avoid jvm consume GPU memory

---

engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java

[pytorch] Ensure shared library loading order for aarch64

---

apt.txt
docker/README.md
docker/tensorrt/Dockerfile
docker/windows/Dockerfile
docs/development/setup.md

[docs] Updates documents to use JDK 17

---

api/src/main/java/ai/djl/training/evaluator/AbstractAccuracy.java
api/src/main/java/ai/djl/training/evaluator/BoundingBoxError.java
api/src/main/java/ai/djl/training/evaluator/Evaluator.java
api/src/main/java/ai/djl/training/evaluator/IndexEvaluator.java
api/src/main/java/ai/djl/training/listener/EvaluatorTrainingListener.java
api/src/main/java/ai/djl/training/loss/AbstractCompositeLoss.java
api/src/main/java/ai/djl/training/loss/Loss.java
extensions/timeseries/src/main/java/ai/djl/timeseries/evaluator/Rmsse.java

This PR proposes adding a method to the `Evaluator` abstract class
```java
public void updateAccumulators(String[] keys, NDList labels, NDList predictions) {
for (String key : keys) {
updateAccumulator(key, labels, predictions);
}
}
```
and then overriding this in subclasses to more efficiently update accumulators.
The reason is that the use of `EvaluatorTrainingListener` can dominate training time - at least when using Apple Silicon + MPS with the recent PR https://github.com/deepjavalibrary/djl/pull/2873
Part of the issue seems to be that `updateAccumulator` needs to be called multiple times for different evaluators after each batch, e.g. accuracy and loss. This results in the same values being recalculated multiple times and transferred to the CPU. The recalculation itself is quite …

Add Evaluator support to update multiple accumulators

---

api/src/main/java/ai/djl/modality/cv/translator/YoloV8Translator.java
examples/src/main/java/ai/djl/examples/inference/Yolov8Detection.java
examples/src/test/java/ai/djl/examples/inference/Yolov8DetectionTest.java
examples/src/test/resources/yolov8_synset.txt

- Improved post-processing performance up to 40x by reducing expensive native calls
- Additional argument 'maxBox' added to improve post-processing performance by reducing number of considered bounding boxes
- Sunset file fixed,, previous version ignored first 4 rows, so recognized classes were 4 off. Adding 4 rows header fixes the problem. New headers pointing to ultralytics doc pages and original coco dataset page.
- Change on yolov8_synset.txt is a backward incompatible, example sunset file was incorrectly formatted and predicted class categories were off by 4.

Yelov8 Translator optimization

---

engines/llama/build.gradle
engines/llama/src/main/java/ai/djl/llama/engine/LlamaModel.java
engines/llama/src/main/java/ai/djl/llama/zoo/LlamaModelZoo.java
engines/llama/src/main/java/ai/djl/llama/zoo/LlamaZooProvider.java
engines/llama/src/main/java/ai/djl/llama/zoo/package-info.java
engines/llama/src/main/resources/META-INF/services/ai.djl.repository.zoo.ZooProvider
engines/llama/src/test/java/ai/djl/llama/zoo/LlamaModelZooTest.java
engines/llama/src/test/java/ai/djl/llama/zoo/package-info.java

[llama.cpp] Adds llama.cpp huggingface model zoo

---

.github/workflows/serving_publish.yml

Add AWSCurl release into the build pipeline

add awscurl release

---

.github/workflows/native_jni_s3_pytorch.yml

[ci] Fix build failure for `build-pytorch-jni-linux`

---

.github/workflows/native_jni_s3_pytorch.yml
.github/workflows/native_s3_tflite.yml

[ci] Fixes native ci build failure

---

api/src/main/java/ai/djl/Device.java
api/src/test/java/ai/djl/DeviceTest.java

This improves upon the creation of MultiDevice in #2819 by moving the getDevices function to the main Device class. This can simplify the usage of something which is potentially a MultiDevice and make it easier to check for the presence of a MultiDevice.

Adds Device.getDevices() for all Device

---

api/src/main/java/ai/djl/engine/Engine.java
docs/development/troubleshooting.md
engines/ml/lightgbm/src/main/java/ai/djl/ml/lightgbm/LgbmEngineProvider.java
engines/ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbEngineProvider.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxEngineProvider.java
engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtEngineProvider.java
engines/paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpEngineProvider.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtEngineProvider.java
engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfEngineProvider.java
engines/tensorrt/src/main/java/ai/djl/tensorrt/engine/TrtEngineProvider.java
engines/tensorrt/src/test/java/ai/djl/tensorrt/engine/TrtEngineTest.java
engines/tensorrt/src/test/java/ai/djl/tensorrt/engine/TrtNDManagerTest.java
engines/tensorrt/src/test/java/ai/djl/tensorrt/integration/TrtTest.java
engines/tflite/tflite-engine/src/main/java/ai/djl/tflite/engine/TfLiteEngineProvider.java

fixes #2875
reverts #2876, #2884
This adds new support for DJL manual initialization of engines to support `DJL_ENGINE_MANUAL_INIT`. Once done, no engines providers will be found or loaded on startup. Instead, they can be added manually by:
```java
PtEngineProvider provider = new PtEngineProvider();
provider.getEngine(); // Optional, throws exception if the provider can't load
Engine.registerEngine(provider);
Engine.setDefaultEngine(provider.getEngineName()); // Optional, sets as default
```

Creates DJL manual engine initialization

---

engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java
engines/pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/ALibUtilsTest.java

[pytorch] Allows to load libstdc++.so.6 form different location

---

api/src/main/java/ai/djl/repository/AbstractRepository.java
api/src/main/java/ai/djl/util/TarUtils.java

[api] Moves commons-compress dependency to standalone class.

---

api/src/main/java/ai/djl/repository/RepositoryFactoryImpl.java

[api] Allows to load .pt or .onnx file from jar url

---

extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/Encoding.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizer.java
extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizerTest.java

[tokenizer] Return if exceed max token length

---

engines/pytorch/pytorch-engine/README.md

[docs] Fixes cuda version for pytorch native library

---

.github/workflows/codeql-analysis-java.yml
.github/workflows/docker_publish.yml
.github/workflows/docs.yml
.github/workflows/native_jni_s3_paddle.yml
.github/workflows/native_jni_s3_pytorch.yml
.github/workflows/native_jni_s3_pytorch_android.yml
.github/workflows/nightly_android.yml
.github/workflows/nightly_publish.yml
.github/workflows/publish-job-success.yml
.github/workflows/publish_android_packages.yml
.github/workflows/serving_publish.yml

Publishes metrics for all scheduled workflow runs to cloudwatch

[ci] add cloudwatch metrics for scheduled workflow failures

---

docs/development/inference_performance_optimization.md

add AWS Graviton3 PyTorch inference tuning details

docs: add AWS Graviton3 PyTorch inference tuning details

---

api/src/main/java/ai/djl/BaseModel.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtModel.java
integration/src/main/java/ai/djl/integration/tests/training/ModelTest.java

This adds support for PyTorch InputStream model load when using imperative models. Before, it would assume symbolic without actually checking. In those cases, it would throw an engine exception. Now, that option is working and tested.

Supports PyTorch stream imperative model load

---

engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java

[pytorch] Avoid loading .lib file from PYTORCH_LIBRARY_PATH

---

.github/workflows/continuous.yml

This integrates the github dependency submission task which is now part of the default gradle github action following
https://github.com/marketplace/actions/build-with-gradle. It can then be used by github to better analyze the dependency tree and recognize Java dependabot alerts

Uses gradle dependency submission

---

.github/workflows/continuous.yml

Excludes test dependencies from dependency submission

---

.github/workflows/native_jni_s3_pytorch.yml

Fixes dependency not found error in the build-pytorch-jni-linux job in the Native JNI S3 Pytorch workflow by rolling back to v3 for configure-aws-credentials to have the right dependency

Fixes failing CI

---

api/src/main/java/ai/djl/engine/Engine.java
docs/development/troubleshooting.md
engines/ml/lightgbm/src/main/java/ai/djl/ml/lightgbm/LgbmEngineProvider.java
engines/ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbEngineProvider.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxEngineProvider.java
engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtEngineProvider.java
engines/paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpEngineProvider.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtEngineProvider.java
engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfEngineProvider.java
engines/tensorrt/src/main/java/ai/djl/tensorrt/engine/TrtEngineProvider.java
engines/tensorrt/src/test/java/ai/djl/tensorrt/engine/TrtEngineTest.java
engines/tensorrt/src/test/java/ai/djl/tensorrt/engine/TrtNDManagerTest.java
engines/tensorrt/src/test/java/ai/djl/tensorrt/integration/TrtTest.java
engines/tflite/tflite-engine/src/main/java/ai/djl/tflite/engine/TfLiteEngineProvider.java

When I create models concurrently using the following methods, I always encounter a null pointer exception because of a problem with the Engine.getEngine("PyTorch ") double-check lock. I wonder if the author has any other intention in this way. However, it is necessary for users to deal with outer layer exceptions.
Model localModel = Engine.getEngine("PyTorch").newModel("test", Device.cpu())

Fixes cases where the getEngine method in the EngineProvider class returns null when called concurrently.

---

api/src/main/java/ai/djl/Model.java
api/src/test/java/ai/djl/translate/TranslatorTest.java

[api] Adds utility method to Model for accessing properties

---

api/src/main/java/ai/djl/util/cuda/CudaUtils.java
api/src/test/java/ai/djl/util/cuda/CudaUtilsTest.java

[api] Fixes typo in CudaUtils

---

model-zoo/README.md

I found a typo in the model-zoo README.

[model-zoo] Fixes typo in README

---

api/src/main/java/ai/djl/metric/Metric.java
api/src/main/java/ai/djl/metric/Metrics.java
api/src/main/java/ai/djl/metric/Unit.java

[api] Adds suffix to percentile metric name

---

api/src/main/java/ai/djl/inference/Predictor.java
api/src/main/java/ai/djl/metric/Metrics.java

[api] Adds dimension for prediction metric

---

examples/src/main/java/ai/djl/examples/inference/face/FaceDetectionTranslator.java

In my application, I employed the `FaceDetectionTranslator`, but encountered an issue with its lack of thread safety. When attempting to process multiple images simultaneously, `EngineError`s occurred. After investigation, I identified the root cause as being related to the variables for width and height.
Fortunately, the `TranslatorContext`'s capacity to carry attachments makes resolving this issue relatively straightforward.

Thread-safe FaceDetectionTranslator

---

.github/workflows/docs.yml
api/src/main/java/ai/djl/training/util/ProgressBar.java

[docs] Disable progress bar for jupyter notebook convertion

---

api/build.gradle
api/src/main/java/ai/djl/util/TarUtils.java
gradle.properties

[api] Upgrades commons compress to 1.26.0 for CVE

---

engines/llama/src/main/java/ai/djl/llama/jni/LibUtils.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/jni/LibUtils.java

Avoid duplicated loading native library

---

.github/workflows/nightly_publish.yml

[ci] Fixes nightly build for onnx 1.17.1

---

engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java

[pytorch] Fixes detecting wrong flavor on macOS issue

---

api/src/main/java/ai/djl/repository/JarRepository.java
api/src/main/java/ai/djl/repository/RepositoryFactoryImpl.java
api/src/test/java/ai/djl/repository/JarRepositoryTest.java

[api] Allows to use relative jar uri for cache folder name

---

examples/src/main/java/ai/djl/examples/inference/nlp/TextGeneration.java
examples/src/main/python/trace_gpt2.py

[example] Adds document about how to trace gpt2 model

---

extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextEmbeddingBatchTranslator.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextEmbeddingTranslator.java

This allows embedding models to obtain token_type_ids from encodings in TextEmbeddingBatchTranslator (TextEmbeddingTranslator already supports it).

support includeTokenTypes in TextEmbeddingBatchTranslator

---

api/src/main/java/ai/djl/ndarray/NDSerializer.java
api/src/test/java/ai/djl/ndarray/NDSerializerTest.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java

[api] Support encode/decode String tensor

---

extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/FillMaskBatchTranslator.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/FillMaskTranslator.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextClassificationBatchTranslator.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextClassificationTranslator.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TokenClassificationBatchTranslator.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TokenClassificationTranslator.java

[tokenizer] Adds includeTokenTypes for all translators

---

extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizer.java
extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizerTest.java

[tokenizer] Add do_lower_case support

---

extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizer.java
extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizerTest.java

Avoid crash when token exceed model max length.

[tokenizer] set truncatation to default

---

extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/CrossEncoderTranslator.java

[tokenizer] Adds option to disable sigmoid for CrossEncoderTranslator

---

engines/llama/src/main/java/ai/djl/llama/zoo/LlamaModelZoo.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/zoo/HfModelZoo.java

- This PR addresses a potential thread safety issue in the **ai.djl.huggingface.zoo.HfModelZoo** and **ai.djl.llama.zoo.LlamaModelZoo** classes. Both classes utilize an init method for initialization and are designed as singletons(**ai/djl/repository/zoo/ModelZoo.java:39**), which may be accessed by multiple threads simultaneously. However, the init methods do not currently implement any mechanism to ensure thread safety. This PR proposes changes to synchronize the init methods to prevent concurrent initialization issues.
If this change is a backward incompatible change, why must this change be made?
- This change is not a backward incompatible change. It is a necessary enhancement to ensure that the …

[fix] Fix HfModelZoo and LlamaModelZoo concurrent init problem

---

api/src/main/java/ai/djl/modality/nlp/TextPrompt.java
api/src/main/java/ai/djl/modality/nlp/translator/TextClassificationServingTranslator.java
api/src/main/java/ai/djl/modality/nlp/translator/TextEmbeddingServingTranslator.java
api/src/main/java/ai/djl/modality/nlp/translator/TokenClassificationServingTranslator.java
extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/TextEmbeddingTranslatorTest.java

[api] Support "inputs" key in json request for text embedding translator

---

api/src/main/java/ai/djl/inference/Predictor.java
api/src/main/java/ai/djl/modality/nlp/translator/TextEmbeddingServingTranslator.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextClassificationBatchTranslator.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextClassificationTranslator.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextEmbeddingBatchTranslator.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TokenClassificationBatchTranslator.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TokenClassificationTranslator.java
extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/TextEmbeddingTranslatorTest.java

- **[api] Support "inputs" key in json request for text embedding translator**
- **[api] Add batch support to TextEmbeddingServingTranslator**

[api] Add batch support to TextEmbeddingServingTranslator

---

api/src/main/java/ai/djl/repository/RepositoryFactoryImpl.java

- getSupportedScheme func in RepositoryFactoryImpl clz return empty set, it seems not correspond to the registerRepositoryFactory func.

[fix] fix RepositoryFactoryImpl getSupportedScheme return value

---

extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextEmbeddingTranslator.java

[tokenizer] Fixes TextEmbeddingTranslator only uses CPU

---

extensions/tokenizers/rust/src/models/mod.rs
extensions/tokenizers/rust/src/ndarray/mod.rs
extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsModel.java

[rust] Avoid panic in error case

---

api/src/main/java/ai/djl/ndarray/types/Shape.java
api/src/main/java/ai/djl/nn/Blocks.java
api/src/main/java/ai/djl/nn/OnesBlockFactory.java
api/src/test/java/ai/djl/nn/BlockFactoryTest.java
extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/TextEmbeddingTranslatorTest.java

[api] Adds OnesBlockFactory to make it easy for testing

---

api/src/main/java/ai/djl/ndarray/BaseNDManager.java

This makes a massive performance difference when using OnnxRuntime, which delegates to PyTorch for some NDArray operations.  This almost makes OnnxRuntime run as fast compared to PyTorch.  Without this change, OnnxRuntime was over 3 times slower.

Ensure the alternative ND manager can use GPUs

---

api/src/main/java/ai/djl/repository/LocalRepository.java
api/src/main/java/ai/djl/util/ClassLoaderUtils.java
api/src/main/java/ai/djl/util/Utils.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxModel.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtModel.java
engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfModel.java
examples/src/main/java/ai/djl/examples/training/util/BertCodeDataset.java
integration/src/main/java/ai/djl/integration/IntegrationTest.java
testing/src/main/java/ai/djl/testing/CoverageUtils.java

[api] Closes file stream

---

.github/workflows/native_build_mxnet_osx.yml
.github/workflows/native_jni_s3_pytorch.yml
.github/workflows/native_s3_fasttext.yml
.github/workflows/native_s3_huggingface.yml
.github/workflows/native_s3_llama.yml
.github/workflows/native_s3_sentencepiece.yml
.github/workflows/nightly_publish.yml

[ci] Update github action runner to macOS x86_64 instance

---

api/src/main/java/ai/djl/BaseModel.java
api/src/main/java/ai/djl/ndarray/types/Shape.java
api/src/main/java/ai/djl/nn/Blocks.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtModel.java
extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsModel.java

Allows -1 in shape string presentation

[rust] Support load DJL model for RsModel

---

api/src/main/java/ai/djl/nn/convolutional/Convolution.java
api/src/main/java/ai/djl/nn/convolutional/Deconvolution.java
api/src/main/java/ai/djl/nn/transformer/BertBlock.java
api/src/main/java/ai/djl/nn/transformer/ScaledDotProductAttentionBlock.java
api/src/main/java/ai/djl/nn/transformer/TransformerEncoderBlock.java
api/src/main/java/ai/djl/training/ParameterServer.java
api/src/main/java/ai/djl/training/listener/EpochTrainingListener.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxOpParams.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/jna/JnaUtils.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArrayEx.java
engines/pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/ProfilerTest.java
engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArrayEx.java
examples/src/main/java/ai/djl/examples/inference/BertClassification.java
examples/src/main/java/ai/djl/examples/inference/SentimentAnalysis.java
examples/src/main/java/ai/djl/examples/inference/UniversalSentenceEncoder.java
examples/src/main/java/ai/djl/examples/inference/cv/PoseEstimation.java
examples/src/main/java/ai/djl/examples/inference/cv/StyleTransfer.java
examples/src/main/java/ai/djl/examples/inference/nlp/RollingBatch.java
examples/src/main/java/ai/djl/examples/inference/nlp/TextGeneration.java
examples/src/main/java/ai/djl/examples/training/TrainSentimentAnalysis.java
examples/src/main/java/ai/djl/examples/training/TrainWithOptimizers.java
examples/src/test/java/ai/djl/examples/inference/StyleTransferTest.java
extensions/fasttext/src/test/java/ai/djl/fasttext/CookingStackExchangeTest.java
extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsNDArray.java
extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsNDArrayEx.java
integration/src/main/java/ai/djl/integration/tests/model_zoo/classification/ResnetTest.java
model-zoo/src/main/java/ai/djl/basicmodelzoo/cv/classification/MobileNetV2.java
tools/gradle/java-formatter.gradle

[ci] Updates google code formatter to 1.22.0

---

docs/interactive_tool.md
docs/quick_start.md

[doc] Removes mention of future lab

---

.github/workflows/native_jni_s3_pytorch.yml
.github/workflows/nightly_publish.yml
engines/pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/ALibUtilsTest.java
engines/pytorch/pytorch-jni/build.gradle
engines/pytorch/pytorch-native/build.gradle
engines/pytorch/pytorch-native/build.sh
engines/pytorch/pytorch-native/src/main/native/djl_pytorch_utils.h
gradle.properties

[pytorch] Updates PyTorch to 2.2.2

---

engines/pytorch/pytorch-engine/README.md

[pytorch] Update PyTorch engine README for version 2.2.2

---

extensions/tokenizers/rust/src/models/mod.rs
extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsModel.java
extensions/tokenizers/src/main/java/ai/djl/engine/rust/RustLibrary.java

[rust] RsModel delete model in close

---

engines/ml/lightgbm/src/main/java/ai/djl/ml/lightgbm/LgbmNDArray.java
engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_torch_pointwise.cc
engines/pytorch/pytorch-native/src/main/native/djl_pytorch_utils.h

In `LgbmNDArray`, within the `intern` method, closing the `replaced` data leads to the release of `floatData` and `doubleData`. This action results in the premature release of `floatData` and `doubleData`.
```java
@Override
public void intern(NDArray replaced) {
if (floatData != null) {
lightgbmlib.delete_floatArray(floatData);
}
if (doubleData != null) {
lightgbmlib.delete_doubleArray(doubleData);
}
LgbmNDArray array = (LgbmNDArray) replaced;
data = array.data;
handle = array.handle;
format = array.format;
floatData = array.floatData;
doubleData = array.doubleData;
typeConstant = array.typeConstant;
shape = array.shape;
dataType = array.dataType;
replaced.close();
}
@Override
public void close() {
super.close();
if (floatData != null) {
lightgbmlib.delete_floatArray(floatData);
}
if …
```

[Lgbm] fix LgbmNDArray replaced.close() release data problem

---

engines/pytorch/pytorch-native/build.sh
engines/pytorch/pytorch-native/src/main/native/djl_pytorch_utils.h

[ci] Fixes pytorch jni build for 1.13.1

---

extensions/tokenizers/.gitignore
extensions/tokenizers/src/main/python/.gitignore
extensions/tokenizers/src/main/python/djl_converter/fill_mask_converter.py
extensions/tokenizers/src/main/python/djl_converter/huggingface_converter.py
extensions/tokenizers/src/main/python/djl_converter/huggingface_models.py
extensions/tokenizers/src/main/python/djl_converter/metadata.py
extensions/tokenizers/src/main/python/djl_converter/model_zoo_importer.py
extensions/tokenizers/src/main/python/djl_converter/question_answering_converter.py
extensions/tokenizers/src/main/python/djl_converter/sentence_similarity_converter.py
extensions/tokenizers/src/main/python/djl_converter/text_classification_converter.py
extensions/tokenizers/src/main/python/djl_converter/token_classification_converter.py

[tokenizer] Refactor djl_convert python code

---

extensions/tokenizers/README.md
extensions/tokenizers/src/main/python/djl_converter/arg_parser.py
extensions/tokenizers/src/main/python/djl_converter/huggingface_converter.py
extensions/tokenizers/src/main/python/djl_converter/model_converter.py
extensions/tokenizers/src/main/python/djl_converter/model_zoo_importer.py
extensions/tokenizers/src/main/python/requirements.txt
extensions/tokenizers/src/main/python/setup.py

- **[tokenizer] Refactor djl_convert python code**
- **[huggingface] Adds more option to convert onnx model**

[huggingface] Adds more option to convert onnx model

---

.github/workflows/native_jni_s3_pytorch.yml
engines/pytorch/pytorch-native/build.cmd
engines/pytorch/pytorch-native/build.sh

[ci] Adds cuda version as github actions parameter for Pytorch JNI build

---

.github/workflows/continuous.yml
api/src/main/java/ai/djl/modality/nlp/generate/TextGenerator.java
examples/src/test/java/ai/djl/examples/inference/nlp/TextGenerationTest.java

[examples] Fixes TextGeneration EOS bug

---

examples/src/test/java/ai/djl/examples/inference/TimeSeriesTest.java
examples/src/test/java/ai/djl/examples/training/TrainResNetTest.java
integration/build.gradle

[ci] Fixes build on macOS aarch64 machine

---

engines/pytorch/pytorch-model-zoo/src/main/java/ai/djl/pytorch/zoo/cv/objectdetection/PtSsdTranslator.java

Fix #3203 (ai.djl.pytorch.zoo.cv.objectdetection.PtSsdTranslator.Builder.self() to return 'this' instead of 'null')

[pytorch-model-zoo]: fix PtSsdTranslator.Builder.self()

---

android/README.md
android/pytorch-native/README.md
api/README.md
basicdataset/README.md
bom/README.md
djl-zero/README.md
examples/pom.xml
gradle.properties

Update the version for DJL to 0.29.0~Snapshot and update doc READMEs to 0.28.0

[djl] update djl version and readmes

---

extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextEmbeddingTranslator.java

This fixes https://github.com/deepjavalibrary/djl/issues/3211, where using `djl://ai.djl.huggingface.pytorch/sentence-transformers/clip-ViT-B-32-multilingual-v1` on 0.28.0 fails on a GPU machine with:
```
Caused by: ai.djl.engine.EngineException: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_mm)
at ai.djl.pytorch.jni.PyTorchLibrary.torchNNLinear(PyTorchLibrary.java) ~[pytorch-engine-0.28.0.jar:?]
at ai.djl.pytorch.jni.JniUtils.linear(JniUtils.java:1376) ~[pytorch-engine-0.28.0.jar:?]
at ai.djl.pytorch.engine.PtNDArrayEx.linear(PtNDArrayEx.java:397) ~[pytorch-engine-0.28.0.jar:?]
at ai.djl.huggingface.translator.TextEmbeddingTranslator.processEmbedding(TextEmbeddingTranslator.java:18 …
```

[tokenizer] Ensure GPU is used in TextEmbeddingTranslator

---

engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtEngine.java

[onnxruntime] Add debug message for OnnxRuntime

---

api/src/test/java/ai/djl/util/cuda/CudaUtilsTest.java

The test was failing on the machine installed cuda but no GPU

[api] Fixes unitest

---

.github/workflows/publish-job-success.yml

[ci] Disable github actions runner for non-djl repo

---

extensions/tokenizers/rust/src/models/mod.rs

[rust] Fix deleteModel error

---

engines/ml/lightgbm/src/main/java/ai/djl/ml/lightgbm/LgbmNDManager.java
engines/ml/xgboost/src/main/java/ai/djl/ml/xgboost/XgbNDManager.java
engines/tensorrt/src/main/java/ai/djl/tensorrt/engine/TrtNDManager.java
extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsNDManager.java

Close all alternative ndmanager

add close method to all nd manager

---

engines/ml/lightgbm/src/main/java/ai/djl/ml/lightgbm/jni/JniUtils.java

https://github.com/deepjavalibrary/djl/issues/3223
This PR introduces an enhancement to the LightGBM inference functionality, specifically targeting multi-classification tasks. It modifies the inferenceMat method to dynamically allocate output buffer size based on the number of classes in the model, thus enabling support for multi-class predictions.
Key Changes:
- The method now retrieves the number of classes in the model using LGBM_BoosterGetNumClasses and allocates the output buffer (outBuffer) accordingly. This ensures that the buffer size is sufficient for storing prediction results for all classes.
- This change is backward compatible as it extends the existing functionality without altering the method signature or expected input/output types. It enhances the method's capability to …

[Lgbm] support multi classification

---

.github/workflows/native_s3_pytorch_android.yml
.github/workflows/nightly_android.yml
android/gradle.properties
tools/gradle/android-formatter.gradle

[android] Updates android with PyTorch 2.2.2

---

extensions/spark/src/main/scala/ai/djl/spark/task/text/QuestionAnswerer.scala
extensions/spark/src/main/scala/ai/djl/spark/task/text/TextClassifier.scala
extensions/spark/src/main/scala/ai/djl/spark/task/text/TextEmbedder.scala

[spark] Use batch predict API

---

engines/ml/lightgbm/src/main/java/ai/djl/ml/lightgbm/LgbmModel.java
engines/ml/lightgbm/src/main/java/ai/djl/ml/lightgbm/LgbmSymbolBlock.java
engines/ml/lightgbm/src/main/java/ai/djl/ml/lightgbm/jni/JniUtils.java
engines/ml/lightgbm/src/test/java/ai/djl/ml/lightgbm/LgbmModelTest.java

This PR is primarily aimed at implementing data inference functionality using the LightGBM model, supporting various types of inference including Raw Score, Leaf Index, and Feature Contribution. The inference task is accomplished through JNI calls to the LightGBM C API, and the results are returned in the form of a ByteBuffer for further processing.
- **Backward Incompatible Changes**: There are no backward incompatible changes in this update. It mainly introduces new functionalities without altering the behavior of existing features. Therefore, existing code and functionalities should not be affected by this change.
- **Interesting Edge Cases to Note**:
- When the prediction type is Leaf Index, although the LightGBM C API returns the results as floating-point numbers (`double`), these …

[Lgbm] support multi type prediction

---

api/src/main/java/ai/djl/metric/Metric.java
api/src/main/java/ai/djl/metric/MetricType.java
api/src/test/java/ai/djl/metric/MetricsTest.java

[api] Adds metric type to Metic class

---

docs/development/example_dataset.md
docs/hybrid_engine.md
docs/load_model.md
engines/ml/lightgbm/README.md
engines/ml/xgboost/README.md
engines/mxnet/mxnet-engine/README.md
engines/mxnet/mxnet-model-zoo/README.md
engines/onnxruntime/onnxruntime-android/README.md
engines/onnxruntime/onnxruntime-engine/README.md
engines/pytorch/pytorch-model-zoo/README.md
engines/tensorflow/tensorflow-api/README.md
engines/tensorflow/tensorflow-engine/README.md
engines/tensorflow/tensorflow-model-zoo/README.md
engines/tensorrt/README.md
extensions/audio/README.md
extensions/aws-ai/README.md
extensions/fasttext/README.md
extensions/hadoop/README.md
extensions/opencv/README.md
extensions/sentencepiece/README.md
extensions/spark/README.md
extensions/tablesaw/README.md
extensions/timeseries/README.md
extensions/timeseries/docs/forecast_with_M5_data.md
extensions/tokenizers/README.md
model-zoo/README.md

[docs] Bump up DJL version to 0.28.0

---

engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxEngineProvider.java
examples/src/main/java/ai/djl/examples/training/TrainBertOnCode.java
examples/src/main/java/ai/djl/examples/training/util/BertCodeDataset.java
examples/src/test/java/ai/djl/examples/training/TrainAirfoilWithTabNetTest.java
examples/src/test/java/ai/djl/examples/training/TrainBertOnGoemotionsTest.java
examples/src/test/java/ai/djl/examples/training/TrainBertTest.java
examples/src/test/java/ai/djl/examples/training/TrainMnistTest.java
examples/src/test/java/ai/djl/examples/training/TrainMnistWithLSTMTest.java
examples/src/test/java/ai/djl/examples/training/TrainSentimentAnalysisTest.java
examples/src/test/java/ai/djl/examples/training/TrainSeq2SeqTest.java
examples/src/test/java/ai/djl/examples/training/TrainTicTacToeTest.java
examples/src/test/java/ai/djl/examples/training/TrainTimeSeriesTest.java

[examples] Enabled training unit tests on macOS M1

---

api/src/main/java/ai/djl/nn/transformer/IdEmbedding.java

[api] Fixes IdEmbedding memory leak

---

extensions/tokenizers/rust/Cargo.toml
extensions/tokenizers/rust/src/compute_cap.rs
extensions/tokenizers/rust/src/layers/cublaslt.rs
extensions/tokenizers/rust/src/layers/linear.rs
extensions/tokenizers/rust/src/layers/mod.rs
extensions/tokenizers/rust/src/lib.rs
extensions/tokenizers/rust/src/models/bert.rs
extensions/tokenizers/rust/src/models/distilbert.rs
extensions/tokenizers/rust/src/models/mod.rs
extensions/tokenizers/rust/src/ndarray/binary.rs
extensions/tokenizers/rust/src/ndarray/cmp.rs
extensions/tokenizers/rust/src/ndarray/creation.rs
extensions/tokenizers/rust/src/ndarray/mod.rs
extensions/tokenizers/rust/src/ndarray/other.rs
extensions/tokenizers/rust/src/ndarray/reduce.rs
extensions/tokenizers/rust/src/ndarray/unary.rs

[rust] Use fused layer

---

engines/mxnet/mxnet-model-zoo/src/test/resources/mlrepo/model/cv/instance_segmentation/ai/djl/mxnet/mask_rcnn/metadata.json

[mxnet-model-zoo] Adds missing translatorFactory in metadata

---

.github/workflows/native_publish_pytorch.yml
engines/pytorch/pytorch-native/build.gradle.kts

The pytorch native jar file become two large, and sonatype auto staging break the artifacts into multiple staging repo and can not close properly.

[pytorch] Split maven publish into two parts

---

engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtUtils.java
engines/onnxruntime/onnxruntime-engine/src/test/java/ai/djl/onnxruntime/engine/OrtTest.java

[onnx] Adds fp16 and bfp16 support for OnnxRuntime

---

.github/workflows/nightly_publish.yml

[pytorch] Adds back PyTorch 2.1.2 support

---

api/src/main/java/ai/djl/repository/zoo/BaseModelLoader.java
examples/src/main/java/ai/djl/examples/training/TrainWithOptimizers.java
examples/src/main/java/ai/djl/examples/training/transferlearning/TrainResnetWithCifar10.java
examples/src/main/java/ai/djl/examples/training/util/Arguments.java
examples/src/test/java/ai/djl/examples/training/TrainResNetTest.java

1. Remove symbolic model training form MXNet
2. Use block factory to load DJL trained model
3. Refactory BaseModelLoader

[examples] Remove symbolic training for MXNet

---

api/src/main/java/ai/djl/util/Platform.java
api/src/main/java/ai/djl/util/cuda/CudaUtils.java
api/src/test/java/ai/djl/util/PlatformTest.java
api/src/test/java/ai/djl/util/cuda/CudaUtilsTest.java

[api] Loads native engine in deterministic order

---

api/src/main/java/ai/djl/modality/cv/BufferedImageFactory.java
api/src/main/java/ai/djl/modality/cv/output/Mask.java
api/src/main/java/ai/djl/modality/cv/translator/InstanceSegmentationTranslator.java
extensions/opencv/src/main/java/ai/djl/opencv/OpenCVImage.java

[api] Refactor drawMask() for instance segmentation

---

examples/src/main/java/ai/djl/examples/training/TrainTimeSeries.java
extensions/timeseries/src/main/java/ai/djl/timeseries/translator/BaseTimeSeriesTranslator.java

[timeseries] Fixes contentLength issue for inference

---

api/src/main/java/ai/djl/modality/cv/output/Rectangle.java
api/src/main/java/ai/djl/modality/cv/translator/YoloPoseTranslator.java
api/src/main/java/ai/djl/modality/cv/translator/YoloPoseTranslatorFactory.java
api/src/main/java/ai/djl/modality/cv/translator/YoloV5Translator.java
api/src/main/java/ai/djl/modality/cv/translator/YoloV8Translator.java
engines/pytorch/pytorch-model-zoo/src/main/java/ai/djl/pytorch/zoo/PtModelZoo.java
engines/pytorch/pytorch-model-zoo/src/test/resources/mlrepo/model/cv/pose_estimation/ai/djl/pytorch/yolov8n-pose/metadata.json
examples/src/main/java/ai/djl/examples/inference/cv/PoseEstimation.java
examples/src/test/java/ai/djl/examples/inference/PoseEstimationTest.java

- **[api] Reactor nms for yolo translator**
- **[pytorch] Adds yolov8n pose estimation model**

[pytorch] Adds yolov8n pose estimation model

---

engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/zoo/OrtModelZoo.java
engines/onnxruntime/onnxruntime-engine/src/test/resources/mlrepo/model/cv/pose_estimation/ai/djl/onnxruntime/yolov8n-pose/metadata.json

[onnxruntime] Adds yolov8n pose model for OnnxRuntime

---

extensions/tokenizers/rust/src/lib.rs
extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizer.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/jni/TokenizersLibrary.java

Fixes #3316
If you call TokenizersLibrary.LIB.getOverflowing you must also clean up all overflow encodings.
If withOverflowingTokens was false no Encodings where generated leaving jni Encoding handles that would not be properly deleted.
This introduces a new native method where you can inquire about number of overflow tokens without using any jni resources. And you will now only call TokenizersLibrary.LIB.getOverflowing(encoding) if withOverflowingTokens is true.

[tokenizers] Fixes memory leak when there is overflowing tokens

---

extensions/tokenizers/src/test/java/ai/djl/engine/rust/NDArrayTests.java
testing/src/main/java/ai/djl/testing/TestRequirements.java

Fix NDArrayTests failure on cuda
1) ai.djl.engine.rust.NDArrayTests.testExpandDim: This is candle bug. I raised an issue in candle. I will add the code back once it's fixed.
```
ai.djl.engine.EngineException: DriverError(CUDA_ERROR_INVALID_VALUE, "invalid argument")
at app//ai.djl.engine.rust.RustLibrary.contentEqual(Native Method)
at app//ai.djl.engine.rust.RsNDArray.contentEquals(RsNDArray.java:368)
at app//ai.djl.engine.rust.RsNDArray.equals(RsNDArray.java:1615)
at app//org.testng.Assert.areEqualImpl(Assert.java:180)
at app//org.testng.Assert.assertEqualsImpl(Assert.java:148)
at app//org.testng.Assert.assertEquals(Assert.java:132)
at app//org.testng.Assert.assertEquals(Assert.java:644)
at …
```

[rust] Fix NDArrayTests failure on cuda

---

extensions/tokenizers/src/test/java/ai/djl/engine/rust/NDArrayTests.java

[rust] Remove 0-dimension tensor compare in NDArrayTests

---

extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/jni/LibUtils.java

[tokenizers] Download jni lib files for cuda

---

.github/workflows/native_s3_huggingface.yml
extensions/tokenizers/build.sh
extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/jni/LibUtils.java

[rust] Update gpu build pipeline to cu122

---

extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/jni/LibUtils.java

[rust] Change loging level to debug

---

android/pytorch-native/README.md
api/README.md
basicdataset/README.md
bom/README.md
djl-zero/README.md
docker/spark/Dockerfile
docs/load_model.md
engines/ml/lightgbm/README.md
engines/ml/xgboost/README.md
engines/mxnet/mxnet-engine/README.md
engines/mxnet/mxnet-model-zoo/README.md
engines/onnxruntime/onnxruntime-android/README.md
engines/onnxruntime/onnxruntime-engine/README.md
engines/pytorch/pytorch-engine/README.md
engines/pytorch/pytorch-model-zoo/README.md
engines/tensorflow/tensorflow-api/README.md
engines/tensorflow/tensorflow-engine/README.md
engines/tensorflow/tensorflow-model-zoo/README.md
engines/tensorrt/README.md
extensions/audio/README.md
extensions/aws-ai/README.md
extensions/fasttext/README.md
extensions/hadoop/README.md
extensions/opencv/README.md
extensions/sentencepiece/README.md
extensions/spark/README.md
extensions/tablesaw/README.md
extensions/timeseries/README.md
extensions/tokenizers/README.md
model-zoo/README.md

[MCM 0.29.0] Bump up versions in documents to point to new url
Notebooks CI will fail because there is no version in sonatype - re-run docs CI and merge it after release in sonatype is complete.

[release] Bump up versions to 0.29.0 in documents to point to new url

---

android/pytorch-native/README.md
api/README.md
basicdataset/README.md
bom/README.md
djl-zero/README.md
docker/spark/Dockerfile
docs/load_model.md
engines/ml/lightgbm/README.md
engines/ml/xgboost/README.md
engines/mxnet/mxnet-engine/README.md
engines/mxnet/mxnet-model-zoo/README.md
engines/onnxruntime/onnxruntime-android/README.md
engines/onnxruntime/onnxruntime-engine/README.md
engines/pytorch/pytorch-engine/README.md
engines/pytorch/pytorch-model-zoo/README.md
engines/tensorflow/tensorflow-api/README.md
engines/tensorflow/tensorflow-engine/README.md
engines/tensorflow/tensorflow-model-zoo/README.md
engines/tensorrt/README.md
extensions/audio/README.md
extensions/aws-ai/README.md
extensions/fasttext/README.md
extensions/hadoop/README.md
extensions/opencv/README.md
extensions/sentencepiece/README.md
extensions/spark/README.md
extensions/tablesaw/README.md
extensions/timeseries/README.md
extensions/tokenizers/README.md
model-zoo/README.md

* Bump up versions in documents to point to new url

[release] Bump up versions to 0.29.0 in documents to point to new url (#3344)

---

api/src/main/java/ai/djl/modality/nlp/preprocess/SimpleTokenizer.java

Like the title says, there is an error in the class `ai.djl.modality.nlp.preprocess.SimpleTokenizer`. It uses `" "` for tokenizing instead of the provided delimiter.

make SimpleTokenizer use the delimiter, not " "

---

extensions/tokenizers/src/main/python/djl_converter/huggingface_converter.py
extensions/tokenizers/src/main/python/djl_converter/model_converter.py
extensions/tokenizers/src/main/python/djl_converter/model_zoo_importer.py

[djl-convert] Support convert local model to DJL format

---

.github/workflows/docs.yml
tools/scripts/build-website.sh

Changes 
1. Moved code fore building versions.json before the mike deploy command 
2. Copy the versions.json to S3, then switch to gh-pages to upload new version 
3. Fixed typo in DJL_VERSION env in Copy files to S3 with the AWS CLI step 
Rationale:
I re-ordered the steps so the workflow would crash if there was an issue with creating the versions.json file before building all the documentation. The code responsible for building the versions.json was unable to access the .toml file from gh-pages. Thus, I refactored the code to generate and upload the versions.json file before uploading the new website directory.

[docs] Build versions.json before mike deploy

---

api/src/main/java/ai/djl/repository/MRL.java
api/src/main/java/ai/djl/repository/zoo/BaseModelLoader.java
api/src/main/java/ai/djl/repository/zoo/Criteria.java
api/src/main/java/ai/djl/repository/zoo/ModelLoader.java
api/src/test/java/ai/djl/repository/ZooTest.java

[api] Adds Criteria.isDownload() api

---

extensions/tokenizers/rust/src/layers/linear.rs
extensions/tokenizers/rust/src/layers/mod.rs
extensions/tokenizers/rust/src/layers/rms_norm.rs
extensions/tokenizers/rust/src/lib.rs
extensions/tokenizers/rust/src/models/mistral.rs
extensions/tokenizers/rust/src/models/mod.rs
extensions/tokenizers/rust/src/utils.rs
extensions/tokenizers/src/main/python/djl_converter/huggingface_converter.py
extensions/tokenizers/src/main/python/djl_converter/huggingface_models.py

[rust] Add mistral embedding model

---

extensions/tokenizers/rust/src/models/camembert.rs
extensions/tokenizers/rust/src/models/distilbert.rs

[rust] Fix camembert and distilbert model loading

---

extensions/tokenizers/src/main/python/djl_converter/huggingface_converter.py

[tokenizers] Replace pt file names to safetensors

---

extensions/tokenizers/rust/src/models/mod.rs
extensions/tokenizers/rust/src/ndarray/mod.rs
extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsModel.java
extensions/tokenizers/src/main/java/ai/djl/engine/rust/RustLibrary.java

[rust] Load model on given device

---

extensions/tokenizers/rust/src/models/mod.rs
extensions/tokenizers/rust/src/models/qwen2.rs
extensions/tokenizers/src/main/python/djl_converter/huggingface_converter.py

[rust] Add qwen2 model

---

extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/jni/LibUtils.java

[rust] Support pre-downloaded rust shared library

---

api/src/main/java/ai/djl/modality/cv/transform/CenterFit.java
api/src/main/java/ai/djl/modality/cv/translator/BaseImageTranslator.java
api/src/main/java/ai/djl/modality/cv/translator/ObjectDetectionTranslator.java
api/src/main/java/ai/djl/modality/cv/translator/SingleShotDetectionTranslator.java
api/src/main/java/ai/djl/modality/cv/translator/YoloPoseTranslator.java
api/src/main/java/ai/djl/modality/cv/translator/YoloSegmentationTranslator.java
api/src/main/java/ai/djl/modality/cv/translator/YoloTranslator.java
api/src/main/java/ai/djl/modality/cv/translator/YoloV5Translator.java
api/src/main/java/ai/djl/modality/cv/translator/YoloV8Translator.java
api/src/main/java/ai/djl/ndarray/NDArray.java
api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_nn_functional.cc
engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsNDArray.java
integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayShapesManipulationOpTest.java

- **[pytorch] Adds pad operator**
- **[api] Adds center fit image operation for Yolo**

[api] Adds center fit image operation for Yolo

---

extensions/tokenizers/rust/src/models/gemma2.rs
extensions/tokenizers/rust/src/models/gte.rs
extensions/tokenizers/rust/src/models/mod.rs
extensions/tokenizers/src/main/python/djl_converter/huggingface_converter.py

[rust] Add GTE and Gemma2 model

---

extensions/tokenizers/src/main/python/djl_converter/arg_parser.py

[djl-import] Fixes missing trust-remote-code arg for import model zoo

---

extensions/tokenizers/src/main/python/djl_converter/arg_parser.py
extensions/tokenizers/src/main/python/djl_converter/huggingface_models.py
extensions/tokenizers/src/main/python/djl_converter/model_zoo_importer.py

[djl-import] Includes requires version when importing model

---

extensions/tokenizers/rust/src/models/gte.rs

[rust] Make tensor contiguous in rotary embedding

---

extensions/tokenizers/rust/src/models/bert.rs

[rust] Fix bert model classifier loading

---

extensions/tokenizers/rust/src/ndarray/reduce.rs

[rust] Allows -1 dim for normalize()

---

api/src/main/java/ai/djl/Application.java
engines/pytorch/pytorch-model-zoo/src/main/java/ai/djl/pytorch/zoo/PtModelZoo.java
engines/pytorch/pytorch-model-zoo/src/test/resources/mlrepo/model/cv/mask_generation/ai/djl/pytorch/sam2-hiera-large-gpu/metadata.json
engines/pytorch/pytorch-model-zoo/src/test/resources/mlrepo/model/cv/mask_generation/ai/djl/pytorch/sam2-hiera-large/metadata.json
engines/pytorch/pytorch-model-zoo/src/test/resources/mlrepo/model/cv/mask_generation/ai/djl/pytorch/sam2-hiera-tiny-gpu/metadata.json
engines/pytorch/pytorch-model-zoo/src/test/resources/mlrepo/model/cv/mask_generation/ai/djl/pytorch/sam2-hiera-tiny/metadata.json
engines/pytorch/pytorch-model-zoo/src/test/resources/mlrepo/model/cv/object_detection/ai/djl/pytorch/sam2-hiera-large-gpu/metadata.json
engines/pytorch/pytorch-model-zoo/src/test/resources/mlrepo/model/cv/object_detection/ai/djl/pytorch/sam2-hiera-tiny-gpu/metadata.json
examples/src/main/java/ai/djl/examples/inference/cv/SegmentAnything2.java

[api] Adds mask generation task for sam2 model

---

extensions/tokenizers/rust/Cargo.toml
extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizerTest.java
gradle/libs.versions.toml

[tokenizer] Updates tokenizer to 0.20.0

---

api/src/main/java/ai/djl/modality/cv/ImageFactory.java
api/src/main/java/ai/djl/modality/cv/translator/BaseImageTranslatorFactory.java
api/src/main/java/ai/djl/modality/cv/translator/ImageServingTranslator.java
api/src/main/java/ai/djl/modality/cv/translator/wrapper/FileImagePreProcessor.java
api/src/main/java/ai/djl/modality/cv/translator/wrapper/StringImagePreProcessor.java
api/src/test/java/ai/djl/modality/cv/translator/ImageClassificationTranslatorFactoryTest.java
api/src/test/java/ai/djl/modality/cv/translator/InstanceSegmentationTranslatorFactoryTest.java
api/src/test/java/ai/djl/modality/cv/translator/YoloTranslatorFactoryTest.java
api/src/test/java/ai/djl/modality/cv/translator/YoloV5TranslatorFactoryTest.java
api/src/test/java/ai/djl/modality/cv/translator/YoloV8TranslatorFactoryTest.java
examples/src/main/java/ai/djl/examples/inference/cv/ActionRecognition.java
examples/src/main/java/ai/djl/examples/inference/cv/MaskDetection.java
examples/src/main/java/ai/djl/examples/inference/cv/Yolov8Detection.java
integration/src/main/java/ai/djl/integration/tests/modality/cv/BufferedImageFactoryTest.java

[api] Adds base64 image support for ImageTranslator

---

api/src/main/java/ai/djl/modality/nlp/translator/CrossEncoderServingTranslator.java
api/src/main/java/ai/djl/modality/nlp/translator/TextEmbeddingServingTranslator.java
extensions/tokenizers/build.gradle.kts
extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/CrossEncoderTranslator.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextEmbeddingTranslator.java
extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/CrossEncoderTranslatorTest.java

[api] Optimized text embedding post processing performance

---

.github/workflows/docker_publish.yml
.github/workflows/docs.yml
.github/workflows/native_jni_s3_pytorch.yml
.github/workflows/native_jni_s3_pytorch_android.yml
.github/workflows/native_jni_s3_tensorrt.yml
.github/workflows/native_s3_fasttext.yml
.github/workflows/native_s3_huggingface.yml
.github/workflows/native_s3_pytorch.yml
.github/workflows/native_s3_pytorch_android.yml
.github/workflows/native_s3_sentencepiece.yml
.github/workflows/native_s3_tensorflow.yml
.github/workflows/native_s3_xgboost.yml
.github/workflows/nightly_publish.yml
.github/workflows/serving_publish.yml

Moves hardcoded aws creds to iam role + github oidc provider. 
I tested this with the serving_publish workflow https://github.com/deepjavalibrary/djl/actions/runs/10796770521

[ci] moving to temporary iam credentials for publishing steps

---

.github/workflows/native_jni_s3_pytorch.yml

[ci][fix] use v2 for aws credentials due to glib issues with node 20

---

examples/build.gradle.kts

[examples] Adds gradle tasks for each example

---

extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/Encoding.java

[tokenizers] Converting encoding to int32 NDList

---

extensions/tokenizers/build.cmd
extensions/tokenizers/build.gradle.kts
extensions/tokenizers/build.sh
extensions/tokenizers/rust/Cargo.toml

[tokenizers] Use tokenizers from rust.io

---

.github/workflows/native_jni_s3_tensorrt.yml

Update tensorrt native build container. To fix the build failure:
```
Run actions/checkout@v3
with:
repository: deepjavalibrary/djl
token: ***
ssh-strict: true
ssh-user: git
persist-credentials: true
clean: true
sparse-checkout-cone-mode: true
fetch-depth: 1
fetch-tags: false
show-progress: true
lfs: false
submodules: false
set-safe-directory: true
/usr/bin/docker exec  9ac06233246d88f35f3935ea5249fd86d8a56e2b13bee361a4bc0fd7d0eb51dc sh -c "cat /etc/*release | grep ^ID"
/__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
```

[ci] Update tensorrt native build container

---

.github/workflows/native_s3_fasttext.yml

[ci] Fixes fasttext native build for nodejs20 issue

---

.github/workflows/native_s3_sentencepiece.yml

[ci] Fixes sentencepiece native build for nodejs20 issue

---

api/README.md
docs/get.md
engines/pytorch/pytorch-engine/README.md
examples/pom.xml
gradle/libs.versions.toml

Increase build version to 0.31.0

---

api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java

[api] alternative NDArray should not be closed in NDScope

---

api/src/main/java/ai/djl/modality/cv/BufferedImageFactory.java
api/src/main/java/ai/djl/modality/cv/Image.java
api/src/main/java/ai/djl/modality/cv/translator/Sam2ServingTranslator.java
api/src/main/java/ai/djl/modality/cv/translator/Sam2Translator.java
api/src/main/java/ai/djl/modality/cv/translator/Sam2TranslatorFactory.java
api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
api/src/test/java/ai/djl/modality/cv/translator/Sam2InputTest.java
api/src/test/java/ai/djl/modality/cv/translator/Sam2TranslatorFactoryTest.java
engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtEngine.java
engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/zoo/OrtModelZoo.java
examples/docs/segment_anything_2.md
examples/src/main/java/ai/djl/examples/inference/cv/SegmentAnything2.java
extensions/opencv/src/main/java/ai/djl/opencv/OpenCVImage.java
extensions/opencv/src/test/java/ai/djl/opencv/OpenCVImageFactoryTest.java

- **[api] alternative NDArray should not be closed in NDScope**
- **[api] Adds sam2 model to onnxruntime model zoo**

[api] Adds sam2 model to onnxruntime model zoo

---

api/src/main/java/ai/djl/modality/cv/translator/Sam2ServingTranslator.java
api/src/main/java/ai/djl/modality/cv/translator/Sam2Translator.java
api/src/main/java/ai/djl/util/JsonSerializable.java
api/src/test/java/ai/djl/modality/cv/translator/Sam2InputTest.java

- **[api] Adds sam2 model to onnxruntime model zoo**
- **[api] Standardizes CV output format**
- **[api] Visualize sam2 output for Sam2ServingTranslator**

[api] Visualize sam2 output for Sam2ServingTranslator

---

api/src/main/java/ai/djl/modality/cv/translator/Sam2Translator.java
engines/pytorch/pytorch-model-zoo/src/main/java/ai/djl/pytorch/zoo/PtModelZoo.java
examples/docs/segment_anything_2.md
examples/docs/trace_sam2_img.py

- **[api] Adds sam2 model to onnxruntime model zoo**
- **[api] Improve Sam2Translator for PyTorch traced model**

[api] Improve Sam2Translator for PyTorch traced model

---

api/src/main/java/ai/djl/modality/cv/translator/Sam2Translator.java
api/src/test/java/ai/djl/modality/cv/translator/Sam2InputTest.java

[api] Makes Sam2 input consistent with other CV model

---

api/src/main/java/ai/djl/modality/cv/translator/SemanticSegmentationTranslatorFactory.java
api/src/main/java/ai/djl/modality/cv/translator/SimplePoseTranslatorFactory.java
api/src/main/java/ai/djl/modality/cv/translator/StyleTransferTranslatorFactory.java
api/src/test/java/ai/djl/modality/cv/translator/SemanticSegmentationTranslatorFactoryTest.java
api/src/test/java/ai/djl/modality/cv/translator/SimplePoseTranslatorFactoryTest.java
api/src/test/java/ai/djl/modality/cv/translator/StyleTransferTranslatorFactoryTest.java

[api] Adds serving support for some CV models

---

api/src/main/java/ai/djl/modality/nlp/translator/QaServingTranslator.java
api/src/main/java/ai/djl/modality/nlp/translator/TokenClassificationServingTranslator.java
api/src/main/java/ai/djl/ndarray/BytesSupplierImpl.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizer.java
extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizerTest.java
extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/QuestionAnsweringTranslatorTest.java

[api] Fixes QaServingTranslator output format

---

extensions/tokenizers/rust/Cargo.toml
extensions/tokenizers/rust/src/lib.rs

Update tokenizer to 0.20.3.
Also change parameters.auth_token to parameters.token, because upstream FromPretrainedParameters changed: https://github.com/huggingface/tokenizers/blob/v0.20.3/tokenizers/src/utils/from_pretrained.rs#L11

[tokenizer] Updates tokenizer to 0.20.3

---

extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizerTest.java
gradle/libs.versions.toml

[tokenizer] Updates tokenizer to 0.20.3 in libs.versions.toml

---

docs/development/troubleshooting.md

- Rewrite
- Add setting PATH in Environment Variables
Triggered by my DJL related Issue in JabRef: https://github.com/JabRef/jabref/issues/12169

Update troubleshooting.md - UnsatisfiedLinkError issue

---

.github/workflows/native_jni_s3_huggingface_android.yml

Looking at https://github.com/deepjavalibrary/djl/actions/runs/11880763848/job/33104304871#step:6:55, I think I didn't install `cargo-ndk` and also required SDKs properly.
Follow-up of https://github.com/deepjavalibrary/djl/pull/3532
I've tried testing it in my fork: https://github.com/naveen521kk/djl/actions/runs/11881317929/job/33105511288 (it fails because it doesn't have access to the AWS resources).

CI: setup cargo-ndk for huggingface tokenizers android builds

---

.github/workflows/nightly_publish.yml
engines/pytorch/pytorch-engine/README.md

Dropping PT 2.1.2 and PT 2.4.0 versions for 0.32.0
- PT 2.1.2 is not needed since 2.3.1 is supported for cu121
- PT 2.4.0 is not needed since 2.5.1 is supported for cu124

[pytorch] Update supported versions of pytorch for 0.32.0

---

.github/workflows/nightly_publish.yml
engines/pytorch/pytorch-engine/README.md

Add PT 2.1.2 since Neuron still depends on it.
Remove PT 2.4.0 from staging publish step.

[pytorch] support pytorch 2.1.2 for Neuron

---

.github/workflows/continuous.yml
.github/workflows/nightly_publish.yml

The continuous workflow for windows is busted, and we've had a silent failure in that test for a long time. 
The issue is that we run 3 separate tests in the final github step of continuous/build-windows, but the success/failure outcome is only dependent on the final command we run. Specifically, we run:
```
./gradlew -Pjni "-Dai.djl.default_engine=PyTorch" test -x examples:test
./gradlew -Pjni --rerun-tasks "-Dai.djl.default_engine=TensorFlow" test -x examples:test
./gradlew --rerun-tasks "-Dai.djl.default_engine=OnnxRuntime" :integration:test
```
When this runs if the 3rd line succeeds, it hides any failure that occurs in the previous two lines.
This change refactors the continuous workflow by unifying the windows test into the existing mac/linux tests, which function as expected. The …

[ci] fix ci to test windows properly

---

extensions/tokenizers/src/main/python/requirements.txt

Remove onnxruntime from djl-convert requirements.txt, in order to put djl-convert to requirements-lmi.txt
See https://github.com/deepjavalibrary/djl-serving/pull/2615#discussion_r1868369448

[djl-convert] Remove onnxruntime from djl-convert requirements.txt

---

.github/workflows/serving-publish.yml

Since our versions will be in sync with DJL and DJLServing, we could keep having serving.publish in DJL.

[ci] adding back serving.publish to DJL

---

extensions/tokenizers/src/main/python/setup.py

[djl-convert] Remove onnxruntime from djl-convert requirements

---

examples/src/main/java/ai/djl/examples/inference/nlp/BertQaInference.java
examples/src/test/java/ai/djl/examples/inference/nlp/BertQaTest.java
extensions/tokenizers/rust/src/lib.rs
extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/Encoding.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizer.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/jni/TokenizersLibrary.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/QuestionAnsweringTranslator.java
extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizerTest.java

[tokenizers] Return detail for QA inference

---

api/src/main/java/ai/djl/ndarray/NDArray.java
api/src/main/java/ai/djl/ndarray/NDArrays.java
api/src/main/java/ai/djl/ndarray/internal/NDArrayEx.java
engines/mxnet/jnarator/build.gradle.kts
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArrayEx.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/jna/JnaUtils.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/jni/CharSpan.java

Fixes java23 compile error

---

extensions/tokenizers/src/main/python/djl_converter/huggingface_converter.py
extensions/tokenizers/src/main/python/djl_converter/token_classification_converter.py

[tokenizer] fixes token_classification import issues

---

extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/Encoding.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/CrossEncoderTranslator.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/FillMaskTranslator.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/QuestionAnsweringTranslator.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextClassificationTranslator.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextEmbeddingTranslator.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TokenClassificationTranslator.java

[tokenizers] Add int32 option to encoding

---

api/src/main/java/ai/djl/Application.java
api/src/main/java/ai/djl/inference/Predictor.java
api/src/main/java/ai/djl/modality/nlp/translator/ZeroShotClassificationInput.java
api/src/main/java/ai/djl/modality/nlp/translator/ZeroShotClassificationOutput.java
api/src/main/java/ai/djl/modality/nlp/translator/ZeroShotClassificationServingTranslator.java
examples/src/main/java/ai/djl/examples/inference/nlp/ZeroShotClassification.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/ZeroShotClassificationTranslator.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/ZeroShotClassificationTranslatorFactory.java
extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/ZeroShotClassificationTranslatorTest.java

[api] Adds ZeroShotClassification support

---

examples/src/test/java/ai/djl/examples/inference/clip/ClipModelTest.java

Not really sure why this value was changed. But on jan 22, we merged this PR, https://github.com/deepjavalibrary/djl/pull/3599/files. This one does some refactoring in ImageTranslators, could be related to it. So changing the expected imgVector value for now.

[ci] Fix ClipModelTest assertion failure

---

extensions/audio/src/main/java/ai/djl/audio/FFmpegAudioFactory.java

- This PR fixes the incorrect normalization of 16-bit PCM samples.
- Previously, samples were divided by Short.MAX_VALUE (32767), causing -32768 to map slightly below -1.
- Now, division by 32768.0 ensures all values remain within [-1,1].

Fix: Corrected 16-bit PCM normalization to avoid overflow issue

---

.github/workflows/continuous.yml
.github/workflows/native_s3_fasttext.yml
.github/workflows/native_s3_pytorch_android.yml
.github/workflows/native_s3_sentencepiece.yml
android/gradle.properties
engines/pytorch/pytorch-native/CMakeLists.txt
extensions/fasttext/CMakeLists.txt
extensions/sentencepiece/CMakeLists.txt

[ci] Fixes CI build for cmake 4.0.0

---

engines/mxnet/jnarator/src/main/resources/log4j2.xml
examples/src/main/resources/log4j2.xml
extensions/aws-ai/src/test/resources/log4j2.xml
integration/src/main/resources/log4j2.xml

`status` configuration in log4j is deprecated as of 2.24.x https://logging.apache.org/log4j/2.x/manual/configuration.html#configuration-attribute-status

remove status from log4j configuration of status logger

---

docs/load_model.md

In the [Load models from the local file system](https://djl.ai/docs/load_model.html) section, the provided code example incorrectly uses the method _**.setSynsetArtifactName("synset.txt")**_  It should be  **_.optSynsetArtifactName("synset.txt")_**.

Correct 'Load Model' documentation: method ImageClassificationTranslator.builder().setSynsetArtifactName() does not exist

---

api/src/main/java/ai/djl/modality/cv/translator/Sam2Translator.java
engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtNDArray.java
engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtSymbolBlock.java
engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtUtils.java
engines/onnxruntime/onnxruntime-engine/src/test/java/ai/djl/onnxruntime/engine/OrtTest.java
examples/build.gradle.kts
examples/src/main/java/ai/djl/examples/inference/whisper/WhisperJet.java

[examples] Add WhisperJet model demo

---

api/build.gradle.kts
djl-zero/build.gradle.kts
engines/mxnet/jnarator/build.gradle.kts
engines/pytorch/pytorch-engine/build.gradle.kts
engines/pytorch/pytorch-model-zoo/build.gradle.kts
engines/tensorrt/build.gradle.kts
examples/build.gradle.kts
extensions/aws-ai/build.gradle.kts
model-zoo/build.gradle.kts
testing/build.gradle.kts

testng 7.x no longer depends on junit

Remove unnecessary exclusion for testng

---

basicdataset/src/main/java/ai/djl/basicdataset/cv/classification/CaptchaDataset.java

TrainCaptcha example fails with IndexError :
```java
Exception in thread "main" ai.djl.engine.EngineException: index 11 is out of bounds for dimension 1 with size 11
at ai.djl.pytorch.jni.PyTorchLibrary.torchGather(Native Method)
at ai.djl.pytorch.jni.JniUtils.pick(JniUtils.java:581)
at ai.djl.pytorch.jni.JniUtils.indexAdv(JniUtils.java:417)
at ai.djl.pytorch.engine.PtNDArrayIndexer.get(PtNDArrayIndexer.java:74)
at ai.djl.ndarray.NDArray.get(NDArray.java:614)
at ai.djl.ndarray.NDArray.get(NDArray.java:603)
```
The label ranges from 0-11 ( 11 label is for special case) , the total options count should be 12. 

Correct CaptchaDataset options count to prevent torch.gather IndexError

---

api/src/main/java/ai/djl/repository/RepositoryFactoryImpl.java
api/src/test/java/ai/djl/repository/FuseRepositoryTest.java

1. No cloud SDK dependencies
2. No need to download the entire bucket
3. High performance

[api] Adds FUSE based repository support

---

api/src/main/java/ai/djl/modality/nlp/generate/SeqBatcher.java

In SeqBatcher Constructor, hashCode() can not be used for dimension check:
```
this.offSets = offSets.getShape().hashCode() == 2 ? offSets : offSets.reshape(-1, 1);
```
should be:
```
this.offSets = offSets.getShape().dimension() == 2 ? offSets : offSets.reshape(-1, 1);
```

Fix dimension check when reshaping offsets in SeqBatcher

---

docs/pytorch/how_to_convert_your_model_to_torchscript.md

Function `torch.traceModule` is not a valid function.

Fix the incorrect function name and minor typo in doc

---

basicdataset/src/main/java/ai/djl/basicdataset/cv/classification/AbstractImageFolder.java

a bug in the `getImageHeight` method of the `AbstractImageFolder` class where it was incorrectly returning the `imageWidth` value instead of `imageHeight`.

Fix incorrect return value in getImageHeight method

---

examples/src/main/java/ai/djl/examples/inference/nlp/ZeroShotClassification.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/ZeroShotClassificationTranslator.java
extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/ZeroShotClassificationTranslatorTest.java

This refactor improves the ZeroShotClassificationTranslator implementation to better reflect the behavior of Hugging Face’s zero-shot-classification pipeline in Python. It replaces several hardcoded assumptions with dynamic logic that adapts based on model configuration.
The translator was optimized to work with the "djl://ai.djl.huggingface.pytorch/facebook/bart-large-mnli" model. When a different model was used, it would either output wrong predictions or throw errors altogether. 
Some models on Hugging Face define their label mapping in a non-standard order. Without reading and honoring label2id, the results returned by the translator may be incorrect or misleading. The previous implementation also failed on models that require token type IDs. These issues are addressed in this …

Align ZeroShotClassificationTranslator with Hugging Face behavior

---

api/src/main/java/ai/djl/ndarray/NDArray.java
api/src/main/java/ai/djl/ndarray/NDArrayAdapter.java
engines/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArray.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtNDArray.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/JniUtils.java
engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/PyTorchLibrary.java
engines/pytorch/pytorch-native/src/main/native/ai_djl_pytorch_jni_PyTorchLibrary_torch_other.cc
engines/tensorflow/tensorflow-engine/src/main/java/ai/djl/tensorflow/engine/TfNDArray.java
extensions/tokenizers/src/main/java/ai/djl/engine/rust/RsNDArray.java
integration/src/main/java/ai/djl/integration/tests/ndarray/NDArrayOtherOpTest.java

Add NDArray diagonal
- In the case of TensorFlow, [DiagPart](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/diag-part) was used instead of [Diag](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/diag) to produce results in the same format as PyTorch.
- In the case of Apache MXNet, It is identified as a retired project, so it was handled with `UnsupportedOperationException` without additional searching.
close https://github.com/deepjavalibrary/djl/issues/2835.

Add NDArray diagonal

---

api/build.gradle.kts
api/src/main/java/ai/djl/engine/rpc/RpcClient.java
api/src/main/java/ai/djl/engine/rpc/RpcEngine.java
api/src/main/java/ai/djl/engine/rpc/RpcEngineProvider.java
api/src/main/java/ai/djl/engine/rpc/RpcModel.java
api/src/main/java/ai/djl/engine/rpc/RpcTranslator.java
api/src/main/java/ai/djl/engine/rpc/RpcTranslatorFactory.java
api/src/main/java/ai/djl/engine/rpc/TypeConverter.java
api/src/main/java/ai/djl/engine/rpc/package-info.java
api/src/main/java/ai/djl/repository/RepositoryFactoryImpl.java
api/src/main/java/ai/djl/repository/RpcRepository.java
api/src/main/resources/META-INF/services/ai.djl.engine.EngineProvider
api/src/test/java/ai/djl/engine/rpc/RpcEngineTest.java
api/src/test/java/ai/djl/engine/rpc/RpcTranslatorFactoryTest.java
api/src/test/java/ai/djl/engine/rpc/package-info.java
testing/src/main/java/ai/djl/testing/TestServer.java

1. Created a RpcEngine to load a REST API as model
2. Use Criteria to load a model deployed on remote model server
3. Allows inject custom translators to make a REST API call

[api] Implements remote REST API call as a model

---

api/src/main/java/ai/djl/training/listener/EarlyStoppingListener.java

This PR fixes issue #3722  by extending the `EarlyStoppingListener` to support `"trainLoss"` as a valid monitored metric in addition to the default `"validateLoss"`.
Previously, if a user specified `"trainLoss"` via `.optMonitoredMetric("trainLoss")`, the early stopping logic would not behave as expected because `TrainingResult.getTrainLoss()` was not considered in the metric selection. This update introduces an explicit check for `"trainLoss"` in the `getMetric(...)` method, ensuring it is properly used for early stopping decisions.
- The `getMetric(...)` method now explicitly supports `"trainLoss"` in addition to `"validateLoss"`.
- When using `.optMonitoredMetric("trainLoss")`, training is now stopped early if the training loss fails to improve as specified.
- This improves flexibility …

Fix earlystopping metric issue #3722

---

extensions/tokenizers/src/main/python/pyproject.toml

Update license in pyproject.toml to fix the build error.
https://github.com/deepjavalibrary/djl/actions/runs/16677328359/job/47207085546#step:6:85
```
ValueError: invalid pyproject.toml config: `project.license`.
configuration error: `project.license` must be valid exactly by one definition (2 matches found):
- keys:
'file': {type: string}
required: ['file']
- keys:
'text': {type: string}
required: ['text']
```

[djl-converter] Update license in pyproject.toml

---

.github/workflows/nightly_publish.yml

[ci] Remove pytorch 2.1.2 and 2.3.1 publish in nightly

---

extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/jni/LibUtils.java

[fix] Fixes load tokenizer gpu shared library issue

---

extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizer.java
extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/TokenizerConfig.java
extensions/tokenizers/src/test/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizerTest.java

This PR improves the HuggingFace tokenizer configuration handling by:
1. **Fixing configuration precedence**: Options now take priority over `tokenizer_config.json` values, allowing runtime overrides of config file settings
2. **Removing doLowerCase from TokenizerConfig**: The `doLowerCase` parameter is now handled exclusively through options, simplifying the configuration model
3. **Adding modelMaxLength support**: Users can now set `modelMaxLength` via options with proper fallback to config values
- **Enhanced `applyConfig()` method**: Only applies config values when not explicitly set in options
- **Improved parameter precedence**: Options → TokenizerConfig → Defaults
- **Better modelMaxLength handling**: Supports runtime override of config's `model_max_length`
This change is backward …

Fix preference of tokenizer_config.json and remove doLowerCase from TokenizerConfig

---

api/build.gradle.kts
api/src/main/java/ai/djl/translate/NoopServingTranslatorFactory.java
api/src/test/java/ai/djl/translate/NoopServingTranslatorFactoryTest.java
basicdataset/build.gradle.kts
basicdataset/src/main/java/ai/djl/basicdataset/tabular/CsvTranslator.java

**Prev PR: https://github.com/deepjavalibrary/djl/pull/3793**
**Summary**
Adds CSV translator support to DJL, enabling direct CSV input/output processing for tabular machine learning models
**Changes**
CSV Translator Implementation: Added CsvTranslator class in basicdataset module
NoopServingTranslatorFactory Integration: Used reflection as suggested instead to load CsvTranslator for CSV input/out processing
Input Processing: Implements CSV parsing with automatic header detection, numeric validation, and consistent column count enforcement
Output Processing: Supports both CSV and JSON output formats based on Accept header specification
Build Configuration: Added commons-csv dependency and runtime integration between API and basicdataset modules
**Test Coverage:**
CSV input with JSON …

Implemented CSV translator that handles CSV input/output support for XGBoost
